sources/org.osbuild.skopeo
Instead of downloading the image directly to the temporary directory and then moving that temporary directory into the cache use one more intermediate directory and move that into the cache. The reason is that on Python 3.6 removing the temporary directory itself will make Python crash like this:
```
Python 3.6.8 (default, Sep  9 2021, 07:49:02)
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> with tempfile.TemporaryDirectory(prefix="tmp-download-") as tmpdir:
...     import os
...     os.rename(tmpdir, "/tmp/foo")
File "<stdin>", line 3, in <module>
File "/usr/lib64/python3.6/tempfile.py", line 809, in __exit__
self.cleanup()
File …
```
=> stages/skopeo: use extra intermediate download dir

stages/org.osbuild.users, test/data/stages/users/b.json, test/data/stages/users/b.mpp.json, test/data/stages/users/diff.json
From IEEE Std 1003.1-2017:
3.437 User Name:
A string that is used to identify a user; see also User Database. To be
portable across systems conforming to POSIX.1-2017, the value is composed
of characters from the portable filename character set. The <hyphen-minus>
character should not be used as the first character of a portable user name.
3.282 Portable Filename Character Set
The set of characters from which portable filenames are constructed.
A B C D E F G H I J K L M N O P Q R S T U V W X Y Z
a b c d e f g h i j k l m n o p q r s t u v w x y z
0 1 2 3 4 5 6 7 8 9 . _ -
The last three characters are the <period>, <underscore>, and <hyphen-minus>
characters, respectively.
---
The regex checking the username in org.osbuild.users stage omitted the
<period> character before. This commit …
=> stages/users: support a dot inside a username

stages/org.osbuild.containers.storage.conf
The schema said `filename` but we were accessing `location`. Also restrict the value of it to the two locations that the storage.conf file will be looked for.
=> `stages/container.storage.conf`: fix `filename` property lookup

stages/org.osbuild.containers.storage.conf
RHEL 8 only has the old pytoml library, so we need to support that as well. Try falling back if importing `toml` fails.
=> stages/containers.storage.conf: support pytoml

tools/osbuild-mpp
This merges the handling of process_stages() and process_format() into
just one process_format(), which incrementally tracks the call stack
of the formating, which allows it to detect when it is hitting a stage
and can call _process_stage().
This means it is possible to mix things like mpp-if and mpp-join with stages.
For example, you can do complex combinations like:
```    
pipelines:
- name: rootfs
stages:
mpp-join:
- - type: org.ostree.foo
- mpp-if: use_bar
then:
type: org.osbuild.bar
- mpp-if: use_extra_stages
then:
mpp-eval: extra_stages
```
This is particularly useful if you included something and you want
to mpp-join something that was set in a variable.
=> osbuild-mpp: Allow use of mpp-* operations for stages

stages/org.osbuild.rpm, stages/org.osbuild.rpm.macros, test/data/manifests/fedora-ostree-commit.json, test/data/manifests/fedora-ostree-commit.mpp.json, test/data/manifests/fedora-ostree-image.json
Allows to specify a different database path for the `rpm` stage. Will create a macro where the `_dbpath` is set, so that `rpm` and other tools can find the db.
=> stages/rpm: allow setting the dbpath

stages/org.osbuild.ostree.remotes
Adding new options tot he ostree.remotes stage.  These will be used in the Fedora IoT raw image to set up the ostree remote to match the official image [0] 
- `gpgkeypath`: import keys from a file on disk or a directory containing multiple keys
- `contenturl`: when specified, is used for content while the `url` is used for metadata only.  Supports `mirrorlist` URLs.
[0] https://pagure.io/fedora-kickstarts/blob/6bdafa15043b2fb27ee9a112136c2b246e535247/f/fedora-iot.ks
=> Add new properties to ostree.remotes stage: gpgkeypath and contenturl

stages/org.osbuild.greenboot
The script will update /etc/greenboot/greenboot.conf if user passes
the parameter in the config. Right now this only tweaks one config but
it will/can be expanded if other use cases come.
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> Add greenboot configuration management via osbuild

osbuild/pipeline.py
When calculating the checksum of the stage, the mount options were not included. This was maybe deliberate, because if the mounts of a stage change, it is very likely that previous stages change too. But the introduction of non-device mounts, like ostree.deployment, have changed the setting, since the content of the tree will be different if that mount is applied or not. And even for the device based mounts it will change the tree if e.g. a device is mounted at at different path but otherwise is formatted with the very same options. In the worst case we miss a few cache hits due to changes in the mount setup that don't lead to tree changes, but that will rarely happen in practice.
=> pipeline: include mounts in stage checksum

.gitlab-ci.yml, Schutzfile, schutzbot/manifest_tests.sh
On each PR test that osbuild don't break the image generation by testing against the manifest-db that the produced image-infos are still the same as the one stored.
This paves the way to replace the old `image_test` imported from `composer` https://github.com/osbuild/osbuild-composer/blob/main/test/cases/image_tests.sh. It will have for advantages:
* to have up to date image-infos and manifests
* to don't rely on diff to diff image-infos
* to don't run on Openstack anymore on the CI.
=> test: manifests testing on each PR

sources/org.osbuild.curl
Some package versions [1] can contain carets and other characters that curl doesn't like.  These need to be URL (percent) encoded.
Interestingly, the documented way of replacing components in a parsed URL from urllib in Python is by calling the (seemingly private) `_replace()` method [2].
Tested manually against the F37 qcow2 manifest in https://github.com/osbuild/osbuild-composer/pull/2914 which contains the URL`https://rpmrepo.osbuild.org/v2/mirror/public/f37/f37-aarch64-fedora-development-20220831/Packages/g/google-noto-serif-vf-fonts-20201206^1.git0c78c8329-2.fc37.noarch.rpm`
[1] https://docs.fedoraproject.org/en-US/packaging-guidelines/Versioning/#_snapshots
[2] https://docs.python.org/3/library/urllib.parse.html#url-parsing
=> Quote URL paths before downloading in curl source

.packit.yaml
This enables Bodhi updates created by packit (see https://packit.dev/docs/configuration/#bodhi_update).
It is preferable at this time to switch to packit because fedora-bot got blocked by authentication changes to Bodhi, so we need to manually publish all updates (until the auth method in Bodhi is fixed). See https://github.com/osbuild/fedora-bot/issues/41
We've been trialing this packit workflow in osbuild-composer for a while already successfully (https://github.com/osbuild/osbuild-composer/blob/main/.packit.yaml#L22).
=> packit: Enable Bodhi updates workflow

assemblers/org.osbuild.oci-archive, stages/org.osbuild.oci-archive
This allows setting Entrypoint (as well as Cmd) in the oci image,
as per the spec:
https://github.com/opencontainers/image-spec/blob/main/config.md
Note: These two are not equivalent, the Cmd part is replaced by the
argument on the `docker run` commandline, whereas the entrypoint is
kept from the config, so it is important to expose both of these.
=> org.osbuild.oci-archive: Support setting Entrypoint

osbuild/main_cli.py, osbuild/monitor.py, osbuild/util/term.py
Terminal escape sequences for formatting were defined multiple times. This is a prelude to more extensive (prettier) formatting.
=> osbuild: share terminal formats between files

osbuild/util/ostree.py, osbuild/util/rhsm.py, test/mod/test_osbuild.py
If you have a newer pylint version than the one in the GHCI container you get various new warnings. This PR disables one (`unspecified-encoding`) and fixes two others.
The `unspecified-encoding` can stay at the "default" (locale encoding), if we were actually using various encodings then I'd agree with the warning.
=> osbuild: pylint version fixes

devices/org.osbuild.loopback, devices/org.osbuild.luks2, inputs/org.osbuild.ostree, inputs/org.osbuild.ostree.checkout, mounts/org.osbuild.noop, mounts/org.osbuild.ostree.deployment, setup.cfg, stages/org.osbuild.greenboot
Fix a set of new pylint warnings. This starts with assemblers/, devices/, inputs/, and mounts/. More to come.
This is triggered by #1106.
=> tree: fix newer pylint warnings

tools/osbuild-mpp
A set of 4 fixes to osbuild-mpp, mostly reported by `pylint` and `mypy`. I extracted the actual changes to the code into separate commits. The coding-style changes are grouped into a single commit.
Note that we are about to enable `pylint` for `osbuild-mpp`, so we want all these warnings fixed first.
=> osbuild-mpp: fix minor issues and coding-style

.gitlab-ci.yml
This test that compiles and compare image-info from manifests is redundant with the tests from manifest-db.
=> ci: remove the composer image test

stages/org.osbuild.greenboot
The `consider-using-f-string` suppression is new, thus old pylint will complain about unknown directives. If we start ignoring unknown directives for this reasons, we will no longer get warned about misspelled directives. Hence, lets avoid this for now and just use an f-string.
=> stages/greenboot: avoid new pylint suppressions

.packit.yaml
Currently, we build only in the CS9 chroot. It contains newer packages than RHEL 9 has which causes the package built in CS9 chroot uninstallable on RHEL 9 - selinux-policy is the usual suspect.
Let's enable builds in the EPEL 9 chroot (which is actually EPEL 9 on RHEL 9) in order to have a repository for users that use RHEL 9.
This was requested in the Image Builder chat room.
=> packit: add epel-9 to copr_build

osbuild.spec
https://fedoraproject.org/wiki/SELinux/IndependentPolicy
- Add dependency on selinux-policy-targeted
- Move %selinux_relabel_pre to osbuild-selinux
- Start shipping osbuild interface file
- Exclude installed policy module file from RPM verification
Ported from https://src.fedoraproject.org/rpms/osbuild/pull-request/88, big thanks to Vojta!
=> selinux: Update based on latest packaging guide

.packit.yaml
As we don't only want to get Bodhi updates for the stable releases, but also the ones still in development, we need to use 'fedora-branched'.
See https://packit.dev/docs/configuration/#aliases
=> packit: Enable Bodhi updates for unstable Fedoras

.github/workflows/checks.yml, .github/workflows/tests.yml, devices/org.osbuild.loopback, devices/org.osbuild.luks2, devices/org.osbuild.lvm2.lv, inputs/org.osbuild.containers, inputs/org.osbuild.files, inputs/org.osbuild.ostree, inputs/org.osbuild.ostree.checkout, inputs/org.osbuild.tree, mounts/org.osbuild.btrfs, mounts/org.osbuild.ext4, mounts/org.osbuild.fat, mounts/org.osbuild.noop, mounts/org.osbuild.ostree.deployment, mounts/org.osbuild.xfs, test/data/manifests/fedora-ostree-image.json, test/mod/test_fmt_v2.py, test/src/test_pylint.py, tools/osbuild-mpp, tools/tree-diff
Improve the file-enumeration to first check for all files ending in `*.py`, and for everything else run `/bin/file` on it, and check for python mime-types.
Note that we expect the caller to open all those files anyway, and thus this should not any significant overhead, unless we end up with lots of non-python files in the repository (which is highly unlikely). But even then, `/bin/file` only reads the first few bytes of a file, and will default if those are not sufficient to detect the file type. Hence, not much overhead is expected by this.
This change will now start adding scripts in ./tools/ to the linter, including osbuild-mpp.
Not ready to be merged. The new linter report still has to be fixed first. Hence, marked as draft.
Fixes #897.
=> test/src: improve file enumeration

.github/workflows/propagate_to_manifestdb.yml
Add a bot to update the SHA dependency to OSBuild on manifest-db automatically.
The OSBuild SHA will be changed only if the manifest-db SHA was updated on the last commit landed on main. This way this ensure that CI ran successfully for this exact version of OSBuild against manifest-db's actual state. Therefore it is safe to assume that we can upgrade the manifest dependency without running the whole CI again.
Testing done:
* On my fork, after this commit, I added first another one ammending the manifest-db dependency. It successfully opened a PR on manifest-db: https://github.com/osbuild/manifest-db/pull/49
* Then I added a second commit on top of this one changing something else in the repo, the bot did not opened a PR on manifest-db. …
=> manifest-db: propage the osbuild SHA on manifest-db

stages/org.osbuild.ostree.config
Small rewrite of https://github.com/osbuild/osbuild/pull/986 as I didn't have permission to modify it.
----
Currently we're using `str(value)` on a boolean which yields `True` or `False` - turns out ostree reads these values case sensitive and despite setting `True|False`, it doesn't just work.
From jlebon on slack:
> the syntax is readonly=true . it's case sensitive
Fix the above and also just remove the loop as, while it's handy, we'll have to differentiate between options' values anyway and it's just two options we support today.
Signed-off-by: Antonio Murdaca <runcom@linux.com>
=> stages: fix ostree config stage

osbuild/buildroot.py, osbuild/formats/v1.py, osbuild/formats/v2.py, osbuild/meta.py, osbuild/monitor.py, osbuild/pipeline.py, runners/org.osbuild.fedora31, runners/org.osbuild.fedora32, runners/org.osbuild.fedora33, runners/org.osbuild.fedora34, runners/org.osbuild.fedora35, runners/org.osbuild.fedora36, runners/org.osbuild.fedora37, runners/org.osbuild.fedora38, runners/org.osbuild.rhel83, runners/org.osbuild.rhel84, runners/org.osbuild.rhel85, runners/org.osbuild.rhel86, runners/org.osbuild.rhel87, runners/org.osbuild.rhel90, runners/org.osbuild.rhel91, runners/org.osbuild.ubuntu2004, test/mod/test_buildroot.py, test/mod/test_fmt_v1.py, test/mod/test_fmt_v2.py, test/mod/test_meta.py, test/mod/test_monitor.py, test/mod/test_osbuild.py
The way that runners were designed is the following: For each distro we have a specific runner. In case a new version of the distro can use the previous runner, we just create a symlink. In case a new distro version needs adjustments, the runner is copied and adjusted. This is a very clean and obvious design. There is one big drawback: For each new distribution a symlink must be created before it can be used. For Fedora that should ideally happen when it is branched; and this will, ipso facto, always be a symlink since at the time of the branching the new distro is the old distro. But at this very moment osbuild will be broken since it does not contain the new runner; the only way to prevent this is to create the corresponding new runner before the distro is branched, where it then must …
=> runners: auto detection based on best matching distro+version

osbuild/util/rhsm.py, sources/org.osbuild.ostree
The consumer certs are used to uniquely identify a system against candlepin. These consumer certs can be used to identify the system when pulling from RH controlled ostree repositories.
=> sources/ostree: pull from remote using rhsm mTLS certs

schutzbot/mockbuild.sh
Running mock as root is broken, this commit can be reverted once rhbz#2135203 is fixed.
=> schutzbot/mockbuild: stop running mock as root

stages/org.osbuild.rpm
From machine-id(5): machine ID is a single *newline-terminated*, hexadecimal, 32-character, lowercase ID.
This commit fixes that by adding a newline.
This broke us on Fedora 38:
This pull request added `set -e` to kernel-install:
https://github.com/systemd/systemd/pull/23881
This caused F38 pipeline failing because the script also runs `read -r MACHINE_ID </etc/machine-id`. `read` returns 1 if the input doesn't contain a newline, thus after the addition of `set -e`, the script started crashing with our bad machine-id. This caused crashing of the whole image build in the grub2 stage which requires kernel-install to work (because kernel-install is responsible for putting vmlinuz into /boot).
=> stages/rpm: make the fake machine-id newline-terminated

stages/org.osbuild.systemd-logind, test/data/stages/systemd-logind/b.json, test/data/stages/systemd-logind/b.mpp.json
Add option to reserve a VT exclusively for `autovt@.service` activation. See logind.conf(5) for more details.
=> stages/logind-systemd: add `ReserveVT` option

stages/org.osbuild.keymap, test/data/stages/keymap/b.json, test/data/stages/keymap/b.mpp.json
Allows the configuration of the console font. systemd-firstboot does not allow to do it, so we need to manually tweak the file.
=> stages/keymap: add font option

stages/org.osbuild.firewall, test/data/stages/firewall/b.json, test/data/stages/firewall/b.mpp.json, test/data/stages/firewall/diff.json
> this would add support for specifying sources in firewalld similar to https://github.com/openshift/microshift/blob/main/scripts/image-builder/config/kickstart.ks.template#L59
Continues Antonio's (@runcom ) work made on PR #1137 (because I cannot add more commits to that PR since I'm not  a maintainer) after @dvdhrm 's review.
=> Extend firewall stage to add sources (continues from PR #1137)

stages/org.osbuild.ostree.preptree
Pick up an old patch by Colin and fix the mentioned broken link.
Replaces #676.
=> stages/ostree.preptree: link to rpm-ostree code

.github/workflows/checks.yml, .github/workflows/coverity.yml, .github/workflows/tests.yml, .github/workflows/trigger-gitlab.yml
This uses the new node 16 version (see [1]), which is the future proof version, since node 12 will be deprecated by summer 2023 (see [2]).
[1] upstream commits:
https://github.com/actions/checkout/commit/8f9e05e482293f862823fcca12d9eddfb3723131 https://github.com/actions/checkout/commit/a12a3943b4bdde767164f792f33f40b04645d846
[2] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> ci: upgrade to actions/checkout@v3

tools/osbuild-dev
Since I've been working on `osbuild-crew` (helper utility to deal with building an developing in the `osbuild`-ecosystem) there was some generalized interest to land some of those things directly into a tool in `osbuild`.
Here's that PR.
This tool requires certain dependencies that are not packaged on RHEL hence it will stay unpackaged but can be run by anyone who has a source checkout (or copied straight into their `~/bin`, I guess ;)).
Note that this went from a rather quick local script into this tool quickly.
Features are:
- By default `osbuild-dev manifest` will replace content hashes back with the names of the RPMs, disable by passing `--no-resolve-sources`.
- By default `osbuild-dev manifest` will skip the `sources` section of the manifest, disable by passing `--no-skip-sources`. …
=> osbuild-dev: a new tool to help with manifests

.github/workflows/checks.yml, .github/workflows/tests.yml
The privdocker action got update to node 16, since node 12 is deprecated and support for it will be remove by summer 2023[1].
[1] https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
=> ci: update to containers/privdocker@552e30c

tools/osbuild-mpp
According to the OCI Image Index specification the mediaType field is not mandatory Assume that it is a list if mediaType is not set while manifests field is
Signed-off-by: Ygal Blum <ygal.blum@gmail.com>
=> osbuild-mpp: recognize manifest without mediaType and with manifests fields as a list

stages/org.osbuild.ignition
was just missing a `set` as the file is sourced
Signed-off-by: Antonio Murdaca <runcom@linux.com>
Signed-off-by: Antonio Murdaca <antoniomurdaca@gmail.com>
=> ignition: fix ignition_network_kcmdline

stages/org.osbuild.grub2.iso
add the ability to configure the grub timeout. Today it defealts to 1 minute and we can't configure it from osbuild-composer either (the simplified-installer is mainly using this afaict and 1 min is just too much).
Signed-off-by: Antonio Murdaca <antoniomurdaca@gmail.com>
=> grub2.iso: add timeout option

stages/org.osbuild.containers.storage.conf
In newer version of the container storage package the config file moved from `/etc/containers` to `/usr/share/containers/`. The latler is not marked as config in the spec file, so we don't want to change it. The current containers code[1] will read _either_ a file in `usr` or in `etc` depending on the existence of the latter. This means we can not just write the keys we want into a file in `/etc/containers` without losing all other defaults set in the config file. A new option `filebase` is therefore added, that when given will be read and form the basis of the configuration data. Then data from the target file (given via `filename`) will be merged into it and finally the actual configuration will be applied on top.
[1] https://github.com/containers/storage/blob/232bf398bd68595d2a6e53ec07d …
=> `stages/containers.storage.conf`: ability to specify a base file 

osbuild/objectstore.py, osbuild/pipeline.py, test/mod/test_objectstore.py
Remove copy-on-write support from `objectstore.Object`. The main reason for introducing copy-on-write was to save an additional copy in the non DAG-pipeline model[1]. With the introduction of the latter and the explicit `--export` option, we can achieve the same result without the complexity of copy-on-write semantics.
[1] See commit https://github.com/osbuild/osbuild/commit/39213b7f44a8ac7e8a29b0cd4df10f20a67e89ea, part of PR #225 [changeset](https://github.com/osbuild/osbuild/compare/3b7c87d563c90256afd80cf08c37ea97efa42108..42a365d12ff6b0dc764941a5b0eaf9935cce4b2b).
=> ❌ 🐮 Remove copy-on-write support for `Object` (no-cow)

test/data/manifests/fedora-ostree-commit.json, test/data/manifests/fedora-ostree-commit.mpp.json, test/data/manifests/fedora-ostree-image.json, test/data/manifests/fedora-ostree-image.mpp.json
Include the new journald config stage to configure journald to persist the journal. This is needed since we don't create the `/var/log/journal` directory that journald uses to switch the default to persistent storage. But instead of creating that directory, we explicitly configure journald via the new stage.
This is also what Fedora CoreOS does, see [`10-coreos-persistent.conf`](https://github.com/coreos/fedora-coreos-config/blob/d709e4f5fc3970fb6b938dc7bcfdb8d602d2db94/overlay.d/05core/usr/lib/systemd/journald.conf.d/10-coreos-persistent.conf)
=> test/data: persist the journal for ostree images

mounts/org.osbuild.ostree.deployment, osbuild/devices.py, osbuild/mounts.py, osbuild/objectstore.py, osbuild/pipeline.py, test/mod/test_fmt_v1.py, test/mod/test_objectstore.py
The `Object.{read,write}` methods were introduced to implement copy on write support. Calling `write` would trigger the copy, if the object had a `base`. Additionally, a level of indirection was introduced via bind mounts, which allowed to hide the actual path of the object in the store and make sure that `read` really returned a read-only path.
Support for copy-on-write was recently removed[1], and thus the need for the `read` and `write` methods. We lose the benefits of the indirection, but they are not really needed: the path to the object is not really hidden since one can always use the `resolve_ref` method to obtain the actual store object path. The read only property of build trees is ensured via read only bind mounts in the build root. 
Instead of using `read` and `write`, …
=> `objectstore`: use direct path input/output for `Object`

devices/org.osbuild.loopback, devices/org.osbuild.luks2, devices/org.osbuild.lvm2.lv, osbuild/devices.py
It is not an error if the device node already exist, which is e.g. the case when we are using `/dev` of the host.
=> devices: tolerate existing device nodes

mounts/org.osbuild.btrfs, mounts/org.osbuild.ext4, mounts/org.osbuild.fat, mounts/org.osbuild.xfs, osbuild/mounts.py, test/run/test_mount.py
This modification will allow a user to ask to mount the system as read only for instance. Which would be super useful for image-info who is progressively using more of OSbuild internals to mount partitions.
=> mounts: use the options object for mountopts

test/mod/test_util_fscache.py
Drop the PathLike annotation, since it is not compatible to py-3.6. Fixed our test-suite on RHEL-8.8.
=> test/fscache: drop PathLike annotation

test/data/stages/users/diff.json
The `/etc/shadow` and `/etc/shadow-` files are changing (salting), so we should not compare them in the test.
=> test/stages/users: ignore non-deterministic files

docs/osbuild.1.rst, osbuild/api.py, osbuild/formats/v1.py, osbuild/formats/v2.py, osbuild/main_cli.py, osbuild/objectstore.py, osbuild/pipeline.py, osbuild/util/parsing.py, schutzbot/manifest_tests.sh, test/mod/test_api.py, test/mod/test_objectstore.py, test/mod/test_osbuild.py, test/mod/test_util_parsing.py, test/test.py
This is a combination of two "patch series":
1) #1186
2) Integrate `FsCache` into `ObjectStore`
Enhance `Object` to be able to store arbitrary metadata alongside its tree and change the stage code to do so. When serialising the results, read the metadata from via the `Object` instead of getting it from `BuildResult`. When the object is later committed the metadata will also be saved. This ensures that all metadata is also present for the object when later builds are resumed from that object, or a previously built object is exported. 
Integrate the recently added file system cache `FsCache` into our object store `ObjectStore`. NB: This changes the semantics of it: previously a call to `ObjectStore.commit` resulted in the object being in the cache (i/o errors aside). But `FsCache.store`, …
=> 🗄Write and read metadata from the store and integrate `FsCache` into `ObjectStore`

schutzbot/manifest_tests.sh
The default cache location for `osbuild-image-test` is actually `/var/osbuild/store`. Pass that to `osbuild` when setting the maximum cache size to set the size for the correct location.
=> schutzbot: set the cache size for the correct store

osbuild/util/rhsm.py
Consumer key and cert paths were swapped.
=> util: fix typo in get_consumer_secrets

test/mod/test_objectstore.py
Port the existing object store tests from `unittest` to `pytest`. Allow all tests that can run without root privileges to do so. No functional change of the test itself.
=> test: convert objectstore test to pytest

osbuild/util/fscache.py, test/mod/test_util_fscache.py
(duplicate PR to work around github-actions-CI weirdness)
Add a new field to the cache-information called `version`, which is a simple integer that is incremented on any backward-incompatible change.
The cache-implementation is modified to avoid any access to the cache except for `<cache>/staging/`. This means, changes to the staging area must be backwards compatible at all cost. Furthermore, it means we can always successfully run osbuild even on possibly incompatible caches, because we can always just ignore the cache and fully rely on the staging area being accessible.
The `load()` method will always return cache-misses. The `store()` method simply discards the entry instead of storing it. Note that `store()` needs to provide a context to the caller, hence this implementation simply …
=> [v2] util/fscache: introduce versioning

stages/org.osbuild.ostree.config
We want to add aboot to the list of possible bootloaders so we can distinguish if we are using aboot or one of the other bootloaders.
Signed-off-by: Eric Curtin <ecurtin@redhat.com>
=> ostree.config: add aboot (Android) bootloader config option

runners/org.osbuild.AutoSD9
AutoSD9 is a CentOS 9 stream derivate.
See https://gitlab.com/CentOS/automotive/sample-images/-/issues/12
Closes #1209
=> runners: add AutoSD runner

osbuild/objectstore.py, osbuild/util/fscache.py, test/mod/test_util_fscache.py, test/mod/test_util_fscache_coherency.py
This series contains a set of improvements and minor fixes to the FsCache implementation which were pointed out during the initial review but were not critical. This includes code-style fixes as well as reducing the kernel-requirements to allow running on a wider set of file-systems. Lastly, this also adds more tests to better verify the atomicity of the cache operations.
=> fscache: post-merge improvements

osbuild/util/fscache.py, test/mod/test_util_fscache.py
The cachedir-tag specification defines how to mark directories as cache-directories. This allows tools like `tar` to ignore those directories if desired (e.g., see `tar --ignore-caches`). This is very useful to avoid huge cache-directories in backups and remote synchronizations.
The spec simply defines a file called `CACHEDIR.TAG` with the first 43 bytes to be: "Signature: 8a477f597d28d172789f06886806bc55" (which happens to be the MD5-checksum of ".IsCacheDirectory". Further content is to be ignored. Any such files marks the directory in question as a cache-directory.
The cachedir-tag has been successfully deployed in tools like `cargo` and `VLC`, and is currently discussed to be implemented in Firefox. More information is available here: https://bford.info/cachedir/
=> util/fscache: add cachedir-tag support

runners/org.osbuild.asahi-fedora-remix
Fedora Asahi is just a minor fork of mainstream Fedora with some Apple Silicon hardware enablement.
See https://github.com/osbuild/osbuild/issues/1215
=> runners: add Fedora Asahi runner

test/mod/test_objectstore.py
Instead of using `Path.stat` use `os.stat` since the former only gained the `follow_symlinks` argument in 3.10 but we still need to support Python 3.6 for RHEL 7 and 8.
Should fix #1214
=> test/objectstore: use os.stat instead Path.stat

stages/org.osbuild.rhsm.facts, test/data/stages/rhsm.facts/diff.json
Instead of creating the file in /usr/share and symlinking to /etc, create it directly in /etc.  This fixes an issue with SELinux labeling.  The file in /usr/share does not get labelled correctly because it doesn't match the policy and causes issues with some tools (rhc).
See [rhbz#2147450](https://bugzilla.redhat.com/show_bug.cgi?id=2147450) for the bug regarding the failure of the `rhc` tool.
See also https://github.com/osbuild/osbuild/pull/1191 for a previous discussion on this issue.  The original plan of adding the policy upstream was abandoned (or postponed?) but in a follow-up discussion with @teg and @gicmo we decided it's not necessary to put the facts file in the alternate location.
=> stages/rhsm.facts: create facts file in /etc

sources/org.osbuild.ostree
Example of broken repo config:
```
...
"tls-client-key-path=/etc/pki/consumer/key.pem"
"tls-client-cert-path=/etc/pki/consumer/cert.pem"
```
---
I managed to build a manifest with rhsm: true using this patch, resulted in:
```
...
tls-client-key-path=/etc/pki/consumer/key.pem
tls-client-cert-path=/etc/pki/consumer/cert.pem
```
=> sources/ostree: fix quotation marks in mTLS remote options

osbuild.spec
See the relevant Fedora change:
https://fedoraproject.org/wiki/Changes/SPDX_Licenses_Phase_1
We already verified that the SPDX format works well in the Enterprise Linux pipeline.
=> osbuild.spec: migrate the license field to SPDX

stages/org.osbuild.mkdir, test/data/stages/mkdir/a.json, test/data/stages/mkdir/a.mpp.json, test/data/stages/mkdir/b.json, test/data/stages/mkdir/b.mpp.json, test/data/stages/mkdir/diff.json
* Explicitly set `mode` using `os.chmod()`. The documentation mentions that the mode passed to `os.mkdir()` may be ignored and also the `umask` value set for the process affects it.
* Add new `exist_ok` stage options property to allow gracefully handling situation when a directory with the specified path already exists. This will make it easier to implement support for creating custom directories in osbuild-composer.
=> stages/mkdir: explicitly set mode using `chmod` and support handling of existing directories

stages/org.osbuild.mkdir, test/data/stages/mkdir/diff.json
As it turned out, the original behavior was intentional. Revert the change. Also enhance the stage documentation to cover the stage behavior in this regard.
=> stages/mkdir: revert explicitly setting mode using `os.chmod`

mounts/org.osbuild.btrfs, mounts/org.osbuild.ext4, mounts/org.osbuild.fat, mounts/org.osbuild.xfs, osbuild/mounts.py, test/run/test_mount.py
Before we could only ask OSBuild to mount a device as readonly. But devices can have more mount options than this. Supporting more options is necessary for the new version of image-info that is using OSBuild's internals in order to mount the image it wants to work on. Otherwise, for instance, some umasks aren't applied properly and we can get differences in rpm-verify results, thus corrupting the DB.
Mount is now accepting:
* readonly
* uid
* gid
* umask
* shortname
=> mounts: accept a wider set of mount options

mounts/org.osbuild.btrfs, mounts/org.osbuild.ext4, mounts/org.osbuild.xfs, osbuild/mounts.py
To avoid kernel panics if the kernel attempts to recover the filesystem when it's mounted as readonly image-info needs to set this flag for ext4 and xfs FS.
=> mounts: add the norecovery option for xfs and ext4

stages/org.osbuild.shell.init, test/data/stages/shell.init/b.json, test/data/stages/shell.init/b.mpp.json
Pattern for valid environment variable names as defined in The Open Group Base Specifications Issue 7, 2018 edition IEEE Std 1003.1-2017 (Revision of IEEE Std 1003.1-2008)
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap08.html
=> stages/shell.init: add pattern for env var names

stages/org.osbuild.ignition
As of today the functionality is broken if somebody passes more than one karg as the join would simply unify the strings but ignition_network_kcmdline is unquoted and results in just the very first karg to be consumed by the set command.
=> stages/ignition: support multi kargs in network kcmdline

.gitlab-ci.yml, Schutzfile, osbuild.spec
Manifest-db is finally unblocked and we can update the reference commit. Done manually this time to speed up the process.
I'm also updating the set of distributions we are testing on, upgrading it to what's is generated on manifest db.
=> ci: update manifest tests

test/mod/test_buildroot.py
Just a test that can't be ran as non-root and needed to be marked.
=> test: this test requires to be able to bindmount

.github/codecov.yml, .github/workflows/tests.yml
`codecov` often reports weird diffs and we rarely take action on a codecov failure in CI.
This closes #1263.
=> ci: remove codecov

.gitlab-ci.yml, Schutzfile, stages/org.osbuild.ovf
The `capture_output` option was added in python3.7, yet el8 has python3.6 by default.
---
See osbuild/osbuild-composer#3371
=> stages/org.osbuild.ovf: support older python3 versions

test/conftest.py, test/run/test_assemblers.py, test/test.py
We test various combinations of filesystems when testing assemblers. One of such filesystems is `btrfs`, which is not supported by CentOS Stream / RHEL kernel.
This PR adds the ability to selectively skip variants of test cases if the tested filesystem is marked as supported by specifying a custom `--unsupported-fs` pytest option. All filesystems not explicitly marked as not supported are treated as supported on the platform where tests are being run.
This also required porting tests from `unittest` to pytest`.
=> Test: skip test cases if the tested filesystem is not supported on the platform

.gitlab-ci.yml, schutzbot/deploy.sh, schutzbot/mockbuild.sh
DNF has more elaborate locking system and can wait for other instances of
itself when installing packages. Using rpm directly to install local
package is causing failures in CI due to it not being able to acquire
lock on `/var/lib/rpm/.rpm.lock`.
Using DNF should improve the situation, although there is no good
documentation to link and support this claim for sure.
=> mockbuild.sh: use dnf to install local package, not rpm

README.md, test/run/test_mount.py, test/run/test_sources.py, test/run/test_stages.py, tools/osbuild-mpp
- README: update required Python version to 3.6
- Don't use `directory` argument with SimpleHTTPRequestHandler constructor
- Don't use `capture_output=True` with `subprocess.run()`
https://github.com/osbuild/osbuild/pull/1262 adds testing on Python 3.6
=> Python 3.6 compatibility fixes

.gitlab-ci.yml
remove old references to 8.7 and 9.1 nightly
=> Update test runners for 8.8 & 9.2 nightly

osbuild/loop.py, osbuild/remoteloop.py, test/run/test_devices.py
LOOP_CONFIGURE allows to atomically configure the decive when opening it. This avoid the possibility of a race condition where between set_fd and set_status some operations are already accepted by the loopback device.
See https://lwn.net/Articles/820408/
As this feature is only available for kernels > 5.8 osbuild keeps retro compatibility when required.
#fix https://github.com/osbuild/osbuild/issues/762
=> loop: use LOOP_CONFIGURE when available

stages/org.osbuild.mkfs.ext4
This allows enabling the ext4 "verity" feature (which is currently default to off). This will be needed in the automotive work we're doing.
=> org.osbuild.mkfs.ext4: Add verity option to

runners/org.osbuild.fedora38
This fixes an issue where Fedora-38 hosts can not build CentOS-Stream-9 images due to an incompatible gpg key with the default settings for rpm.
On Fedora-38, rpm has changed to use a new backend for key verification and by default does not support SHA1 anymore, although the support for SHA1 can be re-enabled via a config file. The (current) CentOS-Stream-9 keys however still require SHA1 support in order to be importable so they are unusable on Fedora-38 unless SHA1 support is re-enabled.
In OSBuild, the initial chroot does not contain the config files and so SHA1 support is disabled when rpmkeys from the host is called. It does not matter if the crypto-policies on the host machine is configured with the exception to support SHA1 because the chroot filters that out. This means it may not …
=> runners: add fedora-38 specific logic for SHA1 key support

stages/org.osbuild.isolinux
Otherwise when `opts` (which isn't `required`) is left out we fail the stage.
```
File "/run/osbuild/bin/org.osbuild.isolinux", line 243, in <module>
ret = main(args["tree"], args["inputs"], args["options"])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/run/osbuild/bin/org.osbuild.isolinux", line 227, in main
"cmdline": " ".join(kopts)
^^^^^^^^^^^^^^^
TypeError: can only join an iterable
```
Fix on the other side is here: https://github.com/osbuild/osbuild-composer/pull/3439
=> stages/isolinux: default list

stages/org.osbuild.sfdisk, tools/osbuild-mpp
`org.osbuild.sfdisk` provides a [schema](https://github.com/osbuild/osbuild/blob/v84/stages/org.osbuild.sfdisk#L69) that allows passing `"attrs"` to set `"Attributes of the partition (GPT)"`. This works fine with the GUID specific bits, but `sfdisk` will error out for bit0-47 passed as indices. There's nothing to do for bit3-47. These are considered to be reserved for future use and sfdisk will return an error if asked to set them. For bit0-2, they are described in the [manpage](https://git.kernel.org/pub/scm/utils/util-linux/util-linux.git/tree/disk-utils/sfdisk.8.adoc?h=v2.38.1#n94) and have to be set using their names.
Additionally, `osbuild-mpp` does not support setting GPT attributes at all. So use the same logic for the `mpp-define-image` use-case.
=> Support GPT partition attribute bits when creating images

stages/org.osbuild.sgdisk, test/data/stages/sgdisk/disk.img.json, test/data/stages/sgdisk/sgdisk.json, test/data/stages/sgdisk/sgdisk.mpp.json
The partition name in the sgdisk stage was previously quoted when passed to sgdisk as an argument. I think that this was done because the sgdisk man page states that:
```
If you want to set a name that includes a space, enclose it in
quotation marks, as in sgdisk -c 1:"Sample Name" /dev/sdb.
```
However, this should apply only when sgdisk is run in a shell, so that the argument is not split by shell into multiple arguments and passes as a single string.
The stage is executing sgdisk using Python `subprocess` module, which does not need strings with spaces to be quoted, because they are passed to the command as separate items which are not split in any way.
The previous behavior of the stage was that these quotes became part of the actual partition name in the partition table.
After a …
=> stages/sgdisk: option to not quote partition names passed to sgdisk

osbuild.spec
Use %forgeautosetup macro to prepare sources in the %prep phase to auto-apply any potential downstream patches just by listing them in the spec file using `PatchX`. Otherwise, the macro needs to be modified each time a downstream patch needs to be applied in downstream.
=> Spec: use `%forgeautosetup` macro in `%prep` phase

schutzbot/mockbuild.sh
We have been observing a race condition in our CI when installing packages at the beginning of the SUT setup. This happens only on RHEL and it is caused by the `rhc` tool, which executes some Ansible playbooks on system startup, which install packages using dnf. This interferes with dnf commands ran by the `mockbuild.sh` script, which results in a job failure.
Since there seems to be no way to determine if `rhc` finished "its thing", let's retry dnf install of packages up to 5 times with exponential backoff in between retries.
=> mockbuild.sh: retry dnf install up to 5 times

README.md
This redoes the headings to have the correct indent levels, it also mentions the Matrix channel that we now have and the mailing list.
=> readme: mention matrix, redo headings

schutzbot/mockbuild.sh
see
https://github.com/osbuild/gitlab-ci-terraform-executor/commit/25d1a458a0fc71d4b9f2364f2e4b62097267b74e
Given that registration is now done inside the runner VMs do we still want to carry this code snippet around ?
=> CI variable name has changed,

osbuild/inputs.py, osbuild/pipeline.py
Prior this commit, the arguments for the input service were passed inline. However, jsoncomm uses the SOCK_SEQPACKET socket type underneath that has a fixed maximum packet size. On my system, it's 212960 bytes. Unfortunately, that's not enough for big inputs (e.g. when building packages with a lot of rpms).
This commit moves all arguments to a temporary file. Then, just a file descriptor is sent. Thus, we are now able to send arbitrarily sized args for inputs, making osbuild work even for large image builds.
Supersedes #1303
=> inputs: Move arguments for InputService.map to a temporary file

runners/org.osbuild.fedora-asahi-remix
This name got changed in Fedora 38, basically the Fedora and Asahi were flipped.
=> runners: Asahi Fedora Remix to Fedora Asahi Remix

stages/org.osbuild.rpm
~Two commits:~
~stages/rpm: set machine-id to uninitialized instead of an empty one~
~From machine-id(5):~
> ~If /etc/machine-id exists and is empty, a boot is not considered the first~
> ~boot.~
~This doesn't seem correct because we obviously want the first boot be considered as a one. Thus, we want to actually write "uninitialized"~
~into the file so the following behaviour is triggered:~
> ~If /etc/machine-id contains the string "uninitialized", a boot is also~
> ~considered the first boot.~
~Note that there's also an option not to create the file at all, but that~
~doesn't work on Fedora/RHEL, because /etc is mounted read-only during~
~early boot (from initramfs) and systemd cannot neither write the machine-id~
~nor bind-mount over it.~
---
stages/rpm: set machine-id to 444
According …
=> stages/rpm: chmod `machine-id` to 0444

stages/org.osbuild.sysconfig, test/data/stages/sysconfig/b.json, test/data/stages/sysconfig/b.mpp.json, test/data/stages/sysconfig/diff.json
expands sysconfig with configuration for `livesys` and `desktop` necessary for fedora spins/editions (they *all* configure this).
note that this pr will remove the need for the current `org.osbuild.livesys` stage but that one got in without noticing that this stage would be the better place for it to live. it isn't removed in this pr due to backwards compatibility.
=> Expand `sysconfig` stage with `livesys` and `desktop`

.gitlab-ci.yml, Schutzfile, schutzbot/terraform
The osbuild-composer libdnf5 PR needs osbuild artifacts for Fedora 39 in order to run the tests.
=> .gitlab-ci.yml: Run rpmbuild for Fedora 39

stages/org.osbuild.squashfs
Fedora and RHEL 9 kernels support it and since it's an interesting alternative to other compression methods, we should support it in osbuild.
I also took the liberty of sorting the compression methods alphabetically.
=> stages/squashfs: add support for zstd compression

stages/org.osbuild.anaconda
Anaconda has deprecated the `kickstart_modules` directive and instead now has `activatable_`, `forbidden_`, and `optional_modules`. This is available starting in Fedora 35.
This change allows frontend code (`osbuild-composer`) to put version checks in place to write the correct keys.
Related: https://bugzilla.redhat.com/show_bug.cgi?id=2023855
=> stage: anaconda, allow access to more config

Schutzfile
Fedora 38 is no longer branched. Switch to the release names for the snapshots.
=> Schutzfile: Fix f38 snapshot references

stages/org.osbuild.rpm
This will hopefully help debug problems when the signature check fails. You need to manually take the hash and look it up in the manifest sources list to figure out what package failed since this stage doesn't have access to sources.
=> org.osbuild.rpm: Add some context to rpmkeys failure

osbuild/main_cli.py, osbuild/pipeline.py
When developing or rebuilding manifests a lot it is common to want to checkpoint everything to the store. It seems we all have small shell scripts hanging around for this.
Let `--checkpoint` take a shell-like glob such as `--checkpoint="*"` to checkpoint everything or `--checkpoint="*.rpm"`.
Note that there's a behavioral change here; previously `osbuild --checkpoint=a` would error if that specific checkpoint wasn't found. Now `osbuild` will only error if nothing was selected by the passed globs.
=> osbuild: add `--checkpoint` can now use globs

stages/org.osbuild.ostree.encapsulate
We have a lot of copypasta of `def ostree()` but in this case it's actually rpm-ostree, and we should be clear about that.
(Also in the future this code will need to change
to use the non-deprecated entrypoint, see
https://github.com/coreos/rpm-ostree/pull/4527 )
=> ostree.encapsulate: It's rpm-ostree, not ostree

.github/workflows/check.yml, Makefile
This PR:
- removes the old `test.src` tests (they were empty anyway)
- adds a new `lint` target to `Makefile` to run all linters
- uses the new target in the CI
=> Improve the linting setup

stages/org.osbuild.dracut, stages/org.osbuild.dracut.conf
Add option to exclude specific kernel modules from the initramfs that's generated by dracut.
=> stages/dracut: add dracut omit drivers option

test/data/manifests/fedora-ostree-native-container.json, test/data/manifests/fedora-ostree-native-container.mpp.yaml
This should just defer to rpm-ostree.
xref https://github.com/coreos/rpm-ostree/issues/4530
(If someone cares about reproducibility here, they can specify it;
alternatively and more reliably, they can create builder container
images and pin to those)
=> tests/ostree-container: Drop hardcoded max layers

stages/org.osbuild.ostree.selinux
We should drop this stage entirely once we have a way to force on selinux in ostree.
=> osbuild.ostree.selinux: xref ostree issue for this

stages/org.osbuild.ostree.deploy
For Fedora CoreOS we don't actually have any root= kernel command line option in our baked images. We have services that rely on this and set up sysroot on first boot. The code in this stage doesn't require for this option to have been provided and actually gracefully handles when it's not provided. Let's just change the schema to also not require it.
=> stages/ostree.deploy: drop requirement on rootfs option

docs/osbuild.1.rst
The file `./samples/base-qcow2.json` used in the osbuild.1.rst man-page does no longer exists. It was removed in e92b409 and `samples` is now a symlink into the test data. The closest in the test data to the original `base-qcow2.json` seems to be the `fedora-boot.json` so this is now used in the examples section.
This removes the references to `./samples/base-rpm-qcow2.json` which was remove in fe95d93. Here `fedora-boot.json` is also used.
=> docs: update the samples used in osbuild.1.rst

inputs/org.osbuild.ostree, osbuild/util/ostree.py, sources/org.osbuild.ostree, tools/osbuild-mpp
See individual commits for rationale.
=> tools/osbuild-mpp: add mpp-resolve-ostree-commits helper

osbuild.spec, setup.py, tools/osbuild-depsolve-dnf
This PR moves `dnf-json` into `osbuild` and creates a new subpackage `osbuild-depsolve` to install the script into `/usr/libexec`. 
At a later date the depsolving code can move into the `osbuild`-library to be shared with `osbuild-mpp`.
=> depsolve: import `dnf-json`

tools/osbuild-mpp
The fix in 980ca03685e674ef6cda7b5383aede84dff44560 ensured that no empty commit object was created, but it still created an (empty) input object, which causes failures, like:
https://gitlab.com/CentOS/automotive/sample-images/-/merge_requests/388
We need to move the check before the line that adds the empty default input object.
=> tools/osbuild-mpp: Really fix empty ostree commit object in deploy stage

test/data/stages/users/diff.json
The test for this stage is failing because etc/shadow changes content depending on the date that it runs on (due to the "date of last password change" field). This causes the checksums to not be constant for our tests and depends on the date.
This commit removes the checksums for etc/shadow from the test so that they are not checked as part of the test. This worksaround the test failure issue for now until a solution to the dynamic contents is determined.
=> test/stages/users: make test data date agnostic

tools/osbuild-mpp
In case the tag was something other than `:latest` let's include the tag in the default name.
=> tools/osbuild-mpp: include container tag in default name

osbuild/objectstore.py
In the case we are not using a buildroot (i.e. we are using the host as the buildroot) let's also mount in /etc into the environment. There are sometimes where software running from /usr can't operate without configuration in /etc and this will allow it to work.
An example of software hitting this problem is skopeo. With a simple config like:
```
version: '2'
mpp-vars:
release: 38
pipelines:
- name: skopeo-tree
source-epoch: 1659397331
stages:
- type: org.osbuild.skopeo
inputs:
images:
type: org.osbuild.containers
origin: org.osbuild.source
mpp-resolve-images:
images:
- source: quay.io/fedora/fedora-coreos
tag: stable
name: localhost/fcos
options:
destination:
type: containers-storage
storage-path: /usr/share/containers/storage
```
We end up hitting an error like this:
``` …
```
=> objectstore: also mount /etc/containers for "host" buildroot

tools/osbuild-depsolve-dnf
The import of `dnf-json` came from `osbuild-composer`, as we sadly have/had multiple copies this wasn't the *right* version as it was lacking previous work to disable weak dependencies.
=> depsolve-dnf: enable weak deps selection

tools/osbuild-depsolve-dnf
A more helpful exception type and message when a repository passed through the input JSON does not contain the necessary fields. See: #1411.
=> depsolve-dnf: helpful exception for repo

osbuild/util/ostree.py, stages/org.osbuild.ostree.commit
This is a feature that was added in rpm-ostree 2023.10 and is needed for the new transient /etc feature to work. What it does is change the labeling of /usr/etc to match those of /etc, so that /usr/etc can be used directly as a bind-mount or an overlay mount when mounted on /etc.
See https://github.com/coreos/rpm-ostree/pull/4640 for details.
=> Add selinux-label-version to the org.osbuild.ostree.commit stage

stages/org.osbuild.mkdir, test/data/manifests/fedora-ostree-bootiso-xz.json, test/data/manifests/fedora-ostree-bootiso-xz.mpp.yaml, test/data/manifests/fedora-ostree-bootiso.json, test/data/manifests/fedora-ostree-bootiso.mpp.yaml, test/data/stages/mkdir/a.json, test/data/stages/mkdir/a.mpp.yaml, test/data/stages/mkdir/b.json, test/data/stages/mkdir/b.mpp.yaml, test/data/stages/mkdir/diff.json
The items of an array are defined under the `items` key, not under `paths`. Let's fix this.
Btw, this is possible because JSON Schema itself doesn't use additionalProperties = false. This allows extending the schemas easily, but is sadly a bit error-prone.
=> stages/mkdir: fix its schema

stages/org.osbuild.copy
Functions for parsing mounts and inputs raise an exception if the referenced entity can't be found in the stage options. However, the exception message always included the value of the `root` variable, which is `None` when an exception is risen. Instead of the `root` value, the `name` variable with the entity name should be used.
=> stage/copy: fix exception msg when parsing mounts and inputs

.github/workflows/test.yml, osbuild.spec, osbuild/testutil/__init__.py, osbuild/testutil/imports.py, stages/test/test_kickstart.py, test/mod/test_testutil_imports.py, tox.ini
This commit adds a simple and lightweight unit test for the new kickstart options. It's pretty trivial but also cheap and runs fast. The idea behind it is that the code of the kickstart stage is tested without the need for a full osbuild tree, just passing the test input options and observing the expected file content. The same pattern could potentially be used for other stages (like the user stage) to check that the content of the output has the expected format (or that options that are mutually exclusive are handled correctly). 
While this is trivial now and looks a bit like a waste of time I think this will become useful as more kickstart stage options get implemented. The goal is to eventually support the options in https://github.com/RedHatInsights/edge-api/blob/main/templates/templat …
=> stages: add new unit test for kickstart stage

.github/workflows/test.yml, tox.ini
Run the `test_stages` test in parallel in the github runner. This test currently takes about 1:30h to 2:30h and running it in parallel will give us big wins in terms of test time. The time is observed to go down to 0:30h to 1h.
Note that the other tests are not run in parallel. The reason is that they fail randomly, it looks like insufficient isolation between them. Some are easy to fix, e.g.:
https://github.com/mvo5/osbuild/commit/721521220b34e0054d8c89e4e919822fececd2c1 but it's probably not worth it as the other tests run a lot faster.
=> tests: run the `test_stages` category in parallel

stages/test/test_kickstart.py, tox.ini
Run `ksvalidator` as part of the test_kickstart.py tests. This ensures that the file we write is valid.
This addresses the suggestion from @bcl in https://github.com/osbuild/osbuild/pull/1424#issuecomment-1796054555 (thank for that!).
One thing that I noticed while adding this is that the "ostree.url" requires a valid file/http/https url so I wonder if we should make our schema stricter?
Alternatively (if we want to avoid the extra test dependency) something like https://github.com/osbuild/osbuild/compare/main...mvo5:kickstart-integration?expand=1#diff-e1602f2a3af5d3fe5bd7f3cbbc64aa2ac0a61fea3b9847668f0c59ff11825ee4R645 could be done and we install/run ksvalidaor inside the stage and test there. However it takes longer and is less flexible so I opted for this approach. But happy to switch …
=> stages(kickstart): run ksvalidator as part of the tests

stages/test/test_kickstart.py
Trivial followup for PR#1426 to include unit test output about the expected kickstart file.
This includes the test that @achilleas-k ran in https://github.com/osbuild/osbuild/pull/1426#issuecomment-1798269903 (thanks for this!)
=> stages(kickstart): add unittest test for zerombr/clearpart

stages/test/test_kickstart.py
Add functional/regression around the schema validation for the kickstart stage. The goal is to ensure that the regexp matching in the schema allows the expected uses and rejects clearly forbidden ones.
AFAICT we don't have tests like this right now but I would love to have them mostly because they help me to quicker validate that the schema properties are actually working the way I expect them to work and to "document" some of the obvious cases where we want to ensure that the strings are rejected. As always I would love your feedback and please give it extra scrutiny :)
The next part of the kickstart support (`autopart`) will also have some regexp patterns so this would also help there.
=> stages(kickstart): add test for schema validation

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
This commit implements the `reboot` option for kickstart files.
Note that there are two ways this can be enabled via the json.
Either via a boolean or by passing a dict with options.
```
{"reboot": true}
{"reboot": {"eject": true, "kexec": true}
```
Passing the empty dict
```
{"reboot": {}}
```
is not allowed by the schema.
=> stages(kickstart): implement "reboot" option

osbuild/testutil/__init__.py, stages/test/test_kickstart.py
I split out the kickstart tests here in two, one that verifies the exact contents and one that calls ksvalidator over the resulting file. The latter is automatically skipped if `ksvalidator` isn't available.
=> stage/test: skip kickstart validate test if no ksvalidator

stages/test/test_kickstart.py
Now that inputs can be relatively easily validated against the schema this should also be used for all the "good" test inputs to ensure that all tests test against valid inputs.
=> stages(kickstart): ensure test inputs pass schema validation

tools/check-runners, tools/check-snapshots, tools/osbuild-mpp, tox.ini
The `./tools` dir was not part of the LINTABLES in the `tox.ini` which meant that pep8/pylint etc checks were not run on the tools there.
This commit adds it and fixes the issues that `make lint` found.
=> tools: add "tools" dir to LINTABLES and fix issues

stages/org.osbuild.ostree.genkey, stages/org.osbuild.ostree.sign
This is the `org.osbuild.ostree.sign/genkey stages from https://github.com/osbuild/osbuild/pull/1343 separated out so we can land them before the rest of the outstanding issues are fixed.
=> Add stages to sign ostree commits

test/test.py, tools/gen-stage-test-diff
While working on PR #1441 I had to run `./gen-stage-test-diff` multiple times and noticed two small issues:
1. The default for the cache-max-size seems to be on the wrong parser argument
2. Running it directly from git without having osbuild installed seems to not work
Both are fixed with this PR. For (2) it uses the same approach as in `test/test.py` to just run it as a python module.
=> tools: tweak `gen-stage-test-diff` to fix defaults for max-size and allow running from a git checkout

stages/org.osbuild.kernel-cmdline.bls-append, test/cases/ostree-images, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
This adds a stage to be able to add kernel arguments on a system by
appending to the BLS [1] config directly either in the tree or in
a mount. This is useful on say systems that don't use `grubby` and
thus can't use the org.osbuild.kernel-cmdline stage.
[1] https://freedesktop.org/wiki/Specifications/BootLoaderSpec/
=> stages: add kernel-cmdline.bls-append stage

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
Tiny PR to add "text" to kickstart and also adds a missing testcase for clearpart (ensure no extra properties are allowed there).
=> stages(kickstart): implement "display_mode" option and tiny test addition

stages/org.osbuild.rpm
Link **/proc/self/fd** to **/dev/fd** within the tree to avoid **"'/dev/fd/63': No such file or directory"** errors
Signed-off-by: Miguel Martín <mmartinv@redhat.com>
=> RPM stage: link /proc/self/fd to /dev/fd

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
This commit implements the `autopart` kickstart option and adds matching tests.
Rational is that we want to support https://github.com/RedHatInsights/edge-api/blob/main/templates/templateKickstart.ks#L6
See also https://docs.fedoraproject.org/en-US/fedora/f36/install-guide/appendixes/Kickstart_Syntax_Reference/#sect-kickstart-commands-autopart
=> stages(kickstart): support autopart

osbuild/util/rmrf.py, tox.ini
When running with python 3.12 on the host (like fc39) `make lint`
fails with some unexpected errors. This PR addresses the first
part of that:
With python 3.12 our pylint version breaks because of
https://github.com/pylint-dev/astroid/issues/2201
This is fixed in 3.0.0a6 but it seems sensible to move
to 3.0.2.
The `shutil.rmtree(onerror=...)` kwarg got deprecated with py3.12.
We still need to support older version of python all the way
back to 3.6 so just ignore this pylint error for a while.
There is still a autopep8 issue with py312 https://github.com/hhatto/autopep8/issues/712
=> tox: move to pylint 3.0.2 for py312 support

docs/osbuild.1.rst
The existing man-page is a bit misleading as it claims that the command in the example will generate an image. Because osbuild generates what is requested this is not actually true. This commit tweaks the examples a bit to make them more useful. It also fixes a numbering bug (we had two "Example 1").
It also tweaks the description of `fedora-boot.json` as it is no longer fedora 34 but 38.
=> docs: tweak the man-page a bit to make the example more useful

osbuild/util/runners.py, runners/org.osbuild.centos9, runners/org.osbuild.fedora30, runners/org.osbuild.fedora38, runners/org.osbuild.rhel7, runners/org.osbuild.rhel81, runners/org.osbuild.rhel82, runners/org.osbuild.ubuntu1804
- Consolidate runners functions into a sigle file
- Create fake machine id within the runner to avoid `Failed to resolve specifiers in '/var/log/journal/%m': No such file or directory` errors
- Remove tmpfiles once the command has been executed by the runner
=> Consolidate functions used by runners

osbuild/meta.py
Add comment why the `ModuleInfo.load()` code uses open()/ast.parse() instead of just using `importlib`.
The reason is that while `importlib` is more convenient and much shorter it would require that all python modules of the osbuild modules are actually installed on the system just to inspect the schema/documentation of the stage.
Added this because I was originally a bit puzzled why not using importlib (which is much simpler :)
=> osbuild. add comment why AST is used and not importlib

osbuild/util/fscache.py, test/mod/test_util_fscache.py
In OSBuild we'll often be operating on sparse files. Let's make the tabulation of the size of files on disk used when determining cache size for pruning consider the actual size of the file usage on disk rather than the size the file reports to be.
This means using os.lstat().st_blocks * 512 versus os.lstat().st_size.
See https://stackoverflow.com/a/55203604
=> osbuild/util/fscache: calculate actual size of files

test/mod/test_meta.py
There is no need for a handcrafted tempdir fixture, pytest already provides a build-in `tmp_path`.
=> tests: remove custom tempdir_fixture

stages/org.osbuild.experimental.ostree.config, stages/org.osbuild.ostree.post-copy
This adds two stages to support ostree ed25519 signatures (`org.osbuild.ostree.genkey` and `org.osbuild.ostree.sign`) and support for composefs (`composefs` key in `org.osbuild.ostree.config` and a new `org.osbuild.ostree.deploy-verity` stage).
Using these with a recent ostree release (2023.4) you can generate a signed ostree digest and build an image with composefs integration working.  Additionally, with the work happening in [ostree-prepare-root](https://github.com/ostreedev/ostree/pull/2921) we will have the ability to verify the generated signatures from the initrd and thus get a fully trusted boot all the way into `/usr`.
For an example of how using this may look, see: https://gitlab.com/CentOS/automotive/sample-images/-/merge_requests/333
=> stages: Add stages to support ostree signatures and composefs

test/mod/test_objectstore.py, test/run/test_devices.py, test/run/test_mount.py, test/run/test_noop.py, test/run/test_sources.py
This commit removes some unnecessary custom tmpdir() fixtures and uses the pytest buildin tmp_path instead.
Some custom tmpdir fixtures are left in place as they configure the tmp location to be under `/var/tmp` which is not trivial to do with pytests `tmp_path`. Not sure or not if the is a deep reason there for using /var/tmp. I assume it's to ensure that the tests run on a real FS not on a potential tmpfs but I don't have the full background so didn't want to change anything.
If someone know if there is a deep reason I will update the PR to add a comment in the relevant places :)
=> tests: remove custom tmpdir() fixtures and use tmp_path

osbuild/loop.py, test/mod/test_loop.py
When osbuild.loop.Loop calls `__init__()` it assigns the `self.fd` on open. However if that open call fails for whatever reason (not found, permissions) the cleanup in `__del__` will fail in confusing ways because `self.fd` is not initialized yet. It also prevents the correct error from getting reported. A tiny test is added to ensure this does not regress.
=> osbuild: fix missing initialization of fd in osbuild.loop.Loop

stages/org.osbuild.oscap.remediation
Remediation bash didn't work correctly without /dev/fd. Link /proc/self/fd to /dev/fd within the tree.
=> stage(oscap.remediation): link /proc/self/fd to /dev/fd

test/data/stages/README.md
Quick rename to have our wording be in-line with the new differences between stage unit tests and stage integration tests; also being applied to the guides.
=> test: stage tests -> stage integration tests

test/data/stages/oscap.remediation-extra/diff.json, test/data/stages/oscap.remediation/diff.json
The oscap remediation tests broke with 810a48d. This commit adds the fixes to get the GitHub actions to go green again.
=> test: fix broken oscap remediation tests

stages/test/test_kickstart.py, stages/test/test_ostree_post_copy.py
Small followup for pr#1343 to ensure https://github.com/osbuild/osbuild/pull/1343#discussion_r1402156667 is captured in a test and comment. So that our future selfs do not accidentally "cleanup" devices from the schema as it appears unused.
=> stages(ostree.post-copy): add stage unit test and comment

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
This PR adds `network`support to the kickstart stage [0].
It is incomplete, i.e. it does not implement all options of [0]. However it is implementing all the pieces that are used in https://github.com/RedHatInsights/edge-api/blob/main/templates/templateKickstart.ks#L6 and everything that looks common.
The network options for kickstart are quite long, so I the following subset:
- bindto
- nodefroute
- nodns
- ethtool
- wepkey
- dhcpclass
- bond{opts,slaves}
- vlanid
- interfacename
- team{slaves,config}
- bridge{slave,opts}
Please let me know (especially people with deep kickstart knowledge like @bcl) if that list is sensible. It it easy enough to add more in future and also easy enough to just add them all.
[0] https://docs.fedoraproject.org/en-US/fedora/f36/install-guide/appendixes/Kickst …
=> stages(kickstart): add `network` support to kickstart

osbuild/util/runners.py, runners/org.osbuild.centos9, runners/org.osbuild.fedora30, runners/org.osbuild.fedora38, runners/org.osbuild.rhel81, runners/org.osbuild.rhel82, stages/org.osbuild.rpm
- runners: create fake machine id when needed
- runners: clean up temp files before exiting the runner
=> Create fake `machine-id` and cleanup before exiting

tools/osbuild-mpp
I'm trying to debug some failures, and having no feedback as to what file we're parsing or what code is evaluated when something fails makes it hard to debug manifests.
This adds some nice error messages that will help.
=> osbuild-mpp: Print better errors if eval fails

devices/org.osbuild.loopback, osbuild/loop.py, test/cases/ostree-images, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml, tools/osbuild-mpp
i.e. physical disks with logical/physical sector sizes of 4096 bytes. 
Support for this was originally discussed/added for CoreOS in:
- https://github.com/coreos/fedora-coreos-tracker/issues/385
- https://github.com/coreos/coreos-assembler/pull/1130
=> enhance support for creating 4k native disk images

stages/org.osbuild.machine-id, stages/test/test_machine-id.py
This is a draft for a new machien-id stage. it would allow us to create image that are in the sytemd "ConditionFirstBoot" state.
Draft for now to ensure it follows the vision/ideas of Tom and the team.
See also https://github.com/osbuild/osbuild/pull/960 for more context (and the commit messages here).
=> stages(machine-id): add a new "machine-id"  stage

tools/osbuild-mpp
`mpp-define-images` can create an image file, using `losetup` to deal with non-standard sector sizes requires root. Not all users run `osbuild-mpp` as root.
While I am not a fan of "suddenly sudo" based on the input manifest this does alleviate builds breaking for manifests with default sector sizes when non-root.
=> osbuild-mpp: conditional losetup

stages/org.osbuild.oscap.autotailor, test/data/stages/oscap.autotailor/b.json, test/data/stages/oscap.autotailor/b.mpp.yaml
This commit extends the current support for OpenSCAP tailoring by accepting an array of key/value overrides. Users will be able to specify override values for specific rules that will update the value when remediating the image.
=> stages:oscap.autotailor: add key/value overrides

osbuild/util/mnt.py, test/mod/test_util_mnt.py
While debugging a failure of osbuild-composer [0] on fc39 it was noticed that a mount failure does not include the output of the mount command:
```
File "/usr/lib/python3.12/site-packages/osbuild/mounts.py", line 78, in mount
path = client.call("mount", args)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/osbuild/host.py", line 348, in call
ret, _ = self.call_with_fds(method, args)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.12/site-packages/osbuild/host.py", line 384, in call_with_fds
raise error
osbuild.host.RemoteError: CalledProcessError: Command '['mount', '-t', 'xfs', '-o', 'ro,norecovery', '--source', '/dev/rootvg/applv', '--target', '/tmp/tmpjtfmth56/app']' returned non-zero exit status 32.
File "/usr/lib/python3.12/site-packages/osbuild/host.py", …
```
=> test,util: fix mount and add test that ensures mount output is part of the exception

osbuild/mounts.py, test/mod/test_util_mnt.py
This commit adds mount output to the error raised by FileSystemMountService.mount(). This is useful when running into mount failures during osbuild runs.
The issue was discovered while debugging a mount failure for osbuild-composer PR#3820. Initially osbuild PR#1490 was meant to fix it but it turned out there is a third mount helper in the code that was originally overlooked (sorry for that!).
This is a quick (and hopefully uncontroversial) fix - I plan to address this also in https://github.com/osbuild/osbuild/pull/1491 (sorry that I overlooked this earlier).
=> osbuild: include std{out,err} in FileSystemMountService.mount() errors

stages/test/test_containers_storage_conf.py, tox.ini
Pytoml is no longer being maintained: https://github.com/avakar/pytoml The author suggest switching to toml.
We already use the 
```
try:
import toml
except ModuleNotFoundError:
import pytoml as toml
```
pattern in stages/org.osbuild.containers.storage.conf so use it in the tests too to prefer "toml" instead of pytoml.
=> osbuild: pytoml is deprecated, replace with toml

sources/org.osbuild.skopeo, sources/org.osbuild.skopeo-index
Update the skopeo sources stage to check other container-transports for downloading container images. This commit adds a transport for `containers-storage` in addition to the existing `docker://` transport.
Jira: https://issues.redhat.com/browse/HMS-3235
=> HMS-3235 sources/skopeo: check containers-storage

stages/test/test_mkfs_ext4.py
This was actually meant to be the starting point of a branch that adds options to control the new `orphan_file` feature of ext4 so that we can fix https://github.com/osbuild/bootc-image-builder/issues/20 by selectively enable/disable this feature based on the distro.
However we decided to go into  a different direction here but given that the test is already written and useful in itself I decided to open it.
=> stages(mkfs.ext4): add basic unit test

stages/org.osbuild.systemd, stages/test/test_systemd.py, test/data/stages/systemd/b.json, test/data/stages/systemd/b.mpp.yaml, test/data/stages/systemd/diff.json
This adds a new key masked_generators, similar to masked_services, which masks systemd generators from running at boot, by creating symlinks to /dev/null in /etc/systemd/systemd-generators, as described in:
https://www.freedesktop.org/software/systemd/man/latest/systemd.generator.html#Description
This will be useful for the automotive project, as it allows disabling of unsupported things like sysv or rc.local legacy support, while improving boot performance.
=> org.osbuild.systemd: Support masking generators

osbuild/main_cli.py, osbuild/objectstore.py, test/mod/test_objectstore.py
This commit allows to exclude preserving ownership from an object
export. This is required to fix the issue that on macOS the an
podman based workflow cannot export objects with preserving
ownerships.
Originally this was a no_preserve: Optional[List[str]] = None)
to be super flexible in what we pass to cp but then I felt like
YAGNI - if we need more we can trivially change this (internal)
API again :)
A version of https://github.com/osbuild/osbuild/pull/1511/ without the crazy^Wcontroversial parts.
=> osbuild: allow to export a tree without preserving the ownership (less tests)

test/mod/test_util_mnt.py
The rename avoids warnings from pytest. It confuses this for a unittest class apparently. And it's really a `Fake` service anyway.
=> test: rename TestFileSystemMountService->FakeFileSystemMountService

.github/workflows/check.yml, .github/workflows/generate.yml, .github/workflows/test.yml
LET'S USE MERGE QUEUES :tada: 
Add the `merge_group` trigger to all checks so they run on the merge queue.
Don't run checks on push to main since the tip of the merge queue will be the same.
=> github: run tests on merge queue

.devcontainer/Dockerfile, Schutzfile, devices/org.osbuild.loopback, mounts/org.osbuild.btrfs, mounts/org.osbuild.ext4, mounts/org.osbuild.fat, mounts/org.osbuild.noop, mounts/org.osbuild.xfs, osbuild/formats/v2.py, osbuild/mounts.py, osbuild/pipeline.py, schemas/osbuild2.json, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml, test/mod/test_fmt_v2.py, test/mod/test_mounts.py, test/run/test_mount.py, tools/osbuild-mpp
This allows us to map in a whole disk as a loopback device with partition
scanning rather than slicing up the disk and creating several loopback
devices.
This depends on https://github.com/osbuild/osbuild/pull/1493 merging first.
Fixes https://github.com/osbuild/osbuild/issues/1495
=> mounts: support mounting partitions

.github/workflows/check.yml, .github/workflows/generate.yml, .github/workflows/test.yml
We've temporarily disabled the merge queue because our tests often require retries to go all-green and this isn't possible to do on the queue, meaning that it's close to impossible to get a PR merged. Run tests on push so that they run in main when a PR is merged.
This reverts commit 63feab7d864743b69ea61255b1509a5d749b9e3a.
=> github: run tests on push again

test/mod/test_fmt_v1.py, test/mod/test_loop.py, test/mod/test_meta.py, test/mod/test_monitor.py, test/mod/test_mounts.py, test/mod/test_objectstore.py, test/mod/test_testutil_fake_tree.py, test/mod/test_testutil_imports.py, test/mod/test_util_fscache.py, test/mod/test_util_fscache_coherency.py, test/mod/test_util_linux.py, test/mod/test_util_mnt.py, test/mod/test_util_ostree.py, test/run/test_devices.py, test/run/test_mount.py, test/run/test_noop.py, test/run/test_sources.py, test/run/test_stages.py, tox.ini
While doing something unrelated I noticed that the tests are not part of the linting. This PR fixes this and also tweaks the test to pass the lint checks. I tried to keep the changes as minimal as possible. It's also split into the linters for easier review, the pylint one is the most "invasive".
=> test: include tests in `make lint` and fix issues

osbuild/testutil/__init__.py, stages/org.osbuild.container-deploy, stages/test/test_container_deploy.py, test/mod/test_testutil_fake_tree.py, tools/osbuild-mpp
This implements a new stage `org.osbuild.container-deploy` so that we can use containers to deploy e.g. a build-root. Kudos to @ondrejbudai. 
This is a split out of https://github.com/ondrejbudai/osbuild/commits/bootc/.
=> stages: add new `org.osbuild.container-deploy` stage

sources/org.osbuild.skopeo, sources/org.osbuild.skopeo-index
For local images copied from an image store other than the default, we need to be able to specify the `storage-location`. This commit enables this functionality.
Jira: https://issues.redhat.com/browse/HMS-3235
=> HMS-3235: Skopeo source storage location

tools/osbuild-mpp
So we can use something like mpp-format-string inside of mpp-embed. An example would be below where we want to substitute the ociarchive var in using `mpp-format-string: 'file://{ociarchive}'`.
```
version: '2'
mpp-vars:
ociarchive: /path/to/fedora-coreos-39.20240104.dev.2-ostree.x86_64.ociarchive
pipelines:
- name: oci-archive
stages:
- type: org.osbuild.copy
inputs:
inlinefile:
type: org.osbuild.files
origin: org.osbuild.source
mpp-embed:
id: fcos.ociarchive
url:
mpp-format-string: 'file://{ociarchive}'
options:
paths:
- from:
mpp-format-string: input://inlinefile/{embedded['fcos.ociarchive']}
to: tree:///fcos.ociarchive
```
=> tools/osbuild-mpp: run _process_format() for mpp-embed dict

stages/org.osbuild.container-deploy, stages/test/test_container_deploy.py
This commit ensures that `/var/tmp` is available. Skopeo expects this dir but the bwrap environment starts with a very minimal `/var` so `/var/tmp` may not be available.
=> stages(container-deploy): ensure `/var/tmp` is available

stages/org.osbuild.grub2, stages/test/test_grub2.py
The EFI binaries are currently pulled from a hardcoded path in the buildroot. When moving to containers as buildroots this will no longer work as they have an alternative layout. This is an easy "fix" - make the location of the `EFI/` directory configurable.
This allows us set `efi_root` to `/usr/lib/bootupd/updates/EFI/` and keep our existing `bootc-image-builder` workflow.
Note that this may actually not be the desired solution and instead we want the new `bootupd`: https://github.com/osbuild/osbuild/pull/1519
=> stages(grub2): allow pulling efi binaries from alternative efi roots

stages/org.osbuild.bootupd, stages/test/test_bootupd.py, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
Add the bootupd stage to install GRUB on both BIOS and UEFI systems,
ensuring that your bootloader stays up-to-date.
Signed-off-by: Renata Ravanelli <rravanel@redhat.com>
=> create org.osbuild.bootupd stage

test/run/test_exports.py, test/stages/README.md, test/stages/org.osbuild.testing.injectpy, test/test.py
This commit allows to exclude preserving ownership from an object
export. This is required to fix the issue that on macOS the an
podman based workflow cannot export objects with preserving
ownerships.
Originally this was a `no_preserve: Optional[List[str]] = None)`
to be super flexible in what we pass to `cp` but then I felt like
YAGNI - if we need more we can trivially change this (internal)
API again :)
It had to do some gymnastics to test it, feel free to tell me I'm crazy and I'm happy to drop some of the commits
Build on top of https://github.com/osbuild/osbuild/pull/1512
=> osbuild: test OSBUILD_EXPORT_FORCE_NO_PRESERVE_OWNER

docs/osbuild.1.rst, osbuild/buildroot.py, osbuild/main_cli.py, osbuild/pipeline.py
Similar to rd.break for dracut this allows a user to specify:
- `--break` or `--break=*`
- to get a shell before each stage is run
- `--break=stage.name`
- to get a shell each time the stage with that name is run
- example: `--break=org.osbuild.copy`
- `--break=stage.id`
- to get a shell each time the stage with that ID is run
- get the ID for the stages for your manifest by running osbuild on the manifest with `--inspect`
- example: `--break=dc6e3a66fef3ebe7c815eb24d348215b9e5e2ed0cd808c15ebbe85fc73181a86`
and get a bash shell where they can inspect the environment to debug and develop OSBuild stages.
=> add --break for requesting a debug shell

stages/org.osbuild.selinux, stages/test/test_selinux.py, test/mod/test_util_selinux.py
This was originally started  because of work Ondrej did in https://github.com/ondrejbudai/osbuild/commit/dbf2ab49334929c186ee6035a0e1a9e992f431e7#diff-b009fdb01bdd4ed236a5c8df69d8b5d19360c70fe37fdde4beb5e222f723377fL36 when working on the containers-as-buildroots stage.
I started with the test and wanted to make file_contexts no longer required. But after further discussion/investigation it seems we don't need this particular change but having the tests is probably still useful and while writing it I noticed a small cleanup opportunity: instead of calling `setfiles` directly we can use the library function in `utils.selinux`. 
Easiest to read is probably commit by commit.
=> stages,util: add org.osbuild.selinux tests and small functional tweaks

stages/org.osbuild.ostree.config, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
Support setting the sysroot.bls-append-except-default value in the OSTree config. This is used by CoreOS to support configuration used for GRUB password support https://github.com/coreos/fedora-coreos-tracker/issues/1333
=> stages/org.osbuild.ostree.config: support bls-append-except-default

test/run/test_mount.py
The new `create_image_with_partitions()` helper fails under rhel8 currently. The reason is that `mkfs.ext4 -E offset=` will warn in older versions about a partition table and require user input.
This got fixed `e2fsprogs` 1.46.3 in Jul 2021 but RHEL8 still has 1.45.
[0] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=989612
=> test: fix new mount tests under rhel8

stages/test/test_containers_storage_conf.py
The test starts failing because a new version of jsonschema (4.21.0)
changed the error messages for `minProperties: 1`.
To fix this we just use a regex and check for both possible values.
As a drive-by the commit also improves the error output in case
the match is not found.
=> test: fix test_schema_validation_containers_storage_conf

test/run/test_exports.py
When constructing a minimal environment for osbuild the exported dirs lacked "schemas" so the test_exports.py test failed on RHEL8.
This commit adds it (and also "assemblers" for good measure). With that the test will pass.
=> test: export schemas in testing_libdir_fixture

osbuild/devices.py, osbuild/inputs.py, osbuild/mixins.py, osbuild/mounts.py, test/mod/test_mixins.py
This is a drive-by change after spending some quality time with the
mount code. The `id` field of `Mount` is calculated only once and
only when creating a `Mount`. This seems slightly dangerous as
any change to an attribute after creation will not update the
id. This means two options:
1. dynamically update the `id` on changes
2. forbid changes after the `id` is calculcated
I went with (2) but happy to discuss of course but it seems more
the spirit of the class.
It also does the same change for "devices.Device"
=> osbuild: error when {Device,Mount} is modified after creation

stages/org.osbuild.mkfs.ext4, stages/test/test_mkfs_ext4.py
Add optional flags to the org.osbuild.mkfs.ext4 stage enabling/disabling the metadata_csum_seed and orphan_file features.
=> stages/org.osbuild.mkfs.ext4: add ext4 options

osbuild/testutil/__init__.py, stages/test/test_autotailor.py, stages/test/test_bootupd.py, stages/test/test_containers_storage_conf.py, stages/test/test_erofs.py, stages/test/test_kickstart.py, stages/test/test_machine-id.py, stages/test/test_mkfs_ext4.py, stages/test/test_ostree_post_copy.py, stages/test/test_selinux.py, stages/test/test_skopeo.py, stages/test/test_xz.py, stages/test/test_zstd.py, test/mod/test_testutil_jsonschema.py
This commit adds a new helper `assert_jsonschema_error_contains()` to `testutil` and uses it everywhere where we check errors from jsonschema.
Based on the excellent feedback from @supakeen in https://github.com/osbuild/osbuild/pull/1542#discussion_r1455353687
=> test: add new testutil.assert_jsonschema_error_contains() helper

Makefile, osbuild/main_cli.py, tox.ini
We have mypy right now which is super nice. However there are quite a few place where it's not used fully right now and where we lack type information. This PR start by adding a new `mypy-strict` tox filter that gradually builds up more and more files to be fully strict. I already see this uncovering potentially real issues in other files that should probably be addressed. But with this simple and humble start we can start addressing more and more of them.
=> osbuild: add "mypy-strict" check

stages/org.osbuild.container-deploy, stages/test/test_container_deploy.py
This commit adds a new `exclude` option to the container-deploy stage. This is needed when we deploy `bootc` containers that are used for the buildroot. Here the  `/sysroot` dir needs to be excluded because it has conflicting selinux definitions for files there and in the normal "root" dir.
See also https://github.com/osbuild/bootc-image-builder/pull/138
=> stages(container-deploy): add new `exclude` option

osbuild.spec, tools/osbuild-depsolve-dnf5
dnf5-json will be used for building Fedora 40 and later.  RHEL and Fedora < 40 will continue to use python3-libdnf via dnf-json.
=> osbuild-depsolve-dnf5: Add libdnf5 based depsolving for Fedora 40

osbuild/sources.py, sources/org.osbuild.curl, sources/org.osbuild.inline, sources/org.osbuild.ostree, sources/org.osbuild.skopeo, sources/org.osbuild.skopeo-index
We parallelize (with a threadpool) our sources, this currently happens in `osbuild.sources`. This PR moves that parallelization into the source implementations themselves.
Initially this leads to some duplicated code (only one stage has had its parallelization removed) but allows sources better control on *how* they want to parallelize their workload, and better control over output which is relevant for #1545.
=> move source parallelization into sources

.github/workflows/test.yml
With pytest 8.0.0 (released 27.01.2024)  the `-k` option seem to have changed it's behavior. This makes our tests fail right now.
This commit drop `-k` therefore to make them work again.
Tests started to fail recently and it looks like this is because pytest 8.0.0 changes the semantic of the `-k` option. We used to pass `-k stages/test` but that seems to no longer work. So pin pytest to the last good version until this is better understood.
Alternative approach to https://github.com/osbuild/osbuild/pull/1563 - may fail with py3.6 which does not have pytest 8.0.0
=> test: drop `-k` from `-k stages/test` test matrix

stages/org.osbuild.cloud-init, stages/test/conftest.py, stages/test/test_autotailor.py, stages/test/test_bootupd.py, stages/test/test_cloud-init.py, stages/test/test_container_deploy.py, stages/test/test_containers_storage_conf.py, stages/test/test_erofs.py, stages/test/test_grub2.py, stages/test/test_kickstart.py, stages/test/test_machine-id.py, stages/test/test_mkfs_ext4.py, stages/test/test_ostree_post_copy.py, stages/test/test_selinux.py, stages/test/test_skopeo.py, stages/test/test_systemd.py, stages/test/test_xz.py, stages/test/test_zstd.py
The `org.osbuild.cloud-init` would create an invalid cloud-init configuration file, if the `datasource_list` config key was specified in the stage options.
Specifically, the configuration file would contain the key dumped in the following format:
```yaml
datasource_list:
- Azure
```
The cloud-init documentation for the `datasource_list` config key [explicitly mentions that](https://cloudinit.readthedocs.io/en/latest/reference/base_config_reference.html#datasource-list):
```
This key is unique in that it uses a subset of YAML syntax. It requires that the key and its contents, a list, must share a single line - no newlines.
```
Therefore, the dump format for the key is supposed to be the following:
```yaml
datasource_list: [Azure]
```
Fix the stage to dump the key in the "flow" format on a …
=> stages/org.osbuild.cloud-init: fix dump format of `datasource_list` key

mounts/org.osbuild.ostree.deployment, osbuild/mounts.py, stages/org.osbuild.chattr, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
Here we add two main changes:
1. a chattr stage to set file/directory attributes
2. a rework of the ostree.deployment mount to support the OSTree musical chairs on mounted filesystems too.
The ostree.deployment rework is needed for the chattr stage to work (i.e. we lose the immutable bit when going through a `org.osbuild.copy` stage).
=> Add chattr stage; support stacked ostree.deployment mounts

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
In the context of specific ostree installation we are missing some kickstart options:
1. rootpw option (despite we only need rootpw --lock, implement the full spec found here https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#rootpw)
2. initlabel a property of clearpart option
3. nohome a property of autopart 
FIXES: https://issues.redhat.com/browse/THEEDGE-3835
=> stages(kickstart): Add missing rootpw, initlabel, nohome

stages/org.osbuild.sfdisk, stages/org.osbuild.sgdisk, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml, test/data/manifests/fedora-ostree-image.json, test/data/manifests/fedora-ostree-image.mpp.yaml, tools/osbuild-mpp
Partitions by default are indexed starting at 1, but in
some cases, such as CoreOS for IBM Z, it may be usefull
to set the 'partnum' for GPT disks explicitly, without
creating dummy partitions.
Now user can define an image:
```
mpp-define-images:
- id: image
size: 10737418240
table:
uuid: 00000000-0000-4000-a000-000000000001
label: gpt
partitions:
- name: boot
type: 0FC63DAF-8483-4772-8E79-3D69D8477DE4
partnum: 3
size: 786432
- name: root
type: 0FC63DAF-8483-4772-8E79-3D69D8477DE4
partnum: 4
size: 4194304
```
So target disk would look like:
```
Disklabel type: gpt
Disk identifier: 00000000-0000-4000-A000-000000000001
Device        Start     End Sectors  Size Type
/dev/loop0p3   2048  788479  786432  384M Linux filesystem
/dev/loop0p4 788480 4982783 4194304    2G Linux filesystem
```
This …
=> support user-defined partition numbers for GPT disks

stages/org.osbuild.ostree.config, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
See https://github.com/ostreedev/ostree/pull/2705 and also https://github.com/osbuild/osbuild/issues/1566.
=> stages(ostree.config): support setting sysroot.bootprefix

stages/org.osbuild.container-deploy
This stage was failing for me in bib, with this change I now get more useful information from podman's stderr, e.g.:
```
RuntimeError: Failed to mount image (125): time="2024-02-06T14:23:06Z" level=error msg="Unmounting /var/lib/containers/storage/overlay/06456126e7c06cf1b21de024e08e64eddead2b8d03779be213e63aeeea9dec94/merged: invalid argument"
Error: creating overlay mount (...snip...)
fuse: device not found, try 'modprobe fuse' first
fuse-overlayfs: cannot mount: No such file or directory
```
=> container-deploy: Output stderr on failure

stages/org.osbuild.zipl.inst, stages/test/test_zipl_inst.py
In some cases it could useful to add additional kernel options without
modifying BLS config, so any subsequent call to `zipl` would ignore them.
We are going to use this to append `ignition.firstboot` to kernel cmdline
for CoreOS on s390x.
=> stages(zipl.inst): support appending kernel options

stages/org.osbuild.copy
It seems like an artifical limitation to prevent copying from one location in the tree to another. It just so happens we need this functionality when building CoreOS images because we want to take a file embedded in the OSTree at a location and copy it to another location in the tree. The particular example here is we want to copy /usr/share/coreos-assembler/platforms.json -> /boot/coreos/platforms.json See https://github.com/coreos/coreos-assembler/pull/3709
Allowing to copy from/to the tree we can now do something like:
```
- type: org.osbuild.copy
options:
paths:
- from: tree:///usr/share/coreos-assembler/platforms.json
to: tree:///boot/coreos/platforms.json
mounts:
- name: ostree.deployment
type: org.osbuild.ostree.deployment
options:
deployment:
ref: ostree/1/1/0
osname: …
```
=> stages(copy): allow copying from a mount or the tree

mounts/org.osbuild.ostree.deployment, osbuild/util/ostree.py, stages/org.osbuild.bootupd, stages/org.osbuild.fstab, stages/org.osbuild.ostree.aleph, stages/org.osbuild.ostree.fillvar, stages/org.osbuild.ostree.selinux, stages/test/test_bootupd.py, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml, test/mod/test_util_ostree.py
This adds a `default: true` option for all cases where OSTree information is specified in schemas and allows for the information to be picked up from the filesystem.
This is a safe operation because when building disk images there is no known case where having two deployments makes sense. In the case there ever were a case then the osname, ref, and serial options still exist and can be used.
=> ostree: add convenience function for using default OSTree deployment

stages/org.osbuild.qemu, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
Modify the stages/org.osbuild.qemu stage such that compression is optional. This resolves the image size differences between an image built with coreos assember vs osbuild, as discussed in: [coreos/fedora-coreos-tracker#1653 (comment)](https://github.com/coreos/fedora-coreos-tracker/issues/1653#issuecomment-1928342241)
=> stages/org.osbuild.qemu: make qcow2 compression optional

osbuild/buildroot.py, stages/org.osbuild.bootc.install-to-filesystem, stages/test/test_bootc_install_to_fs.py, test/data/manifests/manifest.json, test/data/manifests/manifest.mpp.yaml, tools/osbuild-mpp
Support the `bootc install to-filesystem` capability to install a bootc image to a filesystem.
This is base on the excellent work of @ondrejbudai and now that his tweak to include `boot install to-filesysystem --source-ref=` has landed in  https://github.com/containers/bootc/pull/263 we can move to utilize bootc directly.
[edit: this is ready now, thanks to the help of @achilleas-k with the stage test!]
=> stages: add new `org.osbuild.bootc.install-to-filesystem`

mounts/org.osbuild.ostree.deployment, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
We need to pass in the root of the ostree deployment which can be the tree or the mount. Fixes e1cbf92
=> mount/ostree.deployment: Fix ostree deployment call

tools/osbuild-depsolve-dnf
This reverts commit e023fdec1b641ca97e75b17b3759bb4aa2da6e34.
Ends up this was based on an older version of dnf-json, the correct behavior is to use the "install_weak_deps" bool.
=> Revert "osbuild-depsolve-dnf: port weak dependencies"

osbuild/testutil/__init__.py, stages/org.osbuild.container-deploy, stages/test/test_container_deploy.py, test/mod/test_testutil_mock_command.py
I promised to write a small test for the podman mount error handling in https://github.com/osbuild/osbuild/pull/1571. This PR contains a new helper `testutil.mock_command` to create fake commands for things in PATH and a test that ensures that the error messages are handled correct from podman. This lead to a small tweak in deploy-container so that the code only `podman umounts` if the `podman mount` was successful.
=> stages,testutil: add test/tweak for podman mount errror handling

stages/org.osbuild.bootc.install-to-filesystem, stages/test/test_bootc_install_to_fs.py
The bootc.install-to-filesystem code needs to run against the root directory of a mounted tree, i.e. with /boot, /boot/efi mounted. So change the code so that the target dir is the the "mounts" paths. This is similar to how bootupd works and the caller need to arrange the right mount setup there.
This was discovered during the final end-to-end work of osbuild+images+bib
=> stages/bootc.install-to-fs: fix root mount handling

tools/osbuild-depsolve-dnf5
Typo in the previous change, wasn't setting `repo.module_hotfixes`
=> osbuild-depsolve-dnf5: module_hotfixes wasn't really set

tools/osbuild-depsolve-dnf5
Substitutions should be set on Base, not per-repo. Discovered this in lorax's dnf5 code so I am updating it here as well.
=> osbuild-depsolve-dnf5: Fix url substitutions

tools/check-snapshots, tools/gen-stage-test-diff, tools/osbuild-depsolve-dnf5, tools/osbuild-mpp, tox.ini
During the review of https://github.com/osbuild/osbuild/pull/1598 we noticed that tools is not checked by pylint (and the other linters).
This PR adds it back and fixes the issues that pylint found.
For the non-obvious changes I added comments in the commit message and I'm happy (of course) to change/adjust the changes as needed.
One issue that this PR may have is that it uses "tox-backticks" in tox.ini. AFAIK this is only available via pip but not packaged. If this is a problem the way to re-enable pylint (and friends) needs to be re-evaluated.
=> tox,tools: add tools back to lintables

stages/org.osbuild.dracut
As an alternative to just initramfs. Upstream initoverlayfs project:
https://github.com/containers/initoverlayfs
=> stages/dracut: Add functionality to build initoverlayfs with dracut

stages/org.osbuild.ostree.deploy.container
This stage crashes when using `containers-storage` if `/var/tmp` doesn't exist, since the directory is required by `skopeo` for big files. See:
https://github.com/containers/image/blob/4ad2f46269f1a1f6ad4067e418b820a1b3453615/storage/storage_src.go#L163
https://github.com/containers/image/blob/2cb3c9d3c29dc1c23b45f93abeed9b3f57f6a8b4/internal/tmpdir/tmpdir.go#L18
=> stages/ostree-container-deploy: make sure `/var/tmp` exists

sources/org.osbuild.containers-storage
The source implementation used `subprocess.run()` argument `capture_output`, which was added in Python 3.7. Since the minimum supported Python version for osbuild on RHEL-8 is 3.6, the source fails with TypeError.
Example failure: https://artifacts.dev.testing-farm.io/c147b608-c40e-46ed-bf11-6b15ecf718dc/
=> Sources/containers-storage: make the code Python 3.6 compliant

osbuild/util/bls.py, stages/org.osbuild.coreos.platform, stages/org.osbuild.kernel-cmdline.bls-append, test/data/manifests/fedora-coreos-container.json, test/data/manifests/fedora-coreos-container.mpp.yaml
- Process all necessary operations related to CoreOS platforms is crucial and specific to CoreOS. This step is essential for CoreOS exclusively.
- Our approach to handling 'platforms.json' may change as we advance with the OSBuild work. However, we don't have a clear vision about how it will be in the future yet, particularly as we also manage similar components within the osbuild composer to configure cloud parameters. We probably will know better when we start working with the cloud artifacts.
As a summary, let's add it know to unblock us, and if we find a better approach in the future we can always go back and remove it.
=> Add coreos.platforms stage

inputs/org.osbuild.containers-storage, inputs/test/conftest.py, inputs/test/test_containers.py, osbuild/util/containers.py, sources/org.osbuild.containers-storage, sources/test/test_container_storage_source.py, tox.ini
This PR tweaks the excellent work from Gianluca in PR#1550 a
little bit. Now that the container inputs are their own input
type some of the code that used to be part of the original
`inputs/org.osbuild.containers` can be simplified.
It also contains some small misc tests, string/comment updates.
All in their own commits but I can break into multiple PRs for easier
reviews if desired.
=> many: tweak `containers-storage` implementation

stages/org.osbuild.tar, stages/test/test_tar.py
Add a sparse option to the tar stage which make files in the archive sparse if they are sparse on disk. This is needed for CoreOS Assember.
=> stages/org.osbuild.tar: add sparse option

stages/org.osbuild.gzip, stages/test/test_gzip.py, test/data/stages/gzip/b.json, test/data/stages/gzip/b.mpp.yaml
Allow compression level to be specified instead of defaulting to 1. This is needed for CoreOS Assembler.
=> stages/org.osbuild.gzip: add compression level option

.github/workflows/test.yml
With fedora moving to python3.12 we can stop testing on py311.
As a drive-by this commit also documents why we need to test on py36 and py39.
=> workflow: drop python3.11 from matrix (HMS-3697)

.github/workflows/generate.yml, tools/osbuild-mpp
The `Test Data` action takes an incredibly long time to run (2h+).  This job generates all test manifests (mpp.yaml -> json) which involves a lot of depsolving, but it still shouldn't be taking this long.
To speed up the job:
1. ~~Run the generation in parallel (`make -j4`)~~ (Removed: No noticeable improvement)
2. Share the cache across runs
3. Disable zchunks in dnf which causes a lot of slowdowns when caches are shared across architectures
In the very near future we should remove the dnf depsolver from osbuild-mpp and use osbuild-depsolve-dnf instead.
=> workflow, osbuild-mpp: run with cache (HMS-3697)

.github/workflows/test.yml
Assemblers are only used in v1 manifests, so they only need to be tested against a single Python version, i.e. 3.6 (RHEL8).
=> actions/test: Only test assemblers in Python 3.6 (HMS-3697)

.github/workflows/test.yml, test/run/test_assemblers.py
Use the OSBUILD_TEST_STORE in the test_assemblers.py file too and re-use already downloaded sources.
This reduces the time from 46min to 16min now and adding the locking to the LoopControl in the assembler tests hopefully fixed the races we saw earlier.
=> test: use OSBUILD_TEST_STORE in test_assemblers.py and run in parallel (HMS-3697)

.gitlab-ci.yml, test/cases/ostree-images
- Drop testing Fedora ostree artifacts on RHEL
- Run the ostree tests in parallel to make them faster
- Increase the "paralleliness" of the manifest tests to make them faster
=> tests: improve the gitlab tests (HMS-3697)

.gitlab-ci.yml, schutzbot/update_github_status.sh
This is the same change we made in osbuild/images#369.
Never update the GitHub status at the end of a job. Instead, let the job retry and if another failure occurs, when everything is done, the fail job will run in the finish stage and update the status accordingly.
Then we can add retries for any unreliable jobs and avoid registering an early failure before the job is retried so we could then enable a merge-queue for the repository.
=> tests: Report GitLab job failures globally (HMS-3697)

.ruff.toml, Makefile, osbuild/meta.py, osbuild/util/ostree.py, tools/osbuild-dev, tox.ini
This PR aims to make some things faster, it now provides a `make lint-quick` Makefile target that can be used in local pre-commit checks that only checks:
1. Import sorting.
2. Most of pylint.
`make lint` takes about 45 seconds to run on my system, `make lint-quick` takes about 0.3 seconds on my system but does require one to `dnf install ruff`.
This PR might grow to also do formatting through `ruff` as `autopep8` is broken for Python >= 3.12.
Aside from providing the new `lint-quick` target this PR also removes `isort` as it can be done to the same effect with `ruff` everywhere.
=> lint: replace `isort` with `ruff` and provide `lint-quick` (HMS-3697)

.github/workflows/test.yml
Before this commit GitHub Action runs that were triggered by a PR were not canceled when updates were made to the same PR. This lead to even more clogging of our pipelines and not enough runners being available.
This changes the behavior in a way that whenever a PR gets updated all still-in-progress runs get canceled and new runs get spawned.
=> tests: Cancel in-progress tests on PR updates (HMS-3697)

.github/workflows/test.yml, test/run/test_assemblers.py
This reverts commit ea36e25b09a3eb0bd2424361d9fd2f48ab3c3dfd.
It turns out that the assemblers test is (too) racy, I suspect that this is actually a real bug in our org.osbuild.qemu assembler and/or in remoteloop.py but given that we do not use assemblers anymore it's hard to justify spending too much time on this.
But I'm very sad about it.
=> tests: revert "workflow: run assembler tests in parallel" /o\

.github/workflows/test.yml, test/run/test_assemblers.py
The `test_assembler.py` hardcods some filesystem and partition UUIDs. This leads to hard to diagnose test failures when the test is run in parallel. The btrfs and xfs filesystem drivers will see the same uuid for multi created images and error sometimes with someting like:
```
Mar 06 10:22:54 top kernel: BTRFS error: device /dev/loop104 belongs to fsid aff010e9-df95-4f81-be6b-e22317251033, and the fs is already mounted, scanned by mount (123856)
```
Its a race that only happens when two images are checked at the same time.
This commit fixes the issue by just using a randomized UUID in the test_assemblers.py. It also re-enables running the test in parallel (which make it run a lot faster, from 34min to 14min).
=> test: fix test_assembler to support parallel runs and run in parallel (HMS-3697)

.gitlab-ci.yml
Nothing else seems to rely on the image-info generated by the manifest tests, so let's not retain those artifacts. This currently makes the `finish` stage take 6 minutes for no good reason.
=> tests/manifest: Don't retain image-info artifacts (HMS-3697)

osbuild/util/containers.py, osbuild/util/mnt.py, stages/org.osbuild.bootupd.gen-metadata, test/mod/test_util_mnt.py
This is a follow up to #1550 where we enabled a `rw` permissions mode, which is not ideal since it would theoretically be possible to set both `ro` and `rw` modes at the same time. This commit fixes the issue by only allowing one option at a time.
Fixes #1588
=> utils/mnt: fix mount permissions

sources/org.osbuild.curl, sources/test/test_curl_source.py
If `org.osbuild.mtls` is passed as a secret name, look for the mtls data in the environment.
---
This is just a proposal, I'm not sure if there's a more elegant way to pass in secrets.
=> sources/curl: add org.osbuild.mtls secrets support

stages/org.osbuild.kickstart, stages/test/test_kickstart.py
Allow passing the `noswap` option to `autopart`. This is to allow for the kickstart setup for https://github.com/osbuild/images/issues/309
=> stages/kickstart: add `noswap` to `autopart`

osbuild/buildroot.py, test/mod/test_buildroot.py
Colin asked for this in
https://github.com/osbuild/bootc-image-builder/issues/223 and it's easy enough.
=> osbuild: ensure a usable /var/tmp is available inside the buildroot

.github/workflows/test.yml
There were special cases in the workflow for only running specific tests in parallel. However how that the test_assemblers parallel runs are fixed [0] there is really no need for special cases anymore and we can just run them all in parallel.
[0] https://github.com/osbuild/osbuild/pull/1641
=> workflow: run all unit tests in parallel

stages/org.osbuild.users, stages/test/test_users.py
Add the expiredate field to the users option in the org.osbuild.users stage. This option maps to the --expiredate option of useradd/usermod, which can be useful when creating users whose password must be changed upon first login. Fixes #1639
=> stages/org.osbuild.users: add expire date

osbuild/loop.py, test/mod/test_loop.py
This reverts commit 158acaac785056132bffa777755d93e490e2e2d6.
With https://github.com/osbuild/bootc-image-builder/pull/238 the original reason to call mknod goes away so we can just revert it. osbuild now requires not only the loop device but also uses `losetup --partscan` quite a lot now so the mknod approach becomes impractical and the consumers of osbuild in a container should just setup devtmpfs.
This also fixes the issue that @supakeen raised that the mknod call is risky and racy and interferes with udev.
=> Revert "osbuild: ensure loop.Loop() has the required device node"

tox.ini
Trivial PR to update pycodestyle so that we have working python3.12 autopep8 (see https://github.com/hhatto/autopep8/issues/712)
=> tox.ini: update autopep8/pyocdestyle to support py3.12

stages/org.osbuild.bootc.install-to-filesystem, stages/test/test_bootc_install_to_fs.py
To start using the `bootc.instal-to-filesystem` stage we need
to be able to test the generated images. This requires a login
on the disk. Traditionally we did that via the `users` stage.
But on a bootc system we do not want to modify the disk after
bootc did the install to avoid messing with things like the
selinux labels or (future) fsverity setups.
So for now we will use the `--root-ssh-authorized-keys` feature
to inject support for login.
This PR adds two options:
- support injecting the root ssh keys via --root-ssh-authorized-keys
- support adding kernel-options via  --kopt 
The last one is not strictly needed and we could do without it for now (can be a separate PR or YAGNI)
[edit: https://github.com/osbuild/images/pull/462 is updated for this too]
=> stages: add support for  options to bootc-install-to-fs

inputs/test/test_containers.py, osbuild/testutil/__init__.py, sources/test/test_container_storage_source.py, stages/test/test_container_deploy.py, test/mod/test_testutil_make_container.py
The current `make_container()` helper is a bit silly (which is entirely my fault). It requires a container tag as input but all tests end up creating a random number for this input. So instead just remove the input and return the container_id from the podman build in the contextmanager and use that.
=> test: return container_id in `make_container`

osbuild/testutil/__init__.py, stages/test/test_users.py, test/mod/test_testutil_mock_command.py
During the review of https://github.com/osbuild/osbuild/pull/1648 we noticed a small gap in the way we test external programs. This PR helper improving this by allowing to mock real commands instead of mocking subprocess.run
=> stages: add functional user expiredate tests

osbuild/sources.py, sources/org.osbuild.containers-storage, sources/org.osbuild.curl, sources/org.osbuild.inline, sources/org.osbuild.ostree, sources/org.osbuild.skopeo, sources/org.osbuild.skopeo-index, sources/test/test_curl_source.py
The curl source is the only source that uses "transform". And here the name is very generic but in fact we only do a single thing:
we add secrets for subscriptions for for mtls to the download.
So rename to make it clear what this is all about.
Split out from https://github.com/osbuild/osbuild/pull/1573 as it's unrelated and will make reviews for the other simpler.
=> sources: transform() is only used in the curl sources, remove  from ABC and rename

.github/workflows/generate.yml
There are recent GH failures because the github cache action complains:
```
Input required and not supplied: key
```
This is slightly odd as we did not provide a cache key before and it was fine but *shrug*. We also don't really need a cache key, we always get the same cache, osbuild is smart enough to figure it out.
=> github: add cache key to generate.yml flow

osbuild/util/selinux.py, stages/org.osbuild.selinux, stages/org.osbuild.selinux.meta.json, stages/test/test_selinux.py, test/mod/test_util_selinux.py
This option allows to exclude paths like  `/sysroot` from the
selinux labeling. This is needed because on a mounted `bootc` container `setfiles`
without excluding `/sysroot` will create many warnings like:
```
setfiles: conflicting specifications for /run/osbuild/tree/sysroot/ostree/repo/objects/00/0ef9ada2ee87792e8ba21afd65aa00d79a1253018832652b8694862fb80e84.file and /run/osbuild/tree/usr/lib/firmware/cirrus/cs35l41-dsp1-spk-prot-103c8b8f-r1.bin.xz, using system_u:object_r:lib_t:s0.
=> stages(selinux): add option exclude_paths

osbuild/buildroot.py, test/mod/test_buildroot.py
This is a followup for https://github.com/osbuild/osbuild/pull/1649
Instead of symlinking /var/tmp to /tmp which may be on a tmpfs this commit puts it on a real filesystem.
This should fix:
https://github.com/osbuild/bootc-image-builder/issues/285
=> osbuild: ensure /var/tmp is a real directory

.gitlab-ci.yml, Schutzfile, schutzbot/manifest_tests.sh
Migrate manifest tests to RHEL GA 8.9 and 9.3
Related ticket: [COMPOSER-2156](https://issues.redhat.com/browse/COMPOSER-2156?filter=-1)
=> tests: migrate manifest tests

osbuild/buildroot.py
When moving to `bootc install to-filesystem` we need more information for bootc from /etc/selinux than our current /etc/selinux/targeted/contexts policy.
This commit makes all of /etc/selinux available which unblocks the bootc install.
=> osbuild: make the entire /etc/selinux avaialble for the buildroot

.github/workflows/test.yml
Followup of PR https://github.com/osbuild/osbuild/pull/1676
re-run of #1680
Fixing parallel run of tests that can handle it.
=> workflow: re-enable parallel runs to improve speed of test_stages and test_assemblers

Makefile
Stage tests are located in the other place than module or run tests. For consistency separated target in makefile is added.
=> test: Add stage test trigger to makefile

stages/org.osbuild.bootc.install-to-filesystem, stages/test/test_bootc_install_to_fs.py
By default "bootc" will refuse to work on a non-selinux system if the bootc container requires selinux. This is a sensible approach in general but for us it's tricky because we want to be able to generate images when running on developer machines or CI machines that may not necessarily have selinux. So make bootc more relaxed.
Fwiw with the recent improvements in bootc this seems to be working fine for me (i.e. installing from non-selinux).
Note that once https://github.com/containers/bootc/pull/420 is available in our various downstreams this can be dropped.
=> stages: allow bootc.install-to-filesystem work without selinux (HMS-3453)

tools/osbuild-mpp
This way we can extract this information later on.
=> osbuild-mpp: Expand information in PkgInfo

inputs/test/conftest.py, inputs/test/test_containers.py, osbuild/testutil/__init__.py, sources/test/conftest.py, sources/test/test_container_storage_source.py, sources/test/test_curl_source.py
The code to create tests for inputs/sources is a bit repetitive and uses many {Inputs,Sources}Service.from_args() that are just scaffolding to setup the test. This PR consolidates them all into a single (well, two) fixtures to avoid distracting.
People might consider this too much magic, which is fine, in this case I would just open the first commit as I think it is useful to consolidate the helper for the fd into a single place.
=> inputs,sources: add new `{inputs,sources}_service` fixtures

sources/test/test_curl_source.py
There was a regression with the secrets adding of rhsm for the curl source. This was my mistake (sorry!). Here is a regression test that would have prevented this (if we have had it earlier).
=> sources: add regression test for issue#1693

stages/org.osbuild.selinux.meta.json, stages/org.osbuild.users.meta.json, stages/test/conftest.py, stages/test/test_selinux.py, stages/test/test_users.py
When moving to `bootc install to-filesystem` we will need support
for mounting the deployed disk and writing to the deployment root
this requires that we teach the users and selinux stages to
have them available. This is a first step towards this.
It also adds tests to ensure the options can be passed.
The next PR will build on top of this and add a concept of an alternative "tree" dir so that users/selinux can be pointed to "mount://bootc-deploayment-root/" instead of the normal tree dir.
=> stages: move users/selinux to v2 and add devices/mounts support

osbuild/testutil/net.py, sources/test/test_curl_source.py
When moving to parallel downloads in curl we will need more
comprehensive tests. This commits starts with building some
infrastructure for this.
=> source: add curl test in preparation for #1573

sources/org.osbuild.curl
For some context, there are some repositories hosted in consoledot, and the stage ones  not only require MTLS, but also require a proxy to contact them.
=> sources(curl): set HTTP proxy through the environment

osbuild/testutil/atomic.py, osbuild/testutil/net.py, sources/test/test_curl_source.py, tox.ini
The existing code in the reqs counting is not really thread safe, this commit fixes that.
(Small followup to https://github.com/osbuild/osbuild/pull/1703#discussion_r1550058515)
=> testutil: add AtomicCounter() as a threadsafe counter

stages/org.osbuild.mkdir.meta.json
This allows to combine `org.osbuild.mkdir` with the `osbuild.deployment` mount and with the upcoming `org.osbuild.bind` mount. The use case is that we need to create the dir `/var/home` so that `useradd` from inside a ostree root works (there /home is a symlink and useradd will not follow the symlink and create a dir in the target by itself).
This allows to write:
```json
{
"type": "org.osbuild.mkdir",
"options": {
"paths": [
{
"path": "/var/home"
}
]
},
"devices": {
"disk": {
"type": "org.osbuild.loopback",
"options": {
"filename": "disk.raw",
"partscan": true
}
}
},
"mounts": [
{
"name": "part4",
"type": "org.osbuild.ext4",
"source": "disk",
"target": "/",
"partition": 4
},
{
"name": "part3",
"type": "org.osbuild.ext4",
"source": "disk",
"target": "/boot",
"partition": 3
},
{
"name": …
```
=> stages(mkdir): allow to pass in devices/mounts

stages/test/test_mkfs_xfs.py
Add stage unit test for mkfs.xfs
=> Tests: Add unit tests for org.osbuild.mkfs.xfs stage

tools/osbuild-depsolve-dnf, tools/osbuild-depsolve-dnf5
---
To depsolve with snapshots generated on consoledot, we need to go via a proxy. But the proxy can't be set system-wide because that breaks some calls of the aws sdk.
=> osbuild-depsolve-dnf(5): support proxy

tools/osbuild-depsolve-dnf, tools/osbuild-depsolve-dnf5
The "main" branch is failing right now in tests. The reason is that we do not have a merge queue and when
https://github.com/osbuild/osbuild/pull/1715
was merged we had no test for `osbuild-depsolve-dnf` yet.
We have one now (THANK YOU achilleas-k) and it shows an issue :)
This commit fixes the issue.
=> tools: fix proxy key error when "proxy" is not set

mounts/org.osbuild.bind, mounts/test/conftest.py, mounts/test/test_bind.py, tox.ini
[draft: to get early feedback, I think adding a few more test cases would make sense here too but it should be okay]
[edit: the remaining issue is that org.osbuild.user may need to be able to create /var/home as useradd will not follow symlinks when creating dirs]
This adds a new `org.osbuild.bind` mount feature to the osbuild
mount modules. This allows to (r)bind mount parts of another mount
into the tree (or replace the default tree for a stage entirely).
The use case is the `bootc install to-filesystem` where we get
a populated disk and need to do customizations directly there
without going through an intermediate tree.
Note that right now only "--rbind" is supported and used but
we could trivially change that to become an option in either
direction. Given that the main use-case right …
=> mounts: implement new `org.osbuild.bind` mount

tools/osbuild-depsolve-dnf, tools/osbuild-depsolve-dnf5
Originally, I made releasever required only when root_dir was set.  This was initially done to maintain backwards compatibility but we broke that already and osbuild/images will always include releasever in the request.
This will conflict with #1721 so maybe we can pull this commit into that PR (@mvo5?).
=> tools/osbuild-depsolve-dnf(5): require releasever

osbuild/main_cli.py
Add a new line to after a successful build and before the final output is printed to the terminal. Since the final build output and the "manifest finished successfully" line were being printed to the same line.
=> osbuild: fix newline issue with final output 👀 

tools/test/test_depsolve.py
tools: tweak repo_servers_fixture() to redirect stderr to  /dev/null
The default python http.server is very chatty, we don't need this
during the tests.
---
[PATCH] tools: tweak depsolve() helper to show stderr from depsolve
So that we see any error output during the tests in "realtime". With
subprocess check=True and capture_output=True on exit_code != 0 no
stderr as part of the exception by default so this change helps
seeing issues from depsolve-dnf more easily.
=> test: tiny tweaks for the output handling in the test_depsolve.py 

stages/org.osbuild.groups.meta.json, stages/test/test_groups.py
This will allow us to generate `bootc install to-filesystem` compatible devices/mount setups for the groups stage.
=> stages(groups): add support for the mounts for `bootc install to-filesystem` 

stages/org.osbuild.cloud-init.meta.json
Add "Ec2" and "None" datasources, which is needed for RHEL-7.9 EC2 images.
=> Stages/cloud-init: support additional datasources (COMPOSER-2060)

osbuild/meta.py, test/mod/test_meta.py
[as suggested in https://github.com/osbuild/osbuild/pull/1726#pullrequestreview-2000367493]
[edit: note that if we merge this we should simplify org.osbuild.{selinux,users,groups}.meta.json to remove the now redudant/identical schemas for devices/mounts]
With the new `bootc install to-filesystem` support many stages will need a devices/mount setup to bind mount the deployment root from the bootc deployment root of the generated image. To make this globally available just allow "devices/mounts" for all stages in the schema validation.
Note that `mounts` is already globally allowed so this just adds devices (this was added in `7e776a076` with ostree as the use-case). Nothing will change for the filesystem stages that already define "devices" in a more specialized way.
=> meta: automatically allow `devices` as input in the stages schemas

stages/org.osbuild.bootc.install-to-filesystem, stages/org.osbuild.bootc.install-to-filesystem.meta.json, stages/test/test_bootc_install_to_fs.py
We currently do not set the `--target-imgref` and do not allow to override it. This means that on a fresh deploy it is set to an incorrect value. This commit allows to set it via the org.osbuild.bootc.install-to-filesystem stage.
We may need to make this as strict as in https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.ostree.deploy.container.meta.json#L37 ?
=> stages: add support for `--target-imgref` to bootc install to-filesystem

Makefile
The current `make test-all` will only run tests under `test/`. This is no longer the only place we have tests so update the code to just run `pytest` to collect all tests.
=> Makefile: make sure that `make test-all` really runs all tests

stages/org.osbuild.systemd.unit.create, stages/org.osbuild.systemd.unit.create.meta.json, stages/test/test_systemd_unit_create.py
**stage/systemd.unit.create: add After option**
Support the After option in the Unit section of the unit file.
---
**test/systemd_unit_create: Wants, Requires, After**
Add test values for Wants, Requires, and After.
Adding multiple values to test that arrays work and made sure they're
all different.
The units need to be valid, real unit names otherwise the
'systemd-analyze verify' check will fail.
---
**stage/systemd.unit.create: move systemd-analyze verify to tests**
Verifying the systemd unit also checks if any referred systemd units
(Wants, Requires, After) exist and if all commands in Exec exist and are
executable.  Without '--root', the systemd-analyze verify command is
testing this against files in the build root, which isn't valid.
Units and binaries might not exist in the build …
=> systemd.unit.create: support the After option in the Unit section (HMS-3814)

stages/org.osbuild.kickstart, stages/org.osbuild.kickstart.meta.json, stages/test/test_kickstart.py
This commit allows use to append kernel commandline options via the kickstart file. This is useful for e.g. the bootc installer where we support customizing this via blueprints.
=> stages: allow `bootloader --append` via kickstart

osbuild/testutil/imports.py, stages/org.osbuild.selinux, stages/test/test_selinux.py
Previously, the SELinux stage would not force full contexts reset when forcing auto-relabel on first boot. As a result, all files remained `unconfined_u` after the auto-relabeling on first boot and only the type part was reset.
We really need to mimic the behavior of `fixfiles -F onboot` command, which creates the `/.autorelabel` file with "-F" in it.
=> Stages/SELinux: force auto-relabel of full contexts

test/mod/test_util_mnt.py
Latest util-linux mount uses fsconfig(2) instead of mount(2) so the error is different.
See https://artifacts.dev.testing-farm.io/53b552b6-5753-47e2-9cd0-43fa8b6e5f9f/
Closes: https://github.com/osbuild/osbuild/issues/1753
=> osbuild: fix error match in mount test for rawhide

.github/workflows/test.yml
In PR#1752 @schuellerf  noticed (thanks!) that `make_containers` is buggy [0] in one specific testcase. However the GH actions did not trigger and uppon inspection the test is skipped:
```
stages/test/test_container_deploy.py::test_container_deploy_integration SKIPPED [  7%]
```
This commit adds `-rs` to get a summary why the tests are skipped.
This is useful in general, I suspect the test container might miss podman but this commit will bring clarity:
```
2024-04-25T08:35:39.1993788Z SKIPPED [1] stages/test/test_container_deploy.py:17: no podman executable
2024-04-25T08:35:39.1994811Z SKIPPED [1] stages/test/test_container_deploy.py:59: no podman executable
```
[0] https://github.com/osbuild/osbuild/pull/1752#discussion_r1578294358
=> workflow: show summary why tests are skipped

osbuild/testutil/__init__.py, test/mod/test_testutil_make_container.py
During the work on PR#1752 Florian discovered that make_containers() is broken for nested containers like:
```
with make_container(tmp_path, {"file1": "file1 from base"}) as base_tag:
with make_container(tmp_path, {"file1": "file1 from final layer"}, base_tag) as cont_tag:
```
It errors with:
```
Error: 5b947de461ee21b858dd5b4224e80442b2f65b6410189147f2445884d9e4e3d8: image not known
```
The reason is that we work with hashes for the image and then call `podman image rm` which by default will also remove all dangling references. Those are defined by not having a tag and not referenced anymore. So the inner container cleanup also removes the outter.
There are many ways to fix this, I went with re-adding tags to the test containers because it also makes it easy for the user to see if we …
=> testutil: fix `make_container()` cleanup

stages/org.osbuild.skopeo, stages/org.osbuild.skopeo.meta.json, stages/test/test_skopeo.py
Skopeo support destination dir mainly to check if this works for signatures as expected
implemented oci-archive as it could also be helpful and should be simple
=> stages: add support for destination {dir,oci-archive} to the skopeo stage

.gitlab-ci.yml
F40 is safe to use again
This reverts commit dc857025530354984912a6400929b9ca494e29e1.
=> Revert "Disable F40 CI (CVE-2024-3094 response)"

sources/org.osbuild.curl, sources/test/test_curl_source.py
Currently, osbuild downloads are identified as coming from `curl`. This
is unfortunate because some RPM mirrors block requests from curl. Let's
"fix" that by introducing our own user-agent. While this can certainly
be seen as "circumventing" a policy, I think that this change is
actually helpful: Now, the mirror maintainers can actually distinguish
osbuild requests from regular curl calls. If they want to block osbuild,
they certainly can, we have no power there, but at least this allows
more fine-grained filtering.
Thanks @supakeen and @mvo5 for your suggestion!
=> sources/curl: Use our own User-Agent

stages/org.osbuild.skopeo, stages/test/test_skopeo.py
It's defined on the options level, not on the destination level. The first commit adds a quick and dirty test for this, the second commit fixes that.
=> stages/skopeo:  Fix the remove-signatures option

osbuild.spec
On Fedora 40 we switched to dnf5 too early. There is going to be a new version in Fedora 41 soon, with breaking API changes, so in order to reduce the number of things we need to support, switch back to using libdnf on Fedora 40 (and 41 until dnf5 version 5.2.0 is available, see #1768)
=> spec: Install osbuild-depsolve-dnf not dnf5

.github/workflows/test.yml, test/mod/test_util_mnt.py
This will include the latest osbuild-ci container changes from https://github.com/osbuild/containers/pull/73
This includes a bunch of binaries that were missing and lead to skpped tests.
=> workflow: bump osbuild-ci container to include podman, et al.

stages/test/conftest.py, stages/test/test_groups.py, stages/test/test_selinux.py, stages/test/test_users.py, test/mod/test_meta.py
With PR#1727 merged `devices` are now automatically added to all
stage schemas. This makes the existing schema entries of the form:
```json
...
},
"devices": {
"type": "object",
"additionalProperties": true
},
"mounts": {
"type": "array"
}
...
```
redundant. This commit removes them. There are still some left
that are more specific (e.g. for filesystems) than this generic
one.
Note that `mounts` was already part of the stages schema automatically
since https://github.com/osbuild/osbuild/pull/847 (2021).
---
It also removes the stage specific tests for checking that our required bootc devices/mounts get accepted by the schema and moves that into the `test/mod` as it's now a generic module functionality.
=> stages: remove redundant entries of devices/mounts in schemas

test/data/stages/README.md
Readme was pointing to the dead ling with manifest v2 documentation. I have redirected it to the documentation presented in repo.
=> tests: update stage tests readme

test/mod/test_buildroot.py
The motivation for this change is to fix a failing unit test in c9s CI. Specifically an instance of:
https://artifacts.dev.testing-farm.io/2d07b8f3-5f52-4e61-b1fa-5328a0ff1058/#artifacts-/plans/unit-tests https://gitlab.com/redhat/centos-stream/rpms/osbuild/-/merge_requests/135
=> test/buildroot: fix checking /var/tmp mode

osbuild/util/runners.py, runners/org.osbuild.centos9, runners/org.osbuild.fedora30, runners/org.osbuild.fedora38, runners/org.osbuild.rhel81, runners/org.osbuild.rhel82
This reverts commit bc04bfc366ac785810a38a68a66b51a1b346d739.
The `remove_tmpfiles()` helper is nice but it is also problematic because it creates extra output after the command was run and created output. E.g. a test failure on centos stream9 [0]
```
r = root.run(["stat", "--format=%a", "/var/tmp"], monitor)
assert r.returncode == 0
>           assert r.stdout.strip().split("\n")[-1] == "1777"
E           AssertionError: assert '/usr/lib/tmp... such process' == '1777'
E
E             - 1777
E             + /usr/lib/tmpfiles.d/rpcbind.conf:2: Failed to resolve user 'rpc': No such process
```
Here the output from "stat" is not the last output because the rempve_tmpfiles runs `systemd-tmpfiles --clean --remove` which produces some noisy output after stat was run.
This was found by @thozza …
=> runners: revert "runners: clean up temp files before exiting the runner"

test/mod/test_util_mnt.py
The `test_osbuild_mount_failure_msg` currently fails on fc40 when run in tmt, see:
https://artifacts.dev.testing-farm.io/c6588a82-a2cb-46df-8ca8-85dd809465f2/
This is because the failure output is slightly different between a container and a VM/real-machine. The test ensures that we capture the output of mount and present to the user (for easier debugging). So this commit updates this test once more for the error string (that part of the error comes directly from the kernels fsconfig).
If we need another update of the string we should reconsider this test and e.g. just use `testutil.mock_command()` for this. But for now it's easier to just add this one more failure string.
=> test: tweak test_osbuild_mount_failure_msg() for tmt/fc40

tools/osbuild-depsolve-dnf, tools/osbuild-depsolve-dnf5, tools/test/test_depsolve.py
This is required so that callers can enable loading of filelists when using newer versions of libdnf with old repositories or packages that specify dependencies on files.  For example, depsolving against RHEL 9.3 repos on Fedora 40 fails to resolve platform-python with the message
```
nothing provides /usr/libexec/platform-python needed by platform-python-...
```
Further reading:
- https://libdnf.readthedocs.io/en/stable/tutorial-py/#case-for-loading-the-filelists
- https://github.com/rpm-software-management/dnf/releases/tag/4.19.0
- https://dnf.readthedocs.io/en/stable/user_faq.html#starting-with-fedora-40-i-noticed-repository-metadata-is-synchronized-much-faster-what-happened
- https://fedoraproject.org/wiki/Changes/DNFConditionalFilelists
=> tools/osbuild-depsolve-dnf: enable loading of optional metadata

tools/osbuild-depsolve-dnf
The optional_metadata_types option isn't available in older versions of dnf.  We could version-guard the option, but let's be more explicit and check if it exists instead.
If it doesn't we can safely ignore it and rely on dnf's default behaviour.
=> tools/osbuild-depsolve-dnf: ignore optional-metadata for old dnf

test/data/stages/users/diff.json
Since the `/etc/shadow` file contains a timestamp we need to add a `null` value rather than a `sha256` hash to tell the diff tool to ignore these fields. The issue is that the timestamp will always be different meaning the tests will pass for a day, but then fail after that.
=> test/cases: fix users stage

tools/tree-diff
The `tree-diff` tool is used by the `gen-stage-diff` tool to generate the stage `diff.json` files. A few of these stages have timestamped files that need to be edited after the tool is run to replace the `sha256` content hash with `null` so the stage diff tests ignore these files.
This commit updates the `tree-diff` tool to check through a list of the files that contain timestamps and to use the `null` value rather than the `sha256` content hash so the stage tests don't fail.
=> tools/tree-diff: use `null` for timestamped files

osbuild/monitor.py, test/mod/test_monitor.py
Just improve naming of the progress steps…
This is a small preparation for handing over progress towards frontend.
=> osbuild/monitor.py: improve naming of progress

Schutzfile
=> Update snapshots for rhel-9.5 to make them in sync with osbuild-composer

.github/workflows/test-on-centos.yml
In the release loop upstream changes are merged to Centos every two weeks. This creates a delay in error detection when new tests being added upstream.
Running tests in Centos based containers for every pull request should solve the issue.
https://issues.redhat.com/browse/COMPOSER-2125
=> CI: Add testing based on Centos containers (COMPOSER-2125)

sources/org.osbuild.curl, sources/test/test_curl_source.py
Setting the user-agent using `--header` is broken in combination with `--location`, `--proxy`, and an https endpoint which redirects. The user-agent sent to the proxy changes after the client is redirected, tripping up proxies.
For more information see https://issues.redhat.com/browse/RHEL-45364
=> sources/curl: use `--user-agent` option to set the user-agent

stages/org.osbuild.dmverity, stages/org.osbuild.dmverity.meta.json, stages/test/test_dmverity.py
This adds new stage for creating `dm-verity` protected partitions and would be useful for CoreOS with "IBM Secure Execution" (`secex`) images.
=> stages: add stage for creating dm-verity partitions

osbuild/testutil/net.py, sources/org.osbuild.curl, sources/test/test_curl_source.py
This PR is based on the excellent work of @supakeen in https://github.com/osbuild/osbuild/pull/1549 and the findings in https://github.com/osbuild/osbuild/pull/1023
Simon found that curl has a lot of fork/exec overhead in the way we use it. The other issue with our current use of curl is that we do not reuse connections and the overhead of the connection setup (especially for https) is there. 
Newer versions of curl (7.68+) have a nice new feature called `--parallel` that will reuse connections and download 50 streams in parallel by default (this can be controlled via the --parallel-max option). Since we want some more features (like --write-out %{json}) we actually need curl 7.75+ to use --parallel in a nice way. But that is okay because RHEL9/Centos9 have 7.76 as their default (but of …
=> sources(curl): download multiple URLs with the same curl command

sources/org.osbuild.curl, sources/test/test_curl_source.py
Disable `curl --parallel` by default until the failure in https://github.com/osbuild/osbuild-composer/pull/4247
is fully understood. It can be enabled via the environment:
```
OSBUILD_SOURCES_CURL_USE_PARALLEL=1
```
in the osbuild-composer test.
=> sources(curl): disable `curl --parallel` by default

stages/org.osbuild.oscap.remediation
This is a small adjustment to how the `osbuild.util.mnt.mount` fuction is imported. While adding unit tests, the tests failed when trying to patch the function, this commit fixes the issue.
=> stages/oscap.remediation: small import adjustment

sources/org.osbuild.curl, sources/test/test_curl_source.py
As part of the investigation of the CI failure in
https://github.com/osbuild/osbuild-composer/pull/4247 we noticed that curl can return a return_code of `0` even when it did not downloaded all the urls in a `--config` provided file. This seems to be curl version dependent, I had a hard time writing a test-case with the real curl (8.6.0) that reproduces this so I went with mocking it. We definietly saw this failure with the centos 9 version (7.76).
Our current code is buggy and assumes that the exit status of curl is always non-zero if any download fails but that is only the case when `--fail-early` is used.
The extra paranoia will not hurt even when relying on the exit code of curl is fixed.
=> sources(curl): error if curl exists 0 but there are downloads left

stages/org.osbuild.oscap.autotailor, stages/org.osbuild.oscap.autotailor.meta.json, stages/test/test_autotailor.py, test/data/stages/oscap.autotailor-json/b.json, test/data/stages/oscap.autotailor-json/b.mpp.yaml, test/data/stages/oscap.autotailor/b.json, test/data/stages/oscap.autotailor/b.mpp.yaml
We have a bit of a tradeoff with this. On one hand we can can just use the `autotailor` command to override the profile id set by the user in the json tailoring file. We would just need to document this very clearly. The benefit of this is that we can maintain the explicitness of the manifest and we wouldn't have to inspect the generated tailoring XML file for the `tailoring_id`.
The downside is that the user provided `profile_id` from the json contents will get overwritten.
=> Make `tailored_profile_id` required for `json` autotailoring

tools/osbuild-mpp
This commit allows to the user to define the "container-transport" variable when they are defining a container image to be resolved by the osbuild-mpp tool. When the user defines the "container-storage" as "container-transport" osbuild-mpp will look for the image in the local container-storage.
=> mpp: Allow container-storage image resolution

stages/org.osbuild.oscap.autotailor.meta.json, stages/test/test_autotailor.py
There was a small mistake in the schema since either one of `new_profile` or `tailored_profile_id` is required. 
This commit fixes this and updates the tests to check for this case.
=> stages/autotailor: fix stage schema

test/run/test_stages.py
DNF5 contains a breaking change in the repoquery --qf output, specifically it does not include the trailing newline. This breaks the test case e.g. on the latest Fedora Rawhide [1].
As a fix, explicitly use 'dnf4' for now, until the inconsistency is fixed in the upstream [2].
[1] https://artifacts.dev.testing-farm.io/3a3a2898-0a6a-42eb-8792-660f03c35c3c/
[2] https://github.com/rpm-software-management/dnf5/issues/709
=> Test: fix dnf4.mark stage test with DNF5

test/run/test_stages.py
Let's revert to using plain 'dnf', add an explicit newline in the query format and skip empty lines when processing the output. This makes the test case compatible with all DNF versions, even with dnf5 once this issue gets fixed.
The previous approach didn't work on c9s / el9, because there is no
`/usr/bin/dnf4 -> dnf-3` symlink.
Also see:
https://github.com/osbuild/osbuild/actions/runs/10136827918/job/28026181824
Additionally, make the failures to parse dnf output easier by printing the actual line.
=> Fix dnf4 mark stage test

osbuild/main_cli.py, osbuild/monitor.py, test/mod/test_monitor.py
The existing code to record progress was a bit too naive. Instead of just counting the number os pipelines in a manifest to get the total steps we need to look at the resolved pipelines.
with this fix `bib` will report the correct number of steps left when doing e.g. a qcow2 image build. Right now the number of steps is incorrect because the osbuild manifest contains pipelines for qcow2,vdmk,raw,ami and all are currently considered steps that need to be completed. With this commit this is fixed.
C.f. https://github.com/osbuild/bootc-image-builder/pull/525
=> main,monitor: fix total steps in progress reporting

test/run/test_stages.py
When I rolled back from using 'dnf4', to check package markings, to using 'dnf', I didn't verify the test case on Fedora Rawhide with DNF5. It turns out that the strings reported by DNF5 differ and make the test case fail. This time I tested the change on Fedora Rawhide with DNF5 and it works.
See:
- https://src.fedoraproject.org/rpms/osbuild/pull-request/300
- https://artifacts.dev.testing-farm.io/dc84a6c8-1472-452e-8f1d-37255288d996/
=> Test/dnf4.mark: adjust the test for markings used by DNF5

stages/test/test_gunzip.py
This PR adds unit tests for org.osbuild.gunzip stage.
=> Tests: Add unit tests for org.osbuild.gunzip stage

osbuild/solver/dnf.py, osbuild/solver/dnf5.py, tools/test/test_depsolve.py
This commit includes the used sovler in the dnfjson reply. This is mostly information (e.g. in service logs) but also useful in tests to ensure that the expected solver was really run.
Note that this needs https://github.com/osbuild/images/pull/723 first.
=> solver: include "solver" key in the dnfjson reply

Makefile
The spinner is mostly distracting IMHO and it makes the CI logs harder to read as it generates several dozens of lines like:
```
...
⠋ [3/5] pylint | autopep8 | mypy-strict
...
```
I was considering to make it conditional on GH but decided to just disable globally. If someone feels attached to the spinner I only disable it in GH.
=> Makefile: run `tox parallel` without the spinner

test/run/test_stages.py
When subscription-manager DNF plugins are enabled (e.g. on RHEL), they produce messages to the stdout on any DNF command execution. E.g. "Updating Subscription Management repositories.".
Disable all plugins when inspecting package markings so prevent them from modifying the output.
=> test_dnf4_mark(): disable all plugins when inspecting markings

osbuild/inputs.py, osbuild/util/jsoncomm.py, test/mod/test_inputs.py
We recently hit the issue that `osbuild` crashed with:
```
Unable to decode response body "Traceback (most recent call last):
File \"/usr/bin/osbuild\", line 33, in <module>
sys.exit(load_entry_point('osbuild==124', 'console_scripts', 'osbuild')())
File \"/usr/lib/python3.9/site-packages/osbuild/main_cli.py\", line 181, in osbuild_cli
r = manifest.build(
File \"/usr/lib/python3.9/site-packages/osbuild/pipeline.py\", line 477, in build
res = pl.run(store, monitor, libdir, debug_break, stage_timeout)
File \"/usr/lib/python3.9/site-packages/osbuild/pipeline.py\", line 376, in run
results = self.build_stages(store,
File \"/usr/lib/python3.9/site-packages/osbuild/pipeline.py\", line 348, in build_stages
r = stage.run(tree,
File \"/usr/lib/python3.9/site-packages/osbuild/pipeline.py\", line …
```
=> osbuild: make `inputs` `map()` function use fd for reply as well

stages/org.osbuild.dracut, stages/test/test_dracut.py, test/run/test_stages.py
While adding support for `image-installer` image type for RHEL-10, I've ran into multiple issues when trying to boot the Anaconda ISO. One of them was related to Anaconda not being able to parse the kickstart due to missing CA certificates bundle in the initram disk. It turned out that this was caused by the fact that the dracut stage executes the dracut binary in an unsupported environment, which caused it to fail to copy the file into the initram disk.
Fix the stage and extend the unit test to check stage output for suspicious messages.
dracut expects the environment, in which it is run, to have properly mounted `/proc`, `/dev` and `/sys`. Otherwise, some of its modules don't work properly. E.g. dracut fails to embed the CA cert bundle into the initram disk, which means that HTTPS won't …
=> Stages/`org.osbuild.dracut`: fix runtime environment for dracut (COMPOSER-2193)

tools/test/test_depsolve.py
The pytest.skip() argument must be a string.  Calling it with an exception produces an error.
=> test/depsolve: use strings for pytest.skip()

osbuild.spec
osbuild 126 added a new "solver" field in the osbuild-dnf-json output and osbuild-composer only supports this since 116.
This broke production (sorry!). This commit helps mitigate it.
=> osbuild: add "Conflicts"/"Provides" to avoid breaking composer

osbuild/util/chroot.py, stages/org.osbuild.dracut, stages/org.osbuild.update-crypto-policies, test/data/stages/update-crypto-policies/diff.json
**osbuild/util: new module: chroot**
New chroot utility module that sets up a tree with the necessary virtual
filesystems needed for running commands in the root tree in a similar
environment as they would run in the build root.
This is needed for some stages, but may also be used for all chroot
calls to unify the setup and teardown of the root environment.
The Chroot context class was previously part of the org.osbuild.dracut
stage, which was the first stage to need this setup.
---
**stages/update-crypto-policies: use Chroot context**
Recently [1], the update-crypto-policies script added a check to verify
that the FIPS policy was automounted by reading the
/proc/self/mountinfo.  The script will fail if the proc filesystem isn't
available.
Use the new Chroot context to set up the …
=> New utility module: chroot

inputs/org.osbuild.containers-storage, osbuild/util/containers.py, osbuild/util/host.py, osbuild/util/toml.py, sources/org.osbuild.containers-storage, stages/org.osbuild.bootc.install.config, stages/org.osbuild.containers.storage.conf, stages/test/test_bootc_install_config.py, stages/test/test_containers_storage_conf.py, test/mod/test_util_toml.py, tox.ini
The toml module story in osbuild is difficult. Different distro versions have different modules packaged or built-in, sometimes with different capabilities (no writing).  Since we need to support reading and writing toml files both on the host (osbuild internals, sources, inputs) and in the build root (stages), this PR centralises the import decision making in an internal utility module that covers all cases.
The wrapper is quite ugly and there's a few reasons for that.  Two of the modules we might import (`tomli` and `tomllib`) don't support writing, so we need to either import a separate module (`tomli_w`) or raise an exception when `dump()` is called without a write-capable module.  The `tomli` and `tomllib` modules require files be opened in binary mode (not text) while the others …
=> Add toml utility module that wraps every toml Python module ever created

sources/org.osbuild.containers-storage
storage_conf was never not None, so the loading was called every time.
This never crashed because conf was always being set, but it wasn't
working properly regardless.
=> sources/containers-storage: fix load caching

osbuild/main_cli.py, osbuild/pipeline.py, osbuild/sources.py, test/run/test_sources.py
The libdir is passed down for sources but it is never used in any of our sources. As this is confusing and we want to eventually support multiple libdirs remove this code.
It looks like the libdir for soruces was added a long time ago in 8423da368 but there is no indication if/how it is/was supposed to get used and AFACT from going over the git history it was very used.
~Technically it's API break because it was part of the json msg to a source so it could break third party sources modules.~ [actually no, SourceService:dispatch()  never sends it to the actual sources]
=> osbuild: drop `libdir` from `download()` methods

devices/org.osbuild.lvm2.lv, devices/test/test_lv.py
When we create the device node inside the buildroot so far it's
very minimal - just `/dev/{vg}-{lv}` with the appopriate major/minor.
However when mount runs it will create a mapper device with the
same major/minor under `/dev/mapper/{escaped(vg)}-{escaped(lv)}`
and use that to mount the actual filesystem. Without this additional
device findmnt will not be able to detect the udev attributes of
the source (as the source is just missing from /dev).
This commit create the right mapper in the same way that we
create the non-mapper device node.
=> devices: create `/dev/mapper/<logical-volume>` as well

sources/org.osbuild.curl, sources/test/test_curl_source.py
This is a clean version of https://github.com/osbuild/osbuild/pull/1812
Before this gets merged we should:
a) redo a speed test with new curl to ensure we have no regressions in the speed because of the next --nex
b) open the equivalent of https://github.com/osbuild/osbuild-composer/pull/4253 for this PR and ensure all composer tests are green (this is done in https://github.com/osbuild/osbuild-composer/pull/4281 as WIP)
=> sources(curl): use `--next` for each url in curl config

stages/org.osbuild.mkswap, stages/org.osbuild.mkswap.meta.json, stages/test/test_mkswap.py
A stage very similar to the existing mkfs ones (actually, I started from
the xfs one). It creates a swap area on a given device.
I wonder if we should be more strict with the UUID format, but no stage schema currently contains any UUID-format validation, so I did the same.
The test is very similar to the xfs one, which makes me wonder whether we can somehow deduplicate them, but I'm slightly in favor of leaving the duplication in. I like that the tests are currently quite simple.
=> stages: add a new mkswap stage

test/run/test_stages.py
Quick check to see if checkpointing "build" helps with the runtime. Note that the cache size is already 20GB, I doubled it for good measure but we probably can go back to 20, just want to make sure this is not the bottleneck.
Closes: https://github.com/osbuild/osbuild/issues/1874
=> test: checkpoint "build" stage too during `test_stages.py`

osbuild/main_cli.py, test/run/test_noop.py
Current osbuild will always print some non output even when run with `--monitor=JSONSeqMonitor` because of the unconditional `print/sys.stdout.write()` in `main_cli.py`.
This commit adds a new `-q` option to silence this so that something like osbuild-composer can run `osbuild -q --monitor=JSONSeqMonitor` to get pure json-seq output during the build.
The use-case is to run `osbuild --monitor-fd` from e.g. bib and osbuild-composer so that we get pure json from the monitor-fd and anything that goes on std{out,err} can be logged as it is most likely error output.
Companion PR for https://github.com/osbuild/osbuild/pull/1831 - not strictly needed but makes things (IMHO) cleaner.
=> osbuild add new `-q`, `--quiet` option

osbuild/main_cli.py, test/run/test_main.py
The current error message when an export is not found could be improved by printing what exports are actually availalble to make it easier for the user to e.g. spot typos.
[edit: this is ready for review now, I added a small test]
=> osbuild: also print what export is availalble when one is not found

stages/org.osbuild.dmverity.meta.json
We need to pass loopback devices for these properties, but the schema says that there will be a `path` property, so osbuild complains.
osbuild is right of course, but this definitely *did* work in an earlier version, so something changed. Ideally, we'd narrow down here what happened exactly, but at the same time this approach of just making the property more generic matches what's done in e.g. the `zipl.inst` stage where we also use a loopback device.
For reference, this is where we use this stage:
https://github.com/coreos/coreos-assembler/blob/ba45b296ec11734bafcae7728915016f17137a3d/src/osbuild-manifests/platform.qemu.ipp.yaml#L100-L119
=> stages/dmverity: make device objects more generic

test/mod/test_util_chroot.py
Small followup for https://github.com/osbuild/osbuild/pull/1854 which added the return value to `util.Chroot.run`. This commit now adds a (super trivial) test for this.
=> test: add test that ensures return value of `chroot.run()`

stages/org.osbuild.btrfs.subvol, stages/test/test_btrfs_subvol.py
The code currently does not support btrfs subvolumes that are not directly under the root directory. This commit fixes this by adding `-p` to `btrfs subvolume create` and adding an integration test.
Closes: https://github.com/osbuild/osbuild/issues/1882
=> stages: fix btrfs subvolume creation under subdirectories

osbuild/inputs.py, osbuild/pipeline.py, osbuild/sources.py, osbuild/util/jsoncomm.py, osbuild/util/linux.py, test/mod/test_inputs.py, test/mod/test_util_jsoncomm.py, test/mod/test_util_linux.py
The existing jsoncomm is a work of beauty. For very big arguments however the used `SOCK_SEQPACKET` hits the limitations of the kernel network buffer size (see also [0]). This lead to various workarounds in #824,#1331,#1836 where parts of the request are encoded as part of the json method call and parts are done via a side-channel via fd-passing.
This commit changes the code so that the fd channel is automatically and transparently created and the workarounds are removed. A test is added that ensures that very big messages can be passed.
[0] https://github.com/osbuild/osbuild/pull/1833
=> jsoncomm: transparently handle huge messages via fds

devices/org.osbuild.loopback, osbuild/loop.py
It's sometimes useful to set up a loop device for an already formatted disk/filesystem image to derive new artifacts from it. In that case, we want to make sure it's impossible to modify its contents in any way in that process, both for our own purposes and for other stages operating on it.
Notably, mounting some filesystems read-only still seem to touch the disk (like XFS).
=> devices/loopback: add read-only option

stages/org.osbuild.coreos.platform
Switch from shutil.copy2 so that we don't copy over the SELinux labels from the source file.
=> stages/coreos.platform: use shutil.copy

tools/osbuild-mpp
Currently if one uses `mpp-embed` with URLs, osbuild-mpp still wants to download the full file just so it can hash it. Make this more efficient by hashing from the stream instead, which `hashlib` natively supports.
This also makes osbuild-mpp work with large artifacts in environments that may not have enough space to temporarily save the data.
=> tools/osbuild-mpp: hash mpp-embed urls from stream

stages/org.osbuild.containers.unit.create, stages/org.osbuild.containers.unit.create.meta.json, stages/org.osbuild.systemd.unit, stages/org.osbuild.systemd.unit.create, stages/org.osbuild.systemd.unit.create.meta.json, stages/test/test_containers_unit_create.py
This adds enough to make the examples in the automotive documentation not have to use hand-written files for these units.
For example, one could use:
```
- type: org.osbuild.systemd.unit.create
options:
filename: radio.socket
config:
Unit:
Description: An example systemd unix socket
Socket:
ListenStream: "%t/asil-ipc-demo/asil_ipc.socket"
RuntimeDirectory: asil-ipc-demo
Install:
WantedBy:
- sockets.target
```
or
```
- type: org.osbuild.containers.unit.create
options:
filename: radio.container
config:
Unit:
Description: Demo radio service container
Requires:
- routingmanagerd.socket
Wants:
- engine.service
Container:
Image: localhost/auto-apps
Exec: /usr/bin/radio-service
Volume:
- /run/vsomeip:/run/vsomeip
Service:
Restart: always
Install:
WantedBy:
- multi-user.target
```
=> Add support for creating quadlet and systemd socket units

stages/org.osbuild.selinux, stages/org.osbuild.selinux.meta.json, stages/test/test_selinux.py
With the labels option the user is specifying the exact context they want to set on the path so it's not necessary to supply a context here. This can be also useful in the case where you want to set some labels and you haven't yet populated the tree yet.
=> stages/selinux: don't require file_contexts if labels passed

stages/org.osbuild.tar, stages/org.osbuild.tar.meta.json, stages/test/test_tar.py
This commit adds a new `transform` option to the tar stages that
maps directly to the `--transform=` comamndline argument of tar(1).
This allows to transform the names while files/dirs are added to
a tarfile. This is useful for the `gcp` pipeline for
bootc-image-builder where we want to create a gcp tar file that
expects the disk image filename in the tar to be exactly `disk.raw`.
Note that tar allows only a single `--transform` and we leave it
to the user to construct `sed` expressions if multiple renames
are required.
See also https://github.com/osbuild/images/pull/923
=> stages(tar): expose new `transform` option to tar stage

.github/workflows/test-on-centos.yml
After removal of TOML write packages on c9s and c10s some tests using this library needs to be skipped.
=> CI: Update excluded tests list

osbuild/meta.py, test/mod/test_osbuild.py
This commit moves the joining of path fragements from f-strings to pathlib and simplifies some of the map/filter/lambda expressions into more standard list comprehensions.
=> meta: use pathlib to join paths in `class Index`

README.md
I am keeping mailing list link, however, nobody was able to tell me how one can subscribe to it. I think it is Google Groups list now and there is no join option.
=> chore: add dicussions link to README

osbuild.spec
The recent change in https://github.com/osbuild/osbuild/pull/1896 removed the dnf dependency, leading to failures in osbuild-mpp with the following error:
ModuleNotFoundError: No module named 'dnf'
To fix it, add the python3-dnf dependency for the
osbuild-tools package.
=> osbuild.spec: Add python3-dnf dependency for osbuild-tools

osbuild/util/ostree.py, sources/org.osbuild.ostree
In order to move edge service from own S3 repo hosting to on-prem pulp, we need to be able to pull ostree commits from MTLS repo. Additionally, on stage we must use HTTPS proxy in order to reach out there from the cluster.
This patch is quite bold, I am being honest. It adds support for several configuration values from ostree repo config, namely:
* server ca
* permissive mode (useful for testing)
* client cert
* client key (yeah yeah!)
* proxy URL
For more config repo details head over to: https://ostreedev.github.io/ostree/man/ostree.repo-config.html
I really don’t know if this is the right path, sending keys over wire seems weird but I don’t see a better solution.
Please guide me through tests, how and where should test this? Thanks.
https://issues.redhat.com/browse/HMS-4751
=> sources: MTLS and proxy support for ostree

osbuild/testutil/__init__.py, osbuild/util/chroot.py, stages/test/test_dracut.py, test/mod/test_util_chroot.py
[draft as this is a bit of an RFC]
We currently use the absolute path of these binaries in the
helper. This has some advantages but given that we control the
inputs for PATH in general it seems unnecessary.
We are also slightly inconsistent about this in the codebase but
favor the non absolute path version. A quick count:
```
$ git grep '"chroot"'|wc -l
13
$ git grep '"/usr/sbin/chroot"'|grep -v test_|wc -l
8
```
for `mount` and `umount` it seems this is the only place that uses
the absolute path.
It's not an important change but it has the nice property that it
allows us to use e.g. `testutil.mock_command()` in our tests and
it would be nice to be consistent.
=> util: use non-absolute paths for chroot/mount/umount and add test

stages/org.osbuild.mkdir, stages/org.osbuild.mkdir.meta.json, stages/test/test_mkdir.py
This allows creating new directories on mounts:
```
- type: org.osbuild.mkdir
options:
paths:
- path: mount:///boot/efi
devices:
disk: ...
mounts:
- name: boot
target: /boot
...
```
=> org.osbuild.mkdir: support creating dirs on mounts

README.md
Is this a good place to document this or rather introduce an `extras_require` in `setup.py`?
Also there seem to be more missing and the tests requiring an nfs-server need some more prerequisites to be executed, I guess?
e.g. `sudo python -m pytest --rootdir=$(pwd) -v test/mod/test_util_fscache_coherency.py`  
fails even when starting an unconfigured nfs-server
=> README: document test prerequisites

stages/test/conftest.py, stages/test/test_tar.py
As a followup of https://issues.redhat.com/browse/RHEL-4653 it seems that the stages don't return proper
error messages back if the disk is full.
Probably this is known and there is an issue for this, but I didn't find it.
This should be an example environment for more stages to test if they return a proper error in a "disk full scenario"
This PR is ment for a proof of concept for a test environment and basis of discussion
as the error of "disk full" is not properly handled not transformed to a proper error code and not handed over to the stack above in this code.
I think at least stages that have high risk of "disk full", like `tar`, `rpm`, `cp` … should handle "disk full" more gracefully and return a proper error message.
=> stages/org.osbuild.tar: implement disk-full test (RHEL-4653)

osbuild/formats/v2.py, osbuild/pipeline.py, schemas/osbuild2.json, test/data/manifests/fedora-boot.json, test/data/manifests/fedora-boot.mpp.yaml, test/mod/test_fmt_v2.py
A new metadata key at the top level which contains a generators key which is a list of all generators involved in the creation of the manifest.
Tools that generate manifests are, for example: [otk](https://github.com/osbuild/otk), [osbuild-composer](https://github.com/osbuild/osbuild-composer) (through [images](https://github.com/osbuild/images)).
=> schema: `metadata` at the top level

stages/org.osbuild.container-deploy, stages/org.osbuild.container-deploy.meta.json, stages/test/test_container_deploy.py
Add remove-signatures option to container-deploy stage.
The option will be translated to --remove-signatures
skopeo option and passed to skopeo when copying the container.
This option must be set when deploying signed containers.
Signed-off-by: Miguel Martín <mmartinv@redhat.com>
=> feat: add remove-signatures option to container-deploy stage

tools/osbuild-mpp
This allows using e.g. mpp-eval in the resolve-image operation, similar to how it is now possible in the mpp-depsolve handling.
We want this so we can inject the list of images from a list variable (that can then be mpp-join:ed, etc).
=> osbuild-mpp: Allow using formating in the mpp-resolve-images handling

stages/test/test_autotailor.py
The test case is skipped in the upstream CI, because the `autotailor` executable is not installed in the `osbuild-ci` image. This will not be the case in the future and the CI run will reveal a Python 3.6 incompatibility in the test implementation. Fix it.
=> Test/autotailor: fix Python 3.6 compatibility

tox.ini
This is needed to resolve fialure to find `lib2to3` module on F41, which was removed since Python 3.13 used by default there.
Update autopep8 and pycodestyle to the latest upstream releases.
=> Lint/autopep8: update to the latest upstream version v2.3.1

stages/org.osbuild.dnf-automatic.config
On Fedora 41 with DNF5, the dnf-automatic plugin by default does not install any configuration file. This means that the stage would fail in such case.
Previously, the full config file was placed in /etc and its purpose was also to document all possible options. The example config file is now installed only in /usr/share/dnf5/dnf5-plugins/automatic.conf.
Relax the stage implementation to not fail when the configuration file does not exist. Just log a warning and create the configuration file.
=> Stages/dnf-automatic.config: don't fail on non-existent config file

stages/org.osbuild.tuned
Since v2.23.0, TuneD changed the default directory under which it looks for profiles. The profiles are newly nested under `profiles/` directory. More information in [1].
Modify the stage implementation to check if the default profile directories contain `profiles/` directory. If yes, then look for profiles in it. If not, use the original behavior.
[1] https://github.com/redhat-performance/tuned/releases/tag/v2.23.0
=> Stages/tuned: handle changed profiles dir with new TuneD versions

stages/org.osbuild.users, stages/test/test_users.py
Use Chroot class from osbuild.util.chroot module, instead of calling `chroot` directly. The class handles mounting of various paths in the chroot to make us more usable. This resolves new failure when running the stage test on F41 results in `mkhomedir_heper` failing with `6` return code, meaning permissions denied.
Adjust the stage unit tests, because `chroot.Chroot` can't work with `pathlib.Path`.
=> Stages/users: use Chroot from osbuild.util.chroot

stages/org.osbuild.authconfig, stages/org.osbuild.firewall
**stages: use util.chroot in all stages that call "chroot"**
Use the chroot utility module for all cases where we need to chroot
during a stage's execution.
The advantage is that all stages use the same tested code path for
setting up a chroot and all chrooted commands run in the same
environment, with the /proc, /dev, and /sys filesystems mounted.
---
**util/chroot: convert the root path to string**
The root argument of the Chroot constructor can be a pathlib.Pat in some
cases.  Let's ensure it's a string so that we can append paths to it
more freely.
---
**stages/test_users: update test to match new calls**
With the org.osbuild.users stage now using the Chroot context, the
subprocess.run() command is run 6 more times, 3 to mount the /proc,
/dev, and /sys, and 3 more to unmount them. …
=> Use the Chroot context in all stages that require chroot

tools/osbuild-mpp
The change in commit ed3386943069e138b346eef75ac64d9874a07810 to use hashlib.file_digest breaks with older python, because it was added in 3.11.
This change reverts back to hashing all the data in the case where file_digest doesn't exist.
=> osbuild-mpp: Fix error on python < 3.11

test/data/manifests/fedora-coreos-container.json
We updated the container in the registry so we need to update this manifest to unbreak CI.
=> test/data/manifests/fedora-coreos-container: fix CI

.github/workflows/test.yml, sources/test/test_ostree_source.py
This commit adds a tiny smoke test that runs the unit tests as
a normal user on a regular github runner. This should ensure that
we catch issues like in osbuild#1936.
---
workflow: install `python3-pytest` too to workaround
`test_host.py`
The test_host.py:test_signals_on_separate_fd (and more)  runs
itself but that run will happen without the tox env so a pip/tox
installed pytest will not be found, install the pytest package
as a workaround.
---
sources: skip ostree tests if no ostree binary if found
This commit skips the ostree tests if no ostree binary is available.
=> workflow: add smoke test that runs unit tests as user

stages/org.osbuild.containers.unit.create.meta.json, stages/test/test_containers_unit_create.py
Add the option to specify the SELinux type label and file type label for the process.
Add the option to specify a tmpfs mount to create into the container.
=> Expand the options available in containers.unit.create

osbuild/remoteloop.py
This adds lock, partscan, read_only, sector_size to `_create_device()` similar to `make_loop()` from `devices/org.osbuild.loopback`.
=> osbuild/remoteloop: add more loop device options

CODEOWNERS
- Introduce a CODEOWNERS file to designate the CoreOS team as responsible for maintaining files related to CoreOS.
- This change ensures collaborative support, alleviating the burden solely on the osbuild team.
- By assigning ownership, we aim to enhance code quality and responsiveness to issues affecting CoreOS.
=> CODEOWNERS: Assign ownership for CoreOS-related files

stages/org.osbuild.grub2.iso.legacy, stages/org.osbuild.grub2.iso.legacy.meta.json
This is the BIOS version of the grub2 iso stage. It installs the config file and copies over the grub2 modules to /boot/grub2/
=> org.osbuild.grub2.iso.legacy: Add grub2 setup for booting BIOS ISO

stages/org.osbuild.kickstart, stages/org.osbuild.kickstart.meta.json, stages/test/test_kickstart.py
It's a no-op nowadays, we dropped support for the custom ostree-container signature verification status.
=> kickstart: Drop ostree signature verification flag

stages/org.osbuild.erofs, stages/org.osbuild.erofs.meta.json, stages/test/test_erofs.py
This is supported in erofs-utils 1.8 and later.
=> erofs: Add zstd to the list of supported compression algorithms

tools/osbuild-image-info, tools/test/test_osbuild_image_info.py
`read_boot_entries()` could previously fail when trying to split lines in bootloader entries, which contained only "\n" and became an empty string after stripping whitespace characters. This is the case e.g. on F41 images.
Moreover, bootloader entries can contain comments as lines starting with "#", which were previously not ignored by the function and would end up in the parsed entry and could potentially fail to be split.
Add unit test covering the changes and expected behavior.
/jira-epic COMPOSER-2318
JIRA: [HMS-5228](https://issues.redhat.com/browse/HMS-5228)
=> Tools/osbuild-image-info: make `read_boot_entries()` more robust (HMS-5228)

osbuild/util/path.py, stages/org.osbuild.dnf4.sbom.spdx, stages/org.osbuild.dnf4.sbom.spdx.meta.json, stages/org.osbuild.dnf5.sbom.spdx, stages/org.osbuild.dnf5.sbom.spdx.meta.json, stages/org.osbuild.tuned, stages/org.osbuild.tuned.meta.json, stages/test/test_tuned.py, test/mod/test_util_path.py
- Add unit tests for the `org.osbuild.tuned` stage.
- Harden a few corner cases in the `org.osbuild.tuned` stage.
- Add a helper function `util.path.join_abs()` to join paths that may be absolute as if they weren't.
- Use the `util.path.join_abs()` function in the `tuned` and `dnf*.sbom.spdx` stages to construct paths instead of f-strings.
Fix #1941
Fix #1964
=> Don't use f-strings for path construction in `tuned` and `dnf*.sbom.spdx` stages

stages/org.osbuild.xorrisofs, stages/org.osbuild.xorrisofs.meta.json
This creates an iso matching the current method used in Fedora where it uses grub2 for BIOS and UEFI booting. Pass the path to the grub2 hybrid mbr to the stage in the 'grub2' field. eg.
"grub2": "/usr/lib/grub/i386-pc/boot_hybrid.img"
=> org.osbuild.xorriso: Add support for grub2 bootable iso

tools/osbuild-image-info
Add support for swap and btrfs to osbuild-image-info.
Swap support: ignor swap partitions when mounting volumes to analyse the tree.
Btrfs support: scan subvolumes when looking for the OS root to read `/etc/fstab`.
Tested against the new image configurations in osbuild/images which use the disk/partitioning customization:
https://github.com/osbuild/images/blob/f667cdfbaaaa8b2d5e579f9f0294b24c7b680028/test/configs/partitioning-btrfs.json
https://github.com/osbuild/images/blob/f667cdfbaaaa8b2d5e579f9f0294b24c7b680028/test/configs/partitioning-dos-lvm.json
https://github.com/osbuild/images/blob/f667cdfbaaaa8b2d5e579f9f0294b24c7b680028/test/configs/partitioning-lvm.json
https://github.com/osbuild/images/blob/f667cdfbaaaa8b2d5e579f9f0294b24c7b680028/test/configs/partitioning-plain.json
=> osbuild-image-info: support swap partitions and btrfs subvolumes

.devcontainer/Dockerfile, README.md, osbuild.spec, osbuild/formats/v1.py, sources/org.osbuild.librepo, sources/test/conftest.py, sources/test/test_librepo.py, test/data/sources/org.osbuild.librepo/cases/404-metalink.json, test/data/sources/org.osbuild.librepo/cases/404-mirrorlist.json, test/data/sources/org.osbuild.librepo/cases/bad-baseurl-checksum.json, test/data/sources/org.osbuild.librepo/cases/bad-metalink-checksum.json, test/data/sources/org.osbuild.librepo/cases/bad-mirrorlist-checksum.json, test/data/sources/org.osbuild.librepo/cases/baseurl.json, test/data/sources/org.osbuild.librepo/cases/one-metalink.json, test/data/sources/org.osbuild.librepo/cases/one-mirrorlist.json, test/data/sources/org.osbuild.librepo/cases/two-metalink.json, test/data/sources/org.osbuild.librepo/cases/two-mirrorlist.json, test/data/sources/org.osbuild.librepo/data/Packages/a/a, test/data/sources/org.osbuild.librepo/data/Packages/b/b, test/data/sources/org.osbuild.librepo/data/metalink/fedora.xml, test/data/sources/org.osbuild.librepo/data/metalink/one404.xml, test/data/sources/org.osbuild.librepo/data/metalink/updates.xml, test/data/sources/org.osbuild.librepo/data/mirrorlist/fedora, test/data/sources/org.osbuild.librepo/data/mirrorlist/one404, test/data/sources/org.osbuild.librepo/data/mirrorlist/updates, test/data/sources/org.osbuild.librepo/data/updates/Packages/c/c, test/data/sources/org.osbuild.librepo/data/updates/Packages/d/d, test/mod/test_osbuild.py, test/run/test_sources.py
[draft until the "images" (and possible "composer") side is ready so that we know if this really ready]
This is a reopen of https://github.com/osbuild/osbuild/pull/1304 with tiny tweaks to update it to current osbuild. All credit to @bcl.
This is prompted by the issues we see with fedora mirrors currently, e.g.
https://github.com/osbuild/image-builder-cli/issues/40
https://github.com/osbuild/bootc-image-builder/pull/766
The matching PRs for images/bootc-image-builder/image-builder-cli are here as drafts:
- https://github.com/osbuild/images/pull/1132
- https://github.com/osbuild/image-builder-cli/pull/51
- https://github.com/osbuild/bootc-image-builder/pull/786
This of course needs "images"/"bib" integration, I can make this draft until those pieces are added if desired.
=> sources: add an org.osbuild.librepo source

osbuild/monitor.py, osbuild/pipeline.py, test/mod/test_monitor.py
The jsonseq based status reporting does not have error handling right now. If anything goes wrong it will
not reported. This is a problem for frontends like bib or the new ibuilder (image-builder-cli). So this PR
adds error reporting via the "result" mechanism.
This also allows us to avoid having to add `--json` to the output to construct the build result.
With this commit in place consumers can now call `osbuild --monitor-fd` and stream the progress. The consumer needs to keep track of the "build_result" from osbuild to be able to reconstruct the equivalent of the result that is generated via `osbuild --json` [0]. Note that we mostly abandon the format/v2/v2.py:output() and putting the burden on the consumer (but I don't see a way around this).
This is a cleaner version of …
=> monitor: include result in jsonseq monitor streaming (COMPOSER-2393)

stages/org.osbuild.mkfs.ext4, stages/org.osbuild.mkfs.ext4.meta.json, stages/test/test_mkfs_ext4.py
This helps to clear a risk concern for
automotive.
Add optional flag to org.osbuild.mkfs.ext4 stage
to enable/disable both lazy_itable_init and
lazy_journal_init extended options. Both mke2fs
options are controled by the same flag, namely
`lazy_init`.
=> stages/mkfs.ext4: disable lazy_itable_init

.gitlab-ci.yml
Let's not use EOL F39 for OSTree tests and move to the latest supported Fedora version.
=> Gitlab CI: use F41 for OSTree tests

osbuild/main_cli.py
**osbuild/cli: add --cache as an alias for --store**
The name 'cache' is more recognisable and conveys the purpose of the
option just as well (if not better) than 'store'.
Also, the option that controls the size of this directory is called
'cache-max-size', so we're already referring to it as a cache.
---
**osbuild/cli: mention sources in cache/store help**
The cache/store directory is also used to keep sources.  Mention that in
the description of the option.
---
=> Add `--cache` flag as an alias for `--store`

tools/osbuild-image-info, tools/test/test_osbuild_image_info.py
Some image types don't have systemd installed and don't have any default target set, e.g. 'tar' image type. Running osbuild-image-info on such image would result in traceback (e.g. [1]). Handle this case gracefully.
[1] https://gitlab.com/redhat/services/products/image-builder/ci/osbuild/-/jobs/8911649248#L6480
Add a test case for this change.
/jira-epic COMPOSER-2318
JIRA: [HMS-5375](https://issues.redhat.com/browse/HMS-5375)
=> osbuild-image-info: don't fail on no systemd default target (HMS-5375)

osbuild.spec
The modularity changes introduced a new field in the DNF JSON responses (#1933). This bump ensures that current deployments don't break.
=> spec: bump dnf json api version

osbuild.spec
Due to the `modules` field that was added to the depsolve result in #1933 the depsolve json response is now incompatible with previous versions. This requires a bump to the version.
This PR is an un-revert of the #1989 which reverted the API version bump but now based on the fact that we are actually breaking the API version by design and expectation.
---
Note that, as opposed to the nevra field on packages which was a big red herring today; this field is actually *expected* to be added. Hence we can't just remove it from the depsolve response. This also means that the DNF JSON version *will* need to be bumped; even though we didn't want to do that (cc: @ondrejbudai). See the images PR where this field gets added: https://github.com/osbuild/images/pull/1163
=> spec: bump dnfjson api version

tools/osbuild-image-info, tools/test/test_osbuild_image_info.py
For the purpose of using this tool in tests (specifically for manifest tests where we diff image-info reports), it is important that the tools exists with non-zero value if the final report is empty.
Add test for the behavior.
=> osbuild-image-info: exit with non-zero value on empty report

stages/org.osbuild.systemd.unit.create.meta.json, stages/test/test_systemd_unit_create.py
`systemd.mount(5)` describes both `What` and `Where` as mandatory options for the `Mount` section of a unit.
=> stages: Where is mandatory in systemd.unit.create

stages/org.osbuild.kernel-cmdline
Add check to ensure that the size of
the parameters does not exceed the
maximum kernel cmdline size.
Otherwise, the parameters will
be truncated and the command line
will fail.
The size is arch-dependant. In
order to not to over-complicate
the search of the value in the
kernel files (which will probably
not be installed in most cases),
it uses a map with some values
for common architectures.
If architecture is not found in
the map, defaults to 4096, which
is the maximum posible size for
COMMAND_LINE_SIZE.
=> kernel-cmdline: add size check

osbuild/testutil/net.py, sources/org.osbuild.ostree, sources/test/test_ostree_source.py
I noticed that full ostree is pulled just in order to inspect few files from `/usr/etc`. This is wasting of resources since this directory has only like 12 MiB while whole Fedora ostree is about 2 GiB. Here is a code that @achilleas-k pointed on which makes use of this source:
https://github.com/osbuild/osbuild/blob/main/stages/org.osbuild.ostree.passwd#L14
This patch introduces a new optional field `subpath`, it is a list of paths or files to include in the pull command via `--subpath` command option. This option can repeat and cause only these subpaths to be pulled. It appears that it does not affect the commit sha at all, it simply skips the content completely which is exactly what we want.
This is a significant time saver, on my setup this shaves about 40 minutes of download when Pulp …
=> ostree: introduce optional subpath feature

stages/org.osbuild.kernel-cmdline, stages/org.osbuild.kernel-cmdline.meta.json, stages/test/test_kernel_cmdline.py
Add an option called `kernel_line_size`
to allow setting a maximum cmdline size check
value for custom kernels or other restrictions.
- This option will override the arch defaults, otherwise
- The size map is checked for current arch, otherwise
- If the current architecture is not in the map, fallback to
4096, which is the max value allowed for
COMMAND_LINE_SIZE.
=> stages/kernel-cmdline: add max cmdline option

osbuild/testutil/net.py, sources/org.osbuild.ostree, sources/test/test_ostree_source.py
This reverts commit 3bb5bedd8e7dc3ac465e3399f8cd7fd32e071580 as it introduces problems in the caching system used by `osbuild` [1]
[1]: https://github.com/osbuild/osbuild/issues/2009
=> Revert "ostree: introduce optional subpath feature"

tools/osbuild-image-info, tools/test/test_osbuild_image_info.py
Modify the function able to handle messages about skipped binary fcontext files and skip them. This started to happen on c10s. Extend the unit test to cover this new scenario.
This will fix PR #1998
=> Tools/osbuild-image-info: make read_selinux_ctx_mismatch more robust

stages/org.osbuild.coreos.live-artifacts.mono, stages/test/test_coreos_live_artifacts_mono.py
This adds possibility to specify filesystem of `rootfs.img`. 
Issue: https://github.com/coreos/fedora-coreos-tracker/issues/1852
=> stages/coreos.live-artifacts: add erofs support

stages/org.osbuild.dracut, stages/test/test_dracut.py
This commit replaces the `/usr/bin/logger` binary in the dracut chroot with a bind mount to `/usr/bin/true` to silence the spam that we get from dracut during initramfs generation:
```
logger: socket /dev/log: No such file or directory
```
Unfortunately I could not find a nicer way, it seems it is not possible to simply pass `sysloglvl=0` via the commandline or an environment.
Closes: https://github.com/osbuild/osbuild/issues/1976
=> stages: replace "logger" binary in the dracut chroot

.github/workflows/check.yml, .github/workflows/coverity.yml, .github/workflows/create-tag.yml, .github/workflows/generate.yml, .github/workflows/pr_best_practices.yml, .github/workflows/release.yml, .github/workflows/stale-cleanup.yml, .github/workflows/test-on-centos.yml, .github/workflows/test.yml, .github/workflows/trigger-gitlab.yml, .github/workflows/update-images.yml
This replaces ubuntu-latest with ubuntu-24.04 to avoid unexpected changes.
=> Pin CI workflows to ubuntu 24.04

stages/org.osbuild.coreos.live-artifacts.mono
This fixes what was skipped in https://github.com/osbuild/osbuild/pull/2002
=> stages/coreos.live-artifacts: update comments/names to reflect erofs related changes

stages/org.osbuild.cloud-init.meta.json, stages/test/test_cloud-init.py
Adds WSL and NoCloud datasources. The network section only allows you to disable network configuration by cloud-init for now.
=> org.osbuild.cloud-init: add new datasources and network section

stages/org.osbuild.qemu, stages/org.osbuild.qemu.meta.json, test/data/stages/qemu/qemu.json, test/data/stages/qemu/qemu.mpp.yaml
The CoreOS team uses the compat6 and adapter_type options when creating a VMDK for AWS.
https://github.com/coreos/coreos-assembler/blob/e1943d6adb8f0cb257630a76d02d0aa333261c70/src/cosalib/qemuvariants.py#L48
=> stages: add more options to qemu vmdk disk type

stages/org.osbuild.coreos.live-artifacts.mono
This helps reduce the memory requirements of mkfs.erofs since it won't be writing to tmpfs (memory backed) storage, which is what is mounted on /tmp/.
=> stages/coreos.live-artifacts: use /var/tmp for mkfs.erofs

tools/test/test_depsolve.py
The test matrix in `osbuild-depsolve-dnf` got out of hand. We were increasing the parametrization of `test_depsolve()` test case (and others) to test new features. However, for each test case instance, we also ran the same test case 8 times for each possible repo config combination and optional metadata requested in the request (2\*2\*2).
This PR improves the situation by extracting the repo config combo testing to dedicated test cases, which test all combinations with a single test scenario containing multiple repositories.
I've done some additional refactoring along the way to reduce code duplication and improve testing accuracy (e.g., don't set arguments in the request, which should not be used in the test scenario).
From local testing of `python3 -m pytest -vv …
=> Rework `osbuild-depsolve-dnf` tests (HMS-5509)

stages/org.osbuild.dracut.conf, stages/test/test_dracut_conf.py
If the dracut config stage runs early the directory for the dracut config may not be available yet. So just create it.
[this is needed for the riscv work where we need to write the dracut config early, see https://github.com/osbuild/images/pull/1241]
=> stages: ensure dirs for dracut configs are available

stages/org.osbuild.systemd.unit.create, stages/org.osbuild.systemd.unit.create.meta.json, stages/test/test_systemd_unit_create.py, test/data/stages/systemd.unit.create/a.json, test/data/stages/systemd.unit.create/a.mpp.yaml, test/data/stages/systemd.unit.create/b.json, test/data/stages/systemd.unit.create/b.mpp.yaml, test/data/stages/systemd.unit.create/diff.json
Add support for .swap systemd units to the org.osbuild.systemd.unit.create stage.
=> stages/systemd.unit.create: support .swap units

Schutzfile, tools/osbuild-image-info
We have images that are zstd-compresed now so `image-info` needs to be able to deal with them. See: #2040.
---
`mimetypes.guess_type` is a bit weird with zstd compressed archives; there is no `encoding` for it but the mimetype itself is set correctly.
=> tools: support zstd in `image-info`

stages/org.osbuild.grub2.inst, stages/test/test_grub2_inst.py
When writing the grub2 core image, the format should be set based on the platform.  This was accidentally changed to be `i386-pc` for all platforms except when building ISOs.
Set the format to the platform and only change it to `i386-pc-eltorito` when building ISOs.
Fixes #2037
=> stages/grub2.inst: fix format for non-x86_64 image

stages/org.osbuild.insights-client.config, stages/org.osbuild.insights-client.config.meta.json, stages/test/test_insights_client_conf.py
Help and feedback much appreciated, it is entirely possible I missed something :) 
The goal is to create a stage that configures the insights-client proxy url
/jira-epic hms-5317
JIRA: [HMS-5568](https://issues.redhat.com/browse/HMS-5568)
=> stages: add insights-client config stage (HMS-5568)

stages/org.osbuild.coreos.live-artifacts.mono
We originally required there to be only one kernel modules directory since we typically only have one kernel installed. Change this check up a bit since some kernel module RPMs aren't delivering a new kernel but do deliver kmods that were built against a different kernel.
For example v4l2loopback from https://elrepo.org/
```
bash-5.1# rpm -ql kmod-v4l2loopback
/etc/depmod.d/kmod-v4l2loopback.conf
/lib/modules/5.14.0-427.13.1.el9_4.x86_64
/lib/modules/5.14.0-427.13.1.el9_4.x86_64/extra
/lib/modules/5.14.0-427.13.1.el9_4.x86_64/extra/v4l2loopback
/lib/modules/5.14.0-427.13.1.el9_4.x86_64/extra/v4l2loopback/v4l2loopback.ko
/usr/share/doc/kmod-v4l2loopback-0.12.7
/usr/share/doc/kmod-v4l2loopback-0.12.7/GPL-v2.0.txt
/usr/share/doc/kmod-v4l2loopback-0.12.7/greylist.txt
```
This patch now allows …
=> stages/coreos.live-artifacts: loosen requirements on modules dir

stages/org.osbuild.grub2.inst, stages/test/test_grub2_inst.py
Backport https://github.com/osbuild/osbuild/pull/2038 to `rhel-9.6.0` branch.
=> [RHEL-9.6.0] Backport https://github.com/osbuild/osbuild/pull/2038 (RHEL-85560)

runners/org.osbuild.almalinux8, runners/org.osbuild.almalinux9
As part of AlmaLinux shipping the OSBuild stack, allow osbuild to recognize AlmaLinux as a valid host.
=> runners: Add AlmaLinux runner links to permit AlmaLinux as a host

osbuild/pipeline.py, osbuild/util/experimentalflags.py, test/mod/test_util_experimentalflags.py
This commit adds support for more debug for `qemu-user` options. When settings:
```
$ sudo IMAGE_BUILDER_EXPERIMENAL=debug-qemu-user bootc-image-builder ...
```
extra debug will be printed. This hopefully helps to track down the root cause of
https://github.com/podman-desktop/extension-bootc/issues/1475
This is intended to help to track down https://github.com/podman-desktop/extension-bootc/issues/1475
=> osbuild: add experimental flag `debug-qemu-user`

.github/workflows/create-tag.yml
Modify the action to allow passing the version when run manually. This will be useful in the future once we branch-off a `rhel-x.y` branch to backport a fix and will be doing the first "dot" release from such branch.
Depends on https://github.com/osbuild/release-action/pull/29
=> GH Action/create-tag: allow passing the version when run manually

stages/org.osbuild.rhsm.meta.json, test/data/stages/rhsm/b.json, test/data/stages/rhsm/b.mpp.yaml, test/data/stages/rhsm/diff.json
Support setting the `auto_enable_yum_plugins` option in the `rhsm` section of `rhsm.conf`.
Add a unit test for the stage schema and also adjust the stage test manifest.
Related to: https://github.com/osbuild/images/issues/1408
=> Stages/rhsm: support setting 'auto_enable_yum_plugins' option

stages/org.osbuild.chrony, stages/org.osbuild.chrony.meta.json, stages/test/test_chrony.py, test/data/stages/chrony/b.json, test/data/stages/chrony/b.mpp.yaml, test/data/stages/chrony/diff.json
The refclock directive can be used to specify one or more hardware reference clocks to be used as a time source.  Each refclock line must specify a driver and a mandatory parameter, in the form:
refclock driver parameter
Drivers can have driver-specific options:
refclock driver parameter:[driver-option,...]
General refclock options can also be specified:
refclock driver parameter:[driver-option,...] [general-option]...
The stage options schema is written so that the "driver" property is an object that must match one of four schemas corresponding to the four drivers, each with a "name" property matching the driver name.  Each driver defines its required property and any optional driver-specific options.
There are more general refclock options supported than the ones defined in this PR, but …
=> stages/chrony: support specifying refclocks (RHEL-79065)

stages/org.osbuild.waagent.conf, stages/org.osbuild.waagent.conf.meta.json, stages/test/test_waagent_conf.py, test/data/stages/waagent.conf/b.json, test/data/stages/waagent.conf/b.mpp.yaml, test/data/stages/waagent.conf/diff.json
Extend the stage to support setting new options:
- Provisioning.UseCloudInit
- Provisioning.Enabled
Extend the stage test to use them and add a simple stage unit test for
the schema.
Related to https://github.com/osbuild/images/issues/1416
=> Stages/waagent.conf: support additional options

.github/workflows/check.yml
Packit changed the command to validate its configuration, without keeping backward compatibility.
=> Tests: fix packit config validation

stages/org.osbuild.coreos.live-artifacts.mono
The `generic.ins` template uses:
```
images/kernel.img
images/initrd.img
```
However, kernel and initrd are currently stored as:
```
images/pxeboot/vmlinuz
images/pxeboot/initrd.img
```
This change ensures correct paths are used.
Issue: https://github.com/coreos/coreos-assembler/issues/4077
=> stages/coreos.live-artifacts: fix kernel and initrd paths in s390x ISO

osbuild/solver/dnf5.py
The old function has been deprecated by dnf5, use load_repos directly and only load the available repos (the ones osbuild has setup), not the system repos.
Fixes #2080
=> solver: Use load_repos instead of update_and_load_enabled_repos

osbuild.spec
This works around a file conflict on `/usr/bin/typer` between `python3-typer-cli` and `erlang-dialyzer` until the problem can be fixed in `python-typer` and/or `erlang`. See [RHBZ#2359557](https://bugzilla.redhat.com/show_bug.cgi?id=2359557), [RHBZ#2359567](https://bugzilla.redhat.com/show_bug.cgi?id=2359567).
After the file conflict is resolved, the `python3-typer-slim` dependency will still be more precise and minimal than `python3-typer`, so no further change will be required.
By depending on `typer-slim[standard]`, we still get the nice-to-have optional dependencies that plain `typer` would bring in (currently, `rich` and `shellingham`), but without the generic `typer` command-line tool.
After this PR, it is possible to install `osbuild-tools` and `erlang` at the same time; before the …
=>  In Fedora 41+, depend on typer-slim rather than typer

osbuild/solver/dnf.py
DNF apparently doesn't check the expiration time on the cache unless you call this first. It may help improve issues with the cache being out of sync.
Internally dnf checks the mtime of the main repomd.xml file when using baseurl, and it checks the hash values when using metalink so this should not result in any noticeable extra slowdowns when things are fresh.
=> solver: Call update_cache

osbuild/solver/dnf.py, osbuild/solver/dnf5.py, tools/osbuild-depsolve-dnf, tools/test/test_depsolve.py
The PLATFORM_ID got retired from fedora-43 [0] and it seems like it was always kinda optional (at least on fedora). So lets make it optional for real to avoid failing to build fedora-43 images.
[0] https://fedoraproject.org/wiki/Changes/Drop_PLATFORM_ID
See also https://github.com/osbuild/bootc-image-builder/issues/868 which started to fail recently for f43 bootc images.
=> [RFC] tools: drop requirement for `module_platform_id` from request

osbuild/solver/__init__.py, osbuild/solver/dnf.py, osbuild/solver/dnf5.py, tools/osbuild-depsolve-dnf, tools/test/test_depsolve.py
This commit adds an error message if no repositories are defined in the dnfjson query. We had the issue in
https://github.com/osbuild/bootc-image-builder/issues/922 that in a RHEL bootc-container no repositories are defined.
Here the error is quite confusing, as it complains about error marking packages which is technically correct but hides the root of the problem.
With this detect we can construct a more useful error message in the higher layers.
=> dnfjson: detect/error if no repositories are defined

.gitlab-ci.yml
These are no longer consumed by any dependent project AFAICT, so let's drop the EOL Fedora 39 builds.
=> CI: don't build F39 RPMs

stages/org.osbuild.kickstart, stages/org.osbuild.kickstart.meta.json, stages/test/test_kickstart.py
Add a new %post option to the kickstart stage that supports adding multiple post blocks to a kickstart file, with all the options supported by the directive.
In out images, we often need to use `%post` to run things that aren't supported by kickstart commands [1,2].  We work around this by injecting `org.osbuild.inline` files into the ISO and in order to combine them with the kickstart file created by the kickstart stage, we `%include` one from the other.  This makes it hard to document, trace, and troubleshoot the ISO itself.  It also makes it harder to read the manifest itself.  Adding these options to the stage will make everything nicer :rainbow:.
Once this is merged, I will replace all hard-coded `%post` lines in osbuild/images with the new stage option, which will remove the …
=> stages/kickstart: post-installation scripts

test/cases/manifest_tests
In some (ununderstood) cases the combination of `--no-single-branch` and `--depth=1` leads to the revision we want to check out not being available.
@achilleas-k suggested to change the command to this instead.
=> test: simplify git clone command

stages/org.osbuild.tar, stages/org.osbuild.tar.meta.json, stages/test/test_tar.py
The `org.osbuild.tar` stage only supports auto compression which is based on the filename. For several (newer) artifacts such as Vagrant (`.box`) and WSL (`.wsl`) we want to explicitly give the compression algorithm.
I've chosen a (few) commonly used compression algorithms. If others are needed they are one-line followups away.
---
The one "directly" needed is `gzip`, I'd be fine with dropping the others under YAGNI?
=> stages/tar: allow chosen compression (HMS-8573, HMS-6116)

stages/org.osbuild.grub2, stages/org.osbuild.grub2.meta.json, stages/test/test_grub2.py
For the terminal_input, terminal_output, and serial variables in the GRUB_CFG_TEMPLATE, the keys were not set when those variables were not defined in the options.  This caused the template variables to show up in the final file itself, which could break the config.  For example, the following line was being generated for one of our images:
serial --speed=115200 --unit=0 --word=8 --parity=no --stop=1${terminal_input}${terminal_output}
Setting the keys to an empty string when they're not defined solves the issue.
Since this is a stage behaviour change, the new behaviour is toggled by an option that maintains backwards compatibility when not set.
=> stages/grub2: set template vars to empty strings when missing (HMS-8646)

sources/org.osbuild.containers-storage
An error message has changed in skopeo [1] (or one of it's underlying libraries). This new version is now in our CI so let's fix our tests.
[1]: https://github.com/containers/skopeo/commit/f423f01d1bc1e2c0c271de5f06a020f2a99e15be
=> source/containers-storage: error message

stages/test/test_kickstart.py
On Python 3.6 we're getting a *different* error message from other versions in CI. Let's accept both versions.
Specifically only on 3.6 we're getting:
```
stages/test/test_kickstart.py:449: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
res = <osbuild.meta.ValidationResult object at 0x7f2255d54bd0>
expected_err = ' should not be valid under ', expected_num_errs = 1
def assert_jsonschema_error_contains(res, expected_err, expected_num_errs=None):
err_msgs = [e.as_dict()["message"] for e in res.errors]
if expected_num_errs is not None:
assert len(err_msgs) == expected_num_errs, \
f"expected exactly {expected_num_errs} errors in {[e.as_dict() for e in res.errors]}"
re_typ = getattr(re, 'Pattern', None)
if not re_typ:
re_typ = getattr(re, '_pattern_type')
if …
```
=> stages/test: kickstart different messages

.github/workflows/test.yml, tox.ini
Update the CI container and tox configuration to include testing on Python 3.14.
=> compatibility: Fedora 43 is now using python 3.14

stages/test/test_bootc_install_config.py, stages/test/test_containers_storage_conf.py, stages/test/test_systemd_unit_create.py, test/conftest.py, test/mod/test_util_toml.py
- don't attempt to create system units during the RPM build
- skip x86_64-specific tests on different architectures
- mark tests needing a TOML-writing library for easier exclusion downstream (no such library is present in RHEL currently)
This is all based on the test results from #2116
=> Adjust tests to work better in downstream environments

stages/org.osbuild.write-device, stages/org.osbuild.write-device.meta.json, stages/test/test_write_device.py
This stage writes a file to a device using dd. This is a rewrite/backport of one of the stages in osbuild-auto.
The osbuild-auto stage is used in automotive-image-builder to write the aboot image to the "boot_a" partition, to allow android boot systems to boot. We will want similar functionallity in bootc-image-builder, so it is important to upstream this.
=> stages: Add org.osbuild.write-device stage

stages/org.osbuild.vagrant, stages/org.osbuild.vagrant.meta.json, stages/test/test_vagrant.py, test/data/manifests/arch/arch-vagrant-virtualbox.json, test/data/manifests/arch/arch-vagrant-virtualbox.mpp.json
This adds support generating a virtualbox vagrant image. It differs from libvirt by requiring an xml file and a vmdk image.
This still requires some cleanup as the XML file is a bit ugly ...
=> stages/vagrant: add virtualbox support (COMPOSER-2503)

stages/org.osbuild.cloud-init.meta.json, test/data/stages/cloud-init/b.json, test/data/stages/cloud-init/b.mpp.yaml
Adds "ssh_pwauth" to `org.osbuild.cloud-init` to enable/disable (defaults to `false`) ssh authentication using username and password.
=> add ssh_pwauth  to org.osbuild.cloud-init

stages/org.osbuild.vagrant, stages/org.osbuild.vagrant.meta.json, stages/test/test_vagrant.py
When guest additions are not installed in VirtualBox Vagrant boxes then
the default shared `/vagrant` directory must be set to `rsync`,
otherwise Vagrant fails to start as the shared directory cannot be
mounted with the `vboxfs` filesystem.
Let's expand the schema to allow for `synced-folders` (currently only
accepted under the `virtualbox` variant of the schema) to allow setting
the bare subset of relevant options to configure this from `images`.
=> stages/vagrant: allow configuring synced folders (HMS-6116)

stages/org.osbuild.grub2.iso, stages/org.osbuild.grub2.iso.legacy, stages/org.osbuild.grub2.iso.legacy.meta.json, stages/org.osbuild.grub2.iso.meta.json, stages/test/test_grub2_iso.py, stages/test/test_grub2_iso_legacy.py
grub2 iso menus currently default to the first entry, but the official isos all default to the second, boot with test. This allows us to change that.
=> Add ability to set grub2 default menu entry

stages/org.osbuild.tar, stages/org.osbuild.tar.meta.json, stages/test/test_tar.py
The numeric-owner option omits the inclusion of user and group names in the archive metadata.  This is often desirable since name and group mappings can change the ownership of files during extraction.
The test uses the tarfile module to check that the uname and gname attributes in the tar archive itself are empty, which is the intended effect of enabling numeric-owner [1].
RHEL-102854
[1] https://www.gnu.org/software/tar//manual/html_section/Attributes.html
=> stages/tar: add --numeric-owner option [RHEL-102854]

.mypy.ini, osbuild/solver/dnf.py, tools/test/test_depsolve.py
This change is in relation with #2027
@achilleas-k 
This PR is to parse dnfvars for repos in a request and includes a commit for fixing baseurl in testing to be a list which was needed to be able to test dnfvars, also I added it in a different commit to make maintainers able to keep the fix even if the dnfvar change would be removed.
=> osbuild/solver/dnf.py: Add support for DNF variables for osbuild repos

stages/org.osbuild.bootc.install-to-filesystem, stages/org.osbuild.bootc.install-to-filesystem.meta.json
This adds an extra option to make the stateroot name customizable.
Fixes https://github.com/osbuild/osbuild/issues/2151
=> stages/bootc.install-to-filesystem: add more knobs

stages/org.osbuild.coreos.live-artifacts.mono
In https://github.com/osbuild/osbuild/pull/2148, we changed the logic to generate the volume ID from the data in `/usr/lib/os-release` to sever the reliance on metadata in the embedded treefile that will no longer exist.
This had no effect in FCOS, but had an effect in RHCOS, which went from a volume ID of `rhcos-...` to `rhel-coreos-...`. This was considered harmless at the time, but in fact ended up affecting the OpenShift Assisted Image Service. See e.g. https://github.com/openshift/assisted-image-service/pull/477 which attempted to adapt that code. But in the end, it felt safer and less work to just revert back to the previous volume ID. So here we are.
But we still don't want to go back to using the embedded treefile. Instead, we now have access to the OS name to use as a label on …
=> stages/coreos.live-artifacts: rework volume ID handling

.github/CODEOWNERS, CODEOWNERS
We somehow ended up with two CODEOWNERS files, one in the root created by the coreos team and one under .github/ for the rest.  This meant that only the one under .github/ was being used [1].
Merge the two files so all rules are active.  Prefer the file under .github/ to keep the repo root clean.
[1] https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners
=> github: merge CODEOWNERS files

osbuild/util/lorax.py, stages/org.osbuild.lorax-script, stages/org.osbuild.lorax-script.meta.json
This adds support for running the standard lorax `runtime-cleanup.tmpl` template.
I've been testing it by making a netinst manifest, inserting the runtime-cleanup.tmpl stage, and then running the manifest with osbuild. eg.
```
image-builder manifest everything-netinst | jq  > f42-cleanup.json
```
edit and add this after the dracut stage:
```
{
"type": "org.osbuild.lorax-script",
"options": {
"path": "99-generic/runtime-cleanup.tmpl",
"basearch": "x86_64",
"product": {
"name": "",
"version": ""
},
"branding": {
"release": "fedora-release",
"logos": "fedora-logos"
}
}
},
```
And cleanup the leftovers by excluding things from the squashfs stage. The complete stage looks like this:
```
"type": "org.osbuild.squashfs",
"inputs": {
"tree": {
"type": "org.osbuild.tree",
"origin": …
```
=> Add support for runtime-cleanup.tmpl

tools/osbuild-mpp
If we're creating an MBR partition, with more than 4 partitions, and there is no extended partitions defined, then always add one.
Otherwise any partitions after the 4th will be dropped and we fail in the later:
assert len(disk_parts) == len(self.partitions
=> osbuild-mpp: Automatically add extended partition as needed for MBR

osbuild/api.py, osbuild/remoteloop.py
When a remote command fails in remoteloop.py we currently get a quite confusing error:
```
File "/run/osbuild/bin/org.osbuild.rawfs", line 102, in main
with loop_client.device(image) as loop, mount(loop, mountpoint):
File "/usr/lib64/python3.12/contextlib.py", line 137, in __enter__
return next(self.gen)
^^^^^^^^^^^^^^
File "/run/osbuild/lib/osbuild/remoteloop.py", line 138, in device
path = os.path.join("/dev", payload["devname"])
~~~~~~~^^^^^^^^^^^
KeyError: 'devname'
```
The reason is that there is no "devname" as this is a message of type "exception". So this code follows the pattern that objectstore is using to get errors from message now so that we get the get any remote errors and raise them.
=> osbuild: add/use new `api.get_exception_from_msg()` helper

stages/org.osbuild.grub2.iso, stages/org.osbuild.grub2.iso.meta.json, stages/test/test_grub2_iso.py
We currently hardcode the location of the efi binaries to `/boot/efi/EFI`. This makes sense in general but when working with bootc containers the location is usually different and inside `/usr/lib/bootupd/updates/EFI`. So this commit makes the location configurable in a  similar way as we already have it for the grub2 (non-iso) stage (in the grub2 stage its under `uefi` but in this stage everything is flat incuding the vendor so `efi_src_dir` is flat as well).
The rational is that we want to build ISOs from bootc base images (c.f.
https://github.com/osbuild/bootc-image-builder/pull/1053) but also do not want every bootc installer image to have a special bootupd grub iso configuration (which would also hard to maintain as it would be duplicated in every container). So instead we use this …
=> stages: add `efi_src_dir` config to grub2.iso stage

osbuild.spec, selinux/README.md, selinux/osbuild-container.if, selinux/osbuild-container.te
osbuild is sometimes used in a privileged container. To do so you currently need to run with selinux domain unconfined_t. However, even then it doesn't work if any file label is set during the image build that is not part of the host selinux policy. To make that work, the domain requires the mac_admin capability, which unconfined_t doesn't allow. The osbuild_t type in the osbuild selinux policy allows this, but that can't be used in the container.
So, this instead adds a new osbuild_container_t type that can be used with podman run instead of unconfined_t, allowing osbuild to have the required capability. However, instead of making osbuild_container_t be unconfined, we define a tighter set of permissions that seems to make osbuild work for me.
I do sometimes see one remaining AVC:
```
AVC …
```
=> selinux: Add osbuild_container_t domain for using osbuild in a container

osbuild/buildroot.py, osbuild/loop.py, osbuild/remoteloop.py
In general, osbuild needs to run in a very privileged context, as it does all sorts of highly privileged operations. The most problematic is the use of loopback devices to create filesystems, etc. However, some types of images, in particular those creating bootc OCI images doesn't actually need to  use loopback devices, and we should be able to run those in containers with less privileges.
Unfortunately there are some places where osbuild unnecessarily uses highly privileged operations when that isn't necessary that makes this not currently work. However, with the changes in this MR I was able to run osbuild in a rootless podman container (i.e. with no real superuser privileges) and create a bootc container.
=> Allow building bootc images in unprivileged containers

osbuild/monitor.py, osbuild/pipeline.py, test/mod/test_monitor.py
Some stages generate metadata which contains information that can only be generated when a stage is running. The v2 result contains this metadata which was lost when using the JSONSeqMonitor. By passing stage metadata along to the monitor's result function, the JSONSeqMonitor can print it alongside the result.
=> monitor: collect metadata alongside the result of a stage
