osbuild/osbuild

assemblers/io.weldr.qcow2

I forgot that the `output_dir` is not part of the `options` structure, but the parent one (referred to as `args`).

correction for the qcow2 assembler

---

stages/io.weldr.dnf

configparser writes strings with quotes and lists with enclosing
brackets, both of which may not appear in dnf.conf.
dnf.conf(5) defines the format loosely.

stages/dnf: don't use configparser to write dnf.conf

---

assemblers/io.weldr.targz

This was dropped in cebed27cd. However, a tar of a tree is useful in its
own right as an output format.

assemblers: resurrect io.weldr.targz

---

assemblers/io.weldr.qcow2
samples/base-qcow2.json
samples/base-with-grub2.json
stages/io.weldr.grub2

Drop unused code, and reduce any loopback handling to the bare minimum.
The loopback handing for grub2 should be completely unnecessary, but we may need some help from the grub2 team to figure out the tooling. Note that grub2-install both installs the bootloader in the MBR and installs files into /boot, which we do not want.

Simplify our grub2 handling

---

osbuild/__init__.py

This change was requested during the package review process (related to #23):
https://bugzilla.redhat.com/show_bug.cgi?id=1731111

move stages and assemblers into /usr/libexec/

---

.pylintrc
osbuild/__init__.py
osbuild/__main__.py
test/Vagrantfile

See individual commits.
This fixes the vagrant test while still making it possible to run from source, albeit we need to pass `--libdir .` now. That makes more sense to me than guessing based on checking if `stages` is a directory.

Clean up libdir

---

.gitignore
Makefile
test/README.md
test/Vagrantfile
test/testing-rpms/README.md

RPM packages are now kept in output directory after build so that we
know exactly which packages to copy to the test. The test directory now
contains special directory for RPMs. Fedora developer portal is
referenced from README file.

improve vagrant test and its documentation

---

osbuild.spec

The previous commit added a symlink to `../osbuild`, which is helpful
when developing, but shouldn't be included in the rpm.

spec: only install regular files in stages/ and assemblers

---

.travis.yml

Let's always use the latest available Ubuntu release for our CI, we
are interested in potentially building old images, and using old
images as bulid images, but having an old distro as host is not
necessarily an aim. If we want to test with a greater diversity of
distros (which we do), we should do that in VM's, this should just
be for the simple/quick case.
Also restructure a bit to allow for more (named) tests.

travis: move to bionic

---

assemblers/org.osbuild.qcow2
samples/base-qcow2.json
test/2-configure-web-server.json
test/3-compose-qcow2.json
test/4-all.json

It's not necessary to specify it.
I don't think I need to set update any `base_ids`, because I only changed the assembler sample.

qcow2: remove partition_table_id

---

.travis.yml
Makefile
assemblers/org.osbuild.noop
osbuild-run
osbuild/__init__.py
samples/build-from-yum.json
samples/noop.json
stages/org.osbuild.yum

This adds two tests: noop and yum.
Noop just runs osbuild with one noop stage and a noop assembler.
Yum creates a Fedora 27 build image containing dnf and systemd. F27 was chosen as it is the most recent version of Fedora that can installed using yum. The reason to use yum at all is that travis runs on Ubuntu and ubuntu shipps yum (but not dnf).

travis: test osbuild itself in travis

---

.travis.yml
README.md
osbuild/__init__.py
osbuild/__main__.py
test/run-tests.py

This also changes the structure of the object store, though the
basic idea is the same.
The object store contains a directory of objects, which are content
addressable filesystem trees. Currently we only ever use their
content-hash internally, but the idea for this is basically Lars
Karlitski's and Kay Sievers `treesum()`. We may exopse this in the
future.
Moreover, it contains a directory of refs, which are symlinks named
by the stage id they correspond to (as before), pointing to an object
generated from that stage-id.
The ObjectStore exposes two methods, meant to be used with
`whith` blocks, both yielding a path to a tree.
`new_tree()`: When a base_id is provided, the directory will be
initalized with the given base_id, and when a tree_id is given,
the directory will be saved to the …

ObjectStore: add an object store class

---

.travis.yml
osbuild-run
osbuild/__init__.py
samples/base-from-yum.json

This allows the build tree to be generated from a pipeline, an operation which can be nested arbitrarily.
This in particular allows us to bootstrap on Travis, so we can run some more comprehensive tests.

Allow nested piplines

---

osbuild/__init__.py

Even if the yield raises an exception, we must always unmount to
clean up.

ObjectStore/get_tree: make sure to clean up the context manager

---

.gitignore
.travis.yml
osbuild/__init__.py
test/test_osbuild.py

We already allow loading from a description. This adds the opposite direction to export Pipelines, Stages, and Assemblers.

Add description() methods

---

osbuild/__init__.py

Renaming a directory over an existing one is only an error if the
existing one is not empty, in which case ENOEMPTY is thrown.
Tested with:
>>> os.mkdir("foo")
>>> os.mkdir("bar")
>>> os.rename("foo", "bar")
>>> open("foo/a", "w").write("a")
1
>>> try: os.rename("bar", "foo")
... except OSError as e: e.errno == errno.ENOTEMPTY
...
True

osbuild: check for right errno from os.rename()

---

stages/org.osbuild.dnf

Disable the module. There's no need to update the completion databse in
the container.

stages/dnf: supress error from completion module

---

stages/org.osbuild.users

This stage allows to add or modify users. For now, this includes all
fields available in passwd, setting auxiliary groups, and setting an ssh
key.
This is based on #58 by @msehnout, which didn't quite work for Composer's purposes. It didn't deal with existing users and had a few bugs. Sorry I didn't comment there, I was trying things out and changed it to fit my needs in the process.

stages/org.osbuild.users: manage users

---

stages/org.osbuild.dnf

dracut stumbled over the one we set up (errors about not being able to
access /dev/kmsg). Use the one that systemd-nspawn sets up instead.
Fixes #67

stages/dnf: use nspawn's vfs tree

---

samples/base-qcow2.json
stages/org.osbuild.fix-bls

grub2-mkrelpath uses /proc/self/mountinfo to find the source of the file
system it is installed to. This breaks in a container.
Add org.osbuild.fix-bls which goes through /boot/loader/entries and
fixes paths by removing anything before /boot.

stages/fix-bls: add workaround for grub2-mkrelpath

---

assemblers/org.osbuild.qcow2
samples/base-qcow2.json
stages/org.osbuild.dnf
stages/org.osbuild.fstab
stages/org.osbuild.grub2
test/pipelines/web-server.json

In particular, we are now able to boot with selinux enabled.
See individual commits for details.
Also includes some minor cleanups throughout.

dnf/fstab/qcow2: create images more similar to the stock fedora ones

---

samples/base-qcow2.json
stages/org.osbuild.debug-shell

This gives shell access into the image on a given tty. Useful for
testing and debugging, while minimally affecting the image.
Note that this must never be used in production, as it allows root
access without a password.
For instance this could be used to verify that an image was fully
booted:
```
[teg@teg-x270 osbuild]$ qemu-kvm -m 1024 -nographic -serial mon:stdio -snapshot  base.qcow2
sh-5.0# systemctl is-system-running --wait
running
```

stages: add debug shell

---

samples/base-test.json
stages/org.osbuild.test

Adds a new systemd unit to the image that will be pulled in by default,
run a given command, forward the output to a virtio serial port and
shutdown the machine.
We add a sample that uses this to verify that systemd conciders the
machine successfully booted. A simple way to run this test from the
commandline is to use
`$ socat UNIX-LISTEN:qemu.sock -`
to listen for either `running` for success or `degraded` or
`maintenance` for failure.
The image should then be booted using something like
`$ qemu-kvm -m 1024 -nographic -monitor none -serial none -chardev socket,path=qemu.sock,id=char0 -device virtio-serial -device virtserialport,chardev=char0,id=test0 -snapshot  base.qcow2`

stages: add test stage

---

.packit.yaml
Makefile

This is achieved using "jobs" from packit-as-a-service, more
specifically the propose_downstream job. Furthermore
sync_from_downstream job is configured to keep the spec file
synchronized and prevent merge conflicts for new releases.
Also a small change in Makefile was necessary as it does not reflect the
current state of the spec file in Fedora dist-git (tarball name is
different). The spec file itself is not modified in this commit, because
it will be synchronized automatically using Packit.

Set up continuous delivery for Fedora Rawhide/30

---

README.md
assemblers/org.osbuild.qcow2
samples/base-qcow2.json
test/pipelines/f30-boot.json

See individual commits.
Is "block size" correct for the error message? Why did we round to the nearest 512 bytes in the first place?

assemblers/qcow2: Pass size explicitly and clean up tmp handling

---

Makefile
osbuild.spec

Synchronize spec file from downstream (generated automatically by packit) and update makefile to reflect changes in spec file

downstream sync

---

osbuild/pipeline.py

We have never tried to reuse the first stage due to bad range in for loop. This PR fixes it.

osbuild: fix stages caching

---

README.md

Usage was updated to reflect changes of osbuild arguments. Detailed
information how to run osbuild the first time (hello world example)
was added.

README: update to match current state and add running example

---

osbuild/__main__.py

This commit changes the default value of --store argument from
.osbuild/store to just .osbuild. The reason is just to make the path
shorter.

osbuild: Change default value of --store to just .osbuild

---

assemblers/org.osbuild.qcow2
osbuild/buildroot.py

Two steps are required:
1) Introduce persistent storage in build root.
2) Move temporary image in assembler to the new storage.
We've decided to link containers' `/var` to host's `/var/tmp` (actually temporary dir in there) to have some kind of persistent storage in build root.
See individual commits for details.

Optimize memory usage in assembler stage

---

.gitignore
stages/org.osbuild.locale
test/__main__.py
test/integration_tests/__init__.py
test/integration_tests/run.py
test/pipelines/locale.json

Locale stage has been changed so that:
1) It is not used to change the keymap (use keymap stage).
2) It looks like similar stages. `systemd-firstboot` is now used to set the locale.
Also, I've fixed the integration tests. The fix will collide with #83 , but I've felt we need to have integration tests working in master asap.

Refactor locale stage

---

assemblers/org.osbuild.tar
test/__main__.py
test/pipelines/firewall.json
test/pipelines/locale.json
test/pipelines/timezone.json

This PR make two things:
1) Introduces option for tar assembler not to use any compression at all.
2) Drop the compression from all tests to speed up their running times.

Drop the compression from tar assembler in tests

---

stages/org.osbuild.firewall

there is no need to require all arguments in the firewall stage, so
let's reflect this in the code

make firewall options optional

---

.travis.yml
samples/build-from-yum.json

Both tests work in CI just fine so we should run them every time. I
introduce them as a separate jobs because jobs run in parallel so it
takes less time even though it does not share object store.

run timezone and firewall tests in CI

---

.packit.yaml

With packit 0.6, you no longer need to redefine archive and version commands,
packit now updates %[auto]setup line to correctly unpack the archive
`packit srpm`:
```
11:38:13.452 upstream.py       DEBUG  Wrote: /home/tt/g/osbuild/osbuild/osbuild-1.72.gc082222-1.fc30.src.rpm
SRPM is /home/tt/g/osbuild/osbuild/osbuild-1.72.gc082222-1.fc30.src.rpm
SRPM: /home/tt/g/osbuild/osbuild/osbuild-1.72.gc082222-1.fc30.src.rpm
```
`rpmbuild --rebuild $SRPM`:
```
Provides: python3-osbuild = 1.72.gc082222-1.fc30 python3.7dist(osbuild) = 1 python3dist(osbuild) = 1
Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PartialHardlinkSets) <= 4.0.4-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
Requires: python(abi) = 3.7 python3.7dist(setuptools)
Checking for unpackaged …
```

packit: use default tarball and version behavior

---

.travis.yml

Python buffers stdout and stderr if they're not connected to the
terminal. This messes with the ordering of osbuild and stage output,
becasue stages produce output more quickly.
Globally disable output buffering on travis.

travis: disable python's output buffering

---

.travis.yml

We only want to upgrade to a new version of pip after explicitly
opting in. Otherwise, PRs may randmly start failing just because
pylint was upgraded, but unrelated to the code change.

travis: pin the pylint version

---

.travis.yml
test/__main__.py
test/osbuildtest.py
test/test_boot.py

Use the unittest module from the standard library. Also, ensure that
separate runs of this test don't share a osbuild store and clean up
after themselves.
With contributions from Ondřej Budai and Tom Gundersen.

test: refactor boot test

---

README.md
assemblers/org.osbuild.qemu
samples/base-qcow2.json
test/pipelines/f30-boot.json

Make the assembler more generic, and update all the in-tree users.

assembler: rename qcow2 to qemu and add support for more formats

---

osbuild/pipeline.py

copy of commit message:
Storytime! I tried to run multiple osbuilds at once. It failed when
unmounting the buildtree. Weird. It turned out the buildtree was not
there anymore when osbuild tried to unmount it. But who unmounted it?
We need to deep dive into mount-types.
Nowadays, the / directory is shared-mounted by systemd. See:
https://serverfault.com/questions/868682/implications-of-mount-make-private
This has interesting implications, see the following example:
we start osbuild1 with /var/tmp/os1 as its store
osbuild1 creates /var/tmp/os1/tmp
osbuild1 bind-mounts / onto /var/tmp/os1/tmp
we start osbuild2 with /var/tmp/os2 as its store
osbuild2 creates /var/tmp/os2/tmp
osbuild2 bind-mounts / onto /var/tmp/os2/tmp
Now, the shared-mounting goes into effect:
The second mount-event gets …

osbuild/pipeline: Fix crashes when running multiple builds at once

---

samples/base-qcow2.json
stages/org.osbuild.dnf

This allows given packages to be excluded from the transaction. This
is useful if you want to install a group with certain exceptions.
A common thing to do in kicktstart files is:
```
rm -f /boot/*-rescue*
```
By instead excluding the dracut-rescue-config package we end up
with:
```
"deleted_files": [
"/etc/kernel/postinst.d",
"/usr/lib/dracut/dracut.conf.d/02-rescue.conf",
"/usr/lib/kernel/install.d/51-dracut-rescue.install",
"/boot/initramfs-0-rescue-ffffffffffffffffffffffffffffffff.img",
"/boot/vmlinuz-0-rescue-ffffffffffffffffffffffffffffffff"
],
```

stages/dnf: support --exclude

---

osbuild.spec
osbuild/pipeline.py

There is no real difference in these two directories. Composer already
uses /usr/lib, so OSBuild should use the same as well.

move files from /usr/libexec to /usr/lib

---

osbuild.spec

_libdir is platform dependant, but that is not what we want because we
would need additional runtime logic to handle platforms. this patch
overrides the defautl location

replace _libdir with _prefix/lib

---

test/osbuildtest.py

The testosbuild.TestCase class creates a fresh store for each test,
because tests should run independent of each other.
This can lead to long waiting times while developing a new test case.
Allow overriding the store used with OSBUILD_TEST_STORE. This should
never be used where tests are actually run. It is a development-only
feature.

test: introduce OSBUILD_TEST_STORE

---

samples/cloud-base.json

It is similar to the official Fedora cloud base image except for few
minor differences. The reason for this divergence is that we don't want
to include all hacks that are currently present in the official
kickstart file. You can see it here as a reference:
https://pagure.io/fedora-kickstarts/blob/master/f/fedora-cloud-base.ks#_149
* partition-table-id
* partition size
These are differences where I'm not sure we should even "fix" them:
* RPM verify throws much more errors with the official image (most of them are missing in `/usr/share/locale/`). This difference comes from [this line in cloud base ks](https://pagure.io/fedora-kickstarts/blob/master/f/fedora-cloud-base.ks#_149)
* Official image does not contain `linux-firmware` which is dependency of `kernel-core` and therefore cannot be …

Introduce cloud-base sample

---

.travis.yml
test/osbuildtest.py
test/stages_tests/firewall/a.json
test/stages_tests/firewall/b.json
test/stages_tests/firewall/diff.json
test/stages_tests/fstab/a.json
test/stages_tests/fstab/b.json
test/stages_tests/fstab/diff.json
test/stages_tests/hostname/a.json
test/stages_tests/hostname/b.json
test/stages_tests/hostname/diff.json
test/stages_tests/keymap/a.json
test/stages_tests/keymap/b.json
test/stages_tests/keymap/diff.json
test/stages_tests/locale/a.json
test/stages_tests/locale/b.json
test/stages_tests/locale/diff.json
test/stages_tests/systemd/a.json
test/stages_tests/systemd/b.json
test/stages_tests/systemd/diff.json
test/stages_tests/timezone/a.json
test/stages_tests/timezone/b.json
test/stages_tests/timezone/diff.json
test/stages_tests/users/a.json
test/stages_tests/users/b.json
test/stages_tests/users/diff.json
test/test_boot.py
test/test_stages.py
tree-diff

Greetings, this a pretty huge PR, grab yourself a cup of coffee and hear my words!
This PR introduces stage tests: The stage testing is based on an output from the tree-diff tool. During one test two pipelines are run and their outputs are compared using tree-diff. The diff is then compared with expected diff included in the repository.
There are currently some issues with this PR I would like to discuss. **One of them is blocker and we shall not merge this PR before it's solved.**
SELinux works differently on Fedora host than on Ubuntu host. On Fedora users and timezone stages change selinux labels on some files. On Ubuntu it doesn't happen. See also #89
We need to investigate what's exactly happening: Why Fedora changes the labels and why it doesn't happen on Ubuntu.
**Currently, …

Introduce stage testing

---

test/osbuildtest.py

When the test runner receives SIGINT, osbuild's mounts stay around.
osbuild handles SIGING correctly, but it doesn't have time before being
killed because it's parent went away.
Fix this by waiting on it explicitly in the test runner.

test: give osbuild time to clean up on SIGINT

---

assemblers/org.osbuild.qemu

Rather than relying on the offset parameter, simply run mkfs on the
loopback device which is anyway being set up. This also allows us
not to specify the size explicitly.
Before this patch mkfs would complain (uneccesarily) about the
backing file containing a partition table. This is a false positive
as the partition table is in the region of the file before the
passed offset.

assemblers/qemu: simplify mkfs

---

test/osbuildtest.py

We don't close osbuild's stdin when no input is given. Don't open stdin
at all when no input is specified.

tests: fix ResourceWarning: unclosed file when running osbuild

---

stages/org.osbuild.users

Otherwise user may be unable to login. More information:
https://stackoverflow.com/questions/6377009/adding-public-key-to-ssh-authorized-keys-does-not-log-me-in-automatically

stages/users: set authorized_keys file permissions to 600

---

stages/org.osbuild.chrony
test/stages_tests/chrony/a.json
test/stages_tests/chrony/b.json
test/stages_tests/chrony/diff.json

I'm not sure about naming of this stage... `org.osbuild.timeservers` sounds more like the other stages, but `org.osbuild.chrony` is imho more flexible and maintainable... What do you think?

stages: add org.osbuild.chrony stage

---

Makefile
osbuild/pipeline.py

In case osbuild is invoked without libdir parameter, the osbuild files
are not propagated into the buildroot container and therefore all
pipelines containing buildroot fail.
Example:
```
$ sudo osbuild --store /var/osbuild/ qcow2-pipeline.json
...
execv(/usr/lib/osbuild/osbuild-run) failed: No such file or directory
```
Unfortunately this is only the first error. Once you fix it, you realize
that also the symlink from "assemblers" directory is missing and
therefore you cannot import osbuild because it is not available anywhere
in the path. This is why I had to bind the osbuild module from host to
the build container.

fix execv /usr/lib/osbuild/osbuild-run does not exist

---

osbuild-run
osbuild/api.py
osbuild/pipeline.py
osbuild/remoteloop.py

Introduce a new osbuild-`API` through which the container, i.e. `osbuild-run`, can setup input and output (stdio) for the stage. Currently this is done passing fds over the API socket (when requested via `setup-stdio`). Input (the stdin for the container/stage) is a file-backed temp "buffer" to the json data. output (i.e. stdout of the container/stage) is either just the host's `stdin` or another file-backed temp buffer.
The buffer file is reopend for the container to get an independent file descriptor so writes and reads (and file modes) are independent.
This is a RFC, to make sure that is the right direction. If so I will clean the commits up and re-arrange them. I was also thinking of encapsulating that file-backed temp "buffer" code into its own small object (`FileBuffer` or some …

RFC: container-runtime independent stdio setup for the container

---

stages/org.osbuild.dnf
stages/org.osbuild.rpm
stages/org.osbuild.yum

Three stages (`org.osbuild.dnf`, `org.osbuild.yum`, `org.osbuild.rpm`) were writing files with predictable names in `/tmp`, which is generally a Bad Idea. (It makes me especially nervous when that's how they're handling GPG keys..)
So: the first two commits should make those stages use proper tempfiles / temporary directory to store keys and config files.
As an added bonus, the third commit should make `rpm --install` actually check & require valid package signatures so we don't have to manually check them.

Safe tempfiles, rpm cleanups

---

assemblers/org.osbuild.noop
assemblers/org.osbuild.qemu
assemblers/org.osbuild.rawfs
assemblers/org.osbuild.tar
stages/org.osbuild.chrony
stages/org.osbuild.debug-shell
stages/org.osbuild.dnf
stages/org.osbuild.firewall
stages/org.osbuild.fix-bls
stages/org.osbuild.fstab
stages/org.osbuild.groups
stages/org.osbuild.grub2
stages/org.osbuild.hostname
stages/org.osbuild.keymap
stages/org.osbuild.locale
stages/org.osbuild.noop
stages/org.osbuild.rpm
stages/org.osbuild.script
stages/org.osbuild.selinux
stages/org.osbuild.systemd
stages/org.osbuild.test
stages/org.osbuild.timezone
stages/org.osbuild.users
stages/org.osbuild.yum
test/test_stageinfo.py

This commit adds stage info for a few stages. The format of the stage
info is a work in progress, but it works like this:
STAGE_DESC: Short description of the stage.
STAGE_INFO: Longer documentation of the stage, including expected
behavior, required binaries, etc.
STAGE_OPTS: A JSON Schema (in TOML format!) describing the stage's
expected/allowed options.

Add STAGE_DESC, STAGE_INFO, and STAGE_OPTS to stages

---

LICENSE

This reverts commit 6add9c387ba647e5e3e71c268843358657caa212 as I
understood the license text in a wrong way.

Revert "Fill in the license template"

---

stages/org.osbuild.dnf

This is needed by modular repositories.

stages/dnf: add module_platform_id option

---

.gitignore
osbuild.spec
osbuild/pipeline.py

osbuild currently throws an error when not passing a build environment
on the command line, because the runner is unset. This is annoying on
hosts which only need a runner set, but no build pipeline.
To simplify running osbuild in this common case, introduce
`org.osbuild.host`, which is a runner that is defined to work on the
host that osbuild is installed on. Use this runner by default and
include a symlink to the right runner in the Fedora and RHEL packages.
Also add `runners/org.osbuild.host` to `.gitignore`, so that developers
can set the symlink when running osbuild from the source directory.
Fixes #171

pipeline: introduce host runner

---

assemblers/org.osbuild.tar
test/pipelines/f30-base.json
test/test_assemblers.py

Commit 283281f broke compression by appending the argument last to the
tar command line. It needs to appear before the file.
Fix that and add a test.

assemblers/tar: fix compression

---

osbuild/buildroot.py

Together with the `/lib/ld64.so.1 -> /lib64/ld64.so.1` (or `/lib64/ld64.so.2`) being the default on s390x (ppc64le), `systemd-nspawn` not creatling the (`lib64` -> `/usr/lib64` [#14311](https://github.com/systemd/systemd/issues/14311)) leads to the container being broken (no executables can be executed). So for those to platforms we create the missing link ourselves.

Work around an systemd-nspawn not creating /lib64 links on s390x/ppc64le 

---

assemblers/org.osbuild.qemu
samples/f30-aarch64.json
samples/f30-base-uefi.json
stages/org.osbuild.grub2

Since aarch64 is booted via UEFI & grub2 this is based on PR #173 from @bcl with the difference that I dropped the `org.osbuild.uefi-bls` stage and instead added (optional) support for UEFI to the grub2 stage. Also the copying of the grub modules can deal with the case that those are not available (as it is on aarch64). The rest is just adding the right grub2/shim packages. 
The one difference I noted compared to the fedora (rhel) guest images are the entries in `/boot/grub/*` created by anaconda:
```
echo -n "Creating grub.conf for pvgrub"
rootuuid=$( awk '$2=="/" { print $1 };'  /etc/fstab )
mkdir /boot/grub
echo -e 'default=0\ntimeout=0\n\n' > /boot/grub/grub.conf
for kv in $( ls -1v /boot/vmlinuz* |grep -v rescue |sed s/.*vmlinuz-//  ); do
echo "title Fedora ($kv)" >> …
```

mulit-arch: add aarch64 support

---

.editorconfig
osbuild/loop.py

Add a simple [editorconfig](https://editorconfig.org/) file, matching the current indent settings. Also fix some typos in loop.py.

Add editorconfig config file

---

osbuild/__init__.py
osbuild/__main__.py
osbuild/pipeline.py
test/osbuildtest.py

A pipeline run only returned logs in the `StageFailed` and
`AssemblerFailed` exceptions. Remove those and always return structured
data instead.
It only returns data for stages that actually ran (i.e., didn't come
from the cache). This is similar to the output in interactive mode.

pipeline: return logs in --json mode

---

osbuild/pipeline.py

Commit 82a2be53d introduced a new return type from `Pipeline.run()`. It
changed the caller in `__main__.py`, but missed that the build pipeline
uses the same function.

pipeline: return new-style result from build pipeline

---

osbuild/api.py
osbuild/remoteloop.py

The socket that the osbuild and loop apis should talk on are passed into
their `__init__` function. The caller should be responsible for closing
those sockets.
This already happens in all current callers.
This fixes a non-fatal error on RHEL's python 3.6, because it was
calling `socket.close` on an already-closed socket:
File "/usr/lib64/python3.6/asyncio/base_events.py", line 529, in __del__
self.close()
File "/usr/lib64/python3.6/asyncio/unix_events.py", line 63, in close
super().close()
File "/usr/lib64/python3.6/asyncio/selector_events.py", line 99, in close
self._close_self_pipe()
File "/usr/lib64/python3.6/asyncio/selector_events.py", line 109, in _close_self_pipe
self._remove_reader(self._ssock.fileno())
File …

api and remoteloop: don't close the passed-in socket

---

osbuild/pipeline.py
samples/error.json
stages/org.osbuild.error

The recent changes (#184) removed the {Assembler,Stage}Failed exceptions, which includes them being thrown from Stage.run and Assembler.run. Instead result dictionaries are returned even on errors. But the object store, used as a context manager, relies on exceptions to detect the error case and thus needs them to cleanup the temporary objects. Without those exceptions the temporary objects end up in the store even when the sage or assembler failed. Restore the old behavior by throwing a generic BuildError exception from the Stage and Assembler, which will be caught directly in the pipeline and converted to a result dict.
Fixes #188

pipeline: proper object cleanup on errors

---

assemblers/org.osbuild.qemu

Currently the partition table, partition and filesystem information is represented as nested dictionaries with a few helper functions working on those. For [hybrid](https://github.com/gicmo/osbuild/tree/hybrid) and [s390x](https://github.com/gicmo/osbuild/tree/s390x) support I need more functions working on those dictionaries (mainly a `partition_containing_path(path)`). Instead of having those dicts and methods so loosely coupled, introduce proper python objects with methods. The idea is is to later extract them into some sort of library and unit test them as well. The "factory methods" that create the objects from the options are still kept as functions because I am thinking of them as belonging to the stage itself (i.e. the syntax is stage dependent) not to the abstractions.

Introduce proper Partition{Table} & Filesystem objects

---

stages/org.osbuild.dnf

This is an expected error case, so we should not assert, but log
and return failure. In the future we should probably also return
the error as structured data.

stages/dnf: log more clearly in case the repo metadata changes

---

assemblers/org.osbuild.qemu
samples/f30-ppc64le.json
stages/org.osbuild.grub2
test/test_assemblers.py

This includes the necessary changes to the `grub2` stage as well as the `qemu` assembler.
The `grub2` stage has the `legacy` option (keeping compatibility) changed from a boolean to a string, specifying the target platform the legacy modules are being installed for. In the `qemu` the main difference to x86 legacy, i.e. non-efi, is that no stage 1 is required because the core image is stored on a special 'PReP' partition, which must be marked as bootable. The firmware then looks for that partition and directly loads the core from there and executes it. Introduce a `platform` parameter for the grub installer code which controls various platform depended aspects, including a) the path for the modules, b) what modules are compiled into the core, c) if the boot image is written to the MBR and …

multi-arch: add support for ppc64le (open-firmware)

---

osbuild/api.py
osbuild/buildroot.py
osbuild/pipeline.py
osbuild/remoteloop.py
osbuild/sources.py

This might (hopefully) fix a race in destructing the asyncio.EventLoop
that's used in all API classes, which leads to warnings about unhandled
exceptions on CI.
This also puts their creation closer to where the client-side sockets
are created.

osbuild: create API sockets in the thread they're used in

---

assemblers/org.osbuild.qemu
samples/f30-qcow2-gpt.json

Normally, when using Master Boot Record (MBR) partition layout and the grub2 (in non-efi mode) bootloader, the grub2 `core` image is located in the gap between the MBR and the first partition, which exists for history and performance reasons. When the partition layout is GPT this gap does not exist in that predictable way. Instead a specialized (small) partition is used is used, called the [`BIOS boot` partition](https://en.wikipedia.org/wiki/BIOS_boot_partition). The initial grub stage, as well as the gurb `core` image need to be adjusted when this partition is used.
A sample demonstrating the usage is included (`samples/f30-qcow2-gpt.json`). 
It successfully boots but there is one slight delay and a rather big one in grub2 execution. The former at `kern/fs.c:56; Detecting ext2` and the …

Support grub2 booting with GPT layout via BIOS boot partition

---

osbuild/__main__.py
osbuild/pipeline.py
osbuild/sources.py
sources/org.osbuild.dnf
stages/org.osbuild.dnf

Secrets are an extension of sources: a JSON object for each source that contains sensitive data which can be stored and passed separately and should not appear in logs.
Also includes a patch that makes use of secrets by adding support for the `sslcacert`, `sslclientcert`, and `sslclientkey` dnf options.
See individual commits for details.

Introduce secrets

---

assemblers/org.osbuild.qemu
samples/f30-qcow2-gpt.json
stages/org.osbuild.grub2

With the introduction of the `bootloader` (`qemu` assembler) option as well as the change of the `i386-legacy` option (`grub2` stage) the defaults changed, which broke at least the `f30-base-uefi.json` sample. Restore the old defaults.

Revert changed defaults for the qemu assembler and grub2 stage

---

samples/f30-qcow2-hybrid.json
stages/org.osbuild.grub2

Currently an image is either booted via UEFI (GPT partition layput and the grub2 efi binary in a dedicated EFI partition) or legacy boot (grub2 boot and core image on a mbr partition scheme). But, on single image can be made bootable via both methods with by having both a ESP partition (EFI) and the BIOS boot partition for legacy grub2 (see #198). The question was how to structure the configuration, i.e. how to make it so there is only one `grubenv` and main `grub.cfg` that are not duplicated. After talking to @vathpela and @martinezjavier the route chosen was to have the `grubenv` and canonical `grub.cfg` always in `/boot/grub2` and if (and only if) hybrid boot is requested install a small `grub.cfg` on the ESP that finds the canonical one and then loads that.

Hybrid boot support: one image can be booted via UEFI and legacy

---

README.md

Update the command line options help text as well as the sample command line to build the `base-qcow2.json` to include the new sources command line option.

README: add information about 'sources'

---

assemblers/org.osbuild.qemu
samples/f30-bootpart-hybrid.json
stages/org.osbuild.fix-bls
stages/org.osbuild.grub2

Introduce options for the `org.osbuild.grub2` and `org.osbuild.fix-bls` stage so that they support `/boot` being on a separate partition. The basic change for most of the changes in both stages is that if paths need to be specified relative to the root of the filesystem of the partition which is `/boot/...` if `/boot` is on root or `/...` if `/boot` is separate.
Includes a "kitchen-sink" example that supports hybrid boot with `/boot` being on separate partition. 
Maybe the awesome @martinezjavier could have a look? ;D
Closes #208

Support for a separate boot partition

---

osbuild.spec

The Fedora 31 and Fedora 32 runners are symlinks but the spec file only looked for files and not symlinks. Fix that.
Follow up by `6a14ba40f7ef206e8ea577bd8ff8d0f9ca28b186`. Found by @larskarlitski .
NB: This will install the symlinks as actual files, which might not be the worst idea, but not 100% sure that is what we want.

osbuild.spec: actually install runners symlinks

---

stages/org.osbuild.dnf
stages/org.osbuild.error
stages/org.osbuild.grub2
test/test_osbuild.py

Loads `stages` and `assembler` stages as modules and tries to load the json and fail if that fails. Fix the invalid json in `STAGE_OPTS` of the stages that the test discovered.

Add a unit test to verify `STAGE_OPTS` has valid json

---

assemblers/org.osbuild.qemu
assemblers/org.osbuild.rawfs
samples/base-qcow2.json
samples/base-rawfs.json
samples/base-rpm-qcow2.json
samples/cloud-base.json
samples/f30-aarch64.json
samples/f30-base-uefi.json
samples/f30-bootpart-hybrid.json
samples/f30-ppc64le.json
samples/f30-qcow2-gpt.json
samples/f30-qcow2-hybrid.json
samples/f30-s390x.json
stages/org.osbuild.grub2

For the `qemu` and `rawfs` assemblers the image `size` attribute was wrongly declared as `string`. The `qemu` assembler also was missing the `dos` option as an alias for `mbr`. The `grub2` stage allows `legacy` to be a `boolean` or a `string`.
All the samples had wrong types for `org.osbuild.fstab.{freq, passno}` (were `string`, should be `integer`).

Small fixes for the json schemata and the samples

---

.travis.yml
osbuild/__main__.py
osbuild/objectstore.py
osbuild/pipeline.py
test/test_objectstore.py

During `osbuild` development of a certain stage, it very often is the case that one wants to to cache the result of everything up to that stage. This is already currently possible by creating an identical pipeline up to that stage and running that but that is somewhat inconvenient.
Therefore this PR adds support for a new `--checkpoint` option to `osbuild` which can be used to create checkpoints of the tree at arbitrary points in the pipeline. 
The argument to `--checkpoint` will be matched against the stage identifier and supports file name matching a la `fnmatch`. The stage identifier consists of a prefix and the stage name, where the prefix is `"/"` for the main stages or `"build/"` for stage in the build pipeline. Examples:
-  ` "*"`        will match all stages
-   `"/*"`      will …

Add support for checkpoints

---

.gitlab-ci.yml

We're not using the GitLab CI integration yet and we will need to
rethink how to implement it anyway.

Remove unused GitLab CI configuration

---

stages/org.osbuild.dnf

Enabling the fastestmirror plugin allows dnf to choose the fastest
(also usually the closest) mirror to the instance of osbuild. It
has no effect on builds that force the use of a specific server
or mirror.

dnf: enable fastestmirror by default

---

.travis.yml
Makefile

Building rpm directly on Ubuntu is somewhat possible but it's fragile and
it cannot cover all quirks of rpm build. This commit switches the rpm build
tests to using fedora containers. This isn't also the best solution but
imho it's much better than the previous one.
I opened this PR because #226 is failing due to rpm macro failure which doesn't look like fun to fix. As our setup is kinda strange (building rpm directly on Ubuntu) I decided to rework it using Fedora containers. Packit might be a better solution but I'm not sure if we can rely on it currently and I don't mind having another independent rpm build check in Travis CI.
Also, I'm not sure if want to we to test the rpm build build against rawhide, it might be a bit fragile...

ci: run the rpm build tests in Fedora containers

---

Makefile
osbuild.spec

This changes the name of the source tarball, but apart from that has
no effect as-is.
However, if the `commit` global is set, then the source tarball is
expected to be the standard git-archive at that commit, and the
release field is set to contain the date and the git sha. This is
useful for when we want to build rpms between releases.
This works analogously to how osbulid-composer currently works.
See <https://fedoraproject.org/wiki/Forge-hosted_projects_packaging_automation>
for details.
See <https://gist.github.com/teg/f9c267b2da7ba0aafda02a5b306d44ec> for how this could be used.

spec: use forgemeta

---

.github/workflows/build_rpms.yml
.travis.yml
setup.py

* Bump `setup.py` to version 8 to match the spec file
* Build RPMs natively in Fedora 31, 32, and Rawhide containers via GitHub Actions
* Remove redundant RPM builds in Travis CI

Build RPMs via GitHub Actions

---

test/pipelines/sources.json

The chosen mirror was flakey, causing CI to fail. Move to using the baseurl.

test/sources/files: use baseurl

---

.github/workflows/build_rpms.yml

Make RPM building more similar to how RPMs will be built in koji.
This downloads the specfile from github at the given commit, appends
the commit sha to the specfile and uses spectools to download the
correct sources from github.
This should be equivalent to what is done in the makefile, the only
behavioral difference is that the rpms are now versioned based on
the git sha they are built from.
The main purpose of this change is to avoid any differences between
the CI and the real RPMs due to bugs in the Makefile. Correctly
versioned RPMs will also be handy for testing/debugging/deployment.

github: use only specfile to build RPMs

---

osbuild.spec
runners/org.osbuild.fedora33

Add an additional symlink for Fedora Rawhide, which is currently set
as release 33.

Allow osbuild to run on rawhide (f33)

---

.github/workflows/build_rpms.yml

By default, GitHub Actions stops running all RPM builds if one fails.
This means that a temporary repository issue (like what is happening
with F32 today) stops all RPM builds.
Set the `fail-fast` option to `false` to disable this behavior.

🧨 Run all RPM builds even if one fails

---

.github/workflows/build_rpms.yml

Avoid delays and problems with the modularity repositories
by disabling them before building RPMs.

📦 Disable Fedora modular repos

---

runners/org.osbuild.rhel81

Add a rhel 8.1 runner that is based off of the rhel 8.2 runner with the only difference being the etc/os-release content. The spec file cannot currently distinguish between rhel minor releases so this runner is not symlinked as the host runner in the spec file.

runners: add rhel 8.1 runner

---

.github/workflows/tests.yml
osbuild/objectstore.py
osbuild/pipeline.py
test/osbuildtest.py
test/test_objectstore.py

This series of commits does away with the automatic commit at the end of the last stage of the normal pipeline (for now the auto-commit of the last stage of the _build_ pipeline is kept).
It does that by channelling all read and write operations to the store via the object `Object` (renamed from `TreeObject`). This `Object` can have a _base_ (i.e. another `Object`, realisticly a tree) and implements Copy-On-Write semantics: read operations will be done directly from the _base_ directory, if no `write` operation has been done to the tree yet. On such a `write` op, the contents of _base_ will be coped to a temporary directory. When an `Object` is committed to the store, the contents of the temporary directory will be moved inside the store. The `Object` will then be reset (a new temporary …

No automatic commits for the last stage

---

runners/org.osbuild.blank

This adds a new runner called `org.osbuild.blank`, which assumes /usr
is pre-populated and ready to go. It does not perform any OS setup. It
only initializes the environment and executes the stage.
This runner allows easy bootstrapping of new systems. It assumes our
ideal setup where `/usr` describes a host system in its entirety,
without any local policy applied. Thus, this runner is also what we
ultimately want to work towards as a default. This might not happen
anytime soon, though, given how `passwd`, `ldconfig`, `nss`, etc. still
depend on prepopulated caches in `/etc`.

Add blank runner

---

osbuild/__main__.py

(Copied from the commit-message:)
This modifies the help-strings for parameters in `osbuild --help`.
Rather than using the identifier to describe its purpose, make it
describe its type. That is, this changes:
--sources=SOURCES         =>        --sources=FILE
The option-name should already describe the purpose, so lets use the
argument-name for the type. This also improves on the stuttering when
reading the output.
We already do that for options that take directories as arguments. For
some reasons, we did not do that for options that take file-paths.
It is arguable whether this should be `PATH` or `FILE`. The latter has
the advantage that it makes clear that it is not a directory. It should
be obvious that `FILE` allows all kinds of paths.
Lastly, this does not update the positional …

osbuild: make parameter identifiers more descriptive

---

README.md
docs/osbuild.1.rst

This series adds an initial man-page to the project, called `osbuild(1)`, which describes the osbuild command-line tool. This allows us to have a canonical place of where to document the user interface of osbuild, the pipeline definitions, as well as general execution behavior.
As a follow-up, this cleans up the README file, adds referrals to man-pages, websites, etc. for more information, and finally provides build and install instructions.
Comments welcome! Note that this is explicitly kept simple, so we can extend on all of the places in the future. There is a lot more to document in the man-pages, but it is still unclear what our stability guarantees are. Hence, this is left for future updates. For now, this just sets up the infrastructure.

Minor improvements on project documentation

---

RELEASE.md

We don't use Packit any more, so just remove it from the RELEASE document. If we ever want to reintroduce it, feel free to simply revert this commit.

 Remove section about Packit from RELEASE.md

---

osbuild/pipeline.py

Only commit checkpoints to the object store if the run of the stage or assembler was successful. Otherwise we commit a empty, corrupted or old tree to the store. Any subsequent run might then pick up that bogus tree as a starting point.

pipeline: don't commit checkpoints on error

---

MANIFEST.in

The MANIFEST.in file is used to include `LICENSE` in our python source
distribution. However, we never use this. In our spec-files we use the
rpm `%license` macro which copies from the source checkout, anyway.
Lets drop this file so we can forget about it.

build: drop unused MANIFEST.in

---

RELEASE.md

The rule for the tag name is to have a 'v' prefix, update the release instruction to reflect that.

RELEASE.md: update to mention 'v' tag prefix

---

Makefile
osbuild.spec

Since we have a man page for `osbuild` :heart:, build and install it in the RPM.

spec file: build and install the osbuild(1) man page

---

setup.py

Remove the unused 'glob' import. Issue found by lgtm.com

setup.py: remove unused import

---

osbuild/objectstore.py
osbuild/pipeline.py
test/test_objectstore.py

Refactoring of the `Pipeline.run()` code so to not automatically commit the build pipelines to the store. 
Closes #259

Do not automatically commit build pipelines to the store

---

.github/workflows/tests.yml
Makefile
osbuild.spec

This PR extends `make man`. See each commit for details. The driving force is to allow me to extend `osbuild.org` to automatically pull documentation from the respective osbuild repositories and deploy documentation to `osbuild.org`.
I know this touches Makefiles and, thus, triggers all our feelings. I tried to document everything, keep crazy features out, and just make sure the make-rules are solid and work under all circumstances. Ask me if anything is unclear.
Lastly, this extends the CI to actually build the man-pages. This will make us catch any formatting errors (or Makefile corruptions) much earlier. Yey!

Improve Build of Man-pages

---

sources/org.osbuild.files

Add a 10s connection timeout and a 45s overall timeout for each file
transfer.
Also increase the retries to 10 and the concurrent threads to 15.
Hopefully this should make things a bit more stable in the face of
bad mirrors. In the future we may want to reconsider using some
lower-level library if that proves necessary.

sources/files: time-out curl

---

docs/osbuild.1.rst

The used format of `-X, --long=VALUE` is not a valid option-list entry,
even though it is very commonly used all over the linux man-pages. Use
the supported format of `-X VALUE, --long=VALUE`, which will format
correctly in the man-page and html outputs.
For reference, these formats are valid in RST option-lists:
-a                      Short option
-c arg                  Short option with arg.
--long                  Long option.
-2, --two               Aliases on a single line.
-f FILE, --file=FILE    Aliases with arguments.
/V                      VMS/DOS-style option.

docs: fix incorrect option-list formatting

---

osbuild.spec

We have some news for the world to read, therefore include the recently added `NEWS.md` file in the rpm package.

spec: include NEWS.md in docs

---

osbuild/pipeline.py

Delay the cleanup of the build tree of the build pipeline, and first check the result and only cleanup the tree when the build did not fail, because in that case both returned trees will be `None` and trying to cleanup them up will result in an exception. Therefore, also don't clean up `tree` in the error case.
Closes #288

Delay the cleanup of build trees in `build_stages`

---

Makefile

If the local checkout has no git tags, the contributor list cannot be
generated. Just omit the information in that case. We can try to be
more clever here, but lets fix this first. I could not come up with any
reasonable solution to improve on this easily. Hence, the source
includes a comment explaining that you might just have to fetch the git
tags first.

build: fix `make release` contributor list without git tags

---

osbuild/pipeline.py

If there is a build pipeline specified, always build it, even if there are no accompanying stages. If we short-circuit earlier and ignore the build pipeline section, errors in the build pipeline would not be caught at all.
Closes #289

pipeline: ensure the build tree is always built

---

.github/workflows/runtime-tests.yml
.github/workflows/tests.yml
.travis.yml

Heyho
CC: @major 
This converts some more of the runtime tests to github actions. I decided to pick a separate workflow, so we can define globals that affect all jobs in the workflow. I only ended up doing this for the `PYTHONUNBUFFERED` thing, since github-actions is quite limited in its programmability and gives almost no tools to extract things into reusable functions. Anyway, I think this all works fine.
There is still one test left in Travis, since I cannot test it right now as it triggers kernel bugs for me. I will look at them once I figured that out.
Thanks
David

ci: convert more tests to github-actions

---

.github/workflows/tests.yml

Now that containers are being built daily in GitHub Actions from
the container[0] repository, we can use those containers. That will
speed up the GitHub Actions for osbuild and reduce errors from
unreleased Fedora versions.
[0] https://github.com/osbuild/containers

💃 Use pre-built containers

---

osbuild.spec

RPM is smart about dependencies - it goes over all shebangs of packaged files
and adds Requires to them. Prior this commit osbuild package depended on
python 3.6, because rhel runner has /usr/bin/python3.6 as shebang.
This commit fixes it by turning off dependency generators for our internal
stuff: assemblers, runners, stages and sources. They run in a container,
so I think there's no reason generate dependencies from them.

spec: do not generate deps from internal files

---

test/test_boot.py

Recent qemu version will warn with our current code:
qemu-system-x86_64: -accel kvm:hvf:tcg: Don't use ':' with -accel,
use -M accel=... for now instead
Since this might result in hard-errors, lets just follow the advice and
use the `-M` switch.

test/boot: convert `-accel ...` -> `-M accel=...` for qemu

---

osbuild/__main__.py

This drops support for passing in non-manifest style pipelines
directly. It used to be that we directly pass in the pipeline
description, but it got changed to a proper manifest format in:
commit e48c2f178cb047d3872ea494206788072f13594d
Author: Tom Gundersen <teg@jklm.no>
Date:   Thu Feb 13 17:44:54 2020 +0100
osbuild: allow the sources to be passed in on stdin
With 2 releases in between, we are now far enough to drop the old
format. All code has been converted, our API guarantee is not in place,
yet, so lets just drop the legacy code and fully commit to the
manifest.
Fixes #265.
(I am completely unsure whether we fixed all tests. But CI will bail me out!)

osbuild: drop legacy input format

---

runners/org.osbuild.rhel82

The bug was fixed upstream and is available in the latest 8.2 builds.
Since it is not yet released, we don't need to keep the hack around.
Fixes #294

runners: drop os-release hack for rhel-8.2

---

osbuild/__main__.py

osbuild can now take only manifests as its input (the legacy input format
was dropped in e48c2f1). This commit changes all remaining occurrences of
"pipeline" to "manifest" when describing the osbuild input.

osbuild: use "manifest" when describing the osbuild input

---

osbuild/objectstore.py
test/test_objectstore.py

`objectstore.Object` is creating a temporary work dir and then the actual directory for the tree that is being used for write operations. Currently we rely on the cleanup mechanisms of the top level workdir, i.e. `Tempfiles.TemporaryDirectory.cleanup()`, to also remove all the child-directories, including the the `Object._tree` directory.
Internally Python 3 is using its `shutil.rmtree()`, with a custom `onerror` handler that will fixup permissions transparently. Sadly the current [version](https://github.com/python/cpython/blob/50e6e991781db761c496561a995541ca8d83ff87/Lib/tempfile.py#L795) of it will not reset the immutable file attribute (see `chattr(1)`). The result is that cleanup of trees that contain immutable files will fail. 
Therefore, roll a custom `onerror` handler that will …

Make objectstore.Object delete its tree on cleanup

---

osbuild/pipeline.py

Move the whole result handling of the assembler outside the context manager; this includes the cleanup of the object in the error case which would conflict with the ongoing write operation inside the context manager and thus lead to a crash:
```
File "/usr/bin/osbuild", line 11, in <module>;
load_entry_point('osbuild==10', 'console_scripts', 'osbuild')()
File "/usr/lib/python3.7/site-packages/osbuild/__main__.py", line 99, in main
secrets=secrets
File "/usr/lib/python3.7/site-packages/osbuild/pipeline.py", line 362, in run
libdir)
File "/usr/lib/python3.7/site-packages/osbuild/pipeline.py", line 324, in assemble
output.cleanup()
File "/usr/lib/python3.7/site-packages/osbuild/objectstore.py", line 160, in cleanup
self._check_writer()
File …
```

pipeline: check assembler res outside context mgr

---

assemblers/org.osbuild.qemu
samples/f30-qcow2-gpt.json

The GUID Partition Table (GPT) layout supports assigning UUIDs for individual partitions. Add support for specifying those in the partition description.

assembler/qemu: support for GPT partition UUIDs 

---

samples/f30-aarch64.json

The "legacy" option in stages/org.osbuild.grub2 defaults to True:
`legacy = options.get("legacy", True)`
If both legacy and uefi is enable, the stage will try to create a hybrid
image, but that fails for aarch64. This patch makes sure we use uefi
mode only which fixed this issue.
I tested the patch by hand together with the fix from this PR:
https://github.com/osbuild/osbuild/pull/308

samples: set legacy to false in f30 aarch64 sample

---

test/osbuildtest.py

Make sure we prune the caches after each stage-test to keep our disk
footprint small. This does considerably increase build-times since we
no longer share cached entries. However, the current CI builds simply
run out of disk-space.
Once we use separate output-directories we will be able to drop the
automatic checkpointing from the tests, and thus effectively get the
same behavior. Until then, lets prune the caches explicitly.

test: prune cache after each stage-test

---

osbuild/pipeline.py

Causes a problem with ostree-osbuild on CI (travis) otherwise:
```
File "osbuild-ostree", line 345, in <module>
sys.exit(main())
File "osbuild-ostree", line 337, in main
return build(args)
File "osbuild-ostree", line 257, in build
output_id, commit_id = build_commit(builddir, args)
File "osbuild-ostree", line 162, in build_commit
r = pipeline.run(store.store,
File "/home/travis/build/gicmo/ostree-osbuild-demo/osbuild/osbuild/pipeline.py", line 358, in run
r = self.assemble(object_store,
File "/home/travis/build/gicmo/ostree-osbuild-demo/osbuild/osbuild/pipeline.py", line 314, in assemble
r = self.assembler.run(input_dir,
File "/home/travis/build/gicmo/ostree-osbuild-demo/osbuild/osbuild/pipeline.py", line 148, in run
osbuild_module_path = …
```

pipeline: explicitly import importlib.util

---

assemblers/org.osbuild.qemu

VHDX is the best format for uploading to AWS, thus this commit adds the
support for it. Pros over other formats supported by AWS:
- vmdk - doesn't work, qemu-img probably needs some special options
- vhd - the image size gets round up (I can get only a >=7GB volume from
a 6GB image)
- ova - just a wrapper over vmdk/vhd/vhdx adding some metadata
- raw - no compression, the images are huge
Also, the format specification is open, therefore I can't see any issues
with it.

assembler/qemu: add support for vhdx format

---

samples/base-qcow2.json
samples/base-rawfs.json
samples/base-rpm-qcow2.json
samples/cloud-base.json
samples/f30-aarch64.json
samples/f30-base-uefi.json
stages/org.osbuild.grub2
test/pipelines/f30-boot.json

For the sake of backwards compatibility, legacy support was enabled
by default. Flip this around, so that leaving the parameter out
means disabling it.
This is more intuitive, and will pave the way for dropping support
for the value being a bool in the future.
`osbuild-composer` always passes the argumnet explicitly, though
still always as a boolean. We would like to replace that by passing a string. See https://github.com/osbuild/osbuild-composer/pull/501

stages/grub2: default to disabling `legacy` support

---

docs/osbuild.1.rst
osbuild/__main__.py
osbuild/pipeline.py

Add a new output-directory argument which specifies where to store
result objects. For now, this is purely optional and simply copies from
the old `output_id` into the specified directory. This allows a
backwards compatible transition towards removing any external access to
the osbuild cache.
Note that this has still lots of room for improvements:
* We only support assembler-output for now, but we could also easily
support entire trees as output, in case no assembler was selected.
Alternatively, we could introduce a "copy" assembler, that just
outputs the input tree.
* This parameter is optional, but should really be mandatory. There
is little reason to have the default behavior just dropping any
generated content. This would be a breaking change, though.
* We could move data out of a …

osbuild: add --output-directory=DIR

---

stages/org.osbuild.first-boot
test/stages_tests/first-boot/a.json
test/stages_tests/first-boot/b.json
test/stages_tests/first-boot/diff.json

This stage runs a given command only on the first boot of the image,
useful for doing instantiation tasks that can only be done in the
target environment, or that should be done per-instance, rather
than per image.

stage: add org.osbuild.first-boot

---

osbuild.spec

Ship the stages, assembler and source that are necessary to build images with OSTree support in the osbuild-ostree sub-package.

spec: ship ostree specific files in sub-package

---

assemblers/org.osbuild.tar

By default, xz only uses one CPU core even if multiple cores are
available. If xz compression is chosen, allow xz to use all of the
cores available.

🐎 Allow xz to use all available CPUs

---

samples/base-qcow2.json

This fixes a typo: `386-pc` -> `i386-pc`

samples: fix grub2-legacy in base-qcow2

---

stages/org.osbuild.fstab
stages/org.osbuild.grub2

In various places (stages: `fstab`, `grub2`; asembler: `qemu`) it was assumed that file systems were identified via unique ids (uuids); but file systems can also be identified via their labels, and indeed ignition requires them to be done in that way. 
Part of #286

Support for identifying filesystems via their label instead of uuid

---

osbuild/loop.py

The mknod() method currently allows passing no dir_fd, in which case an
internal one is opened. This FD is then never closed, though.
Fix this by simply making the dir_fd mandatory. All callers pass it
(there is actually only a single caller), so no need for the fallback.

loop: fix FD leak in mknod()

---

stages/org.osbuild.grub2

For historical and occult reasons the grubenv file is, according to its [documentation][1] a 'preallocated 1024-byte file'. The unused space in the file needs to be filled with '#' as padding, which tools will count as "free space" and there needs to be a trailing new-line.
Fix our code to do as they say to make grub2-editenv work and in turn greenboot.
[1]: https://www.gnu.org/software/grub/manual/grub/html_node/Environment-block.html
[2] grub-core/lib/envblk.c#L105 (commit 0f102b9844f852d48501d231d32a17e1cc24062d)
Closes #342

stages/grub2: ensure grubenv file has size of 1024

---

osbuild/objectstore.py
osbuild/util/linux.py
osbuild/util/rmrf.py
test/test_objectstore.py
test/test_util_linux.py
test/test_util_rmrf.py

This extracts remove_tree() into its own module so we can use it from other places more easily. This series also contains some minor adjustments and documents the ioctl-details. See each commit for details.

osbuild: extract remove_tree() into its own module

---

osbuild/buildroot.py
osbuild/objectstore.py
stages/org.osbuild.ostree

Two cleanups for the context-managers we use:
* Use `contextlib.AbstractContextManager` if possible. This class
simply provides a default `__enter__` implementation which just
returns `self`. So use it where applicable.
Additionally, it provides an abstract `__exit__` method and thus
allows static checks for an existance of `__exit__` in the dependent
class. We might use that everywhere, but this is a separate
decision, so not included here.
* Explicitly return `None` from `__exit__`. The python docs state:
If an exception is supplied, and the method wishes to suppress
the exception (i.e., prevent it from being propagated), it
should return a true value. Otherwise, the exception will be
processed normally upon exit from this method.
That is, unless we want exceptions to be suppressed, we …

osbuild: cleanup contextlib usage

---

setup.py

Make sure ./osbuild/util/ is considered a python module. Add
__init__.py to declare it as such.

util: mark as module by adding __init__.py

---

osbuild/buildroot.py

This adds one more flags to `systemd-nspawn`:
--keep-unit
This prevents nspawn from creating its own scope unit and
instead uses the scope of the caller. Since we want nspawn to
run with the privileges of the caller, this is fitting for our
use case.
Furthermore, this makes nspawn work without a running system
bus, since it no longer needs to talk to systemd pid1.
(introduced with systemd-v209)
With this in place, osbuild can be run from within docker containers (or
other containers without systemd as pid1). This still requires some
extra setup, but this can all be done in the container manager.

buildroot: reduce nspawn requirements further

---

jenkins/run_tests.sh

Convert the bash script to an ansible playbook so we can gracefully
handle testing failures and gather logs reliably. Colorful output
is nice, too.
This brings osbuild's testing script in line with the script for
osbuild-composer.

🥊 Resilient testing + log gathering

---

osbuild/buildroot.py

Remove an unnecessary format string modifier and unify the usage of quotation marks.

buildroot: micro cleanups for some strings

---

.github/workflows/runtime-tests.yml
.github/workflows/tests.yml
Makefile
test/mod/__init__.py
test/mod/test_util_ostree.py
test/mod/test_util_selinux.py
test/run/__init__.py
test/run/test_sources.py

This PR starts grouping tests in logical sets, easily distinguishable by their path: `./test/mod/` for module unit-tests and `./test/run/` for runtime tests. With this in place, we can now use the auto-discovery of `unittest` to run just a selected set of tests. I also added makefile targets to run `unittest` with the correct parameters: `make test-module` and `make test-runtime`.
I discussed this shortly with @gicmo before. We both would like to have an easier way to run unitests locally. With this in place, a short `make test-module` runs all local unittests. A `make test-runtime` runs the more complex runtime tests, and `make test-all` runs all tests in `./test/`.
I did not move all tests to their correct location in this PR. I first wanted to get a discussion going.
Note that this PR …

Collect tests in logical groups

---

sources/org.osbuild.ostree

Make sure access to the shared ostree metadata is locked properly. This
is the default since 2018.5, but lets be explicit here. This also makes
sure that the option exists and the local version supports locked and
protected access.
It is unclear whether the `ostree init` honors that as well. It really
should, and if it doesn't we can always report it upstream.
(This is untested. I just prototyped this. Lets see what the CI says :eyes:)

sources/ostree: enable locked-access explicitly

---

.github/workflows/tests.yml
osbuild/pipeline.py
osbuild/util/osrelease.py
test/mod/test_util_jsoncomm.py
test/mod/test_util_linux.py
test/mod/test_util_osrelease.py
test/mod/test_util_rmrf.py
test/test_osrelease.py

This moves some more utility tests into `test-module`, as well as moves the os-release parser into `./util/` to keep it with the other helpers.

Move more tests into `make test-module`

---

osbuild/__init__.py
osbuild/__main__.py
osbuild/main_cli.py
setup.py

This series contains some preparations for additional executable entrypoints in `./osbuild/`. With this in place, we can then add `osbuild-api` and similar executables easily to the codebase.

Preparations for additional entrypoints

---

NEWS.md

Create a preliminary NEWS entry for the upcoming v13 release. Lots of
fixes all over the place, but most of them not worth mentioning for the
release. However, we do have some feature improvements as well.
@gicmo As usual, feel free to adjust, extend, delete.

build: fill in preliminary NEWS entry for v13

---

osbuild/buildroot.py

With `--keep-unit` we now run with the privileges and resources of the
caller. We no longer require external services to extend our privileges.
This also means we no longer have to configure our unit sandbox
manually, but simply rely on kernel sandboxing to do the right thing.
This should fix a warning nspawn spits out about `DeviceAllow=` being a no-op.

buildroot: drop unneeded `DeviceAllow=`

---

jenkins/run_tests.sh

Jenkins now uses a non-root user for its agents, so we will need to use
sudo for some commands.
Stolen from osbuild/osbuild-composer#581, big thanks to @major!

jenkins: Use sudo for tests

---

jenkins/run_tests.sh

This commit turns on the `cleanup_composer_directories` option to clean up
the osbuild-composer directories during the time the services are stopped
(when ansible-osbuild is about to deploy the new versions of the
services).
Taken from osbuild/osbuild-composer#575, thanks to @major!

jenkins: remove composer directories before the tests

---

osbuild/buildroot.py

This reverts commit 33844711cd20f29d067047aaeb8682ac188428ba.
There are systems were our runners have no standard python3 location
available. They will fix the environment before invoking any further
utilities. Therefore, we cannot rely on `python3 foo.py` to work in our
ad-hoc containers.
This simply reverts the behavior back to using the shebang.

Revert "buildroot: explicitly invoke runners via python3"

---

jenkins/Jenkinsfile
jenkins/run_tests.sh

By using a small Jenkins pipeline in the repository, we can define
almost all of our testing parameters in the repo itself and not inside
Jenkins.
This also allows us to use the GitHub Branch Source plugin and
auto-discover new repositories without `ok to test` bombs in
pull requests.

🚽 Use Jenkins pipeline for better flow

---

NEWS.md
osbuild.spec
osbuild/main_cli.py
setup.py

Small fix for `main_cli` to always set the `libdir`, small spec file changes and the `NEWS.md` entries.
Did an update test and a quick build of `samples/base-qcow2.json` to ensure that this release is good to put into RPMs. (-:
```
→ rpmlint osbuild.spec rpmbuild/RPMS/noarch/*
osbuild.spec:8: E: hardcoded-library-path in %{_prefix}/lib/%{pypi_name}
osbuild.spec: W: invalid-url Source0: https://github.com/osbuild/osbuild/archive/v14/osbuild-14.tar.gz HTTP Error 404: Not Found
osbuild.noarch: W: incoherent-version-in-changelog 1-3 ['14-1.20200506git0a07bcb.fc32', '14-1.20200506git0a07bcb']
osbuild.noarch: W: only-non-binary-in-usr-lib
osbuild-ostree.noarch: W: only-non-binary-in-usr-lib
osbuild-ostree.noarch: W: no-documentation
3 packages and 1 specfiles checked; 1 errors, 5 warnings.
``` …

Release osbuild version 14

---

docs/osbuild.1.rst
osbuild/main_cli.py
osbuild/pipeline.py

Drop the --build-env command-line argument. It is not used by anything.
Furthermore, our manifests now allow embedding build-environments, so
there is little reason to continue supporting this.

cli: drop --build-env argument

---

osbuild/objectstore.py
osbuild/util/ctx.py
test/mod/test_util_ctx.py

Extract the `suppress_oserror()` function from the ObjectManager and make it available as utility for other code as well.
This also adds a bunch of tests that verify it works as expected.

util/ctx: extract suppress_oserror()

---

schutzbot/Jenkinsfile
schutzbot/run_tests.sh

Attempt osbuild testing on the internal Jenkins deployment with
nodes that are destroyed after each use. The internal Jenkins looks for
a Jenkinsfile inside the `schutzbot` directory.
Let's not remove the `jenkins` directory (used by jenkins.osbuild.org)
yet until we know the internal Jenkins is stable and performs well.

Test with internal Jenkins in parallel

---

osbuild/meta.py
schemas/osbuild1.json

@jkozol discovered that RHEL 8.2 only has jsonschema 2.6.0. Except for `"required": []` in `osbuild1.json` we don't seem to require anything > `draft 4`, so downgrade to that.

Use JSON schema draft 4

---

osbuild/buildroot.py
osbuild/pipeline.py

Drop the `kwargs` forwarding from buildroot.run() to subprocess.run().
We do not use it other than for `stdin=subprocess.DEVNULL`. Set that
option directly instead.
Doing the kwargs forwarding mixes the argument namespaces and is very
hard to read. It is not clear from the call-site which argument goes to
buildroot.run() and which to subprocess.run().
Lastly, it requires us to manually fetch `check` just to make pylint
happy. Lets just drop this dance and make the API explicit.

buildroot: drop kwargs from buildroot.run()

---

.github/workflows/runtime-tests.yml
.travis.yml
test/test_assemblers.py
test/testing-rpms/README.md

This PR contains a set of 4 improvements for the current Github-Actions based CI:
1) The (to-my-knowledge-)unused `./test/testing-rpms` directory is dropped.
2) The `modprobe nbd` invocation is now made non-fatal to allow running on systems with `nbd` pre-loaded, or with `/lib/modules/` not mapped.
3) Use the images provided by `osbuild/containers` for our first set of CI runs. If this works out, we can switch over the other test-cases as well.
4) Move the last travis-based test over to the Github-Actions based CI.

ci: improve reliability and consolidate environment

---

schutzbot/run_tests.sh

Tell ansible-osbuild to build osbuild/osbuild-composer RPMs in a mock
chroot and install them from there instead of building them with
Ansible.
This brings us closer to how koji and brew build RPMs.

CI: Build RPMs in a mock chroot

---

schutzbot/run_tests.sh

When Jenkins clones a repository for testing, it does the base clone
first and then merges the code from the PR afterwards. This ensures that
the code merges properly and is tested properly, but it also makes a SHA
that only exists inside Jenkins. 😢
Tell ansible-osbuild to use the repository that Jenkins made so that the
SHA is valid.

CI: Use Jenkins' merged repo for testing

---

Makefile
NEWS.md

The NEWS file currently uses non-markdown indentation, but uses the markdown file-format. Since both GitHub-Repository-Viewer and the Release Pages can display proper markdown, lets just re-indent the file according to the markdown specs. This way, we can copy the content verbatim to release-pages, website-announcements, etc.
While at it, also switch out the list-indicator in front of the timestamp to a proper hyphen, to avoid it being rendered as list.
See the [rendered](https://github.com/dvdhrm/osbuild/blob/wip/formatnews/NEWS.md) version for how this looks.
(Clearly a bug, so labeled as such!!111)

news: reformat according to markdown

---

osbuild/pipeline.py
osbuild/sources.py
test/run/test_sources.py

The idea is that source can themselves spawn other modules, esp. new secrets modules. For this they need to know the library dir, aka 'libdir' throughout the osbuild source. Therefore change the SourceServer to directly get the library directory instead of just the sub-directory to the sources. Then pass the library directory to via the JSON API to the source.
Adjust all usage of the SourceServer, including the tests.
If it goes in before #405, it can be changed to use that instead of the `__file__` hack.

sources: pass the library dir to the sources

---

osbuild/pipeline.py
test/test.py
test/test_assemblers.py
test/test_boot.py
test/test_stages.py

This series adds a new pipeline executor which no longer relies on "output_id" and "tree_id", and then converts the tests over.

test: convert to new pipeline executor

---

assemblers/org.osbuild.ostree.commit
samples/f31-ostree-commit.json

Introduce a new `tar` option, which when given together with the required `tar.filename` option, will result in the output of the assembler being a tarball that contains the repo and the compose information (`compose.json`).
Requires the `tar` command to be present in the build root. Modify the sample to use that option and include the tar for the build pipeline.

assemblers/ostree.commit: support archiving

---

sources/org.osbuild.files

If osbuild is run on a RHEL machine it can access the Redhat Subscription Manager certificates and attach these to its curl requests. So, if osbuild is building a RHEL image it can access packages on the CDN. The manifest that osbuild accepts now contains secrets in its files urls. 
i.e.
```
"sources": {
"org.osbuild.files": {
"urls": {
"sha256:0129696c208f60326723c650295167b0600791ccb2e9c3d446c4caf9adecb3d7": {
"url": "https://cdn.redhat.com/content/dist/rhel8/8.2/x86_64/baseos/os/Packages/l/libnl3-3.5.0-1.el8.x86_64.rpm",
"secrets": "org.osbuild.rhsm"
},
```

Add ability to fetch packages from the RHEL CDN

---

osbuild/pipeline.py

We want to get rid of `tree_id` and `output_id` because the they are now considered internals of the store and clients should not use them directly. NB: they are still there indirectly as the `id` of the last stage and the assembler.
Also, the `output_id` was never correct here, because it was the `tree_id` as well. Ups.

pipeline: drop {tree, output}_id from --inspect js

---

assemblers/org.osbuild.oci-archive

Add a new assembler that takes a tree and creates a [Open Container Initiative image][oci] according to the OCI [image format][image-spec]. The final result is a tarball, aka a "orci-archive", that can be pulled into podman with `podman pull oci-archive:<archive>`. Currently the only required options are `filename` and `architecture`.
Part of #393 
[oci]: https://www.opencontainers.org/
[image-spec]: https://github.com/opencontainers/image-spec/

assemblers: add new org.osbuild.oci-archive

---

.github/workflows/tests.yml

Work around the quay.io issues by using the standard Fedora containers.
Also, make most of the dnf operations a little quieter to make it easier
to find problems.

GH Actions: Use upstream Fedora containers

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh
schutzbot/run_tests.sh

Build the RPMs in a mock using a simple script so that ansible-osbuild
can focus fully on deployment rather than compiling RPMs.

Build in a mock chroot first

---

sources/org.osbuild.files

When the urls' secrets field is not set, an error is thrown when trying to get the name of the secrets. The secrets now have a default value of {} when they are checked for the name.

sources: fix break when secrets is None

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

Now that we have a fully subscribed RHEL 8 image, let's use that instead
of RHEL 8.2 nightlies.

CI: Use RHEL 8 CDN image

---

osbuild/objectstore.py
osbuild/pipeline.py

Now with the release out, with the German holiday over, and all callers adjusted, we can proceed and drop the `output_id` and `tree_id` from the osbuild results.
The osbuild CI passes with this. Lets see what Schutzbot has to say!
Resolves #390.

pipeline: drop tree/output ID from results

---

osbuild/pipeline.py

Fix osbuild/pipeline.py unused import. We now trigger pylint warnings alongside pylint errors, and a PR rebase did not consider this.

pipeline: fix pylint-warning triggered by rebase

---

osbuild/main_cli.py
osbuild/pipeline.py

Change the assembler-commit to be conditional on checkpoints, just like we already do for stages. This means, assembler output is not automatically committed, but only if you requested so via a checkpoint.
With this in place we can start sharing caches in osbuild-composer. The only thing in the cache will be sources as well as checkpointed stages. We can start checkpointing known pipelines and thus make use of the cache. Furthermore, we can cache sources, as long as we do not fetch an unbound set of RPMs. However, our RPM set is currently static, so this should not be an issue. Nevertheless, it is up to Composer to decide when to enable the cache.
(This is based on #414 and should go in only if that one is merged.)

pipeline: checkpoint assemblers just like stages

---

assemblers/org.osbuild.rawfs
sources/org.osbuild.ostree
stages/org.osbuild.ostree
stages/org.osbuild.systemd
test/src/test_pylint.py

For some reason, pylint did not run on our modules as I expected. I now fixed this, and I also fixed pylint to only run on files that are checked into git.
A prep commit fixes some leftover format-strings that were not caught by the pylint in the CI.

More pylint improvements

---

stages/org.osbuild.ostree

Two small changes. See the individual commits for more details.
Split out from #371

ostree: support pre-populating `var` and make `rootfs` optional

---

stages/org.osbuild.grub2

Convert the `org.osbuild.grub` stage to use templates instead of inline strings. Puts the actually used grub config front and center.
Split out from #371

org.osbuild.grub: convert to use templates

---

stages/org.osbuild.rpm

The content hash of each RPM is already verified, so verifying
signatures again is not necessary if the manifest generation is trusted,
and verifying signatures does not help if the manifest generation is
not.
Let us follow what DNF does and default to not verify signatures, but in
order to preserve features already in use we still allow opting in to
verifying signatures as before on a per RPM basis.
This will make it possible to install unsigned RPMs, or a mixed of
signed and unsigned RPMs.

stages/rpm: make GPG signature verification opt-in

---

osbuild/util/ostree.py
stages/org.osbuild.grub2
stages/org.osbuild.ignition
stages/org.osbuild.rpm-ostree

This is a draft of all the needed changes to support ignition proper:
For all this to work, a new `git` source, together with a new `copy` stage was created to pull in the [`40ignition-ostree`](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/) from[`fedora-coreos-config`](https://github.com/coreos/fedora-coreos-config/). Additionally, grub is modified to set the correct `ignition.firstboot` kernel parameter if the `igintion.firstboot` file is present.

Ignition support

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

Upload artifacts from the mock builds into S3 to allow us to burst into
AWS when needed.

Use S3 for CI repositories

---

assemblers/org.osbuild.qemu
stages/org.osbuild.copy

Most stages and assemblers already use `/var/tmp` to store large
files or trees. Do this in the qemu assembler and copy stage as well.

Take care not to put large content on /tmp

---

osbuild.spec
osbuild/buildroot.py
selinux/osbuild.fc
selinux/osbuild.if
selinux/osbuild.te
selinux/osbuild_selinux.8

A usual step in creating OS file system trees is to apply the correct SELinux labels for all files and directories. This is done by the `org.osbuild.selinux` stage, which internally uses the `setfiles` command in order to do so. The SELiunx policy to be used the for this operation one of the newly created system, not the host one. It therefore can contain labels that are not known on the host. The kernel will prevent setting invalid, i.e. unknown, labels unless the caller has the `CAP_MAC_ADMIN` capability. By default, setfiles is executed in the `setfiles_t` domain, where it lacks that capability. Therefore a custom osbuild SELinux policy was created, with a special transition rule that will execute `setfiles` in the `setfiles_mac_t` domain. All stages, sources and assemblers as well as …

Add custom selinux policy to allow using labels unknown to the host

---

osbuild/util/selinux.py
stages/org.osbuild.selinux
test/data/stages/selinux/test_basic.json
test/run/test_stages.py

Add new option `labels` that can contain `path`: `label` pairs to overwrite the default labels for `path`.
NB: These manually set labels will not survive a relabeling and are most useful to adjust policy in the buildroot, e.g. for `cp` to be able to copy labels unknown to the host, by labeling it as `system_u:object_r:install_exec_t:s0`.

stages/selinux: support label overrides 

---

runners/org.osbuild.rhel81
runners/org.osbuild.rhel82

Runner are invoked to prepare the execution of stages and assemblers inside the container. The setup tasks are specific to the distribution and maybe the version of it, therefore specific runners are used for each distribution+version combination.
The build the first (most nested) build root, `/usr` is taken from the host to bootstrap the container. On RHEL, the python interpreter to be used for software that belongs to the platform is platform-python, as it provides a stable API. Therefore the RHEL runners should use that instead of relying on the presence of `/usr/bin/python3.6`, which might not be installed and is indeed not installed by default.

runners: use platform-python on RHEL

---

Makefile

Rename the 'test-mod' target to 'test-module' to match the help string.
Decided to rename the target not the help string because I think `make test-module` is more informative, bit a teensy-weensy bit.

Makefile: rename 'test-mod' target to match help

---

.github/workflows/coverity.yml
.gitignore
Makefile

Add  coverity related targets to the `Makefile`, including downloading the tool, running the "build", archiving the results and submitting it to coverity for analysis.
The downloading and submitting need `COVERITY_{EMAIL, TOKEN}` to be defined in the environment.
Add a github workflow that will trigger the run of coverity every night at 05:00 UTC. Uses the new Makefile coverity targets.

CI: Add coverity scan

---

sources/org.osbuild.files

curl uses strtod from the C standard library to convert the --max-time's value
from string to double. However, this is what strtod expects:
nonempty sequence of decimal digits optionally containing decimal-point
character (as determined by the current C locale)
Yeah, unfortunately, the decimal-point character is determined by the current
C locale. For example, Czech and German locale uses command as the
decimal-point character.
For reasons I don't fully understand, Python thinks it's running on en_US
locale, even though LC_NUMERIC is set to cs_CZ, so it uses a full stop as the
decimal-point character when converting float to string. However, as written
before, curl fails to parse this because it expects comma.
The fix I chose is simple: Use math.ceil, so only an integer can be passed to …

sources/files: do not pass floats to --max-time

---

.github/workflows/coverity.yml

Don't schedule the run of coverity on forks of osbuild, but only on the main repository.

ci: schedule coverity only for osbuild/osbuild

---

osbuild/main_cli.py
osbuild/pipeline.py
osbuild/sources.py

The way secrets work has been changed via commit 372b117: instead of passing them in via the command line, the information how to obtain secrets are encoded along the sources themselves. The only stage that still has support for the old style way is the deprecated `org.osbuild.dnf stage`, which might be removed in the near future.

Remove ability to pass in secrets via the command line

---

osbuild/__main__.py
osbuild/main_cli.py
setup.py

Instead of having a another indirection via `main_cli`, directly use `osbuild_cli` in as main function in `__main__.py`. Compared to `main_cli` `osbuild_cli` also does indeed return a value that can be given to `sys.exit` in `__main__`.

osbuild: use osbuild_cli directly as main entry

---

schutzbot/Jenkinsfile

We've come a long way and we need to triage failures that occur during
CI for the master branch. This will help us find problems with CI as
well as find other issues that could show up in a customer environment.
Also, let's send a happy notification when everything goes well. 💚

💣 Notify via telegram on master CI failure

---

schutzbot/deploy.sh

The whole rcm subpackage was removed in osbuild-composer's commit fbfa191.
Unfortunately, this broke osbuild's schutzbot because it tries to start
the rcm socket.
This commit removes enabling of the not-anymore-existing socket unit.

schutzbot: remove enabling of rcm socket unit

---

schutzbot/Jenkinsfile

Jenkins' declarative pipelines have interesting requirements around when
you can use traditional groovy scripting in the pipeline and some items
in `post` require special handling.

Use script for telegram notification

---

osbuild/main_cli.py

If the user does not specify an output directory or checkpoints to osbuild, exit 
successfully without building.
Previously, if a user did not include an output directory or checkpoints, it would 
build the manifest and throw out the result. Returning early will be clearer to the 
user and avoid wasting work.

osbuild: return if output-directory not specified

---

.pylintrc
assemblers/org.osbuild.qemu
osbuild/api.py
osbuild/main_cli.py
osbuild/monitor.py
osbuild/objectstore.py
osbuild/pipeline.py
osbuild/remoteloop.py
osbuild/sources.py
test/mod/test_monitor.py

Introduce the concept of pipeline monitoring: A new monitor class is passed to the `pipeline.run()` function. The main idea is to separate the monitoring from the code that builds pipeline. Through the build process various methods will be called on that object, representing the different steps and their targets during the build process. This can be used to fully stream the output of the various stages or just indicate the start and finish of the individual stages.
This replaces the 'interactive' argument throughout the pipeline code. The old interactive behavior is replicated via the new `LogMonitor` class that logs the beginning of stages/assembler, but also streams all the output of them to `stdout`. The non-interactive of not reporting anything behavior is done by using the …

Introduce pipeline monitoring

---

README.md
osbuild.spec
osbuild/buildroot.py

This needs a rebase and minor tweaks to the CI. It works on my machine to build all the fedora images, so if we want to go that route, we can easily pick it up.
*Commit Message:*
This swaps the `systemd-nspawn` implementation for `bubblewrap` to
contain sub-processes. It also adjusts the `BuildRoot` implementation
to reduce the number of mounts required to keep locally.
This has the following advantages:
* We know exactly how the build-root looks like. Only the bits and
pieces we select will end up in the build-root. We can let RPM
authors know what environment their post-install scripts need to
run in, and we can reliably test this.
* We no longer need any D-Bus access or access to other PID1
facilities. Bubblewrap allows us to execute from any environment,
including containers and …

buildroot: use `bwrap` to contain stages

---

osbuild/objectstore.py
osbuild/pipeline.py
test/mod/test_objectstore.py
test/mod/test_osbuild.py

Support for [`os.PathLike`](https://docs.python.org/3/library/os.html#os.PathLike), i.e. has a `__fspath__` method, throughout `objectstore` (and its test) and overall cleaner path handling. This also prepares that in future `Object.{read, write}` can return such `os.PathLike` object instead of plain paths, which can then in turn support setting additional metadata on tree data.

objectstore: support for PathLike and cleaner path handling

---

osbuild/api.py
osbuild/buildroot.py
osbuild/objectstore.py
osbuild/pipeline.py
osbuild/remoteloop.py
osbuild/sources.py
osbuild/util/jsoncomm.py
osbuild/util/types.py
runners/org.osbuild.fedora30
runners/org.osbuild.linux
runners/org.osbuild.rhel81
runners/org.osbuild.rhel82
runners/org.osbuild.ubuntu1804
test/mod/test_api.py
test/mod/test_monitor.py
test/mod/test_util_jsoncomm.py
test/run/test_sources.py

Extract the common code between all API providers, i.e. `API`, `SourcesServer`, `LoopServer`. Refactor the integration between the `BuildRoot` and said API providers, by making the registering of APIs more explicit via a new `register_api` method call. 
Add test for api and `BuildRoot` integration.
This should also provide the bases for unsharing the network with the sandbox.

Clean up API providers and their BuildRoot integration

---

test/run/test_assemblers.py

use one osbuild executor for all qemu tests
This way the test can benefit from osbuild's internal cache:
The first subtest builds all the stages and  runs the assembler
The next subtests can reuse the built stages and just run the assembler
Some data from my machine:
Building the manifest takes about 120 seconds
Running just the assembler on the cache's content takes 30 seconds.
Before this change, the whole manifest was built 3 times:
3 * 120 = 360 seconds
After this change, the whole manifest is built once and the cache
is reused 2 times:
1 * 120 + 2 * 30 = 180 seconds

use cache in assembler tests

---

osbuild/api.py
osbuild/buildroot.py
osbuild/remoteloop.py
osbuild/sources.py
osbuild/util/jsoncomm.py
test/mod/test_api.py
test/mod/test_util_jsoncomm.py

Unshare, i.e. create a new network namespace, for the build root. This will make sure that neither stages, assemblers nor the tools they are using are relying on the host's network.
For this to work, the `jsoncomm.Socket` is switch to use a connection orient protocol `SOCK_SEQPACKET`, which avoids the issue that the host could not send packets to the container, because the address of the client in the container was not visible to the host when the network was "unshared".

Isolate the build root's network

---

test/run/test_assemblers.py
test/run/test_boot.py
test/test.py

Currently, the assembler tests store more built images that needed. This PR deletes them as soon as possible so we don't run out of disk space. Also, the size of the built images was lowered from 2GiB to 512 MiB.
See individual commits for more details.

Finish assembler tests clean-up

---

osbuild/buildroot.py
osbuild/main_cli.py
osbuild/pipeline.py
test/mod/test_osbuild.py

Change the default of libdir to /usr/lib/osbuild and remove redundant logic. 
Additionally, change how the python package is detected.
Instead of checking if libdir is None, check if /usr/lib/osbuild is empty - i.e. 
if the user has specified a different directory than the default.

osbuild: unified libdir handling

---

osbuild/monitor.py

Allow a user to see the duration for each step in the osbuild pipeline.
This allows a user to optimize the build system for the best performance
and identify performance bottlenecks.

monitor: add assembler/stage duration

---

osbuild/pipeline.py

Make the output_directory argument in Pipeline.assemble and Assembler.run required. 
The qemu assembler assumes it is passed in args and will crash without it. Making
it mandatory prevents this.

osbuild: require output_directory

---

selinux/osbuild.if
selinux/osbuild.te

Allow `osbuild_t` to `nnp` and `nosuid` domain transition to `install_t` (for `ostree` and `cp`) and `setfiles_mac_t` (`setfiles`) domains. This is needed because bubblewrap (`bwrap`), which replaced `systemd-nspawn` to contain processes, always bind-mounts with (`nosuid`/`MS_NOSUID`) and always sets the No-New-Privs [flags](https://man7.org/linux/man-pages/man2/prctl.2.html) via `PR_SET_NO_NEW_PRIVS`.
Fixes #494

selinux: allow nnp and nosuid domain transitions

---

assemblers/org.osbuild.ostree.commit
test/data/manifests/fedora-ostree-commit.json
test/data/manifests/mpp-fedora-ostree-commit.json
test/run/test_assemblers.py

Add a new `os_version` option that will result in the `version` metadata being set as commit metadata. This will then be shown in the `rpm-ostree status` output. (That this was missing was pointed out by @mrguitar)

ostree: add support for setting version metadata

---

osbuild/buildroot.py
test/data/README.md
test/data/scripts/mount_flags.py
test/mod/test_api.py
test/mod/test_buildroot.py

Make sure "/sys/fs/selinux" is read-only, otherwise libselinux and tools will assume that SELinux is available and active and in turn use /sys/fs/selinux to e.g. verify the file systems labels; this will then prevent setting unknown labels via `setfiles`.
Fixes #499 
Missing:

buildroot: ensure /sys/fs/selinux is read-only

---

assemblers/org.osbuild.ostree.commit
osbuild/api.py
osbuild/pipeline.py
stages/org.osbuild.noop
stages/org.osbuild.rpm
test/data/stages/rpm/metadata.json
test/mod/test_api.py
test/run/test_assemblers.py
test/run/test_stages.py
test/test.py

Add functionality to `osbuild.api.API` so that metadata can be passed from modules (stages, assemblers) back to osbuild. There add the metadata to the `BuildResult` so it gets passed on further to the caller.
Use the new functionality to return compose information from the `ostree.commit` assembler.

Add support for passing metadata from modules to osbuild

---

osbuild/api.py
osbuild/pipeline.py
test/mod/test_monitor.py

Change the API endpoint to prevent retrieving monitor-output from a
running instance. Instead, we require the caller to exit the API context
before querying the monitor-output. This guarantees that the api-thread
was synchronously taken down and scheduled any outstanding events.
This fixes an issue where a side-channel notifies us of a buildroot
exit, but the api-thread has not yet returned from epoll, and thus might
not have dispatched pending I/O events, yet. If we instead wait for the
thread to exit, we have a synchronous shutdown and know that all
*ordered* kernel events must have been handled.
In particular, imagine a build-root program running (like `echo` in the
test_monitor unittest) which writes data to the stdout-pipe and then
immediately exits. The syscall-order guarantees that …

api: prevent early output retrieval

---

osbuild/objectstore.py
osbuild/pipeline.py

Change objectstore.get to return an object instead of a path, and remove logic 
with the same functionality in pipeline.run by replacing it with a call to objectstore.get.

osbuild: remove objectstore logic in pipeline

---

osbuild/buildroot.py
osbuild/pipeline.py
test/mod/test_buildroot.py

In case that `bubblewrap` fails to, e.g. because it fails to execute the runner, it will print an error message to `stderr`. Currently, this output is not capture and thus not logged. To fix that, the `BuildRoot.run` method now takes a monitor object and will stream `stdout`/`stderr` to the log via the monitor.
Closes #458

Record bubblewrap errors to the log

---

assemblers/org.osbuild.tar
osbuild/buildroot.py
osbuild/pipeline.py
runners/org.osbuild.fedora30
runners/org.osbuild.linux
runners/org.osbuild.rhel81
runners/org.osbuild.ubuntu1804
test/mod/test_api.py
test/mod/test_buildroot.py

Create a new `CompletedBuild` object that wraps and is very similar to the `subprocess.CompletedProcess`, i.e. it has a process member but also has short-cuts for `returncode`. Additionally, the output of the process is not only forwarded to the monitor, but also captured and then handed to `CompletedBuild`, so its output member will actually contain the full build output.
Then use that `BuildRoot.output` to get the output of the runner and modules (stages, assemblers) instead of using `api.setup_stdio` and `api.output`. Drop the latter from all runners and replace `api.output` with `BuildRoot.output`.

Use BuildRoot.output instead of api.setup_stdio

---

osbuild/api.py
runners/org.osbuild.rhel82
test/mod/test_buildroot.py
test/mod/test_monitor.py

API.setup_stdio was replaced in PRs 506 and 507,
remove setup_stdio functions and call sites.

api: remove setup_stdio

---

runners/org.osbuild.fedora34

Fedora 33 recently branched off rawhide and thus Fedora 34 was created. Re-use Fedora 30 runner, as was done for Fedora 33.

runners: add Fedora 34 runner

---

osbuild/api.py
osbuild/pipeline.py
test/mod/test_api.py

Create a new api endpoint called exception, that communicates exception
backtraces separately back to osbuild, as opposed to dumping them into the 
normal log. Additionally, add a corresponding test to check that a call to 
api.exception correctly sets API.exception.

api: add exception endpoint

---

runners/org.osbuild.rhel84

The rhel84 runner is based off of the rhel83 runner. No changes are made between them other than the name.
I am opening this as a draft since I am unsure what additional changes might need to be made to osbuild to support rhel 84.
This PR is depended on by https://github.com/osbuild/osbuild-composer/pull/1018

runners: add rhel84 runner

---

.github/workflows/tests.yml
NEWS.md
osbuild/api.py
osbuild/util/linux.py
sources/org.osbuild.files
test/run/test_stages.py

Use the github [action](https://github.com/codespell-project/actions-codespell) provided by the codespell project to check the spelling on every PR. Run codespell on the source (`codespell -f -L msdos -S coverity -S rpmbuild -S samples`) and fix all uncovered mistakes.

Integrate codespell into CI and fix uncovered spelling mistakes

---

schutzbot/deploy.sh

The osbuild-composer-tests package recently started to list its actual
dependencies, which include packages from EPEL. Enable EPEL in
deploy.sh.
Based on this patch by Ondřej Budai <obudai@redhat.com>:
https://github.com/osbuild/osbuild-composer/pull/1022

schutzbot: enable EPEL in RHEL

---

osbuild/api.py
osbuild/pipeline.py
runners/org.osbuild.fedora30
runners/org.osbuild.rhel81
runners/org.osbuild.rhel82
runners/org.osbuild.ubuntu1804
test/mod/test_api.py

Various clean ups for `api.exception` and more tests for it. One bigger change is to use `API.error` instead of `API.exception` as a more generic error signalling mechanism.
Make use of it in the runners where it makes sense.

Use api.exception in the runners and various cleanups for it

---

test/run/test_stages.py
test/test.py

Cache the file downloaded via the `org.osbuild.files` stage between runs to avoid download errors and potentially speed the tests up a bit. See individual commits for details.

Cache downloaded files for the stage test 

---

osbuild.spec

Stop the rpm post install script from mangling shebangs for runners,
stages, and assemblers. This breaks running them in osbuild containers,
which might contain a different operating systems than the host.
In practice, this means all build roots must have python3 explicitly
installed for most (all?) current stages and assemblers.
Fixes #354
@gicmo, @dvdhrm I couldn't figure out how to test this. Ideally, we'd have a couple of pipelines with nested `build` sections comprised of multiple combinations of operating systems.
@teg Do we always install `python3` from osbuild-composer? (I think we do, just making sure.)

osbuild.spec: don't mangle shebangs

---

osbuild/pipeline.py
osbuild/util/osrelease.py
test/mod/test_buildroot.py
test/mod/test_monitor.py
test/mod/test_osbuild.py

Instead of hard-coding the use of the `org.osbuild.linux` runner, introduce and use the a new `osbuild.pipeline.detect_host_runner` helper to dynamically detect the runner for the host system. That should fix the tests on RHEL systems, where `python3` is by default not present and even if it is manually installed, is an indirection via alternatives (i.e. a link to `/etc/alternatives`), which must be explicitly configured in the build root container for the host (by the appropriate host runner).

Auto detect the host runner in modules tests

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

Fedora 33 is about to be release and Fedora 31 is about to go EOL. Adapt accordingly. The later change is also necessary to unbreak CI, because composer has dropped support for F31.

Update CI to test F33 but not F31 via Schutzi

---

schutzbot/Jenkinsfile

This was never in osbuild-composer and fails CI when the log is empty.

schutzbot: drop collecting AVC logs

---

osbuild/__main__.py
osbuild/main_cli.py
schutzbot/Jenkinsfile
test/run/test_executable.py
test/test.py

osbuild_cli() sometimes returned an exit code, but at the end called
sys.exit() directly. The idea was probably to always return the code
with which the executable should exit.
Make this consistent and call sys.exit() in __main__.py, with the value
returned by osbuild_cli().

osbuild: always return exit code

---

osbuild/loop.py
osbuild/util/jsoncomm.py

Using pylint 2.6.0 resulted in a number of new warnings:
```
test_pylint (test.src.test_pylint.TestPylint) ... ************* Module osbuild.meta
osbuild/meta.py:116:31: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
osbuild/meta.py:214:42: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
osbuild/meta.py:317:40: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
osbuild/meta.py:393:46: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
************* Module osbuild.objectstore
osbuild/objectstore.py:68:22: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
osbuild/objectstore.py:72:28: E1136: Value 'Optional' is unsubscriptable (unsubscriptable-object)
************* Module osbuild.util.jsoncomm …
```

Minor fixes for pylint 2.6.0

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

RHEL 8.3 is already GA therefore we don't need to test it anymore!
Based on osbuild-composer 543f1f4 by Ondřej Budai <obudai@redhat.com>.

schutzbot: drop RHEL 8.3 stages

---

schutzbot/mockbuild.sh

This is https://github.com/osbuild/osbuild/pull/540, rebased to and refiled against `main`.
The main point is to make it easier to use the resulting URLs, without having to look at the log of a previous Jenkins run.

mockbuild: make repository URLs more predictable

---

schutzbot/deploy.sh
schutzbot/mockbuild.sh

Pin the osbuild-composer that schutzbot runs a reverse dependency test against. This allows to control which exact version to test against, and ensures that PRs against osbuild always run against the same version.
Now that osbuild-composer's CI uploads RPMs to a predictable destination (the same one that osbuild uses), we can use that instead of rebuilding osbuild-composer on every CI run. This should speed up the mockbuild stage considerably.
Pin it to v24 now.

schutzbot: pin osbuild-composer

---

osbuild.spec

We do want to turn the dependency generator off for runners, because they are tied to the specific platform, which might, if not disabled, introduce dependencies for that platform to the general package. An prominent example is platform-python used by the RHEL runner.
On the other hand, we do want to pick up the dependency for the stages and assemblers, i.e. /usr/bin/python3, because they need to be able to run on the host, since the host provides the root file-system for the initial build container, the build host. Add an additional comment to the shebang mangling exception to explain that due to the combination of dependency generator and the disabling of shebang mangler for assembler and stages an additionally dependency on /usr/bin/python3 will be added on RHEL, and that this is what …

spec: only disable the dep. generator for runners

---

Makefile
osbuild/api.py
osbuild/objectstore.py
osbuild/pipeline.py
test/run/test_assemblers.py
test/run/test_boot.py
test/run/test_sources.py
test/run/test_stages.py

A few of the test did not have the correct *skip unless* clauses that would make them fail when executed as non-root. Fix all of those. Additionally, do not create `/run/osbuild` eagerly, which also needs root and made `test_noop` fail, but let it be created on-demand by the `BuildRoot.run` method.

Ability to run the full test suit as non-root (with root only tests being skipped)

---

runners/org.osbuild.centos8

This runner is used by both CentOS 8 and CentOS Stream. CentOS is kinda weird because it specifies only number 8 in VERSION_ID in /etc/os-release unlike RHEL. Also the ID is the same for CentOS 8 and CentOS Stream.
This should work fine for now though: CentOS 8 is currently based on RHEL 8.3 and CentOS Stream on devel version of RHEL 8.4. For both RHEL 8.3 and 8.4 we use the RHEL 8.2 runner so it should be safe to assume that it's OK to base the CentOS 8 runner also on the RHEL 8.2 one.
We might need to tweak this at some point but I suggest dealing with it when that time comes.

runners: add CentOS 8 runner

---

.github/codecov.yml
.github/workflows/tests.yml

Integrate with codecov. Define a threshold of 5% to pass. Coverage is cumulative, i.e. all the tests send their coverage to codecov, which will integrate them all into a total.

ci: send coverage data to codecov

---

docs/osbuild.1.rst
osbuild/main_cli.py

This was deprecated in favor of always having the source in the manifest. Remove the command line option and the corresponding code that would override the sources definitions.

cli: remove --source command line option

---

osbuild/__init__.py
osbuild/formats/__init__.py
osbuild/formats/v1.py
osbuild/main_cli.py
osbuild/meta.py
osbuild/pipeline.py
test/mod/test_osbuild.py
test/test.py

Separate the external from the internal representation. This is being done by a having converting between the external manifest description and internal data structures in a format specific module. For now there is only one such module `v1`, which corresponds to manifest schema version `1`. It contains most format code that was distributed over osbuild.
This is the first step towards prepare DAG (direct acyclic pipelines).

Format abstraction

---

osbuild/formats/v1.py
osbuild/main_cli.py
osbuild/objectstore.py
osbuild/pipeline.py
test/mod/test_monitor.py
test/mod/test_osbuild.py
test/test.py

Instead of having build pipelines nested within the pipeline it is the build pipeline for, the nested structure is transferred into a flat list of pipelines. As a result the recursion is gone and all the pipelines and trees are build one after the other. This is now possible since floating objects are kept alive by the store itself and all trees that are being built are transparently via them. The immediate result dictionary changed accordingly. To keep the JSON output of osbuild the same, the result is now routed through a format specific converter. 
Additionally, the v1 format module gained a function to retrieve the global `tree_id` and `output_id`. With the new models those global ids will go away eventually and thus need to go through the format specific code.

Flatten the pipeline

---

.github/workflows/tests.yml
Makefile

Mark `$(TEST_MANIFESTS_GEN)` target as `.PHONY`.
Currently the `test-data` make target does not always trigger regenerating of manifests used for testing various osbuild parts, although it is marked as .PHONY. The reason that its dependency `$(TEST_MANIFESTS_GEN)` is not marked as `.PHONY` and therefore it is not run if the files already exist in repository.
Due to the above reason, CI is actually running `make --always-make test-data` to always regenerate manifests. The appropriate CI step has been updated as part of this change.

📜 test-data: ensure that `make test-data` always regenerate manifests used for testing

---

Makefile

test-coverity: no such target
test-runtime: renamed to test-run

Makefile: clean and update help message

---

docs/osbuild.1.rst

The `--inspect` option is documented in the osbuild usage, but not in
the man page. This makes it harder for new users to find it and use it
for figuring out stage IDs necessary for checkpoints.

📄 Docs: Document `--inspect` option in the man page

---

assemblers/org.osbuild.noop
assemblers/org.osbuild.oci-archive
assemblers/org.osbuild.ostree.commit
assemblers/org.osbuild.qemu
assemblers/org.osbuild.rawfs
assemblers/org.osbuild.tar
inputs/org.osbuild.tree
osbuild/formats/v1.py
osbuild/inputs.py
osbuild/main_cli.py
osbuild/meta.py
osbuild/objectstore.py
osbuild/pipeline.py
test/mod/test_monitor.py
test/mod/test_osbuild.py
test/test.py

Inputs are new concept that provides data in various forms , like `OSTree` commits, files, or tree, which in turn can originate from either `Sources` or pipeline builds to a `Stage`. This is the last puzzle piece needed to convert `Assembler`s into `Stage`s internally and paves the way for assembler pipelines. All existing assemblers are converted to use inputs.
See individual commits for more details.

Introduce inputs and Assemblers as Stages

---

osbuild.spec
osbuild/__init__.py
osbuild/monitor.py
osbuild/pipeline.py
setup.py
test/mod/test_monitor.py

Include the input modules in the RPM package and the `osbuild.formats` in the sub-package (introduce by #561). Maybe we should just use `setuptools.find_packages()` for the latter. Also, we need to have CI catch those issues.
As a bonus is also removes the now unneeded `Assembler` class.

Include new packages and modules in the packages

---

test/run/test_sources.py

The netns() function sets up a new namespace for tests.  The function is
also used to determine whether those tests can be run (using
unittest.skipUnless()).  A bug in the function made the changes stick if
the function failed early.  Specifically, when the "ip link" line fails,
the function exits without reverting to the old namespace.
Since the code is used in "skipUnless()", it's run during test
collection, which means that even if the relevant tests aren't selected,
they affect the environment for other tests.

test: Fix temporary network revert in tests

---

osbuild/formats/v1.py
test/mod/test_fmt_v1.py
test/mod/test_osbuild.py

When the build fails, not all pipelines might have been built and those pipelines will be missing from the results. Currently the code assumes that all pipelines will have a result and this will crash when trying to find an id for a pipeline that did not get built.
Refactor and rework the format specific test and add a new one for the output formatting.

Properly serialise results in case of error and add format specific tests

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

Add a support for developing osbuild via Visual Studio Code
Remote Containers[1]. VS Code, if the extension is installed,
will automatically build the specified container via the
supplied Dockerfile and start a a VS Code server instance in
it and connect to it.
The container has the dependencies to develop osbuild, which
includes running the test and building images. For this the
container is started with `--privileged` since osbuild needs
various capabilities.
NB: not all extensions that are installed on the host are
automatically installed; instead a handful of basic ones that
are needed for python development are pre-installed.
[1] https://code.visualstudio.com/docs/remote/containers

devcontainer: support for vs code devcontainer

---

osbuild/formats/v1.py
osbuild/inputs.py
osbuild/pipeline.py
test/mod/test_fmt_v1.py
test/mod/test_monitor.py
test/mod/test_osbuild.py

This converts the assembler phase of the `Pipeline`[1] with a new pipeline that has the previous assembler as the first and only stage. This was possible to do since the `Assembler` previously got converted into a `Stage`, and that stage has the tree as `Input`; so this stage just got moved to a newly created `Pipeline`. 
Additionally, all pipelines in the manifest now have to have a name assigned. This is currently used in the version 1 format code (`formats/v1`) to identify the pipeline that builds the tree and the pipeline that corresponds to the assembler. 
The inputs of a stage are now included in the `id` calculation. NB: This, and the move of the assembler to a new pipeline, changes the `id` of the assembler.
[1] That is the main pipeline, since for build pipelines the assembler is …

Introduce assembler pipelines and identify pipelines

---

assemblers/org.osbuild.tar
test/run/test_assemblers.py
tools/tree-diff

All of those are opt-in for `tar`, so lets opt in. Only open question is, if it should also be opt-in for the assembler itself. The current code assumes that if you have a tree with any of those properties (selinux, acls, extended attributes), you would want them preserved. Of course that might break on systems/build-roots that have a tar that does not understand any of those options.
Closes #570

tar assembler: include SELinux, ACLs and extended attributes

---

inputs/org.osbuild.files
inputs/org.osbuild.ostree
inputs/org.osbuild.tree
osbuild/formats/v1.py
osbuild/inputs.py
osbuild/objectstore.py
osbuild/pipeline.py
osbuild/sources.py
sources/org.osbuild.files
sources/org.osbuild.ostree
stages/org.osbuild.ostree
stages/org.osbuild.rpm
test/data/stages/rpm/metadata.json
test/mod/test_fmt_v1.py
test/mod/test_osbuild.py

This PR converts the `org.osbuild.rpm` and `org.osbuild.ostree` stages to use `Inputs` instead of sources. For this two new inputs are created: `org.osbuild.files` and `org.osbuild.ostree`. All (two) existing sources are refactored so they are now internally split into a _download_ and a _export_ part. If no `output` directory is provided to a source it will just download. This is used to pre-fetch all specified resources in a manifest before any pipeline is being built. For the above mentioned stages, the v1 loading code creates `Inputs` based on the stage options and the code in the stages is refactored to use the provided inputs.
TODO:

Convert stages to use inputs instead of sources 

---

osbuild/formats/v1.py
osbuild/main_cli.py
osbuild/meta.py
test/mod/test_fmt_v1.py

Add a `FormatInfo` that provides meta information about formats, together with `Index.list_formats` and `Index.get_format_info` to list and obtain said `FormatInfo`. Additionally a `Index.detect_format_info` can be used to infer format information from manifest descriptions.

Introduce format meta information and detection code

---

osbuild/formats/v1.py
osbuild/pipeline.py
osbuild/sources.py
sources/org.osbuild.files
sources/org.osbuild.ostree

All sources fetch various types of `items`, the specific nature
of which is dependent on the source type, but they are all
identifyable by a opaque identifier. In order for osbuild to
check that all the inputs that a stage needs are are indeed
contained in the manifest description, osbuild must learn what
ids are fetched by what source. This is done by standarzing
the common "items" part, i.e. the "id" -> "options for that id"
mapping that is common to all sources.
For the version 1 of the format, extract the files and ostree
the item information from the respective options.

Source: make items that are fetch visible to osbuild

---

osbuild/main_cli.py

Instead of printing the tree_id and output_id, which are format dependent, print all pipelines, with their name and ids.

main: print all pipeline names and ids

---

inputs/org.osbuild.tree
osbuild/buildroot.py
test/mod/test_buildroot.py

Commit d028ea5 introduced bug when introducing the `store` argument to `Stage.run`, instead of passing `var=var`, i.e. `var` is being passed as keyword argument, it is now being passed as a positional one. Since the `path=/run/osbuild` keyword argument comes before the `var=/var/tmp` argument, `var` is now being passed as `path` instead of var. 
Since `var` is always being passed in throughout the entire codebase, make it a positional argument, and move it before `path`.
This also means that we have been using `var`, i.e. the store, as the run dir, and `/var/tmp` as the tmp dir. The latter is interfered with by `systemd`, which cleans it up from time to time. Thus this could be a possible reason for [rhbz#1927343](https://bugzilla.redhat.com/show_bug.cgi?id=1927343).

Fix BuildRoot constructor arguments

---

.github/workflows/tests.yml
schutzbot/send_webhook.py

Previously, we had a webhook relay. It received a notification from Github
and sent it to AWS SQS. Now, the webhook is dead. The new method (already used
in osbuild-composer and image-builder) is to send the notification directly
from a github action to AWS SQS.

ci: trigger schutzbot from github action

---

stages/org.osbuild.oci-archive
test/data/manifests/fedora-ostree-container.json
test/data/manifests/fedora-ostree-container.mpp.json
test/initrd.py

In addition to the required base layer, provided via the the input of the same name, the oci-archive stage now accepts up to nine additional layers that get added on top of each other, sorted in ascending order, i.e. `layer.1` to `layer.9`.
Adapt the `fedora-ostree-container` example manifest so that the ostree commit is now in a separate layer, which makes it possible to share the base layer between different commits container.

org.osbuild.oci-archive: support additional layers

---

osbuild/treesum.py
tools/mpp-depsolve.py

Although MPP supported having multiple repo entries for each depsolve block, in reality that didn't actually work because the same (global) `baseurl` was used for all packages.
Now the `basurl` can still be (optionally) specified globally, but also overridden by the repo block and the package paths will be relative to that.

MPP: properly support multiple repos in mpp-depsolve

---

.github/workflows/tests.yml

Use the new immutable image infrastructure from `osbuild/containers`.
While at it, also switch over to the new github-actions helper, now that
we no longer run `systemd-nspawn` in our tests.
The old image was renamed from `ghci-osbuild` to `osbuild-ci` to avoid
accidentally replacing old images. The new infrastructure uses immutable
images, so downstream will no longer get automatic updates, unless the
`latest` tags are used.
Note that this also switches to a new Dockerfile, so I might need some tries to get this working again.

ci: convert to new immutable ci images

---

stages/org.osbuild.grub2
test/data/manifests/fedora-boot.json
test/data/manifests/fedora-boot.mpp.json

The current grub configuration has no logic to select the default boot entry, which means the next boot entry is chosen by grub2 by the sort order of available entries. This will break tooling like `grub2-set-default` and `grub2-reboot` that set on a specific variable `saved_entry` in the grub environment file `grubenv` to to point to the select boot entry.
Change our grub configuration file to use that `saved_entry` var to select the next boot entry to unbreak the tooling. In addition to the aforementioned tools, the saved_entry is also updated by the kernel install scripts when new kernel is installed, but only if the newly installed kernel is the selected default.
Thus not respecting the `saved_entry` variable might cause a bug where a newly installed non-default kernel gets selected …

org.osbuild.grub2: support `saved_entry` grubenv var 

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

This builds osbuild in F33aarch64 as well as RHEL8.4 and CentOS8. No tests are currently run.
With the mockbuilds in place we will be able to run composer CI against osbuild master, when necessary.

schutzbot/mock: add more distros

---

tools/lorax-template-pkgs.py

The definition of what packages are included in the boot iso installer are in a lorax template called [`runtime-install.tmpl`](https://github.com/weldr/lorax/blob/master/share/templates.d/99-generic/runtime-install.tmpl). There various `installpkg` commands are used to select the packages to install. The command supports globbing and `--optional` together with `--exclude`. These options are processed on a per-command basis, which involves querying and filtering the packages via `dnf`.
Implement a helper that can parse that template and provide a list of to be installed packages that can be used in composer to re-create the boot iso.

Add helper to parse lorax' boot iso install templates 

---

schutzbot/mockbuild.sh

The centos stream 8 config was renamed in mock-core-config, see:
https://github.com/rpm-software-management/mock/commit/75cd9eb52df899d40ae7d82ceb96146bf61bdc88

schutzbot/mock: fix centos stream 8 build

---

assemblers/org.osbuild.oci-archive
stages/org.osbuild.oci-archive

Instead of including SELinux labels for the content layers via the `--selinux` tar option, make sure selinux labels are not included by using the `--no-selinux` option.
The inclusion of the labels was a mistake, since they should be determined by the target system because selinux labels are not namespaced. On RHEL/Fedora the SELinux label used is something like `system_u:object_r:container_ro_file_t:s0` for all the files in the container.
Including the label was leading to permission problems because the files had a different label on the host and programs inside the container get `EACCES`, i.e. Permission denied, errors when accessing files with the different label. 
Interestingly this does not happen on Fedora 33 but only on RHEL.
One possibility is that the overlayfs kernel driver in …

stages/oci-archive: do not include selinux labels

---

stages/org.osbuild.ostree.preptree

Do the check if there is a `/etc/machine-id` before moving `/etc` to `/usr/etc`, because otherwise `/etc/machine-id` will obviously not exist and thus the detection is broken.

stages/ostree.preptree: fix machine-id detection

---

stages/org.osbuild.grub2

Set the `GRUB_CMDLINE_LINUX` variable in `/etc/default/grub` to the kernel command line options. This is used by `grub2-mkconfig` to assemble the full kernel command line when generating the menu entires. NB: `GRUB_CMDLINE_LINUX` does NOT include the root fs bits (`root=...`), since that is generated by `grub2-mkconfig` itself.
Manually tested this change by building a `fedora-boot` image and checking that the config variable is present in `/etc/default/grub` and also that `grub2-mkconfig` will pick it up properly.

stages/grub2: set GRUB_CMDLINE_LINUX default

---

runners/org.osbuild.rhel85

A runner for rhel 8.5 is added. This runner is a sym link to the rhel82
runner as was done for the rhel84 runner.
Needed for https://github.com/osbuild/osbuild-composer/pull/1274
Is there anything else that needs to be done on the osbuild side other than adding the new runner ?

runners: add rhel 85

---

assemblers/org.osbuild.error
osbuild/formats/v1.py
test/mod/test_fmt_v1.py

If the assembler in a v1 format failed, this would not propagate properly to the main `success` entry in the result dictionary. Fix that and add tests to check for this.

Correctly report assembler errors

---

sources/org.osbuild.ostree

Source, for compatability reasons, have two modes: download only and download and export. The difference is the arguments that are passed to the source: For download only, the `output` param is empty. In this case also `checksums` *can* be empty and if so it means everything, i.e. the commits, should be fetched. The latter was not properly handled so far. Adjust the logic, which now closely mimics that of the `org.osbuild.curl` source to fix this case.

source/ostree: fix download only case

---

stages/org.osbuild.xorrisofs

Add an option to set the systemd id of the ISO. The system id is used by e.g. by `osinfo` to identify the RHEL boot isos, where the system id is "LINUX"[1]
[1] https://gitlab.com/libosinfo/osinfo-db/-/blob/master/data/os/redhat.com/rhel-8.4.xml.in#L19

stages/xorrisofs: ability to set system id

---

stages/org.osbuild.ostree.preptree

Since `/home` will not end up in the commit¹  move the home directories to `/var/home`. This is done after the new root file system has been initialized, and only if `/home` is not empty.
¹ it is neither copied back in the preptree stage itself, nor would it be picked up by rpm-ostree compose tree postprocess were it copied back.

stages/preptree: move home dirs to var/home

---

runners/org.osbuild.fedora35

New `org.osbuild.fedora35` which is re-using the f30 runner. Needed since Fedora 35 branched in early February.

runners: add Fedora 35 runner

---

.github/workflows/tests.yml

We explicitly pinned the F32 CI images in the past due to update issues
in F33. However, those have been resolved and we should switch back to
the most recent Fedora CI images.
This commits switches all instances of the osbuild-ci image back to the
latest stream, snapshot taken on 2021-02-19 13:11 (latest-202102191311).

ci: update images to F33

---

inputs/org.osbuild.ostree
stages/org.osbuild.rpm

Instead of deleting and re-creating `/etc/machine-id`, just truncate it to an empty file. This should let the mode be `0444`, which is the mode that systemd also creates it with.
Also has minor fixes for the ostree input.

Fix /etc/machine-id permissions

---

stages/org.osbuild.rpm

This reverts commit 59184b23a24d302eeec627a656f1acefff7d6597 (introduced in PR #609).
This change breaks current testing and is not critical.
We will reintroduce it later when there is time to adapt the tests.

Revert "stages/rpm: truncate the machine id"

---

stages/org.osbuild.oci-archive

Only include a very specific set of extended attributes:
- `user.*`: user specified extended attributes
- `security.ima`: Integrity Measurement Architecture (IMA)
- `security.capability`: Linux capabilities(7)
This follows what [containers/storage][1] and [containers/buildah][2] are doing. It is important to note that we DO NOT want selinux related extended attributes (`security.selinux`) in there, which seems to be pulled in by some versions of `tar` even if that was seemingly excluded via `--no-selinux`. Therefore we also exclude selinux and xattrs explicitly from the wrapping container to make sure they are never included.
[1]: https://github.com/containers/storage/blob/35ebda8ae27dc130c18517cd1e14ad85407ae22f/pkg/archive/archive.go#L399
[2]: …

stages/oci-archive: include limited set of xattrs

---

stages/org.osbuild.oci-archive

According to the OCI Image [Format Specification][1] history entries for layers in the container are optional; but when trying to push a container quay.io via skopeo (copy oci-archive:… docker://quay) it will fail with "Cannot convert an image with 0 history entries". This seems to come from the [containers/image][2] library when the container is converted back from the docker distribution format to `oci-archive` on quay.io. Thus it seems that when `skopeo` converts the image to the docker format for the distribution it does not fill any the history entries, which are then assumed and required to be there when converting back.
To fix this, insert history entries for each layer that is created.
[1]: https://github.com/opencontainers/image-spec/blob/master/config.md
[2]: …

stages/oci-archive: write history entries

---

assemblers/org.osbuild.qemu

Add a new option `qcow2_compat` which can be used explicitly select the compatibility level of the `qcow2` file format. Qemu version 1.1 introduced extensions to the format that became the default with 1.7, which are not readable by qemu < 1.1. Thus if the resulting qcow2 should be read by such older qemu versions, the compatibility level needs to be set to 0.10.
This is actually based on work by @ondrejbudai in composer.

assemblers/qemu: support for qcow2 compat version

---

NEWS.md
osbuild.spec
setup.py

This should sync up with 27.2, i.e. contain at least everything that 27.2 contains.

Prepare release of osbuild 28

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

Renamed the nightly repo variable to use it for both 8.4 and 8.5 repository configurations.

schutzbot: add RHEL 8.5

---

stages/org.osbuild.oci-archive
test/data/manifests/fedora-ostree-container.json
test/data/manifests/fedora-ostree-container.mpp.json

Add support for arbitrary manifest annotations: allow anything with the exception of the `org.osbuild` and `org.opencontainer` prefixes. The former is reserved by us, the latter by the OCI image specification. The latter specifies a set of pre defined keys, which are not yet supported by osbuild but will be in the future, partly via more generic options (creation time).
Define a set of pre-defined ostree related annotations that can and should be used to indicate that a container image contains an OSTree commit. This can be used by other tools to inspect and extract the commit more easily.

`stages/oci-archive`: support for annotations

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

RHEL 8.4 is now GA, so we don't need any extra tests for it. This should also
make the CI more reliable because having two distros with the same DISTRO_CODE
caused some tests to fail randomly (they used the same intermediate
artifacts).
Also, remove Fedora 32 because it's EOL.

ci: remove RHEL 8.4 and Fedora 32

---

osbuild/util/rhsm.py
sources/org.osbuild.curl
test/mod/test_util_rhsm.py

The previous version covered too few use cases, more specifically a
single subscription. That is of course not the case for many hosts, so
osbuild needs to understand subscriptions.
When running org.osbuild.curl source, read the
/etc/yum.repos.d/redhat.repo file and load the system subscriptions from
there. While processing each url, guess which subscription is tied to
the url and use the CA certificate, client certificate, and client key
associated with this subscription. It must be done this way because the
depsolving and fetching of RPMs may be performed on different hosts and
the subscription credentials are different in such case.
More detailed description of why this approach was chosen is available
in osbuild-composer git: osbuild/osbuild-composer#1405

sources/curl: Implement new way of getting RHSM secrets

---

osbuild/meta.py

Parse the JSON directly from the AST node when parsing the module file, because the AST node contains the line number of the schema variable and thus we can resolve the correct line number for errors within the JSON. Convert the `JSONDecodeError` to a `SyntaxError`:
Before:
```
File "/workspaces/osbuild/osbuild/meta.py", line 331, in get_schema
opts = self._make_options(version)
[...]
File "/usr/lib64/python3.9/json/decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 1 (char 14)
```
After:
```
File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None, …
```

meta: proper schema parsing error reporting

---

osbuild.spec

When new ostree related stages and the new ostree input was added they were included in the main package since all the modules were manually listed in the corresponding exclude/include sections.
Change that by using wildcards, since all ostree related modules should start with the `org.osbuild.ostree*` pattern.

spec: move all ostree modules to the sub-package

---

assemblers/org.osbuild.qemu
runners/org.osbuild.rhel82

Work around a bug on `aarch64`[1] where `qemu-img` would hang about a third of the time. To be able to activate the work-around only when it is required, e.g. for certain distributions distribution, introduce an environment variable, `OSBUILD_QEMU_IMG_COROUTINES`, that is set in the runner and then picked up in the assembler.
[1] https://bugs.launchpad.net/qemu/+bug/1805256
Based on work by @major in #483. 
Closes #482.

aarch64: use single qemu-img thread

---

stages/org.osbuild.groups
stages/org.osbuild.users

Use `patternProperties` instead of `propertyNames` and `pattern`, which is not in draft 4 and so did not work (but also did not throw an error).
Found by @thozza with help from @achilleas-k

stages/users: fix user names schema validation

---

stages/org.osbuild.rhsm
test/data/stages/rhsm/b.json
test/data/stages/rhsm/b.mpp.json
test/data/stages/rhsm/diff.json

Extend the `org.osbuild.rhsm` stage to configure selected options in the subscription-manager configuration (in `/etc/rhsm/rhsm.conf`). It is possible to set only values currently set in RHEL AMI images, specifically:
- `manage_repos` option in `rhsm` section
- `auto_registration` option in `rhsmcertd` section
Ensure that the stage does not "touch" any configuration files, unless it actually changes them. This prevents changing the file modification time.
Update the `org.osbuild.rhsm` stage test case to set the additional configuration options.

stages: extend `org.osbuild.rhsm` stage to configure subscription-manager

---

schutzbot/mockbuild.sh

s3cmd sync actually downloads metadata for all objects in a s3 bucket.
We have built a lot of RPMs, thus this takes 5 minutes on AWS and 25 minutes
on my laptop (!!!).
Let's use recursive put instead. This doesn't delete any files on the remote
side. As we upload RPMs only once, this also shouldn't fail on "the
object already exists". Using this method, we should be able to upload the
RPMs in seconds.
The same patch was applied in osbuild-composer cf73edd2

mockbuild: use s3cmd put instead of sync to speed up the RPM upload

---

stages/org.osbuild.systemd
test/data/stages/systemd/b.json
test/data/stages/systemd/b.mpp.json
test/data/stages/systemd/diff.json

Extend the `org.osbuild.systemd` stage to create drop-in configuration files for Systemd `.service` units under `/usr/lib/systemd/system`. Currently, only the `Environment` option in the `Service` section can be configured.
Update the `org.osbuild.systemd` stage test case to create drop-in configuration `10-rh-enable-for-ec2.conf` for `nm-cloud-setup.service` unit, as used in RHEL AMI images.

stages: extend `org.osbuild.systemd` to create .service unit drop-ins

---

stages/org.osbuild.sysconfig
test/data/stages/sysconfig/b.json
test/data/stages/sysconfig/b.mpp.json
test/data/stages/sysconfig/diff.json

Extend the `org.osbuild.sysconfig` stage to create `ifcfg-*` files under `network-scripts` subdirectory. It is possible to set only values currently set in RHEL AMI images, specifically:
- BOOTPROTO
- DEVICE
- IPV6INIT
- ONBOOT
- PEERDNS
- TYPE
- USERCTL
Change all `configure_*` functions to raise ValueError exception, instead of returning values. As a follow up change, remove all checks of the returned value from these functions.
Update the `org.osbuild.sysconfig` stage test case to create ifcfg configuration files for two interfaces.
The schema string has been changed to raw string to prevent `DeprecationWarning: invalid escape sequence \s` warnings.

stages: extend `org.osbuild.sysconfig` to create network-scripts/ifcfg-* files

---

test/mod/test_osbuild.py

It is `assembler` not `assmelber`. Ups.

test/osbuild: fix type in assembler

---

stages/org.osbuild.qemu

The `OSBUILD_QEMU_IMG_COROUTINES` was introduced to allow specifying the number of coroutines used in `qemu-img convert` by the runner, or `osbuild` directly. This can be useful in various scenarios, but is specifically used by the rhel 8.2+ runner to limit the number of coroutines used for Aarch64 to one, since a bug in `qemu-img` leads to random hangs on that platform.

stages/qemu: honour coroutines env variable

---

stages/org.osbuild.sfdisk
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json

Instead of operating directly on a file, which was previously specified by `filename`, operate on a device. This is more flexible since a file can be accessed via a loop back device; but the inverse is obviously not true, like other devices can not be accessed via a plain file.
Therefore, re-factor the stage to use a device and adapt the existing test (`fedora-ostree-image`).

stages/sfdisk: use device not file

---

osbuild.spec

The new modules for devices and mounts need to be installed so that they actually end up in the rpm.

spec: install devices and mounts

---

stages/org.osbuild.copy

The path for inputs:// was appended twice, the tree:/// does not take a network location.

 `stages/copy`: small fixes for the url parsing

---

.packit.yaml

Let's try again if the service works and can help us release osbuild into Fedora.

build: reintroduce Packit

---

assemblers/org.osbuild.ostree.commit

In the ostree assembler, `var`, `usr` and `boot` are copied from the built tree to a newly initialized and ostree-conforming root filesystem. The way in which `cp` was called resulted in the source being created inside the target, if the latter existed. This was the case for `var` resulting in `var/var`. Use `cp ${source}/. {target}` to fix that.

assemblers/ostree: fix copying of `var`

---

osbuild/objectstore.py

In the object store, temporary bind mounts are used when accessing the content, i.e. the individual trees. Their unmount is currently done with the `--lazy` flag. The use of this flag goes way back to commit da121beda1570f9b43fda75f3aefbba2c848d7f2, which sadly does not mention why the flag was introduced. Since the tree and files in the tree will be used by consequent stages it seems reasonable to do the un-mounting eagerly and thus this reverts back to that behavior.

objectstore: eagerly unmount bind-mounts

---

osbuild/buildroot.py

This will prevent any modification of anything in `/sys`. It will also prevent `udevadm tigger` to run, which needs /sys writeable. This is a desired effect, since uevents are not delivered to the contained environment, so `udevadm trigger` might hang. This is to counter issues like https://github.com/osbuild/image-builder/issues/206
I have tested it locally, specifically with a rhel based artefact that contains `rng-tools` and it seems to not cause any issues.

buildroot: mount /sys as read-only

---

stages/org.osbuild.keymap
test/data/stages/keymap/b.json
test/data/stages/keymap/b.mpp.json
test/data/stages/keymap/diff.json

Add a new option 'x11-keymap' for configuring the X11 keyboard settings. The value of the option is a dictionary with keys representing settings which can be configured. Currently, only the 'layouts' setting can be configured. Its value is a list of strings, representing the specific layouts, which should be configured for the X11 keyboard.
Update the stage test case with the new option 'x11-keymap'.

stages/keymap: add option to configure X11 keyboard

---

stages/org.osbuild.tar

Add support different archive formats. The list is taken from what `tar` currently supports.

stages/tar: support choosing the format

---

test/data/manifests/fedora-boot.mpp.json
test/data/manifests/fedora-ostree-bootiso.mpp.json
test/data/manifests/fedora-ostree-image.mpp.json
tools/mpp.py

This lets a mpp manifest define some variables and then use these variables inside python f-strings to expand things in a flexible way. This allows a single value such as `rootfs_size` to be expanded in various places, including using  computations to   e.g. define the partition offsets and sizes.

Add support to mpp.py to format strings (and simplify manifests)

---

tools/mpp.py

I was getting:
.sources.org.osbuild.curl.items.sha256:02c8f76fd8b13972c541e4fa3bd2101681b7d4baa1320e3101bc4167b5531685:
{'url': 'https://cdn.redhat.com/content/dist/rhel8/8/aarch64/baseos/os/Packages/e/elfutils-libelf-0.182-3.el8.aarch64.rpm', 'secrets': 'org.osbuild.rhsm'} is not valid under any of the given schemas
Because the secrets key should have an object, not a string value.

mpp: Use the right format for the file secrets

---

.devcontainer/Dockerfile

This is needed for the pylint to work correctly with the new cloud-init stage.
While there, add some more utilities useful for debugging. Also add glibc-langpack-en needed for `en_GB`.

devcontainer: add pyyaml dependency

---

test/test.py

The command and its arguments are the most important part of the arguments to `subprocess.run`, so they should be highlighted in the indentation.
This was originally going to be a trivial spelling fix as a test of the process of contributing to `osbuild`, but your comments and docstrings are all impeccably spelled!
Signed-off-by: Paul Wayper <paulway@redhat.com>

test: isolate command and arguments in use of subprocess.run

---

.gitlab-ci.yml

we need the RPM before we can even start testing osbuild-composer on
aarch64.

ci: Start building on 8.5 aarch64

---

test/data/manifests/fedora-boot.mpp.json
tools/osbuild-mpp

Also, set the `module_platform_id` again, since that accidentally got dropped during the re-factoring.
Test this in `fedora-boot.mpp.json`.

mpp: Properly support substitutions

---

devices/org.osbuild.loopback
osbuild/objectstore.py

This is in order to help with possible caching issue like issue #697 
NB: in theory we should not  _have_ to actually do this, but it does seem to help in certain cases, although this might just be because it creates different timings or sequence of sys calls. But it does help and surely does not hurt.

Sync more: before unmount in the store and the file backing loop devices

---

osbuild/api.py
osbuild/host.py
osbuild/pipeline.py
test/mod/test_api.py

Instead of using the JSONCOMM RCP mechanism, write the arguments to a file which is then bind-mounted into the container. Adapt `api.arguments` to just read that file, so nothing changes for the stages.

Pass arguments to stages as a plain file

---

test/data/manifests/fedora-ostree-image.mpp.json
tools/osbuild-mpp

It is now possbile to define a partiton layout via `mpp-define-image`. The defined layout is actually written to a temporary sparse file and read back via `sfdisk`, so that all partiton data like `size` and `start` include actual padding and such. The `image` variable will be defined with `size` and `layout` keys, the latter containing the partition layout data. It can be accessed via the "String expansion" mechanism.

mpp: support for defining partition layouts

---

osbuild/objectstore.py

I have re-done the initial attempt. While we are still recursively bind-mounting trees in the `objectstore`, we also _only_ grab `/usr` from the host. This ensures we are not accidentally messing with other bits of the host. See the commit messages.

objectstore: use recursive bind mounts

---

stages/org.osbuild.qemu
test/data/manifests/fedora-ostree-image.mpp.json
tools/osbuild-mpp

Add `skip_if_unavailable` as an supported attribute for the repository configuration.
Support more than one image definition by introducing a `id` attribute which can be used to specify how the variable for the definition is called.

mpp: support `skip_if_unavailable` and multiple image definitions

---

schutzbot/deploy.sh
schutzbot/mockbuild.sh

Let's explain how RPMs for RHEL are built:
We use a subscribed RHEL 8.x machine and mock build these on it. Mock
initializes its own buildroot based on the latest RHEL 8 CDN content, see[1].
This means that the minor version of the buildroot is independent of the minor
version of the host.
However, we currently upload RPMs to a directory whose name consists also of
the minor version of the host. Our hosts are currently running RHEL 8.3 so
the RPMs are uploaded into rhel-8.3 directory despite them being built in the
RHEL 8.4 buildroot (RHEL 8 CDN buildroot specifically). This means that
we cannot guarantee that they are installable on RHEL 8.3 which is weird.
This PR adds a special case for hosts that run on subscribed RHEL and
thus build RPMs in a buildroot constructed from RHEL CDN. …

ci: upload rpms built in RHEL 8 CDN buildroot into rhel-8-cdn directory

---

docs/osbuild.1.rst

This is used to export an image but isn't present in the osbuild man page.

docs: add --export option to the osbuild man page

---

README.md

The current Build section is misleading, since running the commands that
are mentioned there will lead to only the osbuild module and osbuild-mpp
tool to be installed.
But none of the other required artifacts (sources, stages, schemas, etc)
will, causing the installed osbuild to not work at all. Instead, have an
Install section that explains how osbuild can be installed from RPMs.

README: improve Build section

---

test/data/manifests/fedora-boot.json
test/data/manifests/fedora-boot.mpp.json
test/data/manifests/fedora-container.json
test/data/manifests/fedora-container.mpp.json
test/data/manifests/fedora-ostree-bootiso.json
test/data/manifests/fedora-ostree-bootiso.mpp.json
test/data/manifests/fedora-ostree-commit.json
test/data/manifests/fedora-ostree-commit.mpp.json
test/data/manifests/fedora-ostree-container.json
test/data/manifests/fedora-ostree-container.mpp.json
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json
test/data/manifests/fedora-ostree-tarball.json
test/data/manifests/fedora-ostree-tarball.mpp.json

The manifests set a "en_US" locale but this causes gnome-terminal to not
run due a non UTF-8 locale being used, which is an unsupported config:
gnome-terminal-server[1899]: Non UTF-8 locale (ISO-8859-1) is not supported!
Reported-by: Stephen Smoogen <ssmoogen@redhat.com>

test/data: use UTF-8 locale on all manifests

---

.gitlab-ci.yml
schutzbot/deploy.sh

The newer composer commit has test manifests generated from rpmrepo that should be more stable than kernel mirrors. I also enabled Fedora 33 tests on aarch64.

update composer to make the tests more stable

---

stages/org.osbuild.authselect
test/data/stages/authselect/b.json
test/data/stages/authselect/b.mpp.json

Rename the `profile_id` option to `profile` in the stage schema. This is a follow-up to PR#696 comment after is has been merged [1].
[1] https://github.com/osbuild/osbuild/pull/696#discussion_r661253293

stages/authselect: rename `profile_id` option to `profile`

---

assemblers/org.osbuild.ostree.commit

Commit 92cc269 fixed a bug where `/var` was copied into `/var` resulting in `/var/var`. Sadly the fix broke copying links, like `bin -> usr/bin`, where now the content of the link would be copied but not the link itself. Use the `-t` command line flag for `cp` which should ensure that we copy links as links but also copy the contents for `/var` should the target dir, i.e. `/var` already exist.
cc @henrywang

assembler/ostree.commit: fix copying of links

---

stages/org.osbuild.grub2.iso

Add a new stage to build a boot filesystem tree. Supports EFI but
can be extended to support isolunux as well.
cc @gicmo @nullr0ute
Signed-off-by: Antonio Murdaca <runcom@linux.com>

stages: add org.osbuild.grub.iso stage

---

stages/org.osbuild.isolinux
stages/org.osbuild.squashfs
test/data/manifests/fedora-ostree-bootiso.json
test/data/manifests/fedora-ostree-bootiso.mpp.json

Implement all the necessary stages and changes to be able to split up the `org.osbuild.bootiso.mono` stage. The EFI booting part builds on work form @runcom in PR #719.
This is marked as draft since PR 719 should go in first.
EFI and Legacy boot works on x86_64.

Split up the `bootiso.mono` stage

---

tools/osbuild-mpp

We create the urls for the packages after dep-solving. During the big refactoring (802f4010) the code that would expand the base url during that step got lost. Re-introduce that so that local repos work correctly again.
Discovered by @smooge (sorry about that).

tools/mpp: expand baseurl after dep-solving

---

mounts/org.osbuild.noop
osbuild/formats/v2.py
schemas/osbuild2.json
stages/org.osbuild.copy
stages/org.osbuild.noop
stages/org.osbuild.zipl.inst
test/data/manifests/fedora-ostree-bootiso.json
test/data/manifests/fedora-ostree-bootiso.mpp.json
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json
test/mod/test_fmt_v2.py

The order of entries in a dictionary is not specified by the JSON standard and hard to control when marshalling dictionaries in Go. Since the order of mounts is important and the wrong order leads to wrong mount trees change the `mounts` field to an array. This breaks existing manifests but after careful deliberation it was concluded that the original schema with mounts as dictionaries is not something we want to support. Apologies to everyone.

Mounts are arrays

---

osbuild/util/rhsm.py

The problem is that some deployments might not have the redhat.repo
file, yet they might have the key and certificate to access Red Hat CDN.
If that was the case, the new approach would cause a regression compared
to the previous behavior.
This patch uses the previous method if the redhat.repo file is not
found. This can still cause a regression if the file is empty or does
not contain any matching entries.

util/rhsm: Implement a fallback to the previous behaviour

---

stages/org.osbuild.cloud-init
stages/org.osbuild.dracut.conf
stages/org.osbuild.modprobe
stages/org.osbuild.systemd
stages/org.osbuild.systemd-logind
stages/org.osbuild.systemd.unit
test/data/stages/cloud-init/b.json
test/data/stages/cloud-init/b.mpp.json
test/data/stages/dracut.conf/b.json
test/data/stages/dracut.conf/b.mpp.json
test/data/stages/modprobe/b.json
test/data/stages/modprobe/b.mpp.json
test/data/stages/systemd-logind/b.json
test/data/stages/systemd-logind/b.mpp.json
test/data/stages/systemd.unit/a.json
test/data/stages/systemd.unit/a.mpp.json
test/data/stages/systemd.unit/b.json
test/data/stages/systemd.unit/b.mpp.json
test/data/stages/systemd.unit/diff.json
test/data/stages/systemd/diff.json

Instead of creating multiple files per stage, create only one configuration file. This generally makes the stage and its schema easier to read and gives us more flexibility to add options on the top-level, per file, like the directory the file it is created in or a top-level comment explaining the content.

Create only one configuration file in cloud-init, dracut, modprobe stages

---

stages/org.osbuild.fstab
test/data/stages/fstab/b.json
test/data/stages/fstab/b.mpp.json

For the fs spec field, support traditional device nodes as well as partition labels. Adjust the test accordingly.

stages/fstab: support device nodes and partlabel

---

stages/org.osbuild.cloud-init

Add back a schema constrain, that at least one configuration must be specified for the configuration file.
This has been forgotten/missed as part of https://github.com/osbuild/osbuild/pull/739.

stages/cloud-init: configuration file must contain at least one option

---

.github/workflows/tests.yml
osbuild/sources.py
osbuild/util/rhsm.py
sources/org.osbuild.curl
test/mod/test_util_rhsm.py

This feature has been requested for backporting into RHEL8.4. As opposed to the "main" osbuild branch, this one contains a fallback to the previous behavior in case it magically worked for someone. At systems with proper subscription this should not be the case.

[RHEL8.4 branch] sources/curl: Implement new way of getting RHSM secrets with a fallback mechanism

---

stages/org.osbuild.grub2.inst

The location property is required, otherwise the stage will fail due to
KeyError at line 261:
location = options["location"]
This commit adds the property to the list of required ones.

stages/grub2.inst: add location to required properties

---

runners/org.osbuild.rhel86

Just a symlink to RHEL 8.2, no changes are required.

runners: add a runner for RHEL 8.6

---

stages/org.osbuild.grub2.inst

When the partition layout is `dos` or `mbr`, the correct name for it in the prefix is `msdos`. The function to convert the option to the label already existed but was not used. Fix it by actually using said function.
Reported-by: Achilleas Koutsou <achilleas@koutsou.net>

stages/grub2.inst: fix prefix for dos layouts

---

devices/org.osbuild.loopback
osbuild/devices.py
osbuild/loop.py
osbuild/remoteloop.py
test/mod/test_loop.py
test/run/test_assemblers.py
test/run/test_devices.py

Add a `close` method so that we can properly release the underlying file descriptor for the `LoopControl` object. Use that in `devices/org.osbuild.loopback` but more importantly in `RemoteLoop`. The latter is instantiated on every `Stage.run` call and thus the leaks would accumulate over the run of `osbuild` (whereas `devices/org.osbuild.loopback` will release the fd once the process is terminated, which is after the stage has run).
Additionally, create a new `LoopControl.loop_for_fd` helper based on the `make_loop` method in `devices/org.osbuild.loopback`. This is so the code can be shared with other places that want to open loop devices and bind them to file descriptors.

Loop controller improvements

---

devices/org.osbuild.loopback

That ironically fix the underlying bug that `flush_buf` is trying to fix too, since now an exception is thrown and we are back to auto clear. The file fd is then closed when the process is terminated. Anyway, the right fix is to call the correct function.

devices/loopback: it is flush_buf not flushbuf

---

inputs/org.osbuild.ostree.checkout
osbuild/util/ostree.py
stages/org.osbuild.ostree.passwd
test/mod/test_util_ostree.py

See commit messages for further explanation.
Reproducer for testing the passwd and group merge (doesn't really verify the issue with kernel-rt, which should be tested in `osbuild-composer` instead):
```bash
#!/bin/bash
set -ex
TMPDIR=$(mktemp --directory)
pushd "${TMPDIR}"
ostree --repo=ostree-passwd init
mkdir -p tree/usr/lib
mkdir -p tree/usr/etc
cat > tree/usr/lib/passwd << STOPHERE
root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
STOPHERE
cat > tree/usr/etc/passwd << STOPHERE
bin:x:8:8:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
STOPHERE
cat > tree/usr/lib/group << STOPHERE
root:x:0:
bin:x:1:
STOPHERE
cat > tree/usr/etc/group << STOPHERE
bin:x:8:
daemon:x:2:
STOPHERE
COMMIT=$(ostree --repo=ostree-passwd commit --branch=foo tree/)
popd
cat > …
```

Fix issue with changing content in /etc/passwd and /etc/groups in OSTree deployments

---

runners/org.osbuild.fedora36

New `org.osbuild.fedora36` which is re-using the f30 runner. Needed since Fedora 36 was branched already.
Release Notes:
```markdown
* `runners/org.osbuild.fedora36`: new runner for Fedora 36, reusing the existing f30 runner.
```

 runners: add Fedora 36 runner

---

stages/org.osbuild.lvm2.metadata

It is zero to nine, not zero and nine.

stages/lvm2.metadata: fix typo in regex

---

inputs/org.osbuild.ostree.checkout

The `refs` variable is used as parameter to indicate which commits to checkout, but it also was used as result variable to store the ids of the commits that actually got checked out; naturally, it was initialized to the empty array. This of course meant nothing was ever actually checked out. Doh.

`inputs/ostree.checkout`: don't overwrite refs

---

stages/org.osbuild.kickstart

The code of the `org.osbuild.kickstart` stage already supported adding the `--remote` option for `ostreesetup` via the `remote` option but it was not included in the schema.

stages/kickstart: add schema for remote option

---

stages/org.osbuild.bootiso.mono

Use the aarch64 templates if the efi architecture was set to AA64.
NB: since we only support efi booting for aarch64 this should be good enough for aarch64 selection.

stages/bootiso.mono: support for aarch64 tempates

---

stages/org.osbuild.kickstart

Surround the ssh key by quotes since it might contain spaces.

stages/kickstart: quote ssh-key

---

stages/org.osbuild.kickstart

The password is assumed to be encrypted so the `--iscrypted` option is required.

stages/kickstart: set passwords with --iscrypted

---

osbuild/util/rhsm.py

When `get_fallback_rhsm_secrets` was used, `Subscriptions.repositories`
was None, and `get_secrets` never returned the fallback secrets.
So check if `repositories` is None before
iterating over it, otherwise return the fallback secrets.

util/rhsm: Check if repositories is None before iterating

---

stages/org.osbuild.ostree.config
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json

Ability to set the bootloader backend that OSTree should use. NB: normally this should be set to `none` since in modern distros and bootloaders the BLS is used and the BLS snippets are generated on `none` but none of the of the specific bootloader tools are run, like `grub2-mkconfig` for grub.
Update the fedora image manifest to use that config setting.

ostree.config: add `bootloader` config option

---

.packit.yaml

Since we have made good experiences with packit and rawhide for the most recent releases I propose to extend it to all active Fedora releases.
(I proposed the same change to osbuild-composer: https://github.com/osbuild/osbuild-composer/pull/1756)

packit: Propose PRs to all Fedoras

---

tools/osbuild-mpp

Since `.sort()` returns None, we were checking that None == None
which is not what we aimed to do.
Quick reproducer:
```
>>> assert [1,2,3].sort() == [2,3,4].sort()
>>> assert sorted([1,2,3]) == sorted([2,3,4])
File "<input>", line 1, in <module>
assert sorted([1,2,3]) == sorted([2,3,4])
AssertionError
```
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

Fix the assert as `.sort()`  returns None

---

osbuild/main_cli.py
osbuild/pipeline.py
osbuild/sources.py
sources/org.osbuild.curl
sources/org.osbuild.inline
sources/org.osbuild.ostree
test/run/test_sources.py

Align sources with inputs, devices and mounts to use the host service infrastructure. This is the first step to have better logging and reporting of download status.
Includes the commit from pr #758 to avoid a rebase there (and as a side effect this will test the pr via Schutzbot).

Port sources to the host service infrastructure

---

stages/org.osbuild.qemu

The option got renamed to `compat` (and moved into the `qemu` object) when the stage was extracted from the `qemu` assembler; but the code, taken from the assembler, still used the old `qcow2_compat` name for the option. Fix this.

stages/qemu: fix 'compat' option

---

tools/osbuild-mpp

Using this we can now define variables in the variable section using
basic expression that are evaluated as f-string.
For example, you can use the syntax:
```
"mpp-vars": {
"rootfs_uuid": {"mpp-format-string": "{__import__('uuid').uuid1()}"},
"bootfs_uuid": "156f0420-627b-4151-ae6f-fda298097515"
},
```
This will automatically call uuid.uuid1() for rootfs_uuid, thus allowing
to dynamically set the uuid for the rootfs variable.
This variable being able to be overridden via the -D argument of the
osbuild-mpp tool.
In addition, you can also define variable based on variables defined
above, for example:
```
"mpp-vars": {
"rootfs_size": 4294967296,
"homefs_size": {"mpp-format-string": "{rootfs_size}"}
},
```
Signed-off-by: Pierre-Yves Chibon <pingou@pingoured.fr>

Add support for defining variables from other variables or basic expression

---

.github/workflows/trigger-gitlab.yml

The `workflow_run` event is triggered either when a workflow was requested or complete (see `types`). We can use this event as a trigger for the gitlab ci conditioning on a successful workflow run of the main tests ("Tests" workflow). This will ensure that, with outside contributor protection turned o, no secrets are leaked via PRs from non-contributors, but also that gitlab ci is run for those PRs once they were manually allowed to run. The only downside is that now the gitlab ci will only run after the main workflow ("Tests) has completed and thus serializing both CI runs. OTOH gitlab CI is quite intense so maybe this is not so bad after all. If in the future we want to parallelize both CI runs we could have a third "precheck" condition with maybe the spell checker and the pylint tests …

ci: trigger gitlab ci via workflow run event

---

.github/workflows/trigger-gitlab.yml

This workflow doesn't have access to the original pull request event
that resulted in this workflow being triggered.
Simply use `head_sha` which will contain the PR sha if it was triggered
by a PR's workflow, or the branch sha if it was triggered from a
branch's workflow.

.github: Use the workflow_run event data in trigger-gitlab

---

.github/workflows/trigger-gitlab.yml

Sadly `github.event.workflow_run.pull_requests` is empty if the pull
request was opened from another fork. Use the sha to find an open PR,
otherwise assume it's a branch.

.github: Get PR number from sha

---

selinux/README.md

Add a first outline of the integration points of osbuild and selinux, from two perspectives: how osbuild interacts with the host and how osbuild labels the target artefact and the resulting peculiarities.

docs: document osbuild and selinux integration

---

README.md

As discussed in our previous "How we work" session Im proposing to add a "Contributing" section that refers to our developer guide.

README: Add a link to our developer guide

---

osbuild/buildroot.py
osbuild/pipeline.py
setup.cfg

Currently, we take to paths from the root file system supplied to the `BuildRoot` class: `/boot` and `/usr`. The reason for
mounting `/boot` is that grub2 and shim install efi binaries there and for certain images we want to copy the binaries from the build root and not install the respective packages.
However, if we build to build root itself, we probably don't want the mount the hosts' `/boot` since we don't want to copy anything from there. So never mount the build root from the host, i.e. only mount it if the stage has a build pipeline specified.

Do not bind-mount the `/boot` directory from the host into the build root

---

mounts/org.osbuild.btrfs
mounts/org.osbuild.ext4
mounts/org.osbuild.fat
mounts/org.osbuild.noop
mounts/org.osbuild.ostree.deployment
mounts/org.osbuild.xfs
osbuild/devices.py
osbuild/formats/v2.py
osbuild/meta.py
osbuild/mounts.py
osbuild/pipeline.py
schemas/osbuild2.json
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json
test/run/test_devices.py

This PR introduces a new mount service that will set up bind mounts inside the tree very much as it is done by OSTree in early boot. This allows any stage to transparently work with OSTree deployments. As a pre-requirement the v2 schema was changed to give the individual stages more control over the `source` and `target` properties. Also the device and mount code was refactored to prepare this use case. See the individual commits for more details.

Transparent support for ostree deployments

---

.github/workflows/release.yml

We need a privileged / admin user doing the post-release version bump as
this is a direct commit to main (i.e. without a PR) so switch to using
schutzbot with a scoped personal access token (only public_repo).

Let schutzbot do the post-release version bump

---

stages/org.osbuild.lvm2.create
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.json

The `size` option was using `-l`, which in fact was `--extents`. Fix that to use `--size` and add a new option `extents` that will in fact call translate to `--extents` and this replace the current use of the `size` option.
Adapt the `fedora-ostree-image` test manifest to use `extents`.

stages/lvm2.create: fix 'size' and add 'extents'

---

stages/org.osbuild.modprobe
test/data/stages/modprobe/b.json
test/data/stages/modprobe/b.mpp.json
test/data/stages/modprobe/diff.json

Add support for new 'install' command in the org.osbuild.modprobe stage.
Extend the unit test coverage to test the new command.

Support 'install' command in org.osbuild.modprobe stage

---

stages/org.osbuild.grub2
test/data/stages/grub2/b.json
test/data/stages/grub2/b.mpp.json

This commit adds options to the org.osbuild.grub2 stage to configure
terminal input and output and serial console.
The functionality and configuration schema is the same as in the legacy
grub2 stage.

stages/grub2: add support for terminal and serial config

---

stages/org.osbuild.cloud-init
test/data/stages/cloud-init/b.json
test/data/stages/cloud-init/b.mpp.json
test/data/stages/cloud-init/diff.json

- Added support for configuring the Azure datasource.  Only options currently needed are defined.  More can be added later. Each defined datasource has to be listed in a top-level array in the config file.  This is added automatically.
- Added support for configuring reporting handlers.  It's likely that the names of the handlers can be arbitrary strings, but I couldn't confirm this, so I added the known names.

New options for cloud-init: Azure datasource and reporting/logging

---

stages/org.osbuild.rhsm

Adds support to configure `yum-plugins`, which currently is a full alias for `dnf-plugins`, although this might change in the future, in case dnf options diverge from yum. It allows for both yum and dnf plugins to be configured at the same time since on RHEL 7 both files will be present.

`stages/rhsm`: add support to configure yum plugins

---

stages/org.osbuild.selinux

This should not be needed in any case but can be a sledgehammer for situations where we cannot properly label a file; it turns out such a scenario is if a label, lets call it `a1`, is is an alias to another label, lets call it `l1`. Setting `a1` will lead to `a1` being read back, and thus copying the label `a1` will result on the label `l1` being copied instead. Now if the target distribution does not have `l1` but `a1` we cannot set it and thus will end up with an unlabeled file.

stages/selinux: ability to force an auto-relabel

---

osbuild/formats/v2.py

Commit 5b1cd2b made `source` and `target` for mounts optional, but the corresponding code in `describe` still assumes that the device will always be present. Fix this so that source will only be used if it is set.

formats/v2: fix describe for mount without source

---

stages/org.osbuild.yum.config
test/data/stages/yum.config/b.json
test/data/stages/yum.config/b.mpp.json
test/data/stages/yum.config/diff.json

The new stage enables users to configure the langpacks plugin of YUM. Its
schema is derived from the rhsm stage and is designed to be flexible if
we need to add ability to configure more YUM plugins, or even YUM itself.

stages/yum.config: add a new stage to configure YUM langpacks plugin

---

.packit.yaml

Setting this option enables packit to use the Github upstream release description for the specfile instead of just using all commit messages.
See also: https://packit.dev/docs/configuration/#copy_upstream_release_description
As we're doing good GitHub release notes I hope this will make downstream release notes more consistent with upstream.

packit: Use upstream github release description

---

tools/osbuild-mpp

This allows you to optionally do and operation, for example on a specific arch with an "if then" statement, or select between two options with an "if then else" statement.
I'm needing this in a manifest that needs some per-arch differences (in particular, the kernel image file has different formats on aarch64 and needs per-arch handling).

osbuild-mpp: Add mpp-if feature

---

.packit.yaml

I forgot to enable CS9 builds on main previously, let's fix that.

packit: enable copr builds for CS9 on main

---

tools/osbuild-mpp

This makes it a lot easier to understand failures when files are
including other files.

osbuild-mpp: Report the path of the json file when parsing fails

---

tools/osbuild-mpp

yaml files are essentially compatible with json files, although they have some advantages, like allowing comments and being easier for humans to read/write.
This changes the reading of the file to use a yaml parser instead of a json parser, but still produces json at the end. I tried manually converting a json file to yaml and running osbuild-mpp, and it produced an identical file.
By default the yaml parser doesn't respect order so i had to tweak the loader a bit to use OrderedDict.

osbuild-mpp: Support loading yaml as well as json files

---

osbuild.spec

osbuild-mpp has learned to read yaml files but with it gained a hard dependency on python3-pyyaml. Specify so in the spec file.

spec: require python3-pyyaml for osbuild-tools

---

tools/osbuild-mpp

This is what we do in the automotive-sig, and it would look a lot cleaner if we could import each sub-manifest only once. Also, it makes a lot of sense that the includer shouldn't have to be aware of the sub-pipelines that the including pipeline should need.

osbuild-mpp: Allow importing multiple pipelines from a manifest

---

stages/org.osbuild.ostree.fillvar

The idea behind the stage is to provision `var` of the stateroot, i.e. the `var` the is shared amongst all deployments for a given os (indicated by `osname`, e.g. `fedora`, `centos`, ...). For `systemd-tmpfiles` to infer the correct paths, it needs to be run on the deployment. The `var` of the latter needs to be bind- mounted to the `var` of the stateroot, because it is shared. This was always the intention but not what the code did. Fix this by getting the `var` of the stateroot and bind it to the `var` of the deployment.
NB: In reality this never mattered since systemd-tmpfiles is also run during system startup.

stages/ostree.fillvar: fill the correct var

---

stages/org.osbuild.grub2.inst

On Arch Linux grub-mkimage is provided by the `grub` package which is
grub2 and grub (1) no longer exists.

stages/grub2.inst: Make grub-mkimage binary configurable

---

osbuild/buildroot.py
test/mod/test_buildroot.py

Since we bind `/proc` inside the container, we leak certain information that comes with it. One of this is the kernel command line. None of the decisions done by software running inside the container should depend on the kernel command line on the host, so overwrite the kernel command line by creating a temporary directory and mapping it inside the build- root. For now we default to a simple `root=/dev/osbuild` fake kernel command line.

Buildroot: mask `/proc/cmdline`

---

mounts/org.osbuild.ostree.deployment
test/mod/test_osbuild.py

Small fix for `mounts/ostree.deployment` and an order check for `depsolve`

---

.github/mergify.yml

Define a merge queue "default", with all current checks (minus the ostree one) are required to get out of.
Two rules to get into the queue:
1.  standard branch protection, plus packit, plus the `ci:automerge`
2. dependabot, does not require the standard branch protection since that implies reviews. Instead the checks are manually listed.

ci: initial mergify configuration

---

.github/mergify.yml

For dependabot we dont want it anyway (but it is true by default). Also remove it for "merge via auto-label", so that once all the conditions are met the PR is queued and the label is removed. Currently the queuing might not happen because the branch protection is not met. Therefore we make the condition explicit and remove the branch protection.

[skip ci] ci: don't require branch protection

---

.github/mergify.yml

Don't try to do it in the same action as otherwise the bot will refuse to actually add it to the queue.

[skip ci] ci: remove label _after_ pr is merged

---

stages/org.osbuild.sshd.config
test/data/stages/sshd.config/a.json
test/data/stages/sshd.config/a.mpp.json
test/data/stages/sshd.config/b.json
test/data/stages/sshd.config/b.mpp.json
test/data/stages/sshd.config/diff.json

Add support for `PermitRootLogin` option in the
`org.osbuild.sshd.config` stage.
I kept the "yes" and "no" values for consistency with other stage
options. While it will make the implementation in osbuild-composer
harder, it won't be impossible as we already have a precedence for doing
it this way (e.g. in the `org.osbuild.pam.limits.conf`).
Modify the stage unit tests to check the new option.
Remove the empty `org.osbuild.sshd.config` stage from `a.mpp.json`
since it does not add any value and it actually made the `tree-diff`
tool provide a weird tree diff results.
Fix #910

sshd.config stage: support PermitRootLogin option

---

.github/mergify.yml
.github/workflows/automerge.yml

Instead of using merify which seems to not do what we want, use a combination of mergify and automerge. We let mergify review dependabot PRs. We let mergify dismiss reviews on updates but exclude those from Schutzbot. We then let Schutzbot update and merge the PRs via automerge if the `ci:automerge` label is set.

[skip ci] ci: switch to using automerge

---

.github/workflows/automerge.yml

Allow automerge to update the PR without any labels present.

[skip ci] ci: do not require label for rebase

---

osbuild/buildroot.py
test/mod/test_buildroot.py

Isolate the environment from the host to not leak any information. Set the `container` env variable to indicate we are running inside a container.

build root: isolate container environment from the host and set `CONTAINER`

---

stages/org.osbuild.users

On distributions such as Arch Linux the home directory is not created by
default.

stages/users: Explicitly create a home directory

---

.github/workflows/release.yml

Passing the webhook URL is necessary because GH composite actions don't
support handling secrets.
See also osbuild/release-action#3
[skip ci]

release-action: Send notification to our Slack channel

---

stages/org.osbuild.sysconfig

The sysconfig stage currently does not produce expected results when
used multiple times within the same pipeline. Specifically, the stage
always truncates respective configuration files for properties `kernel`
and `network`, if if these are not set in the stage options. Due to this
reason, the outcome of the image builds may depend on the order of
multiple occurrences of the sysconfig stage.
The following two pipeline snippets would produce different
configuration files content:
Configuration files are truncated:
```json
{
"type": "org.osbuild.sysconfig",
"options": {
"kernel": {
"update_default": true,
"default_kernel": "kernel"
},
"network": {
"networking": true,
"no_zero_conf": true
}
}
},
{
"type": "org.osbuild.sysconfig",
"options": {
"network-scripts": {
"ifcfg": {
"eth0": { …
```

stages: allow using sysconfig stage multiple times.

---

stages/org.osbuild.kickstart

Post nor anaconda wasn't ever set to something truthy, let's just remove them. To simplify extending of the kickstart file, ensure a newline at the end of the file.
Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2036971
Closes: #942

org.osbuild.kickstart adjustments

---

stages/org.osbuild.grub2
stages/org.osbuild.grub2.legacy
stages/org.osbuild.pacman
test/data/manifests/arch/arch-build.json
test/data/manifests/arch/arch-build.mpp.json

This is the final piece for generating a successful booting Arch Linux VM. Arch Linux can't use the normal grub stage as the the open bootloader specification patches are not merged upstream yet.

Arch legacy grub compatibility

---

stages/org.osbuild.grub2
test/data/manifests/fedora-boot.json
test/data/manifests/fedora-boot.mpp.json
test/mod/test_osbuild.py

Currently we always write the kernel command line to the `grubenv` file, if only to include the root device. Starting with Fedora 33 and thus RHEL 9, the kernel command line included statically in the BLS snippets and the grubenv `kernelopts` variable not used. Instead one of the {/usr/lib,/etc}/kernel/cmdline files is read and the parameters in them used during the creation of the BLS snippets.
Therefore we add a new `write_cmdline` option that, if set to FALSE, will prevent us from writing the kernel command line.

`stages/grub2`: ability to not write kernel cmdline

---

.gitlab-ci.yml

This will cancel old running pipelines if a new one is created.
I want to just test it here because this seems to be more responsive then osbuild-composer repository.

ci: make jobs interruptible

---

osbuild/util/linux.py

ioctl contants are platform dependent. It should be the same on x86, aarch64 and s390x but it is indeed different on ppc64le. This lead to the call to `ioctl_blockdev_flushbuf` actually raising an exception of `OSError: [Errno 22] Invalid argument`.
The constant was calculated with a little python snippet that in theory could also go directly into the code, but for now the simpler condition in this patch is enough.
The snippet is a port of the defines from the Linux kernel, specifically `/usr/include/asm-generic/ioctl.h`.
class IOConstants:
"""IO Commands for Linux"""
if platform.machine() == "ppc64le":
NRBITS = 8
TYPEBITS = 8
SIZEBITS = 13
DIR_NONE = 1
else:
NRBITS = 8
TYPEBITS = 8
SIZEBITS = 14
DIR_NONE = 0
NRSHIFT = 0
TYPESHIFT = NRSHIFT+NRBITS
SIZESHIFT = TYPESHIFT+TYPEBITS
DIRSHIFT = …

util/linux: fix BLK_IOC_FLSBUF on ppc64le

---

schutzbot/sonarqube.sh

Only use the branch options if it's actually running in a branch and
analyse main without them, sonarqube otherwise doesn't recognize the
main branch.

tests/ci: fix sonarqube analysis for main branch

---

runners/org.osbuild.rhel87

As always, it can be just a symlink to rhel-82

runners: add rhel-87

---

osbuild/buildroot.py
osbuild/formats/v2.py
osbuild/pipeline.py
schemas/osbuild2.json
stages/org.osbuild.oci-archive
test/mod/test_osbuild.py

This adds a source-epoch option on the pipeline, which if set is passed down as `SOURCE_DATE_EPOCH` in the buildroot environment, as per the spec at:
https://reproducible-builds.org/docs/source-date-epoch/
In addition it passes the epoch to the stages, and there are some inital code in the oci-archive stage to use it to override the creation time of the container config file.
There are also some general changes to the tar creation in the oci-archive stage in order to make the tarfiles more reproducible.
One of my goals with this is to be able to create an oci-archive from a pipeline and then end up with an identical oci config file and uncompressed layer tarball, because then that will imply that the installed container image will get the same id. However, this currently requires more …

Initial work on more reproducible builds

---

.github/workflows/tests.yml
test/run/test_executable.py

During the rework done in commit "use and require explicit exports" with commit id https://github.com/osbuild/osbuild/commit/7ae4a7e7858f1ffd1936711966048e76bc9e0b75, the test got overlooked. Add an empty list of checkpoints to the `obs.compile` invocation as to actually trigger the osbuild invocation.
Also actually run the test in ci.

Fix executable test

---

stages/org.osbuild.skopeo

Each time the overlay backend runs on an xfs fs it creates the
file "overlay/backingFsBlockDev" in the containers storage directory.
It is not needed in the image as skopeo recreates it each boot, and
since it is a block device its existance means we can't store the
resulting tree in ostree. Lets just get rid of it.

skopeo stage: remove overlay/backingFsBlockDev file after install

---

stages/org.osbuild.oci-archive

According to OCI image specification the `created` property needs to be in the format describe in RFC 3339, section 5.6 "Internet Date / Time Format". The suffix is the "time-offset" which is either "Z" or "time-numoffset". Before commit 25b5679[2] we the datetime object, created via `utcnow` did not have timezone information so "Z" was manually appended. This was changed with commit 25b5679 and now the timezone information was indeed included, which also meant that `isoformat` now included the offset, i.e. `+00:00`. But the `Z` was still appended and the result was `+00:00Z`, something that is not standard compliant. Fix this by removing the extra `Z`.
[1] https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
[2] 25b567990bcc1ac2cf1a6e5804499126f9434f89

stages/oci-archive: fix creation time format

---

osbuild/util/udev.py

The udev inhibitor rules are checking for `device-$major:$minor` but we created them with `f"device-{major}-{minor}"`. So they did indeed not actually work. Fix that.

util/udev: fix path for udev device inhibitor

---

stages/org.osbuild.firewall
test/data/stages/firewall/b.json
test/data/stages/firewall/b.mpp.json
test/data/stages/firewall/diff.json

Extend the firewall stage to allow setting the default firewall zone.
Modify the stage unit test accordingly.
This is needed for the GCE image.
TODO:

Extend firewall stage to set the default zone

---

stages/org.osbuild.rpm

Add a new option `gpgkeys.fromtree` that when specified will import the specified gpg keys from files located in the tree, such as `/etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release`.
Manually tested and verified via a manifest and a patch to Composer.

stages/rpm: option to import gpg keys from tree

---

devices/org.osbuild.lvm2.lv
test/mod/test_util_lvm2.py

In all invocations of `subprocess.run` stderr and stdout were both combined in a shared pipe, but lvm sometimes spits out notices and informational messages on stderr and thus potentially interfering with the data we are interested in on stdout. Separate the two.

LVM2: separate stderr, stdout

---

stages/org.osbuild.firewall
test/data/stages/firewall/b.json
test/data/stages/firewall/b.mpp.json

When the firewall stage is provided with stage options, which set only
the default firewall zone, the `firewall-offline-cmd` command is
executed unconditionally without any parameters. This is because in this
case `ports`, `enabled_services` and `disabled_services` are all an
empty lists. This results in a failure with the following error message:
`Opening of '/etc/sysconfig/system-config-firewall' failed, exiting.`
Make sure that the second invocation of `firewall-offline-cmd` happens
conditionally, only when at least one of the `ports`, `enabled_services`
or `disabled_services` is a non-empty list.
Adjust the stage test to cover this scenario.

stages/firewall: fix fail when setting only the default zone

---

stages/org.osbuild.grub2
test/data/stages/grub2/b.json
test/data/stages/grub2/b.mpp.json

When `saved_entry` is set, write `GRUB_DEFAULT=saved` to grub defaults, i.e. `/etc/default/grub`.

stages/grub2: write GRUB_DEFAULT on saved_entry

---

.packit.yaml

Add srpm_build_deps key to the Packit configuration to specify the needed dependencies for SRPM build
and indicate to build SRPM in Copr.
If you are interested in the transition to building SRPMs in Copr, you can read more about it [here](https://packit.dev/posts/copr-srpms/).

Packit: build SRPMs in Copr

---

sources/org.osbuild.curl

Some RPMs might be very large, and limiting the total download time
might lead to failed build even in cases where downloading is making
progress. Instead, set a minimum download speed (1kbps). If the
minimum is not surpassed for 30 seconds in a row, the download fails
and is retried. This follows the logic employed by DNF.
Adjust the number of retries to 10 and the connection timeout to 30,
in order to match what DNF does. One difference is that DNF does 10
retries across all downloads, whereas we do it per download, this
could be changed in a follow-up.
Old:
- a download taking more than 5 minutes is unconditionally aborted
New:
- slow but working downloads will never be aborted
- downloads will be stalled for at most five minutes
in total before being aborted
- time spent making …

sources/curl: don't limit total download time

---

osbuild/util/selinux.py
stages/org.osbuild.selinux
test/mod/test_util_selinux.py

Instead of using `chcon`, directly call `selinux.setfilecon`. On systems without SELinux support, i.e. coreutils was built without `<selinux.h>` present, `chcon` will return `ENOTSUP` for all selinux related calls like `setfilecon` even if the selinux libraries are later installed. Therefore we directly call the library function which should ensure that we don't error out as long as the library is present.  The only other thing `chcon` is doing besides a cal to the `setfilecon` method is to convert the context string to a `contex_t` and back to validate it. This should not be needed since the kernel will do this for us. On system without SELinux support `context_new` will also not validate the context.

stages/selinux: directly call setfilecon

---

.github/workflows/create-tag.yml

Instead of a human pushing a tag with the release notes let a bot do the
work.
The bot is part of our composite action in osbuild/release-action on the
create-tag branch. It calculates the next subsequent release version and
creates a tag based on pull request titles associated with the changes
since the last release.
Finally the tag is pushed to the repository.
Unfortunately GH Actions don't allow for reliably fortnightly schedules,
so we do an additional check that determines if this is an even or an
odd week. This will help with correctly scheduling alternating osbuild
and osbuild-composer releases.
For reference, we do exactly the same for osbuild-composer already:
https://github.com/osbuild/osbuild-composer/blob/main/.github/workflows/create-tag.yml
Here's the actual successful …

Enable scheduled upstream releases

---

stages/org.osbuild.sfdisk

The GPT attribute field is a 64-bit field that contains two subfields. The higher field is interpreted only in the context of the partition ID, while the lower field is common to all partition IDs. sfdisk supports to change this fields, and also a osbuild user might be interested on change these bits. This patchset adds support to change these bits in the sfdisk stage. 
The meaning of these bits (from Wikipedia) :
- 0 Platform required (required by the computer to function properly, OEM partition for example, disk partitioning utilities must preserve the partition as is)
- 1 EFI firmware should ignore the content of the partition and not try to read from it
- 2 Legacy BIOS bootable (equivalent to active flag (typically bit 7 set) at offset +0h in partition entries of the MBR partition …

stages/sfdisk: support changing GPT partition attribute bits

---

.gitlab-ci.yml
Schutzfile
schutzbot/ci_details.sh
schutzbot/mockbuild.sh
tools/set-env-variables.sh

Adding Schutzfile to enable system repo pinning and using them in mockbuild.
Adding `set-env-variables.sh` script
Updating `ci-details.sh` and running it in CI.

Pin rpmrepo snapshots for CI runners + use them in mockbuild + ci improvements

---

osbuild/buildroot.py

This is a left-over from the time when `systemd-nspawn` was used, which only retained a limited set of capabilities which did not include `CAP_MAC_ADMIN`[1]. Bubblewrap, on the other hand, retains all currently capabilities if the process is run as root[2].
[1] see e.g. [src/nspawn/nspawn.c#L147](https://github.com/systemd/systemd/blob/c52950c292be639aec38f9a5db1681005203c2cd/src/nspawn/nspawn.c#L147) of commit c52950c
[2] see commit [abc56644566a6095bb72a5bf70fcee7dd90e9447](https://github.com/containers/bubblewrap/commit/abc56644566a6095bb72a5bf70fcee7dd90e9447)

buildroot: don't explicitly add `CAP_MAC_ADMIN`

---

devices/org.osbuild.lvm2.lv

LVM2 introduced system.devices as an alternative way to filter devices. Since we create devices in a stage the devices won't be added to the /etc/lvm/devices/system.devices file since /etc/ is inside the container. As a result the we can't see these devices and will fail with "Could not find parent device".
Therefore we add support for managing our own per-service devices file, iff a `system.devices` is present.

devices/lvm2.lv: add support for lvm devices files

---

osbuild/util/ostree.py
stages/org.osbuild.ostree.passwd
test/mod/test_util_ostree.py

When merging user and group database from individual commits also merge the corresponding `/etc/sub{u,g}id` database. These are created when the users are added via `useradd` and thus also need to be imported with the corresponding users.

stage/ostree.passwd: also merge /etc/sub{u,g}id

---

stages/org.osbuild.luks2.format

I've been looking at:
https://archive.fosdem.org/2018/schedule/event/cryptsetup/attachments/slides/2506/export/events/attachments/cryptsetup/slides/2506/fosdem18_cryptsetup_aead.pdf
And it seems if you want integrity checking, dm-crypt is not enough,
but should be combined with dm-integrity. This allows this by using
the --integrity option with cryptsetup.
It should be noted that the slides above mention that this is marked
experimental in the docs because the existing algorithms usable for
this is a bit slow. Something to be aware of if you want to use this.

org.osbuild.luks2.format: Support dm-integrity

---

osbuild/loop.py
osbuild/monitor.py
setup.cfg
test/mod/test_monitor.py

This was disabled globally due to `LoopInfo` and its dynamic attributes and thus some actual issues found their way into the code base. Fix those and silence the `LoopInfo` false positive locally; then re-enable the warning globally.

Re-enable pylint warning W0201 (attribute-defined-outside-init)

---

osbuild/sources.py
osbuild/util/ostree.py
sources/org.osbuild.curl
sources/org.osbuild.inline
sources/org.osbuild.ostree
sources/org.osbuild.skopeo
test/mod/test_util_ostree.py

This refactor integrate the download method into `SourceService` in order to simplify the code base on all the sub downloading programs. The API now requires each downloading program to define a method named `fetch_one`. The objective of this method is to execute the proper downloading of a single element.
The generalization process has let us define a better workflow to perform the downloading. The workdfow is:
Setup -> Filter -> Prepare -> Download.
* Setup initializes the cache
* Filter checks if elements are already in it
* Prepare amends the input data to include things like subscriptions
* Download calls fetch_one for each element.
The overloading class in the sub program has the ability of customizing each step of the workflow.
To customize the filtering it can overload the `exits` …

sources: refactor the SourceService class

---

osbuild/meta.py

Show the stage name (if one is set) when failing the stage in the
validator. This closes #1007, example output:
```
€ python3 -m osbuild supakeen-os.json
supakeen-os.json has errors:
pipelines[0].stages[0]
could not find schema information for 'org.osbuild.rpmb'
.pipelines[0].stages[0].inputs.packages:
could not find schema information for 'org.osbuild.filesz'
```

meta: show stage name when schema is missing

---

stages/org.osbuild.ostree.passwd

The sub{g,u}id files in the commit are located in `/usr/etc` not `/etc`. Read the files from there.

stages/ostree.passwd: fix subid source path

---

sources/org.osbuild.curl

This changes the curl source to use the number of cpus times two for its thread count. A conservative number but a commonly used default.
Tiny benchmark on my system (with 8 logical cores, so 16 workers):
```
user@desktopa osbuild € rm -rf .osbuild && time osbuild samples/fedora-container.json
...
osbuild samples/fedora-container.json  47.03s user 3.09s system 41% cpu 2:01.47 total
user@desktopa osbuild € rm -rf .osbuild && time osbuild samples/fedora-container.json
...
osbuild samples/fedora-container.json  42.64s user 2.35s system 147% cpu 30.569 total
```
There's room for discussion on the multiplier, I went with two because while the curl processes are waiting a bunch for network I/O the fork+exec (or posix_spawn) actions are still CPU intensive and happen a lot.

sources: curl max_workers 2 * num_cpus

---

test/run/test_stages.py

When a `-` is in the version (meaning a version such as: `2.38-rc1`), take only the part before the dash.
This closes #1036.

tests: handle `-` in the sfdisk version test

---

sources/org.osbuild.curl

Add support for the `--insecure` curl flag, which makes curl skip the verification step when making secure connections (e.g., https://).  This allows osbuild to download files from servers configured with SSL/TLS but whose certificate cannot be validated.
This is supported for configuring repository sources in osbuild-composer.

Support calling curl with --insecure

---

.github/workflows/create-tag.yml

Adjust the timer for our automated releases to trigger the workflow at 8 UTC. This corresponds to 10am in most of our team's timezone and to the reminder event in our team calendar.
See the corresponding PR for osbuild-composer: https://github.com/osbuild/osbuild-composer/pull/2744

ci: Adjust release schedule timer

---

stages/org.osbuild.qemu
test/data/stages/qemu/checks.json
test/data/stages/qemu/qemu.json
test/data/stages/qemu/qemu.mpp.json

Currently we hard code the vpc options `subformat=fixed` and `force_size`, which are needed to generate valid azure images with newer versions of qemu. But for other use cases or other versions of qemu these options might not be wanted or valid.
Expose all the options but with defaults corresponding to the old behavior.

stages/qemu: expose vpc options

---

stages/org.osbuild.mkfs.fat

The option will force `mkfs.fat` to ignore existing partitions on the target device. The check is done via the corresponding device node in sysfs, i.e. the contents of the `partition` attribute in `/sys/dev/block/<major>:<minor>`. In certain situations this info can be stale. Passing `-I` will work-around these situations.

stages/mkfs.fat: pass `-I` command line option

---

osbuild/objectstore.py
osbuild/pipeline.py
test/mod/test_objectstore.py

Cleanup some left over dead code and simplify areas that had to be more complicated when we still had recursive pipelines.

store: various code cleanups

---

osbuild/inputs.py
osbuild/pipeline.py

Introduce a new class to manage inputs, `InputManger` and move the code to map inputs from the `Input` here. The main insight of why the logic should be place here is that certain information is needed to map inputs, independently of specific type: the path to the input directory, `root`, the store API, `storeapi` and the service managerinstance to start the actual service. Instead of passing all this information again and again to the `Input` class, we now have a specialized (service) manager class for inputs that has all the needed information all the time.

inputs: introduce new input manager class

---

.gitignore

Super minor, I often use virtual environments during testing, this puts them on the ignore list.

git: ignore common virtual env locations

---

stages/org.osbuild.dnf.config
test/data/stages/dnf.config/b.json
test/data/stages/dnf.config/b.mpp.json
test/data/stages/dnf.config/diff.json

Add support for specifying rpm transaction flags via the `tsflags` options. See `dnf.conf(5)` for more details.

`stages/dnf.config`: ability to configure rpm transaction flags

---

Makefile
osbuild/__init__.py
osbuild/main_cli.py

Add `__version__` to `__init__.py` and an argument to show it.
This closes #992 by adding a `--version` argument.
```
user@desktopa osbuild € python3 -m osbuild --version
osbuild 58
```
and
```
user@desktopa osbuild € python3 -m osbuild          
usage: osbuild [-h] [--store DIRECTORY] [-l DIRECTORY] [--checkpoint ID]
[--export ID] [--json] [--output-directory DIRECTORY]
[--inspect] [--monitor NAME] [--monitor-fd FD]
[--stage-timeout STAGE_TIMEOUT] [--version]
MANIFEST
osbuild: error: the following arguments are required: MANIFEST
```

main: add a --version argument

---

docs/osbuild.1.rst
osbuild/main_cli.py

Bring `osbuild(1)` up-to-date, plus some minor fixes in the `--help` output.
Note that there is lots of room for improvement in `osbuild(1)`, but this is just an attempt to move it one step closer to being a useful reference.

docs: update osbuild(1)

---

.github/workflows/checks.yml
.mypy.ini
assemblers/org.osbuild.qemu
devices/org.osbuild.loopback
devices/org.osbuild.luks2
devices/org.osbuild.lvm2.lv
osbuild/api.py
osbuild/buildroot.py
osbuild/devices.py
osbuild/formats/v1.py
osbuild/formats/v2.py
osbuild/host.py
osbuild/inputs.py
osbuild/meta.py
osbuild/mounts.py
osbuild/objectstore.py
osbuild/pipeline.py
osbuild/sources.py
osbuild/util/jsoncomm.py
osbuild/util/linux.py
osbuild/util/lorax.py
osbuild/util/lvm2.py
osbuild/util/ostree.py
osbuild/util/path.py
osbuild/util/types.py
sources/org.osbuild.curl
stages/org.osbuild.sfdisk
stages/org.osbuild.sgdisk
stages/org.osbuild.udev.rules

`osbuild` currently has incomplete type annotations. This PR first fixes them where necessary and will then expand to enable `--strict` for `mypy`.

osbuild: fix current partial type annotations
