osbuild/osbuild

osbuild
osbuild.py

I need this for running it from python, where all output is captured and can be put into logs.

Make running osbuild without any output possible

---

osbuild
osbuild.py
samples/base-qcow2.json
samples/base-with-grub2.json
samples/base-with-locale.json
samples/base-with-selinux.json

This is the start of a rework of PR #8.

Introduce classes for assemlers/stages

---

osbuild.py

Make BuildRoot.run() a method that bind-mounts a binary into the build
root and runs it. It has the same API as subprocess.run().
Move stage- and assembler-specific code to Stage.run() and
Assembler.run().

osbuild.py: separate BuildRoot.run() from Stage.run()

---

osbuild
osbuild.py

osbuild.py: clean up API

---

.pylintrc
.travis.yml
assemblers/io.weldr.qcow2
osbuild.py
stages/io.weldr.ansible
stages/io.weldr.dnf
stages/io.weldr.grub2
stages/io.weldr.noop

Goals:
Please check the configuration and share your thoughts. I have already disabled `missing-docstring`, but we also have a lot of `invalid-name` warnings.

CI configuration

---

osbuild/__init__.py

This really only makes sense if we are running systemd as PID1
inside the container, but we are not booting a system, just using
it as a glorified chroot.
This means entering the namespaces from the outside will be a bit
more cumbersome, but that was not used much and was never reliable
to begin with.

BuildRoot: do not register with systemd-machined

---

osbuild-run
osbuild/__init__.py
samples/base-qcow2.json
samples/base-with-grub2.json
samples/base.json
test/1-create-base.json
test/2-configure-web-server.json
test/3-compose-qcow2.json
test/4-all.json

Remove systemResourcesFromEtc

---

.gitignore
MANIFEST.in
Makefile
osbuild.spec
setup.py
test/Makefile
test/Vagrantfile

See also the rhbz review request:
https://bugzilla.redhat.com/show_bug.cgi?id=1731111
and a Copr repository with `osbuild` package:
https://copr.fedorainfracloud.org/coprs/msehnout/osbuild/

introduce spec file

---

Makefile
test/Makefile
test/Vagrantfile

* destroy vm after running the test
* add additional make target to keep the vm running

make vagrant-test idempotent

---

README.md

Minimal update, feel free to do more changes on top, but at least now it is not wrong.

README: update to match current state

---

samples/base-qcow2.json
samples/base-with-grub2.json
samples/base-with-locale.json
samples/base-with-selinux.json

I broke them with the io.weldr → org.osbuild move.

samples: fix base ids

---

stages/org.osbuild.timezone
test/run-tests.py
test/timezone-test.json

add timezone stage

---

stages/org.osbuild.grub2

As documented here:
https://weldr.io/lorax/lorax-composer.html#customizations-kernel
we should support additional kernel options.
If you have an idea for a test of this feature, let me know!

introduce support for user-defined kernel options

---

.packit.yaml
Makefile
osbuild.spec

packit service is not triggered on pull request, this change should introduce this feature

update packit config

---

stages/org.osbuild.firewall
test/firewall-test.json
test/run-tests.py

as described in lorax documentation, we need to support raw
ports/protocols and services as defined by firewalld:
https://weldr.io/lorax/lorax-composer.html#customizations-firewall

introduce firewall stage

---

stages/org.osbuild.hostname

Check #48 for alternative implementation.

introduce hostname stage

---

bump-version.sh
osbuild.spec
setup.py

also includes "version bumper" script

release version 2

---

tree-diff

The tool compares two trees based on the information that constitutes
the treesum.

tools: add a helper to generate a 'deep diff' of two trees

---

.travis.yml
README.md
osbuild/__main__.py
osbuild/objectstore.py
osbuild/pipeline.py
test/__main__.py
test/integration_tests/build.py
test/integration_tests/config.py
test/integration_tests/run.py
test/integration_tests/test_case.py
test/test_osbuild.py

Also some cleanup commits related to that.
Fixes #103

Store outputs in object store

---

samples/base-from-yum.json
samples/base-qcow2.json
samples/base.json
samples/build-from-yum.json
samples/noop.json
test/pipelines/f30-boot.json
test/pipelines/firewall.json
test/pipelines/locale.json
test/pipelines/timezone.json

This key carries no information and is never used anywhere. The json
files are not meant to be human readable, so simply drop this.

pipeline: stop naming pipelines

---

README.md
samples/base-from-yum.json
samples/base-qcow2.json
samples/base.json
stages/org.osbuild.dnf
test/pipelines/f30-boot.json
test/pipelines/firewall.json
test/pipelines/locale.json
test/pipelines/timezone.json

The names carry no information, and do not affect the produced image.
Generate them instead.

stages/dnf: don't name the repositories

---

samples/base-from-yum.json
samples/build-from-yum.json
stages/org.osbuild.yum

See 840bfd580c74fce0ec1eda52c783a007288881d2.

stages/yum: don't name the repositories

---

README.md
assemblers/org.osbuild.qemu
samples/base-qcow2.json
stages/org.osbuild.grub2
test/pipelines/f30-boot.json
test/test_boot.py

This is a proof-of-concept showing how we would like grub2-install to behave.

replace grub2-install

---

osbuild.spec
setup.py

Release osbuild-3

---

.travis.yml
assemblers/org.osbuild.qemu
assemblers/org.osbuild.rawfs
osbuild/remoteloop.py
samples/base-rawfs.json
test/osbuildtest.py
test/pipelines/f30-base.json
test/test_assemblers.py
tree-diff

Also moves more code from org.assembler.qemu to LoopClient, so that this new assembler can reuse it.

Add org.osbuild.rawfs

---

.gitignore
samples/base-rpm-qcow2.json
stages/org.osbuild.rpm

A new stage that downloads a list of packages and installs them using
`rpm`.
Fixes #135

stages: add org.osbuild.rpm

---

.packit.yaml

Update packit.yaml for f31

---

LICENSE

Fill in the license template

---

assemblers/org.osbuild.qemu

partially fixes #164, the image can be imported but it does not boot for unknown reason and fails with timeout

Support for vpc format in qemu assembler 

---

assemblers/org.osbuild.qemu
assemblers/org.osbuild.rawfs

Needed for RHEL, which defaults to xfs.

Add xfs support to rawfs and qemu assemblers

---

stages/org.osbuild.systemd

Allow setting the default to boot into.

stages/systemd: add default_target

---

osbuild.spec

Missed it in 510e2b1e9439e65038e02605ed84bfa52720ca06.

osbuild.spec: install sources directory

---

osbuild/loop.py
osbuild/remoteloop.py

loop: close dangling file descriptors and handle set_status returning EBUSY

---

osbuild/pipeline.py

The dnf stage wants to import `osbuild.sources` but currently the osbuild module is not available in the stages. Apply the same hack done in the Assembler also in for the stages, i.e. bind mount the osbuild module to the stages/osbuild.

pipeline: bind mount the osbuild module for the stages

---

.gitlab-ci.yml

This is the first test of connecting gitlab CI to the github
repository.

Add the first gitlab ci YAML

---

osbuild/buildroot.py
osbuild/pipeline.py

buildroot: back /var in the buildroot by the store

---

.gitignore

Ignore files related VS Code, PyCharm and gdb.

gitignore: ignore IDE files

---

osbuild/__main__.py
osbuild/pipeline.py
test/test_osbuild.py

This is in preparation of osbuild-composer outputing sources as well as pipelines.

Allow sources to be passed in over stdin

---

.github/workflows/tests.yml
.travis.yml

* Run unit tests in GitHub Actions
* Remove unit tests from Travis CI
🚦 Requires #230 to merge first.

unit tests: run in GitHub Actions

---

.github/workflows/tests.yml

🤦‍♂️ Restore the Fedora modularity workaround

---

osbuild/objectstore.py
osbuild/pipeline.py
test/test_objectstore.py

With #225 merged and automatic commits of the final tree to the store gone, there is no need to raise exceptions in `Stage.run` nor `Assembler.run`, because the only reason we had this in the first place was to abort the (auto-) commit of new `Object`s to the store in case of errors.
Additionally, introduce a context around `Object.write` as to enforce the "exactly one writer or many readers" policy.

No exceptions from `.run` and enforce singler writer to `objectstore.Object`

---

osbuild/pipeline.py
test/os-release/arch
test/test_osrelease.py

Two minor improvements on the recently introduced `detect_os()` function. Details in each commit-message.

Improvements on `detect_os()`

---

osbuild/__main__.py

Two minor cleanups in `mark_checkpoints()`. No functional change, I hope.

Minor cleanups on checkpoint marking

---

Makefile
bump-version.sh
osbuild.spec

Assortment of minor fixes in `Makefile` and the specfile. See each commit-message with details. Adding @msehnout since he seemed to be the one using `bump-version`.

Minor fixes in `Makefile` and specfile

---

.gitignore
Makefile

This is similar to what I did for osbuild-composer: https://github.com/osbuild/osbuild-composer/pull/280

Simplify make rpm

---

.github/workflows/tests.yml

Use the new `make rpm` step from the `Makefile` in osbuild's GitHub Actions workflow. Also, add emojis because why not? :thinking:

📦 Use new 'make rpm' in GitHub Actions

---

docs/osbuild-manifest.5.rst
docs/osbuild.1.rst
samples/base-rpm-qcow2.json
schemas/osbuild1.json

More improvements to the documentation and specification. The commits should be self-contained and self-explanatory. See each commit-message for details.
This improves on the formatting and correctness of the `EXAMPLES` section, followed by an introduction of JSON schemas, and ends with a man-page documenting the manifest format.

Manifest definition and documentation

---

jenkins/run_tests.sh

Test a deployment of osbuild along with osbuild-composer for each PR.
More testing could be stacked on top.

🤏 Add a little bit more testing

---

Makefile
NEWS.md

Prepare a NEWS entry for osbuild-12, as well as 2 minor fixes related to it.

Prepare NEWS for upcoming release

---

.github/workflows/tests.yml
test/osbuildtest.py
test/test_assemblers.py
test/test_boot.py
test/test_objectstore.py
test/test_osbuild.py
test/test_osrelease.py
test/test_sources.py
test/test_stageinfo.py
test/test_util_ostree.py
test/test_util_selinux.py

A bunch of pylint checks for `./test` and then a CI adjustment to make sure pylint runs for `./test` as well as `./osbuild/util`.

Pylint all the Things

---

osbuild/sources.py

This changes the sources module to explicitly cleanup event-loops.
Additionally, the implementation is protected against re-entrency which
we do not support (and do not need).
We did occasionally get the following exception when running
source-servers:
/usr/lib/python3.8/asyncio/base_events.py:654: ResourceWarning: unclosed event loop <_UnixSelectorEventLoop running=False closed=False debug=False>
_warn(f"unclosed event loop {self!r}", ResourceWarning, source=self)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f92589d14c0>
File "/usr/lib/python3.8/asyncio/base_events.py", line 656, in __del__
self.close()
File "/usr/lib/python3.8/asyncio/unix_events.py", line 58, in …

sources: make cleanup explicit

---

jenkins/run_tests.sh

Although we are doing a good job of finding osbuild breakage when we
test osbuild-composer, we aren't finding osbuild-composer breakage
when we test osbuild.
Run the image tests from osbuild-composer whenever we do CI for osbuild.
Fixes #362.

🔧 Run osbuild-composer tests in osbuild CI

---

test/test_boot.py

This changes `-chardev stdio` to `-chardev file` and uses a temporary
file to communicate with QEMU.
This fixes an issue where `-chardev stdio` hangs if `STDIN` is not a
TTY. I could not figure out how to make it work without a TTY, and it
does not print any meaningful diagnostics. Problem is, in CI and other
automated runners, we do not necessarily have a TTY as STDIN.
This just switches to a temporary file, which seems to work under all
circumstances.

test/boot: use `-chardev file` over `-chardev stdio`

---

schutzbot/Jenkinsfile

1. Test osbuild on RHEL 8.2 with osbuild-composer's image tests
2. Bring over the jenkinsfile improvements from osbuild-composer

Enable testing on RHEL 8.2

---

NEWS.md
osbuild.spec
setup.py

Preprare release 15

---

NEWS.md
osbuild/pipeline.py
osbuild/util/jsoncomm.py

A minor collection of fixes which were discussed in previous PRs.

Minor fixes for previous PRs

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh
schutzbot/run_tests.sh

This commit brings over updates for mock builds from osbuild-composer.

CI: Store RPMs by SHA

---

osbuild/meta.py
sources/org.osbuild.dnf
sources/org.osbuild.files
sources/org.osbuild.ostree
test/test_osbuild.py

Add the necessary bits and pieces to do source verification and validation.

Source verification

---

stages/org.osbuild.users

Also support new users with  duplicate uids. See the individual commit for details.

stages/users: fix conditionals for zero & "" strs

---

schutzbot/Jenkinsfile
schutzbot/ci_details.sh

Dump data about the machine running the test very early in the job run.

Add CI details script

---

assemblers/org.osbuild.oci-archive
osbuild/util/ostree.py
test/mod/test_util_ostree.py
test/test.py

python3.6: small fixes to be compatible with python 3.6

---

test/run/test_assemblers.py

Using the network block device (`nbd`) kernel module to test all the non-raw image formats often caused tests to fail due to `nbd` not being stable itself (see below).
Instead convert non-raw images to the raw format via `qemu-img` convert and mount those with loop-back devices. All the testing code itself stays the same.
Example nbd error messages:
```
kernel: block nbd15: NBD_DISCONNECT
kernel: block nbd15: Disconnected due to user request.
kernel: print_req_error: 89 callbacks suppressed
kernel: blk_update_request: I/O error, dev nbd15, sector 0 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
kernel: buffer_io_error: 134 callbacks suppressed
kernel: Buffer I/O error on dev nbd15, logical block 0, async page read
kernel: blk_update_request: I/O error, dev nbd15, sector 1 op 0x0:(READ) …
```

test: don't use nbd for the assembler unit tests

---

stages/org.osbuild.systemd
test/data/stages/systemd/b.json
test/data/stages/systemd/diff.json

stages/systemd: support of masking services and make enabled services option

---

samples/noop.json
stages/org.osbuild.noop

The documentation states that the stage accepts any options and dumps them but the schema was not allowing any. Fix that and also change the sample to include a random option.

stages/noop: fix the schema to allow any props

---

NEWS.md
osbuild.spec
setup.py

Prepare release 19

---

schutzbot/Jenkinsfile
schutzbot/mockbuild.sh

🤖 schutzbot: Bring over updates from osbuild-composer

---

runners/org.osbuild.ubuntu2004

Base it on the ubuntu 18.04 runner.

runners: add support for ubuntu 20.04

---

NEWS.md

Prepare the v20 release and list the significant changes since v19.
@gicmo: It even includes your location (no, I am not stalking you!) and an ambitious date! Feel free to adjust the entries to your liking.

build: create `NEWS` entry for v20

---

osbuild/pipeline.py

Remove output.export and associated logic in pipeline.assemble.
Instead, return output or None, and export only once in pipeline.run.

pipeline: unify object exporting

---

NEWS.md
osbuild.spec
setup.py

Release 20

---

schutzbot/Jenkinsfile
schutzbot/run_image_tests.sh

🚚 Bring over osbuild-composer CI changes

---

NEWS.md
osbuild.spec
setup.py

Prepare osbuild 22 release

---

.editorconfig
NEWS.md
osbuild.spec
setup.py

Prepare the release via the usual procedure:
Also includes a commit to add markdown files to the `.editorconfig`.

Prepare the release of version 23

---

Makefile
schutzbot/Jenkinsfile
schutzbot/mockbuild.sh
schutzbot/run_image_tests.sh

I've pushed osbuild-composer's main branch (exact copy of master). Once this lands, I'll switch the default branch to main.

master → main

---

schutzbot/Jenkinsfile
schutzbot/deploy.sh
schutzbot/mockbuild.sh

This is https://github.com/osbuild/osbuild-composer/pull/1075, but for osbuild.

schutzbot: don't copy dnf repo file between stages

---

.github/workflows/tests.yml
Makefile
README.md
requirements.txt

- Nicer output
- Prepare to use its functionality
- Prepare to report coverage

Use pytest for testing

---

NEWS.md
osbuild.spec
setup.py

Prepare the release of osbuild 24.

Release 24 preparations

---

NEWS.md
osbuild.spec
setup.py

Update news, bump versions.
Big thanks to @larskarlitski and @teg for helping with the release notes.

Prepare the release 25

---

NEWS.md
osbuild.spec
setup.py

Update the `NEWS.md`, bump the versions. The usual spiel.

Prepare release 26

---

NEWS.md

Just some typos I noticed while working on the composer side of the changes mentioned in the news.

NEWS: small typo fixes

---

schutzbot/Jenkinsfile

needed for
https://github.com/osbuild/osbuild-composer/pull/1229

schutzbot: build osbuild for aarch64 RHEL8/CentOS 8

---

NEWS.md
osbuild.spec
setup.py

Release 27

---

stages/org.osbuild.oci-archive

Cherry picks for fixes for RHEL 8.4.0.
Contains:
- PR #622: stages/oci-archive: write history entries
- fixes [RHBZ#1944266](https://bugzilla.redhat.com/show_bug.cgi?id=1944266).
- PR #623: stages/oci-archive: include limited set of xattrs

RHEL 8.4.0 cherry picks

---

NEWS.md
osbuild.spec
setup.py

*NB: This release is specifically for RHEL 8.4.0.*

Release 27.1

---

NEWS.md
assemblers/org.osbuild.qemu
osbuild.spec
setup.py

Release 27.2 for RHEL 8.4.0

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json

vscode devcontainer: include more utilities and preserve fish history

---

NEWS.md
osbuild.spec
setup.py

Prepare the 29 release:
- version bump
- `NEWS.md`

Prepare release 29

---

.packit.yaml

See the comment here: https://github.com/osbuild/osbuild/pull/683#issuecomment-865117035

packit: build on every commit to main

---

osbuild.spec

See individual commits, nothing major.

Minor specfile tweaks

---

NEWS.md
osbuild.spec
setup.py

Prepare release 30

---

test/run/test_noop.py

test_noop: the test needs root access to mount

---

devices/org.osbuild.loopback
osbuild/loop.py
osbuild/util/linux.py
test/mod/test_loop.py

See individual commits for details.

Flush the loop back device buffer cache before clearing the fd

---

.devcontainer/Dockerfile
.packit.yaml
Makefile
test/data/manifests/fedora-boot.mpp.json
test/data/manifests/fedora-build.mpp.json

Updates for PackIt, the devcontainer and include version agnostic build manifest

---

NEWS.md
osbuild.spec
setup.py

Prepare release 31

---

.packit.yaml

Create the downstream, i.e. fedora dist-git, pr on releases.

packit: create downstream prs on release

---

NEWS.md
osbuild.spec
setup.py

Prepare release 36

---

NEWS.md
osbuild.spec
setup.py

Prepare release 37

---

osbuild/host.py
osbuild/sources.py
test/mod/test_host.py

Since source were converted to host services (c902a7a754c352d0b69c368945440393400098a2) it now uses a unix socket instead of stdin to pass the arguments, which includes the list of items to download. The latter can become quite big, in fact too big to fit into a single package (NB: `SOCK_SEQPACKET` is used for the underlying transport).
Therefore write the actual items to a temporary file and pass the fd of it along the message.
Should fix #822

sources: pass items via a temporary file

---

osbuild/host.py
test/mod/test_host.py

Release Notes:
```
* host services: make file descriptor passing more robust by checking the fds
before sending them.
```

host: more robust fd passing

---

.packit.yaml

packit: enable builds on ppc64le

---

test/mod/test_util_lvm2.py

Instead of having custom code that basically duplicates the functionality of `LoopControl.loop_for_fd` use that instead. Additionally, the version used in the test had a bug where it did not re-create the Loop device in the main loop when it was close due to an error, leading errors in subsequent usages of the device that would often manifest in CI runs:
fcntl.ioctl(self.fd, self.LOOP_SET_FD, fd)
ValueError: file descriptor cannot be a negative integer (-1)

test/lvm2: use LoopControl.loop_for_fd

---

.github/workflows/checks.yml
.github/workflows/tests.yml
setup.cfg

Needed for LUKS (#879) but also for @alexlarsson osbuild-mpp yaml work (#893).

CI: update the osbuild-ci container

---

.gitlab-ci.yml
schutzbot/deploy.sh

Also enable testing on RHEL-8.6 nightly.
Just trying to see if it's going to work as-is.

tests: enable testing on aarch64 RHEL

---

osbuild/util/rmrf.py

The current implementation of `rmtree` will try to fix permissions when it encounters permission errors during its operation. This is done by opening the target via `os.open` and then adjusting the immutable flag and the permission bits. This is a problem when the target is a broken symlink since open will fail with `ENOENT`. A simple reproducer of this scenario is:
$ mkdir subdir
$ ln -s foo subdir/broken
$ chmod a-w subdir/
$ python3 -c 'import osbuild; osbuild.util.rmrf.rmtree("subdir")'
Since subdir is not writable, removing `subdir/broken` will fail with `EPERM` and the `on_error` callback will try to fix it by invoking `fixperms` on `subdir/broken` which will in `open` since the target does not exist (broken symlink).
This is fixed by using `O_NOFOLLOW` to open so we will never open …

util/rmrf: handle broken symlinks

---

.github/mergify.yml

[skip ci] ci: accept LGTM neutral (mergify)

---

.github/mergify.yml

As suggested by @ondrejbudai 
See individual commits.

Mergify rereview

---

Makefile

Unexpected results otherwise.
cc @achilleas-k

make: require clean git for make make

---

stages/org.osbuild.dnf.config
test/data/stages/dnf.config/b.json
test/data/stages/dnf.config/b.mpp.json
test/data/stages/dnf.config/diff.json

stages/org.osbuild.dnf.config: Edit /etc/dnf/dnf.conf

---

stages/org.osbuild.mkinitcpio
test/data/manifests/arch/arch-build.mpp.json

This stage generates the initrd for Arch Linux and derivates.

Add mkinitcpio stage

---

stages/org.osbuild.tar

Fix typo in tar stage schema option enum

---

stages/org.osbuild.squashfs
test/cases/ostree-images
test/data/manifests/fedora-ostree-bootiso-xz.json
test/data/manifests/fedora-ostree-bootiso-xz.mpp.json

Using lz4 in squashfs reduces the time to complete the stage from 446s
to 4s on my laptop while making the produced iso going from 1.6G to
2.0G.

Add the option of compressing using lz4

---

.gitlab-ci.yml
schutzbot/sonarqube.sh

Minor oversight from previous commit. Do not try to fetch PR when running on main branch.

test/ci: fix sonarqube run on main

---

assemblers/org.osbuild.oci-archive
stages/org.osbuild.oci-archive

Signed-off-by: Roy Golan <rgolan@redhat.com>

Fix typo orci-archive/oci-archive

---

stages/org.osbuild.clevis.luks-bind
stages/org.osbuild.luks2.remove-key

These are needed to support encrypted raw images for the simplified installer - require needed stages plumbed into osbuild-composer too once this goes in

Add clevis-luks-bind and luks-remove-key stages

---

osbuild/host.py
test/mod/test_host.py

This commit brings signals to the host. With the possibility for the
services to send info to their client counterpart while running.
The signal can take file descriptors as extra parameters to send data on
separate files.

Host.Service: add signals

---

runners/org.osbuild.rhel91

Add RHEL-9.1 runner

---

assemblers/org.osbuild.qemu

Support VMDK subformat in qemu assembler

---

stages/org.osbuild.grub2.legacy

Change this before it gets actually used in the wild. See the individual commits.

`stages/grub2.legacy`: small schema fixes

---

stages/org.osbuild.oci-archive

`stages/oci-archive`: small cleanups

---

mounts/org.osbuild.fat
mounts/org.osbuild.noop

Just a set of two minor fixes to the mount modules. No functional-changes intended.

mounts: minor fixes with no functional changes

---

.gitlab-ci.yml
schutzbot/deploy.sh

Built on top of https://github.com/osbuild/osbuild/pull/1051

COMPOSER-1622: Enable Fedora 36 testing

---

docs/osbuild-manifest.5.rst
osbuild/meta.py
schemas/osbuild2.json

A set of assorted fixes to the schema definitions and handling. None of them critical, yet they do fix issues when passing wrongly formatted or non-standard manifests.

schema: assorted fixes for schema formatting and handling

---

stages/org.osbuild.gcp.guest-agent.conf

`stages/gcp.guest-agent.conf`: various small fixes

---

.github/workflows/checks.yml
assemblers/org.osbuild.oci-archive
assemblers/org.osbuild.rawfs
osbuild/pipeline.py
osbuild/util/ostree.py
osbuild/util/path.py
runners/org.osbuild.rhel81
stages/org.osbuild.bootiso.mono
stages/org.osbuild.firewall
stages/org.osbuild.locale
stages/org.osbuild.nginx.conf
stages/org.osbuild.oscap.remediation
stages/org.osbuild.sysconfig
stages/org.osbuild.tuned
test/mod/test_api.py
test/mod/test_fmt_v1.py
test/mod/test_objectstore.py
test/mod/test_util_lorax.py
test/mod/test_util_path.py
test/mod/test_util_rhsm.py
test/run/test_stages.py
test/src/test_pylint.py
test/test.py

Run `autopep8` in CI to check the source is well formatted. Fix anything that was not yet properly formatted.

Check source via `autopep8`

---

runners/org.osbuild.fedora38

It's that time of the year again.

runners: add fedora38

---

test/data/stages/README.md

Adds a `README.md` which explains what do you need 
to do to add a new test for an stage
This hopes to document a bit how to add new tests for an stage.

test: add README.md on how to make tests for stages

---

stages/org.osbuild.lorax-script

See individual commits, no functional changes.

stages/lorax-script: minor schema adjustments

---

.bandit

`bandit` is a fast Python vulnerability scanner, this provides a default configuration file for it for those that want to run it.
`bandit --ini .bandit -r osbuild/` will get you results.

lint: provide bandit configuration

---

test/mod/test_util_ostree.py
test/run/test_assemblers.py
tools/tree-diff

Fix two issues encountered while trying to make unit tests work in RHEL gating.

Various fixes

---

osbuild/loop.py

The fallback that was initially present in #1253 is needed for the current GitLab runners which have a Container-Optimized OS [1] with kernel 5.4 [2] without support for LOOP_CONFIGURE [3].
[1] https://docs.gitlab.com/ee/ci/runners/saas/linux_saas_runner.html
[2] https://gitlab.com/cki-project/containers/-/jobs/4381560305#L31
[3] https://gitlab.com/cki-project/containers/-/jobs/4381560305#L1166

Restore LOOP_CONFIGURE fallback for kernel < 5.8

---

osbuild.spec
setup.py
tools/osbuild-dev

I've been using `osbuild-dev` quite a bit on manifests, however it seems to have broken? This fixes it and some other minor improvements.

tools: `osbuild-dev` quality of life

---

.gitlab-ci.yml
schutzbot/unregister.sh

schutzbot: unregister test hosts

---

stages/org.osbuild.ostree.deploy

Prep for possibly adding inputs to the ostree.deploy stage in the future.

stages/ostree.deploy: switch to v2 schema

---

README.md

fix link to developer guide

---

osbuild/util/containers.py
stages/org.osbuild.skopeo

This is prep for adding another stage that accepts containers as an input. The code
is common so we should share it amongst all stages that use containers as input.

osbuild/util: hoist container handling code from skopeo stage into util/containers

---

stages/org.osbuild.mkfs.fat
test/data/stages/fat/manifest.json
test/data/stages/fat/manifest.mpp.yaml
test/run/test_stages.py

Hi,
Some platforms (like the TI AM62 SoC) have specific requirements when it comes to the boot partition filesystem geometry.
Failing to follow those requirements will prevent the board from booting entirely, so we need to ensure that the geometry matches what the CPU expects.
Let me know what you think

Support FAT FS Geometry Options

---

osbuild/util/ostree.py
stages/org.osbuild.ostree
stages/org.osbuild.ostree.config
stages/org.osbuild.ostree.deploy
stages/org.osbuild.ostree.init
stages/org.osbuild.ostree.init-fs
stages/org.osbuild.ostree.os-init
stages/org.osbuild.ostree.passwd
stages/org.osbuild.ostree.pull
stages/org.osbuild.ostree.remotes
test/data/manifests/fedora-ostree-image.json
test/data/manifests/fedora-ostree-image.mpp.yaml

See individual commit messages.

refactor ostree stages; add inputs to ostree.deploy stage

---

.github/workflows/check.yml
.packit.yaml

- Configure Packit to handle only release tags without a "dot".
- Validate Packit config as part of CI.

:package: Packit configuration enhancements

---

tools/check-runners

This should help keep Schutzfile cleaned up.

Add a tool script to help check for unused runners

---

osbuild/loop.py
test/mod/test_loop.py

When loop.Loop() is called and a new loop device must be allocated there is no gurantee that the correct device node is available on the system. In containers /dev is often just a tmpfs with static device nodes. So when /dev/loopN is not available when the container is created the device node will be missing even if `get_unbound()` create a new loop device for us.
This commit ensures that the device node is available. It creates it unconditionally and ignores any EEXIST errors to ensure there is no TOCTOU issue.
Note that the test could have passed a `Loop(dir_fd=open(tmpdir))` instead of creating/patching loop.DEV_PATH but it seems slightly nicer to test the flow without a custom dir_path as this is what the real code that creates a loop device is also using.

osbuild: ensure loop.Loop() has the required device node

---

stages/test/test_autotailor.py

stages(autotailor): add small unit test

---

Makefile
README.md

I have removed dead makefile target from the code.
Also I have updated README to be consistent with osbuild-composer readme (missing build related section).

Readme update

---

schutzbot/terraform
stages/org.osbuild.kickstart
stages/test/test_kickstart.py

Add support for the `ostreecontainer` kickstart command, see: https://pykickstart.readthedocs.io/en/latest/kickstart-docs.html#ostreecontainer

stages(kickstart): add `ostreecontainer`

---

osbuild/testutil/__init__.py
stages/org.osbuild.containers.storage.conf
stages/test/test_containers_storage_conf.py
tox.ini

This fixes some issues and adds new options from https://github.com/containers/storage/blob/15c3cb7881e43958753303a93f2ec0d0be4da7e9/docs/containers-storage.conf.5.md

Update containers storage conf stage

---

osbuild/util/fscache.py
osbuild/util/linux.py
test/mod/test_util_fscache.py
test/mod/test_util_linux.py

This is an attempt to start fixing https://github.com/osbuild/osbuild/issues/392, i.e. that when the fscache is full it will just stop caching instead of removing the oldest piece from the cache and continuing. This behavior is now explicitly tested as part of the PR so that we can later change it for something that removes the oldest entries.
When looking at this I noticed that AFAICT we have no mechanism right now to identify how recently an object in the cache was used. This PR adds a helper "FsCache._last_used()" and uses the per object lock files `atime` for this. It has to be at the file level because the cache is designed to be accessible from multiple programs at once and this seems to be the least invasive and robust way. But better ideas are of course welcome!
Once this …

fscache: implement "last_used()" helper

---

stages/org.osbuild.skopeo
stages/test/test_skopeo.py

This cherry-picks some commits from #1418 by @ondrejbudai, the changes to the kickstart stage were (mostly) made in #1488.

stages/skopeo: destinations

---

osbuild/mounts.py

This PR contains two possible fixes for https://github.com/osbuild/osbuild/issues/1492
- osbuild/buildroot: also mount in tmp dev directory
- This is a big hammer but is unlikely to hurt anything.
- If we decided to we could probably ship this commit as is.j
- osbuild/mounts: adjust the source path to use when mounting devices
- This is an idea for another way to fix the problem, but it's unlikely to be polished enough to be accepted as is. What I think I would want to do is find a more appropriate place to set the correct value (string/path location) to be used when calling `mount`.

fix for inaccurate mountinfo inside bwrap env

---

runners/org.osbuild.debian
test/run/test_stages.py

Tiny PR to fix running the tests on a relatively pristine Debian system.

test: fix running on debian hosts

---

stages/org.osbuild.ostree.aleph
test/data/manifests/fedora-coreos-container.mpp.yaml

Also misc commit to parameterize `container_imgref` in FCOS manifest.

stages/ostree.aleph: don't manipulate image name from origin

---

tools/osbuild-depsolve-dnf

Ported from https://github.com/osbuild/osbuild-composer/commit/61e6f75281af007d6afc013de971431a6a1b8fde
Needed for https://github.com/osbuild/osbuild-composer/pull/3828

osbuild-depsolve-dnf: module_hotfixes support

---

tools/osbuild-depsolve-dnf

ported from https://github.com/osbuild/osbuild-composer/commit/d48da99a1267a79e22a1c197b1159a2ce1e62f51

osbuild-depsolve-dnf: port weak dependencies

---

README.md

I have added the OSBuild principles based on our discussion and agreement. I have reformulated some sentences for clarity.

README: Add OSBuild's principles

---

README.md

Fix developer guide link in README.md

---

osbuild/util/bls.py
stages/org.osbuild.coreos.platform
stages/test/test_coreos_platform.py
test/mod/test_util_bls.py

Followup for https://github.com/osbuild/osbuild/pull/1589

stages,util: tweaks for the platform/bls handling

---

.github/workflows/pr_best_practices.yml

This pipeline tests:
1. If the PR description is not empty (blocking)
2. If the PR title follows our format (non-blocking) `component: This is the change (JIRA-001)`
3. If 1. and 2. are True, it adds a 'best practice' label to the PR

actions: Add a PR best practices check

---

stages/test/test_systemd_unit_create.py

Small followup for https://github.com/osbuild/osbuild/pull/1620

test: add unit-{type,path} test coverage

---

osbuild/remoteloop.py

The LoopServer._create_device() duplicates the code from `Loop.loop_for_fd()` right now. Given that this is relatively subtle code it's better to not duplicate it and instead just reuse the loop_for_fd() implementation in LoopServer.
A bit of a drive-by cleanup. While trying to figure out the race in test_assembers.py I looked over the various loopback related code and noticed that we have some easy to avoid duplication here.

osbuild: reuse loop_for_fd() in LoopServer

---

test/run/test_exports.py

Simon discovered that `os.unsetenv()` will not remove the env from os.environ so this commit fixes this.
Thanks for figuring this out!

test: use `del os.environ[]` instead of `os.unsetenv` (thanks Simon)

---

osbuild/buildroot.py
osbuild/main_cli.py
osbuild/monitor.py
osbuild/pipeline.py
osbuild/sources.py
sources/org.osbuild.curl
test/mod/test_monitor.py
tools/osbuild-json-seq-progress-example-renderer

This is a draft to get opinions/feedback. Based on the excellent work from @achilleas-k 
Some open questions:
1. I moved from jsonnl to json-seq - I am not sure about this anymore though, it seems most other RH tooling just uses jsonnl
2. The sources progress is a hack right now but it's really important as a lot of time is spend on fetching things, feedback here also welcome
Best read commit by commit I think.

many: jsonseq based progress reporting for osbuild

---

docs/osbuild.1.rst
test/mod/test_monitor.py

Add basic documentation about the new json sequence progress support.

doc: document the new json-sequence monitor

---

stages/org.osbuild.systemd.unit.create
stages/test/test_systemd_unit_create.py
test/data/stages/systemd.unit.create/b.json
test/data/stages/systemd.unit.create/b.mpp.yaml

Added new systemd unit config : ConditionPathIsDirectory

stage/systemd-unit-create:new systemd unit config params

---

osbuild/util/parsing.py
stages/org.osbuild.chattr
stages/org.osbuild.copy
stages/org.osbuild.kernel-cmdline.bls-append
test/mod/test_util_parsing.py
tox.ini

- Move functions to the 'util' to centralize common functionality, reducing code duplication and improving maintainability across the codebase.

util: Consolidate parse functions into util

---

sources/org.osbuild.curl

curl: fix RHSM url retrieval

---

sources/test/test_curl_source.py

Small simplifications while working on this file.

sources: some small tweaks to the curl tests

---

sources/test/test_curl_source.py

Using pytests support for changing setenv() in tests makes things a little bit more concise.

sources(curl): tweak tests to use monkeypatch.setenv()

---

sources/test/test_curl_source.py

This commit adds a small test that ensures that the environement is correctly set.
We should probably refactor this a bit later so that we generate a curl config without actually having to run it. This will be needed when we switch to `curl --parallel` anyway so let's not do it just yet :)
[edit: related to https://github.com/osbuild/osbuild/pull/1708#pullrequestreview-1985754161]

curl: test that OSBUILD_SOURCES_CURL_PROXY works correctly

---

test/data/testrepos/README.md
test/data/testrepos/custom/repodata/repomd.xml
tools/osbuild-depsolve-dnf5
tools/test/test_depsolve.py

Tweak the package name a bit to more it very explicit what it's about.

tools: rename "nothing" to "pkg-with-no-deps" to make it a bit clearer

---

tools/test/test_depsolve.py

Extract make_dnf_scafolding as a helper, mostly so that the config_combos() function is easier to read. It seems one core concept here is the iteration of "combo[0]" and "combo[1]" so having them symetrical at the same indent level feel easier to read to me.
This is best (re)viewed side-by-side to see the new structure is more symetrical:
```python
def config_combos(tmp_path, servers):
for combo in combo_idxs:
for idx in combo[0]:
...
root_dir, repos_dir, keys_dir = make_dnf_scafolding(tmp_path)
for idx in combo[1]:  # servers to be configured through root_dir
...
```

tools: extract make_dnf_scafolding() from config_combos()

---

tools/test/test_depsolve.py

Given that the tests `test_depsolve{,_dnf5}` are identical except the `command` extract a common helper. This will also help to avoid drift between the two resolvers.

tools: extract common _test_depsolve_both_dnf_dnf5 helper.

---

.github/workflows/test.yml
tools/osbuild-depsolve-dnf5
tools/test/test_depsolve.py

This PR does the things described in the commit messages :) It uses a ci container with libdnf5, it enables it in tox, it finds a bug in osbuild-depsolve-dnf5, and it fixes the bug.

Enable osbuild-depsolve-dnf5 testing and fix a bug

---

test/mod/test_util_path.py

Any sub-second or larger time adjustments by chrony or similar would corrupt this time sensitive test without a
counter measure like this

test_clamp_mtime: avoid clashing with chrony

---

osbuild/testutil/__init__.py
stages/test/test_bootc_install_to_fs.py
stages/test/test_container_deploy.py
stages/test/test_skopeo.py

Tiny strawman followup for https://github.com/osbuild/osbuild/pull/1752

stages: tweak the skopeo copy test

---

stages/test/test_mkfs_fat.py

Add unit tests for mkfs.fat stage

Tests: Add unit tests for org.osbuild.mkfs.fat stage

---

stages/org.osbuild.systemd.unit.create.meta.json
stages/test/test_systemd_unit_create.py

Support the Before option in the Unit section of the unit file.
Required for https://github.com/osbuild/images/pull/668#issuecomment-2101466853

stage/systemd.unit.create: add Before option

---

stages/org.osbuild.users
stages/org.osbuild.users.meta.json
stages/test/test_users.py

This PR is the new version of https://github.com/osbuild/osbuild/pull/1695. I am making a new PR because the old branch name is misleading given the discussion on the previous PR

Add user force password reset

---

.gitlab-ci.yml
Schutzfile

Test/manifests: start testing on c10s and el10.0-nightly (COMPOSER-2161)

---

osbuild/util/jsoncomm.py
test/mod/test_util_jsoncomm.py

When `jsoncomm` fails because the message is too big it currently does not indicate just how big the message was. This commit adds this information so that it's easier for us to determine what to do about it.
We could also include a pointer to `/proc/sys/net/core/wmem_defaults` but it seems we want to not require fiddling with that so let's not do it for now.
See also https://github.com/osbuild/osbuild/pull/1838 and https://github.com/osbuild/osbuild/pull/1833

jsoncom: gracefully report EMSGSIZE errors

---

stages/test/test_mkfs_btrfs.py
stages/test/test_mkfs_fat.py
stages/test/test_mkfs_xfs.py
test/run/test_mount.py
tools/osbuild-mpp

Running `make lint` locally detected some issues, this PR fixes all of them.

general: Fix linter issues across the codebase

---

osbuild/util/chroot.py
stages/org.osbuild.dracut
stages/org.osbuild.update-crypto-policies
stages/test/test_dracut.py
test/mod/test_util_chroot.py

This PR addresses comments and suggestions made in #1860.

Some chroot context improvements

---

stages/org.osbuild.bootc.install-to-filesystem.meta.json
stages/org.osbuild.bootc.install.config.meta.json
stages/org.osbuild.bootupd.gen-metadata.meta.json
stages/org.osbuild.chrony.meta.json
stages/org.osbuild.copy.meta.json
stages/org.osbuild.coreos.platform.meta.json
stages/org.osbuild.crypttab.meta.json
stages/org.osbuild.fdo.meta.json
stages/org.osbuild.fix-bls.meta.json
stages/org.osbuild.fstab.meta.json

adding paths in `` ` `` and fixing typos to prepare for spellchecking and better layout

stages: fix some documentation typos to prepare for spellchecking

---

osbuild/util/parsing.py
stages/org.osbuild.mkdir
stages/org.osbuild.selinux
stages/org.osbuild.selinux.meta.json
stages/test/test_selinux.py
test/mod/test_util_parsing.py

Required for: https://github.com/osbuild/osbuild/issues/1877

org.osbuild.selinux: support working on mounts

---

sources/test/test_ostree_source.py

Not all distros ship `/var/empty` so just create an empty dir on demand as needed.
This also tweaks `test_ostree_source_exists()` into calling `make_repo()` instead of duplicating that code.

sources: fix ostree_sources test to work without `/var/empty`

---

osbuild/util/chroot.py

- Implement `mount_bind` and `umount` methods to allow flexible mounting and unmounting of additional directories as needed within the chroot environment.

util/chroot: Add support for custom directory bind mounts

---

stages/org.osbuild.grub2.inst
stages/org.osbuild.grub2.inst.meta.json
stages/test/test_grub2_inst.py

Editing the description in order to make the test happy. Not sure why github didn't pick up the text from the first commit.

Make an iso9660 eltorito image

---

tools/test/test_depsolve.py

This commit adds a small test that ensures that we notice when the solver API adds new top-level keys. When this happens the images library breaks and we need to increase the
`Provides: osbuild-dnf-json-api` version in the `osbuild.spec`.
See e.g. https://github.com/osbuild/osbuild/pull/1992

tools: add test that ensures we notice if the solver api breaks

---

osbuild/monitor.py
test/mod/test_monitor.py

This commit fixes a race/threading issue with the way the monitor works. The osbuild monitor can be called from multiple threads, e.g. in buildroot.py:run() monitor.log() is called but also in host.py:_stdout_ready(). This can lead to out-of-order writes when many messages need to be processed.
We did not notice this so far because we were lucky and also log was just used for information. But now it is used to transmit the jsonseq data which means out-of-order communication results in broken json.
Closes: https://github.com/osbuild/image-builder-cli/issues/110

osbuild: add a mutex to the _jsonseq() writer

---

.github/workflows/update-images.yml
schutzbot/update-schutzfile-images
tools/osbuild-image-info

A few minor follow-up fixes for PR #1983 
/jira-epic COMPOSER-2318
JIRA: [HMS-5434](https://issues.redhat.com/browse/HMS-5434)

Follow-up fixes to PR#1983 (HMS-5434)

---

.github/workflows/update-images.yml

GH/update-images: fix missing quote in the script

---

osbuild/monitor.py
test/mod/test_monitor.py

This commit limits the output in the json pipeline to a "reasonable" length. We ran into issues (e.g. [0]) from a combination of a stage that produce tons of output (dracut, ~256 kb, see issue#1976) and the consumer ("images" osbuild/monitor.go) that used a golang scanner with a max default buffer of 64kb before erroring. So limit it here.
The stage result from via json is mostly for information and any error will most likely at the end. Plus consumers can collect the individual log lines on their own if desired via the "log()" messages that are stream in "real-time" with the added benefit that e.g. timestamps can be added to the logs etc.
[0] https://issues.redhat.com/browse/RHEL-77988

monitor: limit the amount of data sent in JSONSeqMontior.result()

---

tools/test/test_depsolve.py

Test/tools/depsolve: reword function doc text

---

stages/org.osbuild.containers.unit.create
stages/org.osbuild.containers.unit.create.meta.json

This pull request fixes the description in the `org.osbuild.containers.unit.create.meta.json` and updates comments in the `org.osbuild.containers.unit.create` files, addressing issue #2053.

stages: fix description for org.osbuild.containers.unit.create

---

stages/org.osbuild.systemd.unit.create.meta.json
stages/test/test_systemd_unit_create.py
test/data/stages/systemd.unit.create/b.json
test/data/stages/systemd.unit.create/b.mpp.yaml
test/data/stages/systemd.unit.create/diff.json

Add support for the StandardOutput option in the [Service] section of
systemd units.
https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#StandardOutput=

stages/systemd.unit.create: support StandardOutput (RHEL-79065)

---

.github/workflows/check.yml

github: bump ubuntu runners to 24.04

---

stages/test/test_rhsm.py

I forgot to add the file to https://github.com/osbuild/osbuild/pull/2070.

Stages/rhsm: add unit test for the stage schema

---

test/run/test_stages.py

RPM 6.0 (landed in F43, current rawhide), no longer uses short key ID for the 'gpg-pubkey' pseudo-package, but to prevent any collision, it uses full key ID.
This means that we can't consistently just compare the pipeline rpm stage metadata from the test data with what we get from building the test manifest. The reason is that we need to keep running the unit test in upstream and downstream CI pipelines for OSes, which may ship RPM 6.0, but also older RPM version.
Extend the test case to do a special case check for any 'gpg-pubkey' package in the metadata if the package version length differs between the test data and data got from building the manifest.

Test/stages/rpm: add compatibility with RPM 6.0

---

osbuild/loop.py

In https://github.com/osbuild/osbuild/pull/2187 we added code to allow running osbuild with less privileges. However the new code fails in the test_assemblers.py code when the assemblers try to request a loop device from inside the bubble wrap container and Loop.mknod() will not be able to bind mount the device to the passed dir_fd. The exact reason is unclear, it seems related to the mount namespace rules [0] but there are some open questions about this theory.
To fix the regression (and potential future issues) always fallback to the previous `mknod()` if the bind mount fails.
[0] https://github.com/osbuild/osbuild/pull/2187#issuecomment-3327117870

osbuild: if Loop.mknod() cannot bind mount fallback to mknod
